# theme = "adwaita-dark"
# theme = "kanagawa"
# theme = "base16_transparent"
# background = "transparent"
theme = "fleet_dark"
[editor]
# line-number = "relative"
# ui.background" = { bg = "bg" }
mouse = true

scroll-lines = 1
cursorline = true
auto-save = false
completion-trigger-len = 2
true-color = true
color-modes = true
# completion-
auto-pairs = false
rulers = [120]
idle-timeout = 50
auto-info = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

# [editor.cursor-shape]
# insert = "bar"
# normal = "bar"
# select = "bar"


[editor.indent-guides]
# render = true
# character = "▏"

[editor.lsp]
display-messages = false
display-inlay-hints = false
auto-signature-help = true
display-signature-help-docs = true

[editor.smart-tab]
enable = true
supersede-menu = false

[editor.statusline]
left = ["mode", "spinner", "file-name", "file-type", "total-line-numbers", "file-encoding"]
center = []
right = ["selections", "primary-selection-length", "position", "position-percentage", "spacer", "diagnostics", "workspace-diagnostics", "version-control"]


#[[language]]
#language-servers = ["typescript-language-server", "copilot"]
#name = "typescript"

[keys.select]
y = "yank_main_selection_to_clipboard"
p = "paste_clipboard_before"
# backspace = ["insert_mode", "delete_selection"]
# ["delete_char_forward", "insert_mode"]

[keys.normal]

"A-T" = "file_picker"
"A-P" = "command_palette"
"A-w" = "make_search_word_bounded"
"C-n" = ["move_prev_word_start", "move_next_word_end", "search_selection", "extend_search_next"]

C-K = "goto_prev_paragraph"
C-J = "goto_next_paragraph"

y = "yank_main_selection_to_clipboard"
p = "paste_clipboard_before"

"ret" = ["insert_mode"]
C-ret = ["goto_line_end_newline", "insert_mode", "insert_newline"] 
A-j = ["extend_to_line_bounds", "delete_selection", "paste_after"]
A-k = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]

# "x" = "delete_selection"
"backspace" = ["delete_char_backward", "insert_mode"]


# Some nice Helix stuff
C-h = "select_prev_sibling"
C-j = "shrink_selection"
C-k = "expand_selection"
C-l = "select_next_sibling"
esc = ["collapse_selection", "keep_primary_selection", "normal_mode"]


# ccvscode

# C-n = ["move_prev_word_start", "move_next_word_end", "search_selection", "extend_search_next"]
# "*" = ["move_prev_word_start", "move_next_word_end", "search_selection"]

# sdq qsd "qsd" dqs

"A-b" = "move_prev_long_word_end"
"C-left" = "move_prev_long_word_end"

"A-f" = "move_next_long_word_end"
"C-right" = "move_next_long_word_end"


[keys.insert]
esc = ["collapse_selection", "normal_mode"]
"A-space" = "completion"
"A-ù" = "completion"
"A-b" = "move_prev_long_word_end"
"C-left" = "move_prev_long_word_end"
"A-f" = "move_next_long_word_end"
"C-right" = "move_next_long_word_end"
