complete -c ambr -l key-from-file -d 'Use file contents of KEYWORD as keyword for search'
complete -c ambr -l rep-from-file -d 'Use file contents of REPLACEMENT as keyword for replacement'
complete -c ambr -l verbose -d 'Verbose message'
complete -c ambr -s r -l regex -d 'Enable regular expression search'
complete -c ambr -l column -d 'Enable column output'
complete -c ambr -l row -d 'Enable row output'
complete -c ambr -l binary -d 'Enable binary file search'
complete -c ambr -l statistics -d 'Enable statistics output'
complete -c ambr -l skipped -d 'Enable skipped file output'
complete -c ambr -l preserve-time -d 'Enable timestamp preserve'
complete -c ambr -l no-interactive -d 'Disable interactive replace'
complete -c ambr -l no-recursive -d 'Disable recursive directory search'
complete -c ambr -l no-symlink -d 'Disable symbolic link follow'
complete -c ambr -l no-color -d 'Disable colored output'
complete -c ambr -l no-file -d 'Disable filename output'
complete -c ambr -l no-skip-vcs -d 'Disable vcs directory ( .hg/.git/.svn ) skip'
complete -c ambr -l no-skip-gitignore -d 'Disable .gitignore skip'
complete -c ambr -l no-fixed-order -d 'Disable output order guarantee'
complete -c ambr -l no-parent-ignore -d 'Disable .*ignore file search at parent directories'
complete -c ambr -l tbm -d '[Experimental] Enable TBM matcher'
complete -c ambr -l sse -d '[Experimental] Enable SSE 4.2'
complete -c ambr -s h -l help -d 'Prints help information'
complete -c ambr -n __fish_no_arguments -s V -l version -d 'Prints version information'
complete -c ambr -l max-threads -d '<NUM>          Number of max threads [default: 8]'
complete -c ambr -l size-per-thread -d '<BYTES>    File size per one thread [default: 1048576]'
complete -c ambr -l bin-check-bytes -d '<BYTES>    Read size for checking binary [default: 256]'
complete -c ambr -l mmap-bytes -d '<BYTES>         [Experimental] Minimum size for using mmap [default: 1048576]'

