complete -c arp-scan -s h -l help -d 'Display this usage message and exit.'
complete -c arp-scan -s v -l verbose -d 'Display verbose progress messages.'
complete -c arp-scan -n __fish_no_arguments -s V -l version -d 'Display program version details and exit.'
complete -c arp-scan -s I -l interface -d 'Use netw k interface .'
complete -c arp-scan -s f -l file -d 'Read hostnames addresses from the specified file'
complete -c arp-scan -s l -l localnet -d 'Generate addresses from interface configuration.'
complete -c arp-scan -l file -d 'option give targets on the command line.'
complete -c arp-scan -s O -l ouifile -d 'Use IEEE registry vend mapping file .'
complete -c arp-scan -s m -l macfile -d 'Use custom vend mapping file .'
complete -c arp-scan -s q -l quiet -d 'Display minimal output f each responding host.'
complete -c arp-scan -s x -l plain -d 'Supress header and footer text.'
complete -c arp-scan -l ign -d edups\ -g\ Don\'t\ display\ duplicate\ packets.
complete -c arp-scan -s D -l rtt -d 'Calculate and display the packet round-trip time.'
complete -c arp-scan -l quiet -d 'option is specified.'
complete -c arp-scan -s R -l random -d 'Randomise the target host list.'
complete -c arp-scan -l randomseed -d 'Seed the pseudo random number generat .'
complete -c arp-scan -s r -l retry -d 'Set total number of attempts per host to ,'
complete -c arp-scan -s b -l backoff -d 'Set backoff fact to , default1.50.'
complete -c arp-scan -s t -l timeout -d 'Set initial per host timeout to  ms, default500.'
complete -c arp-scan -s i -l interval -d 'Set minimum packet interval to .'
complete -c arp-scan -s B -l bandwidth -d 'Set outbound bandwidth to , default256000.'
complete -c arp-scan -s N -l numeric -d 'Targets must be IP addresses, not hostnames.'
complete -c arp-scan -s d -l resolve -d 'Resolve responding addresses to hostnames.'
complete -c arp-scan -s u -l arpsha -d 'Set the ARP source Ethernet address.'
complete -c arp-scan -s w -l arptha -d 'Set the ARP target Ethernet address.'
complete -c arp-scan -s H -l arphrd -d 'Set the ARP hardware type, default1.'
complete -c arp-scan -s p -l arppro -d 'Set the ARP protocol type, default0x0800.'
complete -c arp-scan -s a -l arphln -d 'Set the hardware address length, default6.'
complete -c arp-scan -s P -l arppln -d 'Set the protocol address length, default4.'
complete -c arp-scan -s o -l arpop -d 'Specify the ARP operation, default1.'
complete -c arp-scan -s s -l arpspa -d 'Set the source IPv4 address.'
complete -c arp-scan -s S -l srcaddr -d 'Set the source Ethernet MAC address.'
complete -c arp-scan -s T -l destaddr -d 'Set the destination MAC address.'
complete -c arp-scan -s y -l prototype -d 'Sets the Ethernet protocol type, default0x0806.'
complete -c arp-scan -s L -l llc -d 'Use RFC 1042 LLC/SNAP encapsulation f 802.2 netw ks.'
complete -c arp-scan -s Q -l vlan -d 'Use 802.1Q tagging with VLAN id .'
complete -c arp-scan -s M -l limit -d 'Exit after the specified number of hosts have responded.'
complete -c arp-scan -s W -l pcapsavefile -d 'Write received packets to pcap savefile .'
complete -c arp-scan -s n -l snap -d 'Set the pcap snap length to . Default64.'
complete -c arp-scan -s Y -l retry-send -d 'Set number of send attempts, default20.'
complete -c arp-scan -s E -l retry-send-interval -d 'Set interval between send attempts.'
complete -c arp-scan -s A -l padding -d 'Specify padding after packet data.'
