complete -c cat -l nonprintable-notation -d '<notation>'
complete -c cat -s l -l language -d '<language>'
complete -c cat -s H -l highlight-line -d '<N:M>'
complete -c cat -l file-name -d '<name>'
complete -c cat -l diff-context -d '<N>'
complete -c cat -l tabs -d '<T>'
complete -c cat -l wrap -d '<mode>'
complete -c cat -l terminal-width -d '<width>'
complete -c cat -l color -d '<when>'
complete -c cat -l italic-text -d '<when>'
complete -c cat -l decorations -d '<when>'
complete -c cat -l paging -d '<when>'
complete -c cat -l pager -d '<command>'
complete -c cat -s m -l map-syntax -d '<glob:syntax>'
complete -c cat -l ignored-suffix -d '<ignored-suffix>'
complete -c cat -l theme -d '<theme>'
complete -c cat -l style -d '<components>'
complete -c cat -s r -l line-range -d '<N:M>'
