complete -f -c cloudflared -n __fish_use_subcommand -a update -d 'Update the agent if a new version exists'
complete -f -c cloudflared -n __fish_use_subcommand -a version -d 'Print the version'
complete -f -c cloudflared -n __fish_use_subcommand -a proxy-dns -d 'Run a DNS over HTTPS proxy server.'
complete -f -c cloudflared -n __fish_use_subcommand -a tail -d 'Stream logs from a remote cloudflared'
complete -f -c cloudflared -n __fish_use_subcommand -a service -d 'Manages the cloudflared launch agent'
complete -f -c cloudflared -n __fish_use_subcommand -a help -d 'Shows a list of commands or help for one command'
complete -c cloudflared -l credentials-file -d 'value, --cred-file value  Filepath at which to read/write the tunnel credentials [$TUNNEL_CRED_FILE]'
complete -c cloudflared -l region -d 'value                               Cloudflare Edge region to connect to. Omit or set to empty to connect to the global region. [$TUNNEL_REGION]'
complete -c cloudflared -l edge-ip-version -d 'value                      Cloudflare Edge IP address version to connect with. {4, 6, auto} (default: "4") [$TUNNEL_EDGE_IP_VERSION]'
complete -c cloudflared -l edge-bind-address -d 'value                    Bind to IP address for outgoing connections to Cloudflare Edge. [$TUNNEL_EDGE_BIND_ADDRESS]'
complete -c cloudflared -l label -d 'value                                Use this option to give a meaningful label to a specific connector. When a tunnel starts up, a connector id unique to the tunnel is generated. This is a uuid. To make it easier to identify a connector, we will use the hostname of the machine the tunnel is running on along with the connector ID. This option exists if one wants to have more control over what their individual connectors are called.'
complete -c cloudflared -l management-diagnostics -d 'Enables the in-depth diagnostic routes to be made available over the management service (/debug/pprof, /metrics, etc.) (default: true) [$TUNNEL_MANAGEMENT_DIAGNOSTICS]'
complete -c cloudflared -s f -l overwrite-dns -d 'Overwrites existing DNS records with this hostname (default: false) [$TUNNEL_FORCE_PROVISIONING_DNS]'
complete -c cloudflared -s h -l help -d 'show help (default: false)'
