complete -c csvlens -s d -l delimiter -d '<char>           Delimiter character (comma by default) or "auto" to auto-detect the delimiter'
complete -c csvlens -s t -l tab-separated -d Use\ tab\ separation.\ Shortcut\ for\ -d\ \'\\t\'
complete -c csvlens -l no-headers -d 'Do not interpret the first row as headers'
complete -c csvlens -l columns -d '<regex>            Use this regex to select columns to display by default'
complete -c csvlens -l filter -d '<regex>             Use this regex to filter rows to display by default'
complete -c csvlens -l find -d '<regex>               Use this regex to find and highlight matches by default'
complete -c csvlens -s i -l ignore-case -d 'Searches ignore case. Ignored if any uppercase letters are present in the search string'
complete -c csvlens -l echo-column -d '<column_name>  Print the value of this column to stdout for the selected row'
complete -c csvlens -l debug -d 'Show stats for debugging'
complete -c csvlens -s h -l help -d 'Print help'
complete -c csvlens -n __fish_no_arguments -s V -l version -d 'Print version'
