complete -c curl_chrome99 -s d -l data -d '<data>          HTTP POST data'
complete -c curl_chrome99 -s f -l fail -d 'Fail fast with no output on HTTP errors'
complete -c curl_chrome99 -s h -l help -d '<category>      Get help for commands'
complete -c curl_chrome99 -s i -l include -d 'Include protocol response headers in the output'
complete -c curl_chrome99 -s o -l output -d '<file>        Write to file instead of stdout'
complete -c curl_chrome99 -s O -l remote-name -d 'Write output to a file named as the remote file'
complete -c curl_chrome99 -s s -l silent -d 'Silent mode'
complete -c curl_chrome99 -s T -l upload-file -d '<file>   Transfer local FILE to destination'
complete -c curl_chrome99 -s u -l user -d '<user:password> Server user and password'
complete -c curl_chrome99 -s A -l user-agent -d '<name>    Send User-Agent <name> to server'
complete -c curl_chrome99 -s v -l verbose -d 'Make the operation more talkative'
complete -c curl_chrome99 -n __fish_no_arguments -s V -l version -d 'Show version number and quit'
