complete -c dappprof -s p -d 'PID          # examine this PID'
complete -c dappprof -s a -d '# print all details'
complete -c dappprof -s c -d '# print syscall counts'
complete -c dappprof -s e -d '# print elapsed times (us)'
complete -c dappprof -s o -d '# print on cpu times'
complete -c dappprof -s T -d '# print totals'
complete -c dappprof -s u -d 'lib          # trace this library instead'
complete -c dappprof -s U -d '# trace all libraries + user funcs'
complete -c dappprof -s b -d 'bufsize      # dynamic variable buf size'
