complete -c ghfs -l prefix -d '<value>  serve files under URL path instead o'
complete -c ghfs -l default-sort -d '<val Default: default sort for files and director Available sort k - `n` sort by name ascend - `N` sort by name descend - `e` sort by type(suffix) ascend - `E` sort by type(suffix) descend - `s` sort by size ascend - `S` sort by size descend - `t` sort by modify time ascend - `T` sort by modify time descend - `_` no s Directory so - `/<key>` directories before fi - `<key>/` directories after fi - `<key>` directories mixed with fi'
complete -c ghfs -l user -d '<value>  user info: <username>:<passwo'
complete -c ghfs -l user-base64 -d '<value>  user info: <username>:<base64-passwo'
complete -c ghfs -l user-md5 -d '<value>  user info: <username>:<md5-passwo'
complete -c ghfs -l user-sha1 -d '<value>  user info: <username>:<sha1-passwo'
complete -c ghfs -l user-sha256 -d '<value>  user info: <username>:<sha256-passwo'
complete -c ghfs -l user-sha512 -d '<value>  user info: <username>:<sha512-passwo'
complete -c ghfs -l global-a -d 'require Basic Auth for all director'
complete -c ghfs -l auth -d '<value>  url path that require Basic A'
complete -c ghfs -l auth-user -d '<value>  url path that require Basic Auth for specific users, <sep><url-path>[<sep><user>.'
complete -c ghfs -l auth-dir -d '<value>  file system path that require Basic A'
complete -c ghfs -l auth-dir-user -d '<value>  file system path that require Basic Auth for specific users, <sep><fs-path>[<sep><user>.'
complete -c ghfs -l index -d '<value>  Default url path that allow directory in'
complete -c ghfs -l index-user -d '<value>  url path that allow index files for specific users, <sep><url-path>[<sep><user>.'
complete -c ghfs -l index-dir -d '<value>  file system path that allow index fi'
complete -c ghfs -l index-dir-user -d '<value>  file system path that allow index files for specific users, <sep><fs-path>[<sep><user>.'
complete -c ghfs -l upload-user -d '<value>  url path that allow upload files for specific users, <sep><url-path>[<sep><user>.'
complete -c ghfs -l upload-dir-user -d '<value>  file system path that allow upload files for specific users, <sep><fs-path>[<sep><user>.'
complete -c ghfs -l global-mk -d 'allow mkdir files for all url pa'
complete -c ghfs -l mkdir -d '<value>  url path that allow mkdir fi'
complete -c ghfs -l mkdir-user -d '<value>  url path that allow mkdir files for specific users, <sep><url-path>[<sep><user>.'
complete -c ghfs -l mkdir-dir -d '<value>  file system path that allow mkdir fi'
complete -c ghfs -l mkdir-dir-user -d '<value>  file system path that allow mkdir files for specific users, <sep><fs-path>[<sep><user>.'
complete -c ghfs -l global-del -d 'allow delete files for all url pa'
complete -c ghfs -l delete -d '<value>  url path that allow delete fi'
complete -c ghfs -l delete-user -d '<value>  url path that allow delete files for specific users, <sep><url-path>[<sep><user>.'
complete -c ghfs -l delete-dir -d '<value>  file system path that allow delete fi'
complete -c ghfs -l delete-dir-user -d '<value>  file system path that allow delete files for specific users, <sep><fs-path>[<sep><user>.'
complete -c ghfs -l archive -d '<value>  url path that enable download as archive for specific director'
complete -c ghfs -l archive-user -d '<value>  url path that allow archive files for specific users, <sep><url-path>[<sep><user>.'
complete -c ghfs -l archive-dir -d '<value>  file system path that enable download as archive for specific director'
complete -c ghfs -l archive-dir-user -d '<value>  file system path that allow archive files for specific users, <sep><fs-path>[<sep><user>.'
complete -c ghfs -l global-c -d 'enable CORS headers for all director'
complete -c ghfs -l cors -d '<value>  url path that enable CORS head'
complete -c ghfs -l cors-dir -d '<value>  file system path that enable CORS head'
complete -c ghfs -l global-restrict-access -d '<value>  restrict access to all url paths from current host, with optional extra allow l'
complete -c ghfs -l restrict-access -d '<value>  restrict access to specific url paths from current host, with optional extra allow list, <sep><url-path>[<sep><allowed-host>.'
complete -c ghfs -l restrict-access-dir -d '<value>  restrict access to specific file system paths from current host, with optional extra allow list, <sep><fs-path>[<sep><allowed-host>.'
complete -c ghfs -l global-header -d '<value>  custom headers for all url paths, e.g. <name>:<val'
complete -c ghfs -l header -d '<value>  url path for custom headers, <sep><url><sep><name><sep><val'
complete -c ghfs -l header-dir -d '<value>  file system path for custom headers, <sep><dir><sep><name><sep><val'
complete -c ghfs -l listen-plain -d '<value>  address and port to listen, force plain http proto'
complete -c ghfs -l listen-tls -d '<value>  address and port to listen, force https proto'
complete -c ghfs -l hostname -d '<value>  hostname for the virtual h'
complete -c ghfs -l theme -d '<val external theme f'
complete -c ghfs -l theme-dir -d '<val external theme direct'
complete -c ghfs -l hsts -d '<val enable HSTS(HTTP Strict Transport Securi'
complete -c ghfs -l to-https -d '<val redirect http:// to https://, with optional target p'
complete -c ghfs -l config -d '<val external config f'
complete -c ghfs -l vers -d 'print vers'
