complete -c gtar -s c -l create -d 'create a new archive'
complete -c gtar -l delete -d 'delete from the archive (not on mag tapes!)'
complete -c gtar -s r -l append -d 'append files to the end of an archive'
complete -c gtar -l test-label -d 'test the archive volume label and exit'
complete -c gtar -s t -l list -d 'list the contents of an archive'
complete -c gtar -s u -l update -d 'only append files newer than copy in archive'
complete -c gtar -l check-device -d 'check device numbers when creating incremental'
complete -c gtar -s G -l incremental -d 'handle old GNU-format incremental backup'
complete -c gtar -l ignore-failed-read -d 'do not exit with nonzero on unreadable files'
complete -c gtar -l no-check-device -d 'do not check device numbers when creating'
complete -c gtar -l no-seek -d 'archive is not seekable'
complete -c gtar -s n -l seek -d 'archive is seekable'
complete -f -c gtar -n __fish_use_subcommand -a the -d '-T option; NUMBER defaults to 1'
complete -f -c gtar -n __fish_use_subcommand -a --sparse-version -d 'MAJOR[.MINOR]'
complete -f -c gtar -n __fish_use_subcommand -a set -d 'version of the sparse format to use (implies'
complete -c gtar -s S -l sparse -d 'handle sparse files efficiently'
complete -c gtar -l exclude-backups -d 'exclude backup and lock files'
complete -c gtar -l exclude-caches -d 'exclude contents of directories containing'
complete -c gtar -l exclude-caches-all -d 'exclude directories containing CACHEDIR.TAG'
complete -c gtar -l exclude-caches-under -d 'exclude everything under directories containing'
complete -c gtar -l exclude-vcs -d 'exclude version control system directories'
complete -c gtar -l exclude-vcs-ignores -d 'read exclude patterns from the VCS ignore files'
complete -c gtar -l no-null -d 'disable the effect of the previous --null option'
complete -c gtar -l no-recursion -d 'avoid descending automatically in directories'
complete -c gtar -l no-unquote -d 'do not unquote input file or member names'
complete -c gtar -l no-verbatim-files-from -d '-T treats file names starting with dash as'
complete -c gtar -l null -d '-T reads null-terminated names; implies'
complete -c gtar -l recursion -d 'recurse into directories (default)'
complete -c gtar -l unquote -d 'unquote input file or member names (default)'
complete -c gtar -l verbatim-files-from -d '-T reads file names verbatim (no escape or option'
complete -c gtar -l anchored -d 'patterns match file name start'
complete -c gtar -l ignore-case -d 'ignore case'
complete -c gtar -l no-anchored -d patterns\ match\ after\ any\ \'/\'\ \(default\ for
complete -c gtar -l no-ignore-case -d 'case sensitive matching (default)'
complete -c gtar -l no-wildcards -d 'verbatim string matching'
complete -c gtar -l no-wildcards-match-slash -d wildcards\ do\ not\ match\ \'/\'
complete -c gtar -l wildcards -d 'use wildcards (default for exclusion)'
complete -c gtar -l wildcards-match-slash -d wildcards\ match\ \'/\'\ \(default\ for\ exclusion\)
complete -c gtar -l keep-directory-symlink -d 'preserve existing symlinks to directories when'
complete -c gtar -l keep-newer-files -d don\'t\ replace\ existing\ files\ that\ are\ newer\ than
complete -c gtar -s k -l keep-old-files -d don\'t\ replace\ existing\ files\ when\ extracting,
complete -c gtar -l no-overwrite-dir -d 'preserve metadata of existing directories'
complete -c gtar -l overwrite -d 'overwrite existing files when extracting'
complete -c gtar -l overwrite-dir -d 'overwrite metadata of existing directories when'
complete -c gtar -l recursive-unlink -d 'empty hierarchies prior to extracting directory'
complete -c gtar -l remove-files -d 'remove files after adding them to the archive'
complete -c gtar -l skip-old-files -d don\'t\ replace\ existing\ files\ when\ extracting,
complete -c gtar -s U -l unlink-first -d 'remove each file prior to extracting over it'
complete -c gtar -s W -l verify -d 'attempt to verify the archive after writing it'
complete -c gtar -l ignore-command-error -d 'ignore exit codes of children'
complete -c gtar -l no-ignore-command-error -d 'treat non-zero exit codes of children as'
complete -c gtar -s O -l to-stdout -d 'extract files to standard output'
complete -c gtar -l clamp-mtime -d 'only set time when the file is more recent than'
complete -c gtar -l delay-directory-restore -d 'delay setting modification times and'
complete -c gtar -s m -l touch -d don\'t\ extract\ file\ modified\ time
complete -c gtar -l no-same-owner -d 'extract files as yourself (default for ordinary'
complete -c gtar -l no-same-permissions -d apply\ the\ user\'s\ umask\ when\ extracting\ permissions
complete -c gtar -l numeric-owner -d 'always use numbers for user/group names'
complete -c gtar -l same-owner -d 'try extracting files with the same ownership as'
complete -c gtar -l acls -d 'Enable the POSIX ACLs support'
complete -c gtar -l no-acls -d 'Disable the POSIX ACLs support'
complete -c gtar -l no-selinux -d 'Disable the SELinux context support'
complete -c gtar -l no-xattrs -d 'Disable extended attributes support'
complete -c gtar -l selinux -d 'Enable the SELinux context support'
complete -c gtar -l xattrs -d 'Enable extended attributes support'
complete -c gtar -l force-local -d 'archive file is local even if it has a colon'
complete -c gtar -s M -l multi-volume -d 'create/list/extract multi-volume archive'
complete -c gtar -s B -l read-full-records -d 'reblock as we read (for 4.2BSD pipes)'
complete -c gtar -s i -l ignore-zeros -d 'ignore zeroed blocks in archive (means EOF)'
complete -c gtar -l posix -d 'same as --format=posix'
complete -c gtar -s a -l auto-compress -d 'use archive suffix to determine the compression'
complete -c gtar -s j -l bzip2 -d 'filter the archive through bzip2'
complete -c gtar -s J -l xz -d 'filter the archive through xz'
complete -c gtar -l lzip -d 'filter the archive through lzip'
complete -c gtar -l lzma -d 'filter the archive through lzma'
complete -c gtar -l lzop -d 'filter the archive through lzop'
complete -c gtar -l no-auto-compress -d 'do not use archive suffix to determine the'
complete -c gtar -l zstd -d 'filter the archive through zstd'
complete -c gtar -l hard-dereference -d 'follow hard links; archive and dump the files they'
complete -c gtar -s h -l dereference -d 'follow symlinks; archive and dump the files they'
complete -c gtar -l one-file-system -d 'stay in local file system when creating archive'
complete -c gtar -s P -l absolute-names -d don\'t\ strip\ leading\ \'/\'s\ from\ file\ names
complete -c gtar -l full-time -d 'print file time to its full resolution'
complete -c gtar -s l -l check-links -d 'print a message if not all links are dumped'
complete -c gtar -s R -l block-number -d 'show block number within archive with each message'
complete -c gtar -l show-defaults -d 'show tar defaults'
complete -c gtar -l show-omitted-dirs -d 'when listing or extracting, list each directory'
complete -c gtar -l utc -d 'print file modification times in UTC'
complete -c gtar -s v -l verbose -d 'verbosely list files processed'
complete -c gtar -s o -d 'when creating, same as --old-archive; when'
complete -c gtar -l restrict -d 'disable use of some potentially harmful options'
complete -c gtar -l usage -d 'give a short usage message'
complete -c gtar -n __fish_no_arguments -l version -d 'print program version'
