complete -c harx -s l -d 'List files,            lead by [index]'
complete -c harx -l lu -d 'urlPattern            List files filtered by UrlPattern'
complete -c harx -l lm -d 'mimetypePattern       List files filtered by response Mimetype'
complete -c harx -s x -d 'dir                    eXtract all content to [dir]'
complete -c harx -l xi -d 'index                 eXtract the [index] content to stdout , need run with -l first to get [index]'
complete -c harx -l xu -d 'urlPattern      dir   eXtract to [dir] with UrlPattern filter'
complete -c harx -l xm -d 'mimetypePattern dir   eXtract to [dir] with MimetypePattern filter'
complete -c harx -l xmd -d 'mimetypePattern dir   eXtract to [dir] Directly without hostname and path info, with MimetypePattern filter'
complete -c harx -s v -d 'Print version information'
