complete -c ig -l editor -d '<EDITOR>         Text editor used to open selected match [possible values: vim,'
complete -c ig -s g -l glob -d '<GLOB>             Include files and directories for searching that match the given'
complete -c ig -s h -l help -d 'Print help information'
complete -c ig -s i -l ignore-case -d 'Searches case insensitively'
complete -c ig -s S -l smart-case -d 'Searches case insensitively if the pattern is all lowercase.'
complete -c ig -s t -l type -d '<TYPE_MATCHING>    Only search files matching TYPE. Multiple types may be provided'
complete -c ig -s T -l type-not -d '<TYPE_NOT>     Do not search files matching TYPE-NOT. Multiple types-not may be'
complete -c ig -l theme -d '<THEME>           UI color theme [default: dark] [possible values: light, dark]'
complete -c ig -l type-list -d 'Show all supported file types and their corresponding globs'
complete -c ig -n __fish_no_arguments -s V -l version -d 'Print version information'
