complete -c lzbench -s b0 -d 'set block/chunk size to 0 KB (default = MIN(filesize,1747626 KB))'
complete -c lzbench -s c0 -d 'sort results by column 0 (1=algname, 2=ctime, 3=dtime, 4=comprsize)'
complete -c lzbench -s e0 -d 0=compressors\ separated\ by\ \'/\'\ with\ parameters\ specified\ after\ \',\'\ \(deflt=fast\)
complete -c lzbench -s j -d 'join files in memory but compress them independently (for many small files)'
complete -c lzbench -s l -d 'list of available compressors and aliases'
complete -c lzbench -s R -d 'read block/chunk size from random blocks (to estimate for large files)'
complete -c lzbench -s m0 -d 'set memory limit to 0 MB (default = no limit)'
complete -c lzbench -s o0 -d 'output text format 1=Markdown, 2=text, 3=text+origSize, 4=CSV (default = 2)'
complete -c lzbench -s p0 -d 'print time for all iterations: 1=fastest 2=average 3=median (default = 1)'
complete -c lzbench -s r -d 'operate recursively on directories'
complete -c lzbench -s s0 -d 'use only compressors with compression speed over 0 MB (default = 0 MB)'
complete -c lzbench -s v -d 'disable progress information'
complete -c lzbench -s x -d 'disable real-time process priority'
complete -c lzbench -s z -d 'show (de)compression times instead of speed'
