complete -c madge -n __fish_no_arguments -s V -l version -d 'output the version number'
complete -c madge -s b -l basedir -d '<path>     base directory for resolving paths'
complete -c madge -s s -l summary -d 'show dependency count summary'
complete -c madge -s c -l circular -d 'show circular dependencies'
complete -c madge -s d -l depends -d '<name>     show module dependents'
complete -c madge -s x -l exclude -d '<regexp>   exclude modules using RegExp'
complete -c madge -s j -l json -d 'output as JSON'
complete -c madge -s i -l image -d '<file>       write graph to file as an image'
complete -c madge -s l -l layout -d '<name>      layout engine to use for graph'
complete -c madge -l orphans -d 'show modules that no one is depending on'
complete -c madge -l leaves -d 'show modules that have no dependencies'
complete -c madge -l dot -d 'show graph using the DOT language'
complete -c madge -l rankdir -d '<direction>    set the direction of the graph layout'
complete -c madge -l extensions -d '<list>      comma separated string of valid file extensions'
complete -c madge -l require-config -d '<file>  path to RequireJS config'
complete -c madge -l webpack-config -d '<file>  path to webpack config'
complete -c madge -l ts-config -d '<file>       path to typescript config'
complete -c madge -l include-npm -d 'include shallow NPM modules (default: false)'
complete -c madge -l no-color -d 'disable color in output and image'
complete -c madge -l no-spinner -d 'disable progress spinner'
complete -c madge -l stdin -d 'read predefined tree from STDIN (default: false)'
complete -c madge -l warning -d 'show warnings about skipped files (default: false)'
complete -c madge -l debug -d 'turn on debug output (default: false)'
complete -c madge -s h -l help -d 'display help for command'
