complete -c mongoimport -l help -d 'print usage'
complete -c mongoimport -n __fish_no_arguments -l version -d 'print the tool version and exit'
complete -c mongoimport -l quiet -d 'hide all log output'
complete -c mongoimport -l ssl -d 'connect to a mongod or mongos that has ssl enabled'
complete -c mongoimport -l sslFIPSMode -d 'use FIPS mode of the installed openssl library'
complete -c mongoimport -l tlsInsecure -d bypass\ the\ validation\ for\ server\'s\ certificate\ chain
complete -c mongoimport -l headerline -d 'use first line in input source as the field list'
complete -c mongoimport -l jsonArray -d 'treat input source as a JSON array'
complete -c mongoimport -l columnsHaveTypes -d 'indicates that the field list (from --fields,'
complete -c mongoimport -l legacy -d 'use the legacy extended JSON format'
complete -c mongoimport -l useArrayIndexFields -d 'indicates that field names may include array indexes'
complete -c mongoimport -l drop -d 'drop collection before inserting documents'
complete -c mongoimport -l ignoreBlanks -d 'ignore fields with empty values in CSV and TSV'
complete -c mongoimport -l maintainInsertionOrder -d 'insert the documents in the order of their'
complete -c mongoimport -l stopOnError -d 'and restricts NumInsertionWorkers to 1.'
complete -c mongoimport -l stopOnError -d 'halt after encountering any error during importing.'
complete -c mongoimport -l mode -d 'is set to upsert or merge'
complete -c mongoimport -l writeConcern -d \'\{w:\ 3,\ wtimeout:\ 500,\ fsync:\ true,
complete -c mongoimport -l bypassDocumentValidation -d 'bypass document validation'
