complete -c mongod -l networkMessageCompressors -d 'arg (=snappy,zstd,zlib)'
complete -c mongod -s h -d '[ --help ]                         Show this usage information'
complete -c mongod -n __fish_no_arguments -l version -d 'Show version information'
complete -c mongod -s f -d '[ --config ] arg                   Configuration file specifying'
complete -c mongod -l configExpand -d 'arg                    Process expansion directives in config'
complete -c mongod -l port -d 'arg                            Specify port number - 27017 by default'
complete -c mongod -l ipv6 -d 'Enable IPv6 support (disabled by'
complete -c mongod -l listenBacklog -d 'arg (=128)            Set socket listen backlog size'
complete -c mongod -l maxConns -d 'arg (=1000000)             Max number of simultaneous connections'
complete -c mongod -l pidfilepath -d 'arg                     Full path to pidfile (if not set, no'
complete -c mongod -l timeZoneInfo -d 'arg                    Full path to time zone info directory,'
complete -c mongod -l nounixsocket -d 'Disable listening on unix sockets'
complete -c mongod -l unixSocketPrefix -d 'arg                Alternative directory for UNIX domain'
complete -c mongod -l filePermissions -d 'arg                 Permissions to set on UNIX domain'
complete -c mongod -l fork -d 'Fork server process'
complete -c mongod -s v -d '[ --verbose ] [=arg(=v)]           Be more verbose (include multiple times'
complete -c mongod -l quiet -d 'Quieter output'
complete -c mongod -l logpath -d 'arg                         Log file to send write to instead of'
complete -c mongod -l syslog -d Log\ to\ system\'s\ syslog\ facility\ instead
complete -c mongod -l syslogFacility -d 'arg                  syslog facility used for mongodb syslog'
complete -c mongod -l logappend -d 'Append to logpath instead of'
complete -c mongod -l logRotate -d 'arg                       Set the log rotation behavior'
complete -c mongod -l timeStampFormat -d 'arg                 Desired format for timestamps in log'
complete -c mongod -l setParameter -d 'arg                    Set a configurable parameter'
complete -c mongod -l bind_ip -d 'arg                         Comma separated list of ip addresses to'
complete -c mongod -l bind_ip_all -d 'Bind to all ip addresses'
complete -c mongod -l noauth -d 'Run without security'
complete -c mongod -l transitionToAuth -d 'For rolling access control upgrade.'
complete -c mongod -l slowms -d 'arg (=100)                   Value of slow for profile and console'
complete -c mongod -l slowOpSampleRate -d 'arg (=1)           Fraction of slow ops to include in the'
complete -c mongod -l profileFilter -d 'arg                   Query predicate to control which'
complete -c mongod -l auth -d 'Run with security'
complete -c mongod -l clusterIpSourceAllowlist -d 'arg        Network CIDR specification of permitted'
complete -c mongod -l profile -d 'arg                         0=off 1=slow, 2=all'
complete -c mongod -l cpu -d 'Periodically show cpu and iowait'
complete -c mongod -l sysinfo -d 'Print some diagnostic system'
complete -c mongod -l noscripting -d 'Disable scripting engine'
complete -c mongod -l notablescan -d 'Do not allow table scans'
complete -c mongod -l keyFile -d 'arg                         Private key for cluster authentication'
complete -c mongod -l clusterAuthMode -d 'arg                 Authentication mode used for cluster'
complete -c mongod -l oplogSize -d 'arg                       Size to use (in MB) for replication op'
complete -c mongod -l replSet -d 'arg                         arg is <setname>[/<optionalseedhostlist'
complete -c mongod -l enableMajorityReadConcern -d '[=arg(=1)] (=1)'
complete -c mongod -l serverless -d 'arg                      Serverless mode implies replication is'
complete -c mongod -l configsvr -d 'Declare this is a config db of a'
complete -c mongod -l shardsvr -d 'Declare this is a shard db of a'
complete -c mongod -l storageEngine -d 'arg                   What storage engine to use - defaults'
complete -c mongod -l dbpath -d 'arg                          Directory for datafiles - defaults to'
complete -c mongod -l directoryperdb -d 'Each database will be stored in a'
complete -c mongod -l syncdelay -d 'arg (=60)                 Seconds between disk syncs'
complete -c mongod -l journalCommitInterval -d 'arg (=100)    how often to group/batch commit (ms)'
complete -c mongod -l upgrade -d 'Upgrade db if needed'
complete -c mongod -l repair -d 'Run repair on all dbs'
complete -c mongod -l restore -d 'This should only be used when restoring'
complete -c mongod -l oplogMinRetentionHours -d 'arg (=0)     Minimum number of hours to preserve in'
complete -c mongod -l wiredTigerCacheSizeGB -d 'arg           Maximum amount of memory to allocate'
complete -c mongod -l zstdDefaultCompressionLevel -d 'arg (=6)'
complete -c mongod -l wiredTigerJournalCompressor -d 'arg (=snappy)'
complete -c mongod -l wiredTigerDirectoryForIndexes -d 'Put indexes and data in different'
complete -c mongod -l wiredTigerCollectionBlockCompressor -d 'arg (=snappy)'
complete -c mongod -l wiredTigerIndexPrefixCompression -d 'arg (=1)'
complete -c mongod -l tlsOnNormalPorts -d 'Use TLS on configured ports'
complete -c mongod -l tlsMode -d 'arg                         Set the TLS operation mode'
complete -c mongod -l tlsCertificateKeyFile -d 'arg           Certificate and key file for TLS.'
complete -c mongod -l tlsCertificateKeyFilePassword -d 'arg   Password to unlock key in the TLS'
complete -c mongod -l tlsClusterFile -d 'arg                  Certificate and key file for internal'
complete -c mongod -l tlsClusterPassword -d 'arg              Internal authentication key file'
complete -c mongod -l tlsCAFile -d 'arg                       Certificate Authority file for TLS.'
complete -c mongod -l tlsClusterCAFile -d 'arg                CA used for verifying remotes during'
complete -c mongod -l tlsCRLFile -d 'arg                      Certificate Revocation List file for'
complete -c mongod -l tlsDisabledProtocols -d 'arg            Comma separated list of TLS protocols'
complete -c mongod -l tlsAllowConnectionsWithoutCertificates
complete -c mongod -l tlsAllowInvalidHostnames -d 'Allow server certificates to provide'
complete -c mongod -l tlsAllowInvalidCertificates -d 'Allow connections to servers with'
complete -c mongod -l tlsCertificateSelector -d 'arg          TLS Certificate in system store'
complete -c mongod -l tlsClusterCertificateSelector -d 'arg   SSL/TLS Certificate in system store for'
complete -c mongod -l tlsLogVersions -d 'arg                  Comma separated list of TLS protocols'
complete -c mongod -l tlsClusterAuthX509ExtensionValue -d arg
complete -c mongod -l tlsClusterAuthX509Attributes -d 'arg    If specified, clients performing X.509'
complete -c mongod -l awsIamSessionToken -d 'arg              AWS Session Token for temporary'
