complete -c mysql2sqlite -s f -l sqlite-file -d 'PATH          SQLite3 database file  [required]'
complete -c mysql2sqlite -s d -l mysql-database -d 'TEXT       MySQL database name  [required]'
complete -c mysql2sqlite -s u -l mysql-user -d 'TEXT           MySQL user  [required]'
complete -c mysql2sqlite -s p -l prompt-mysql-password -d 'Prompt for MySQL password'
complete -c mysql2sqlite -l mysql-password -d 'TEXT           MySQL password'
complete -c mysql2sqlite -s t -l mysql-tables -d 'TUPLE        Transfer only these specific tables (space'
complete -c mysql2sqlite -s e -l exclude-mysql-tables -d TUPLE
complete -c mysql2sqlite -s L -l limit-rows -d 'INTEGER        Transfer only a limited number of rows from'
complete -c mysql2sqlite -s C -l collation -d '[BINARY|NOCASE|RTRIM]'
complete -c mysql2sqlite -s K -l prefix-indices -d 'Prefix indices with their corresponding'
complete -c mysql2sqlite -s X -l without-foreign-keys -d 'Do not transfer foreign keys.'
complete -c mysql2sqlite -s Z -l without-tables -d 'Do not transfer tables, data only.'
complete -c mysql2sqlite -s W -l without-data -d 'Do not transfer table data, DDL only.'
complete -c mysql2sqlite -s h -l mysql-host -d 'TEXT           MySQL host. Defaults to localhost.'
complete -c mysql2sqlite -s P -l mysql-port -d 'INTEGER        MySQL port. Defaults to 3306.'
complete -c mysql2sqlite -s S -l skip-ssl -d 'Disable MySQL connection encryption.'
complete -c mysql2sqlite -s c -l chunk -d 'INTEGER             Chunk reading/writing SQL records'
complete -c mysql2sqlite -s l -l log-file -d 'PATH             Log file'
complete -c mysql2sqlite -l json-as-text -d 'Transfer JSON columns as TEXT.'
complete -c mysql2sqlite -s V -l vacuum -d 'Use the VACUUM command to rebuild the SQLite'
complete -c mysql2sqlite -l use-buffered-cursors -d 'Use MySQLCursorBuffered for reading the'
complete -c mysql2sqlite -s q -l quiet -d 'Quiet. Display only errors.'
complete -c mysql2sqlite -l debug -d 'Debug mode. Will throw exceptions.'
complete -c mysql2sqlite -n __fish_no_arguments -l version -d 'Show the version and exit.'
complete -c mysql2sqlite -l help -d 'Show this message and exit.'
