complete -c noti -s t -l title -d 'string     Set notification title. Default is utility name.'
complete -c noti -s m -l message -d 'string   Set notification message. Default is "Done!". Read from stdin with "-".'
complete -c noti -s e -l time -d 'Show execution time in message.'
complete -c noti -s b -l banner -d 'Trigger a banner notification. This is enabled by default.'
complete -c noti -s s -l speech -d 'Trigger a speech notification.'
complete -c noti -s c -l bearychat -d 'Trigger a BearyChat notification.'
complete -c noti -l keybase -d 'Trigger a Keybase notification.'
complete -c noti -s p -l pushbullet -d 'Trigger a Pushbullet notification.'
complete -c noti -s o -l pushover -d 'Trigger a Pushover notification.'
complete -c noti -s u -l pushsafer -d 'Trigger a Pushsafer notification.'
complete -c noti -s l -l simplepush -d 'Trigger a Simplepush notification.'
complete -c noti -s k -l slack -d 'Trigger a Slack notification.'
complete -c noti -s n -l gchat -d 'Trigger a Google Chat notification.'
complete -c noti -s a -l mattermost -d 'Trigger a Mattermost notification'
complete -c noti -s g -l telegram -d 'Trigger a Telegram notification'
complete -c noti -s z -l zulip -d 'Trigger a Zulip notification'
complete -c noti -l twilio -d 'Trigger a twilio SMS notification'
complete -c noti -s w -l pwatch -d 'int       Monitor a process by PID and trigger a notification when the pid disappears. (default -1)'
complete -c noti -s f -l file -d 'string      Path to noti.yaml configuration file.'
complete -c noti -l verbose -d 'Enable verbose mode.'
complete -c noti -n __fish_no_arguments -s v -l version -d 'Print noti version and exit.'
complete -c noti -s h -l help -d 'Print noti help and exit.'
