complete -c pgcli -s h -l host -d 'TEXT         Host address of the postgres database.'
complete -c pgcli -s p -l port -d 'INTEGER      Port number at which the postgres instance is'
complete -c pgcli -s U -l username -d 'TEXT     Username to connect to the postgres database.'
complete -c pgcli -s u -l user -d 'TEXT         Username to connect to the postgres database.'
complete -c pgcli -s W -l password -d 'Force password prompt.'
complete -c pgcli -s w -l no-password -d 'Never prompt for password.'
complete -c pgcli -l single-connection -d 'Do not use a separate connection for completions.'
complete -c pgcli -n __fish_no_arguments -s v -l version -d 'Version of pgcli.'
complete -c pgcli -s d -l dbname -d 'TEXT       database name to connect to.'
complete -c pgcli -l pgclirc -d 'FILE          Location of pgclirc file.'
complete -c pgcli -s D -l dsn -d 'TEXT          Use DSN configured into the [alias_dsn] section of'
complete -c pgcli -l list-dsn -d 'list of DSN configured into the [alias_dsn] section'
complete -c pgcli -l row-limit -d 'INTEGER     Set threshold for row limit prompt. Use 0 to disable'
complete -c pgcli -l less-chatty -d 'Skip intro on startup and goodbye on exit.'
complete -c pgcli -l prompt -d TEXT\ \ \ \ \ \ \ \ \ \ \ Prompt\ format\ \(Default:\ \"\\u@\\h:\\d\>\ \"\).
complete -c pgcli -l prompt-dsn -d 'TEXT       Prompt format for connections using DSN aliases'
complete -c pgcli -s l -l list -d 'list available databases, then exit.'
complete -c pgcli -l auto-vertical-output -d 'Automatically switch to vertical output mode if the'
complete -c pgcli -l warn -d 'TEXT             Warn before running a destructive query.'
complete -c pgcli -l ssh-tunnel -d 'TEXT       Open an SSH tunnel to the given address and connect'
complete -c pgcli -l help -d 'Show this message and exit.'
