complete -f -c pqrs -n __fish_use_subcommand -a cat -d 'Prints the contents of Parquet file(s)'
complete -c pqrs -n '__fish_seen_subcommand_from cat' -s c -l csv -d 'Use CSV format for printing'
complete -c pqrs -n '__fish_seen_subcommand_from cat' -l no-header -d 'Use CSV format without a header for printing'
complete -c pqrs -n '__fish_seen_subcommand_from cat' -s j -l json -d 'Use JSON lines format for printing'
complete -c pqrs -n '__fish_seen_subcommand_from cat' -s h -l help -d 'Print help'
complete -f -c pqrs -n __fish_use_subcommand -a head -d 'Prints the first n records of the Parquet file'
complete -c pqrs -n '__fish_seen_subcommand_from head' -s c -l csv -d 'Use CSV format for printing'
complete -c pqrs -n '__fish_seen_subcommand_from head' -s j -l json -d 'Use JSON lines format for printing'
complete -c pqrs -n '__fish_seen_subcommand_from head' -s n -l records -d '<RECORDS>  The number of records to show (default: 5) [default: 5]'
complete -c pqrs -n '__fish_seen_subcommand_from head' -s h -l help -d 'Print help'
complete -f -c pqrs -n __fish_use_subcommand -a merge -d 'Merge file(s) into another parquet file'
complete -c pqrs -n '__fish_seen_subcommand_from merge' -s i -l input -d '<INPUT>...  Parquet files to read'
complete -c pqrs -n '__fish_seen_subcommand_from merge' -s o -l output -d '<OUTPUT>   Parquet file to write'
complete -c pqrs -n '__fish_seen_subcommand_from merge' -s h -l help -d 'Print help'
complete -f -c pqrs -n __fish_use_subcommand -a row-count -d 'Prints the count of rows in Parquet file(s)'
complete -c pqrs -n '__fish_seen_subcommand_from row-count' -s h -l help -d 'Print help'
complete -f -c pqrs -n __fish_use_subcommand -a sample -d 'Prints a random sample of records from the Parquet file'
complete -c pqrs -n '__fish_seen_subcommand_from sample' -s j -l json -d 'Use JSON lines format for printing'
complete -c pqrs -n '__fish_seen_subcommand_from sample' -s n -l records -d '<RECORDS>  The number of records to sample'
complete -c pqrs -n '__fish_seen_subcommand_from sample' -s h -l help -d 'Print help'
complete -f -c pqrs -n __fish_use_subcommand -a schema -d 'Prints the schema of Parquet file(s)'
complete -c pqrs -n '__fish_seen_subcommand_from schema' -s D -l detailed -d 'Enable printing full file metadata'
complete -c pqrs -n '__fish_seen_subcommand_from schema' -s j -l json -d 'Print in JSON format'
complete -c pqrs -n '__fish_seen_subcommand_from schema' -s h -l help -d 'Print help'
complete -f -c pqrs -n __fish_use_subcommand -a size -d 'Prints the size of Parquet file(s)'
complete -c pqrs -n '__fish_seen_subcommand_from size' -s p -l pretty -d 'Show pretty, human readable size'
complete -c pqrs -n '__fish_seen_subcommand_from size' -s c -l compressed -d 'Show compressed size'
complete -c pqrs -n '__fish_seen_subcommand_from size' -s h -l help -d 'Print help'
complete -f -c pqrs -n __fish_use_subcommand -a help -d 'Print this message or the help of the given subcommand(s)'
complete -c pqrs -s d -l debug -d 'Show debug output'
complete -c pqrs -s h -l help -d 'Print help'
complete -c pqrs -n __fish_no_arguments -s V -l version -d 'Print version'
