complete -c prettybat -l nonprintable-notation -d '<notation>'
complete -c prettybat -s l -l language -d '<language>'
complete -c prettybat -s H -l highlight-line -d '<N:M>'
complete -c prettybat -l file-name -d '<name>'
complete -c prettybat -l diff-context -d '<N>'
complete -c prettybat -l tabs -d '<T>'
complete -c prettybat -l wrap -d '<mode>'
complete -c prettybat -l terminal-width -d '<width>'
complete -c prettybat -l color -d '<when>'
complete -c prettybat -l italic-text -d '<when>'
complete -c prettybat -l decorations -d '<when>'
complete -c prettybat -l paging -d '<when>'
complete -c prettybat -l pager -d '<command>'
complete -c prettybat -s m -l map-syntax -d '<glob:syntax>'
complete -c prettybat -s m -d \'\*.build:Python\'.\ To\ highlight\ files\ named\ \'.myignore\'\ with\ the\ Git\ Ignore\ syntax,\ use
complete -c prettybat -s m -d \'.myignore:Git\ Ignore\'.\ Note\ that\ the\ right-hand\ side\ is\ the\ \*name\*\ of\ the\ syntax,\ not
complete -c prettybat -l ignored-suffix -d '<ignored-suffix>'
complete -c prettybat -l theme -d '<theme>'
complete -c prettybat -l style -d '<components>'
complete -c prettybat -s r -l line-range -d '<N:M>'
