complete -c recode -s T -l find-subsets -d 'report all charsets being subset of others'
complete -c recode -s C -l copyright -d 'display copyright and copying conditions'
complete -c recode -l help -d 'display this help and exit'
complete -c recode -n __fish_no_arguments -l version -d 'output version information and exit'
complete -c recode -s v -l verbose -d 'explain sequence of steps and report progress'
complete -c recode -s f -l force -d 'force recodings even when not reversible'
complete -c recode -s t -l touch -d 'touch the recoded files after replacement'
complete -c recode -s s -l strict -d 'use strict mappings; discard untranslatable characters'
complete -c recode -s d -l diacritics -d 'convert only diacritics and special characters for'
complete -c recode -s c -l colons -d 'use colons instead of double quotes for diaeresis'
complete -c recode -s g -l graphics -d 'approximate IBMPC rulers by ASCII graphics'
complete -c recode -s I -l prefer-iconv -d 'use iconv if possible'
