complete -c rqlited -s auth -d string
complete -c rqlited -s auto-backup -d string
complete -c rqlited -s auto-restore -d string
complete -c rqlited -s auto-vacuum-int -d duration
complete -c rqlited -s bootstrap-expect -d int
complete -c rqlited -s bootstrap-expect-timeout -d duration
complete -c rqlited -s cluster-connect-timeout -d duration
complete -c rqlited -s cpu-profile -d string
complete -c rqlited -s disco-config -d string
complete -c rqlited -s disco-key -d string
complete -c rqlited -s disco-mode -d string
complete -c rqlited -s http-addr -d string
complete -c rqlited -s http-adv-addr -d string
complete -c rqlited -s http-allow-origin -d string
complete -c rqlited -s http-ca-cert -d string
complete -c rqlited -s http-cert -d string
complete -c rqlited -s http-key -d string
complete -c rqlited -s join -d string
complete -c rqlited -s join-as -d string
complete -c rqlited -s join-attempts -d int
complete -c rqlited -s join-interval -d duration
complete -c rqlited -s mem-profile -d string
complete -c rqlited -s node-ca-cert -d string
complete -c rqlited -s node-cert -d string
complete -c rqlited -s node-id -d string
complete -c rqlited -s node-key -d string
complete -c rqlited -s node-verify-server-name -d string
complete -c rqlited -s on-disk-path -d string
complete -c rqlited -s raft-addr -d string
complete -c rqlited -s raft-adv-addr -d string
complete -c rqlited -s raft-apply-timeout -d duration
complete -c rqlited -s raft-election-timeout -d duration
complete -c rqlited -s raft-leader-lease-timeout -d duration
complete -c rqlited -s raft-log-level -d string
complete -c rqlited -s raft-reap-node-timeout -d duration
complete -c rqlited -s raft-reap-read-only-node-timeout -d duration
complete -c rqlited -s raft-snap -d uint
complete -c rqlited -s raft-snap-int -d duration
complete -c rqlited -s raft-snap-wal-size -d uint
complete -c rqlited -s raft-timeout -d duration
complete -c rqlited -s trace-profile -d string
complete -c rqlited -s write-queue-batch-size -d int
complete -c rqlited -s write-queue-capacity -d int
complete -c rqlited -s write-queue-timeout -d duration
