complete -c rs-duckdb-server -l cors -d 'Enable CORS'
complete -c rs-duckdb-server -l database -d '<DATABASE>      Database URL (default: :memory:). Can be set using the DATABASE'
complete -c rs-duckdb-server -l disable-http -d 'Disable HTTP'
complete -c rs-duckdb-server -l disable-ws -d 'Disable WebSockets'
complete -c rs-duckdb-server -s h -l help -d 'Print help information'
complete -c rs-duckdb-server -l http-host -d '<HTTP_HOST>    HTTP host (default: 127.0.0.1). Can be set using the HTTP_HOST'
complete -c rs-duckdb-server -l http-port -d '<HTTP_PORT>    HTTP port (default: 3000). Can be set using the HTTP_PORT'
complete -c rs-duckdb-server -l poolsize -d '<POOLSIZE>      Connection pool size (default: 16). Can be set using the POOLSIZE'
complete -c rs-duckdb-server -l tls-cert -d '<TLS_CERT>      TLS certificate file. Can be set using the TLS_CERT environment'
complete -c rs-duckdb-server -l tls-key -d '<TLS_KEY>        TLS key file. Can be set using the TLS_KEY environment variable'
complete -c rs-duckdb-server -n __fish_no_arguments -s V -l version -d 'Print version information'
