complete -c snazy -s r -l regexp -d '<REGEXP>'
complete -c snazy -s S -l skip-line-regexp -d '<SKIP_LINE_REGEXP>'
complete -c snazy -l shell-completion -d '<SHELL_COMPLETION>'
complete -c snazy -s f -l filter-levels -d '<FILTER_LEVELS>'
complete -c snazy -s c -l color -d '<when>'
complete -c snazy -l time-format -d '<TIME_FORMAT>'
complete -c snazy -l kail-prefix-format -d '<KAIL_PREFIX_FORMAT>'
complete -c snazy -s k -l json-keys -d '<JSON_KEYS>'
complete -c snazy -l action-regexp -d '<ACTION_REGEXP>'
complete -c snazy -l action-command -d '<ACTION_COMMAND>'
