complete -f -c sttr -n __fish_use_subcommand -a ascii85-decode -d 'Decode your text to Ascii85 ( Base85 ) text'
complete -f -c sttr -n __fish_use_subcommand -a ascii85-encode -d 'Encode your text to Ascii85 ( Base85 )'
complete -f -c sttr -n __fish_use_subcommand -a base32-decode -d 'Decode your base32 text'
complete -f -c sttr -n __fish_use_subcommand -a base32-encode -d 'Encode your text to Base32'
complete -f -c sttr -n __fish_use_subcommand -a base64-decode -d 'Decode your base64 text'
complete -f -c sttr -n __fish_use_subcommand -a base64-encode -d 'Encode your text to Base64'
complete -f -c sttr -n __fish_use_subcommand -a base64url-decode -d 'Decode your base64 text with URL Safe'
complete -f -c sttr -n __fish_use_subcommand -a base64url-encode -d 'Encode your text to Base64 with URL Safe'
complete -f -c sttr -n __fish_use_subcommand -a bcrypt -d 'Get the Bcrypt hash of your text'
complete -f -c sttr -n __fish_use_subcommand -a camel -d 'Transform your text to CamelCase'
complete -f -c sttr -n __fish_use_subcommand -a completion -d 'Generate completion script'
complete -f -c sttr -n __fish_use_subcommand -a count-chars -d 'Find the length of your text (including spaces)'
complete -f -c sttr -n __fish_use_subcommand -a count-lines -d 'Count the number of lines in your text'
complete -f -c sttr -n __fish_use_subcommand -a count-words -d 'Count the number of words in your text'
complete -f -c sttr -n __fish_use_subcommand -a extract-emails -d 'Extract emails from given text'
complete -f -c sttr -n __fish_use_subcommand -a extract-ip -d 'Extract IPv4 and IPv6 from your text'
complete -f -c sttr -n __fish_use_subcommand -a hex-decode -d 'Convert Hexadecimal to String'
complete -f -c sttr -n __fish_use_subcommand -a hex-encode -d 'Encode your text Hex'
complete -f -c sttr -n __fish_use_subcommand -a hex-rgb -d 'Convert a #hex-color code to RGB'
complete -f -c sttr -n __fish_use_subcommand -a html-decode -d 'Unescape your HTML'
complete -f -c sttr -n __fish_use_subcommand -a html-encode -d 'Escape your HTML'
complete -f -c sttr -n __fish_use_subcommand -a interactive -d 'Use sttr in interactive mode'
complete -f -c sttr -n __fish_use_subcommand -a json -d 'Format your text as JSON ( json decode )'
complete -f -c sttr -n __fish_use_subcommand -a json-escape -d 'JSON Escape'
complete -f -c sttr -n __fish_use_subcommand -a json-msgpack -d 'Convert JSON to MSGPACK text'
complete -f -c sttr -n __fish_use_subcommand -a json-unescape -d 'JSON Unescape'
complete -f -c sttr -n __fish_use_subcommand -a json-yaml -d 'Convert JSON to YAML text'
complete -f -c sttr -n __fish_use_subcommand -a kebab -d 'Transform your text to kebab-case'
complete -f -c sttr -n __fish_use_subcommand -a lower -d 'Transform your text to lower case'
complete -f -c sttr -n __fish_use_subcommand -a markdown-html -d 'Convert Markdown to HTML'
complete -f -c sttr -n __fish_use_subcommand -a md5 -d 'Get the MD5 checksum of your text'
complete -f -c sttr -n __fish_use_subcommand -a morse-encode -d 'Decode Morse Code to text'
complete -f -c sttr -n __fish_use_subcommand -a msgpack-json -d 'Convert MSGPACK to JSON text'
complete -f -c sttr -n __fish_use_subcommand -a remove-newlines -d 'Remove all new lines'
complete -f -c sttr -n __fish_use_subcommand -a remove-spaces -d 'Remove all spaces + new lines'
complete -f -c sttr -n __fish_use_subcommand -a reverse -d 'Reverse Text ( txeT esreveR )'
complete -f -c sttr -n __fish_use_subcommand -a reverse-lines -d 'Reverse Lines'
complete -f -c sttr -n __fish_use_subcommand -a rot13-encode -d 'Encode your text to ROT13'
complete -f -c sttr -n __fish_use_subcommand -a sha1 -d 'Get the SHA1 checksum of your text'
complete -f -c sttr -n __fish_use_subcommand -a sha224 -d 'Get the SHA224 checksum of your text'
complete -f -c sttr -n __fish_use_subcommand -a sha256 -d 'Get the SHA256 checksum of your text'
complete -f -c sttr -n __fish_use_subcommand -a sha384 -d 'Get the SHA384 checksum of your text'
complete -f -c sttr -n __fish_use_subcommand -a sha512 -d 'Get the SHA512 checksum of your text'
complete -f -c sttr -n __fish_use_subcommand -a shuffle-lines -d 'Shuffle lines randomly'
complete -f -c sttr -n __fish_use_subcommand -a slug -d 'Transform your text to slug-case'
complete -f -c sttr -n __fish_use_subcommand -a snake -d 'Transform your text to snake_case'
complete -f -c sttr -n __fish_use_subcommand -a sort-lines -d 'Sort lines alphabetically'
complete -f -c sttr -n __fish_use_subcommand -a title -d 'Transform your text to Title Case'
complete -f -c sttr -n __fish_use_subcommand -a unique-lines -d 'Unique Lines'
complete -f -c sttr -n __fish_use_subcommand -a upper -d 'Transform your text to UPPER CASE'
complete -f -c sttr -n __fish_use_subcommand -a url-decode -d 'Decode URL entities'
complete -f -c sttr -n __fish_use_subcommand -a url-encode -d 'Encode URL entities'
complete -f -c sttr -n __fish_use_subcommand -a version -d 'Print the version of sttr'
complete -f -c sttr -n __fish_use_subcommand -a yaml-json -d 'Convert YAML to JSON text'
complete -f -c sttr -n __fish_use_subcommand -a zeropad -d 'Pad a number with zeros'
complete -c sttr -s h -l help -d 'help for sttr'
