string replace -a -- {} undatum  {} --help
complete -c undatum -l help -d 'Show this message and exit.'
complete -f -c undatum -n __fish_use_subcommand -a analyze -d 'Analyzes given data file and returns human readable insights...'
complete -f -c undatum -n __fish_use_subcommand -a apply -d 'Runs script against each record of input file'
complete -f -c undatum -n __fish_use_subcommand -a convert -d 'Converts one file to another.'
complete -f -c undatum -n __fish_use_subcommand -a flatten -d 'Flatten data records.'
complete -f -c undatum -n __fish_use_subcommand -a frequency -d 'Field value frequency calc'
complete -f -c undatum -n __fish_use_subcommand -a headers -d 'Returns fieldnames of the file.'
complete -f -c undatum -n __fish_use_subcommand -a query -d 'Query data using mistql (experimental, require mistql).'
complete -f -c undatum -n __fish_use_subcommand -a scheme -d 'Generate data schema from file'
complete -f -c undatum -n __fish_use_subcommand -a select -d 'Select or re-order columns from file.'
complete -f -c undatum -n __fish_use_subcommand -a split -d 'Splits the given file with data into chunks.'
complete -f -c undatum -n __fish_use_subcommand -a stats -d 'Returns detailed stats on selected dataset'
complete -f -c undatum -n __fish_use_subcommand -a uniq -d 'Returns all unique files of certain field(s)'
complete -f -c undatum -n __fish_use_subcommand -a validate -d 'Validates selected field against validation rule'
