complete -c vsce -n __fish_no_arguments -s V -l version -d 'output the version number'
complete -c vsce -s h -l help -d 'display help for command'
complete -f -c vsce -n __fish_use_subcommand -a ls -d '[options]                       Lists all the files that will be'
complete -c vsce -n '__fish_seen_subcommand_from ls' -l yarn -d 'Use yarn instead of npm (default inferred from'
complete -c vsce -n '__fish_seen_subcommand_from ls' -l no-yarn -d 'Use npm instead of yarn (default inferred from'
complete -c vsce -n '__fish_seen_subcommand_from ls' -l packagedDependencies -d '<path>  Select packages that should be published only'
complete -c vsce -n '__fish_seen_subcommand_from ls' -l ignoreFile -d '<path>            Indicate alternative .vscodeignore'
complete -c vsce -n '__fish_seen_subcommand_from ls' -l dependencies -d 'Enable dependency detection via npm or yarn'
complete -c vsce -n '__fish_seen_subcommand_from ls' -l no-dependencies -d 'Disable dependency detection via npm or yarn'
complete -c vsce -n '__fish_seen_subcommand_from ls' -s h -l help -d 'display help for command'
