complete -c afsctool -s v -d 'Increase verbosity level'
complete -c afsctool -s f -d 'Detect hard links'
complete -c afsctool -s l -d 'List files that are HFS+/APFS compressed (or if the -c option is given, files which fail to compress)'
complete -c afsctool -s L -d 'Allow larger-than-raw compressed chunks (not recommended; always true for LZVN compression)'
complete -c afsctool -s n -d 'Do not verify files after compression (not recommended)'
complete -c afsctool -s m -d '<size> Largest file size to compress, in bytes'
complete -c afsctool -s s -d '<percentage> For compression to be applied, compression savings must be at least this percentage'
complete -c afsctool -s t -d '<ContentType/Extension> Return statistics for files of given content type and when compressing,'
complete -c afsctool -s i -d "Compress or show statistics for files that don't have content type(s) or extension(s) given by -t <ContentType/Extension> instead of those that do"
complete -c afsctool -s b -d 'make a backup of files before compressing them'
complete -c afsctool -s jN -d 'compress (only compressable) files using <N> threads (compression is concurrent, disk IO is exclusive)'
complete -c afsctool -s JN -d 'read, compress and write files (only compressable ones) using <N> threads (everything is concurrent except writing the compressed file)'
complete -c afsctool -s S -d 'sort the item list by file size (leaving the largest files to the end may be beneficial if the target volume is almost full)'
complete -c afsctool -s RM -d '<M> of the <N> workers will work the item list (must be sorted!) in reverse order, starting with the largest files'
complete -c afsctool -s T -d '<compressor> Compression type to use: ZLIB (= types 3,4), LZVN (= types 7,8), or LZFSE (= types 11,12)'
