complete -c arangoimport -l auto-rate-limit -d '<boolean>               Adjust the data loading rate automatically, starting at `--batch-size` bytes per thread per second. (default: false) (introduced in v3.7.11)'
complete -c arangoimport -l backslash-escape -d '<boolean>              Use backslash as the escape character for quotes. Used for CSV and TSV imports. (default: false)'
complete -c arangoimport -l batch-size -d '<uint64>                     The size for individual data batches (in bytes). (default: 8388608)'
complete -c arangoimport -l check-configuration -d '<boolean>           Check the configuration and exit.'
complete -c arangoimport -l collection -d '<string>                     The name of the collection to import into. (default: "")'
complete -c arangoimport -l config -d '<string>                         The configuration file or "none". (default: "")'
complete -c arangoimport -l configuration -d '<string>                  The configuration file or "none". (default: "")'
complete -c arangoimport -l convert -d '<boolean>                       Convert the strings `null`, `false`, `true` and strings containing numbers into non-string types. For CSV and TSV only. (default: true)'
complete -c arangoimport -l create-collection -d '<boolean>             create collection if it does not yet exist (default: false)'
complete -c arangoimport -l create-collection-type -d '<string>         The type of the collection if it needs to be created (edge or document).'
complete -c arangoimport -l create-database -d '<boolean>               Create the target database if it does not exist. (default: false)'
complete -c arangoimport -l datatype -d '<string...>                    Force a specific datatype for an attribute (null/boolean/number/string) using the syntax "attribute=type". For CSV and TSV only. Takes'
complete -c arangoimport -l define -d '<string...>                      Define a value for a `@key@` entry in the configuration file using the syntax `"key=value"`. (default: )'
complete -c arangoimport -l dump-dependencies -d '<boolean>             Dump the dependency graph of the feature phases (internal) and exit.'
complete -c arangoimport -l dump-options -d '<boolean>                  Dump all available startup options in JSON format and exit.'
complete -c arangoimport -l file -d '<string>                           The file to import ("-" for stdin). (default: "")'
complete -c arangoimport -l from-collection-prefix -d '<string>         The collection name prefix to prepend to all values in the `_from` attribute. (default: "")'
complete -c arangoimport -l headers-file -d '<string>                   The file to read the CSV or TSV header from. If specified, no header is expected in the regular input file. (default: "") (introduced in v3.'
complete -c arangoimport -l ignore-missing -d '<boolean>                Ignore missing columns in CSV and TSV input. (default: false)'
complete -c arangoimport -l latency -d '<boolean>                       Show 10 second latency statistics (values in microseconds). (default: false)'
complete -c arangoimport -l log -d '<string...>                         Set the topic-specific log level, using `--log level` for the general topic or `--log topic=level` for the specified topic (can be'
complete -c arangoimport -l merge-attributes -d '<string...>            Merge attributes into new document attribute (e.g. "mergedAttribute=[someAttribute]-[otherAttribute]") (CSV and TSV only) (default: )'
complete -c arangoimport -l on-duplicate -d '<string>                   The action to perform when a unique key constraint violation occurs. Possible values: update, ignore, replace, error'
complete -c arangoimport -l overwrite -d '<boolean>                     Overwrite the collection if it exists. WARNING: This removes any data from the collection! (default: false)'
complete -c arangoimport -l overwrite-collection-prefix -d '<boolean>   If the collection name is already prefixed, overwrite the prefix. Only useful in combination with `--from-collection-prefix` /'
complete -c arangoimport -l progress -d '<boolean>                      Show the progress. (default: true)'
complete -c arangoimport -l quote -d '<string>                          Quote character(s). Used for CSV and TSV. (default: """)'
complete -c arangoimport -l remove-attribute -d '<string...>            remove an attribute before inserting documents into collection (for CSV, TSV and JSON only) (default: )'
complete -c arangoimport -l separator -d '<string>                      The field separator. Used for CSV and TSV imports. Defaults to a comma (CSV) or a tabulation character (TSV). (default: "")'
complete -c arangoimport -l skip-lines -d '<uint64>                     The number of lines to skip of the input file (CSV and TSV only). (default: 0)'
complete -c arangoimport -l skip-validation -d '<boolean>               Skip document schema validation during import. (default: false) (introduced in v3.7.0)'
complete -c arangoimport -l threads -d '<uint32>                        Number of parallel import threads. (default: 8)'
complete -c arangoimport -l to-collection-prefix -d '<string>           The collection name prefix to prepend to all values in the `_to` attribute. (default: "")'
complete -c arangoimport -l translate -d '<string...>                   Translate an attribute name using the syntax "from=to". For CSV and TSV only. (default: )'
complete -c arangoimport -l type -d '<string>                           The format of import file.'
complete -c arangoimport -n __fish_no_arguments -l version -d '<boolean>                       Print the version and other related information, then exit.'
complete -c arangoimport -l version-json -d '<boolean>                  Print the version and other related information in JSON format, then exit. (introduced in v3.9.0)'
complete -c arangoimport -l log.color -d '<boolean>                     Use colors for TTY logging. (default: true)'
complete -c arangoimport -l log.escape-control-chars -d '<boolean>      Escape control characters in log messages. (default: true) (introduced in v3.9.0)'
complete -c arangoimport -l log.escape-unicode-chars -d "<boolean>      Escape Unicode characters in log messages. (default: false) (introduced in v3.9.0)"
complete -c arangoimport -l log.file -d "<string>                       shortcut for '--log.output file://<filename>' (default: "")"
complete -c arangoimport -l log.file-group -d '<string>                 group to use for new log file, user must be a member of this group (default: "") (introduced in v3.4.5)'
complete -c arangoimport -l log.file-mode -d '<string>                  mode to use for new log file, umask will be applied as well (default: "") (introduced in v3.4.5)'
complete -c arangoimport -l log.force-direct -d '<boolean>              Do not start a separate thread for logging. (default: false)'
complete -c arangoimport -l log.foreground-tty -d '<boolean>            Also log to TTY if backgrounded. (default: false)'
complete -c arangoimport -l log.hostname -d '<string>                   The hostname to use in log message. Leave empty for none, use "auto" to automatically determine a hostname. (default: "") (introduced in v3.'
complete -c arangoimport -l log.ids -d '<boolean>                       Log unique message IDs. (default: true) (introduced in v3.5.0)'
complete -c arangoimport -l log.level -d '<string...>                   Set the topic-specific log level, using `--log.level level` for the general topic or `--log.level topic=level` for the specified topic (can'
complete -c arangoimport -l log.line-number -d '<boolean>               Include the function name, file name, and line number of the source code that issues the log message. Format: `[func@FileName.cpp:123]`'
complete -c arangoimport -l log.max-entry-length -d '<uint32>           The maximum length of a log entry (in bytes). (default: 134217728) (introduced in v3.7.9)'
complete -c arangoimport -l log.output -d '<string...>                  Log destination(s), e.g. file:///path/to/file (any occurrence of $PID is replaced with the process ID). (default: )'
complete -c arangoimport -l log.performance -d '<boolean>               Shortcut for `--log.level performance=trace`. (default: false) (deprecated in v3.5.0)'
complete -c arangoimport -l log.prefix -d '<string>                     Prefix log message with this string. (default: "")'
complete -c arangoimport -l log.process -d '<boolean>                   Show the process identifier (PID) in log messages. (default: true) (introduced in v3.8.0)'
complete -c arangoimport -l log.request-parameters -d '<boolean>        include full URLs and HTTP request parameters in trace logs (default: true)'
complete -c arangoimport -l log.role -d '<boolean>                      Log the server role. (default: false)'
complete -c arangoimport -l log.shorten-filenames -d '<boolean>         shorten filenames in log output (use with --log.line-number) (default: true)'
complete -c arangoimport -l log.structured-param -d '<string...>        Toggle the usage of the log category parameter in structured log messages. (default: ) (introduced in v3.10.0)'
complete -c arangoimport -l log.thread -d '<boolean>                    Show the thread identifier in log messages. (default: false)'
complete -c arangoimport -l log.thread-name -d '<boolean>               Show thread name in log messages. (default: false)'
complete -c arangoimport -l log.time-format -d '<string>                The time format to use in logs.'
complete -c arangoimport -l log.use-json-format -d '<boolean>           Use JSON as output format for logging. (default: false) (introduced in v3.8.0)'
complete -c arangoimport -l log.use-local-time -d '<boolean>            Use the local timezone instead of UTC. (default: false) (deprecated in v3.5.0)'
complete -c arangoimport -l log.use-microtime -d '<boolean>             Use Unix timestamps in seconds with microsecond precision. (default: false) (deprecated in v3.5.0)'
complete -c arangoimport -l random.generator -d '<uint32>               The random number generator to use (1 = MERSENNE, 2 = RANDOM, 3 = URANDOM, 4 = COMBINED (not available on Windows), 5 = WinCrypt (Windows'
complete -c arangoimport -l server.authentication -d '<boolean>         Require authentication credentials when connecting (does not affect the server-side authentication settings). (default: true)'
complete -c arangoimport -l server.connection-timeout -d '<double>      The connection timeout (in seconds). (default: 5)'
complete -c arangoimport -l server.database -d '<string>                The database name to use when connecting. (default: "_system")'
complete -c arangoimport -l server.endpoint -d "<string...>             The endpoint to connect to. Use 'none' to start without a server. Use http+ssl:// as schema to connect to an SSL-secured server endpoint,"
complete -c arangoimport -l server.max-packet-size -d '<uint64>         The maximum packet size (in bytes) for client/server communication. (default: 1073741824)'
complete -c arangoimport -l server.password -d '<string>                The password to use when connecting. If not specified and authentication is required, the user is prompted for a password \(default: ""\)'
complete -c arangoimport -l server.request-timeout -d '<double>         The request timeout (in seconds). (default: 1200)'
complete -c arangoimport -l server.username -d '<string>                The username to use when connecting. (default: "root")'
complete -c arangoimport -l ssl.protocol -d '<uint64>                   The SSL protocol (1 = SSLv2 (unsupported), 2 = SSLv2 or SSLv3 (negotiated), 3 = SSLv3, 4 = TLSv1, 5 = TLSv1.2, 6 = TLSv1.3, 9 = generic TLS'
complete -c arangoimport -l temp.path -d '<string>                      The path for temporary files. (default: "")'
