complete -f -c ass -n __fish_use_subcommand -a compress -d 'Compress files'
complete -c ass -n '__fish_seen_subcommand_from compress' -s l -l level -d '<LEVEL>'
complete -c ass -n '__fish_seen_subcommand_from compress' -s r -l minimum-compression-ratio -d '<MINIMUM_COMPRESSION_RATIO>'
complete -c ass -n '__fish_seen_subcommand_from compress' -s c -l compression -d '<COMPRESSION>'
complete -c ass -n '__fish_seen_subcommand_from compress' -l chrome-tracing -d '<CHROME_TRACING>'
complete -f -c ass -n __fish_use_subcommand -a decompress -d 'Decompress files'
complete -c ass -n '__fish_seen_subcommand_from decompress' -l chrome-tracing -d '<CHROME_TRACING>'
complete -f -c ass -n __fish_use_subcommand -a info -d 'Get info about compression for file(s)'
complete -c ass -n '__fish_seen_subcommand_from info' -l chrome-tracing -d '<CHROME_TRACING>'
complete -f -c ass -n __fish_use_subcommand -a help -d 'Print this message or the help of the given subcommand(s)'
complete -c ass -l chrome-tracing -d '<CHROME_TRACING>'
complete -c ass -n '__fish_seen_subcommand_from compress' -s l -l level -d '<LEVEL>'
complete -c ass -n '__fish_seen_subcommand_from compress' -s r -l minimum-compression-ratio -d '<MINIMUM_COMPRESSION_RATIO>'
complete -c ass -n '__fish_seen_subcommand_from compress' -s c -l compression -d '<COMPRESSION>' -xa "lzfse lzvn zlib"
complete -c ass -n '__fish_seen_subcommand_from compress' -l chrome-tracing -d '<CHROME_TRACING>'
complete -c ass -n '__fish_seen_subcommand_from decompress' -l chrome-tracing -d '<CHROME_TRACING>'
complete -c ass -n '__fish_seen_subcommand_from info' -l chrome-tracing -d '<CHROME_TRACING>'
