complete -c bat -l nonprintable-notation -d '<notation>'
complete -c bat -l binary -d '<behavior>'
complete -c bat -s l -l language -d '<language>'
complete -c bat -s H -l highlight-line -d '<N:M>'
complete -c bat -l file-name -d '<name>'
complete -c bat -l diff-context -d '<N>'
complete -c bat -l tabs -d '<T>'
complete -c bat -l wrap -d '<mode>'
complete -c bat -l terminal-width -d '<width>'
complete -c bat -l color -d '<when>'
complete -c bat -l italic-text -d '<when>'
complete -c bat -l decorations -d '<when>'
complete -c bat -l paging -d '<when>'
complete -c bat -l pager -d '<command>'
complete -c bat -s m -l map-syntax -d '<glob:syntax>'
complete -c bat -s m -d "'*.build:Python'. To highlight files named '.myignore' with the Git Ignore syntax, use"
complete -c bat -s m -d "'.myignore:Git Ignore'. Note that the right-hand side is the *name* of the syntax, not"
complete -c bat -l ignored-suffix -d '<ignored-suffix>'
complete -c bat -l theme -d '<theme>'
complete -c bat -l theme-light -d '<theme>'
complete -c bat -l theme-dark -d '<theme>'
complete -c bat -l squeeze-limit -d '<squeeze-limit>'
complete -c bat -l strip-ansi -d '<when>'
complete -c bat -l style -d '<components>'
complete -c bat -s r -l line-range -d '<N:M>'
complete -c bat -l decode -d '<COMMAND>'
complete -c bat -l format -d '<COMMAND>'
complete -c bat -l pre -d '<COMMAND>'
complete -c bat -l completion -d '<SHELL>'
