complete -c bear -l output -d '<arg>       path of the result file (default: compile_commands.json)'
complete -c bear -l verbose -d 'run in verbose mode'
complete -c bear -l append -d 'append result to an existing output file'
complete -c bear -l config -d '<arg>       path of the config file'
complete -c bear -l force-preload -d 'force to use library preload'
complete -c bear -l force-wrapper -d 'force to use compiler wrappers'
complete -c bear -l bear-path -d '<arg>    path to the bear executable (default: /opt/homebrew/Cellar/bear/3.1.5_9/bin/bear)'
complete -c bear -l library -d '<arg>      path to the preload library (default: /opt/homebrew/Cellar/bear/3.1.5_9/lib/bear/libexec.dylib)'
complete -c bear -l wrapper -d '<arg>      path to the wrapper executable (default: /opt/homebrew/Cellar/bear/3.1.5_9/lib/bear/wrapper)'
complete -c bear -l wrapper-dir -d '<arg>  path to the wrapper directory (default: /opt/homebrew/Cellar/bear/3.1.5_9/lib/bear/wrapper.d)'
complete -c bear -l help -d 'print help and exit'
complete -c bear -n __fish_no_arguments -l version -d 'print version and exit'
