complete -c brotli -s c -l stdout        -d "write on standard output"
complete -c brotli -s d -l decompress    -d decompress
complete -c brotli -s f -l force         -d "force output file overwrite"
complete -c brotli -s h -l help          -d "display this help and exit"
complete -c brotli -s j -l rm            -d "remove source file(s)"
complete -c brotli -s s -l squash        -d "remove destination file if larger than source"
complete -c brotli -s k -l keep          -d "keep source file(s) (default)"
complete -c brotli -s n -l no-copy-stat  -d "do not copy source file(s) attributes"
complete -c brotli -s o -l "output"      -d "=FILE output file (only if 1 input file)"
complete -c brotli -s q -l "quality"     -d "=NUM compression level (0-11)"
complete -c brotli -s t -l test          -d "test compressed file integrity"
complete -c brotli -s w -l lgwin         -d "=NUM set LZ77 window size (0, 10-24)"
complete -c brotli -s D -l dictionary    -d "=FILE use FILE as raw (LZ77) dictionary"
complete -c brotli -s S -l suffix        -d "=SUF output file suffix (default:'.br')"
complete -c brotli -s Z -l best          -d "use best compression level (11) (default)"
complete -c brotli -s v -l verbose       -d "verbose mode"