# Completions for bun repl

# Flags with arguments (various types)
complete -c bun -n "__fish_bun_using_subcommand repl" --long elide-lines -x -d "Lines of script output shown with --filter"
complete -c bun -n "__fish_bun_using_subcommand repl" -s F --long filter -x -d "Run in workspace packages matching pattern"
complete -c bun -n "__fish_bun_using_subcommand repl" --long shell -x -a "bun\tBun shell\tsystem\tSystem shell" -d "Control shell used for package.json scripts"
complete -c bun -n "__fish_bun_using_subcommand repl" --long watch-kill-signal -x -d "Signal when --watch restarts process"
complete -c bun -n "__fish_bun_using_subcommand repl" -s r --long preload -F -d "Import module before other modules load"
complete -c bun -n "__fish_bun_using_subcommand repl" --long require -F -d "Alias of --preload for Node.js compatibility"
complete -c bun -n "__fish_bun_using_subcommand repl" --long import -F -d "Alias of --preload for Node.js compatibility"
complete -c bun -n "__fish_bun_using_subcommand repl" --long inspect -x -d "Activate Bun debugger"
complete -c bun -n "__fish_bun_using_subcommand repl" --long inspect-wait -x -d "Activate debugger, wait before executing"
complete -c bun -n "__fish_bun_using_subcommand repl" --long inspect-brk -x -d "Activate debugger with breakpoint on first line"
complete -c bun -n "__fish_bun_using_subcommand repl" --long cpu-prof-name -F -d "Name of CPU profile file"
complete -c bun -n "__fish_bun_using_subcommand repl" --long cpu-prof-dir -F -d "Directory for CPU profile"
complete -c bun -n "__fish_bun_using_subcommand repl" --long cpu-prof-interval -x -d "Sampling interval in microseconds for CPU profiling"
complete -c bun -n "__fish_bun_using_subcommand repl" --long heap-prof-name -F -d "Name of heap profile file"
complete -c bun -n "__fish_bun_using_subcommand repl" --long heap-prof-dir -F -d "Directory for heap profile"
complete -c bun -n "__fish_bun_using_subcommand repl" --long heap-prof-interval -x -d "Average sampling interval in bytes for heap profiling"
complete -c bun -n "__fish_bun_using_subcommand repl" --long install -x -a "auto\tAuto-install when no node_modules\tfallback\tMissing packages only\tforce\tAlways auto-install" -d "Configure auto-install behavior"
complete -c bun -n "__fish_bun_using_subcommand repl" -s e --long eval -x -d "Evaluate argument as script"
complete -c bun -n "__fish_bun_using_subcommand repl" -s p --long print -x -d "Evaluate and print result"
complete -c bun -n "__fish_bun_using_subcommand repl" --long port -x -d "Default port for Bun.serve"
complete -c bun -n "__fish_bun_using_subcommand repl" --long conditions -x -d "Custom conditions for resolve"
complete -c bun -n "__fish_bun_using_subcommand repl" --long fetch-preconnect -x -d "Preconnect URL while code loads"
complete -c bun -n "__fish_bun_using_subcommand repl" --long max-http-header-size -x -d "Maximum HTTP header size in bytes"
complete -c bun -n "__fish_bun_using_subcommand repl" --long dns-result-order -x -a "verbatim\tDefault\tipv4first\tIPv4 first\tipv6first\tIPv6 first" -d "Order of DNS lookup results"
complete -c bun -n "__fish_bun_using_subcommand repl" --long disable-warning -x -d "Silence warnings by code or type"
complete -c bun -n "__fish_bun_using_subcommand repl" --long title -x -d "Set process title"
complete -c bun -n "__fish_bun_using_subcommand repl" --long redirect-warnings -F -d "Write warnings to file instead of stderr"
complete -c bun -n "__fish_bun_using_subcommand repl" --long cron-title -x -d "Title for cron execution mode"
complete -c bun -n "__fish_bun_using_subcommand repl" --long cron-period -x -d "Cron period for cron execution mode"
complete -c bun -n "__fish_bun_using_subcommand repl" --long main-fields -x -d "Main fields to lookup in package.json"
complete -c bun -n "__fish_bun_using_subcommand repl" --long extension-order -x -d "File extension resolution order"
complete -c bun -n "__fish_bun_using_subcommand repl" --long tsconfig-override -F -d "Custom tsconfig.json path"
complete -c bun -n "__fish_bun_using_subcommand repl" -s d --long define -x -d "Substitute K:V during parsing"
complete -c bun -n "__fish_bun_using_subcommand repl" --long drop -x -d "Remove function calls"
complete -c bun -n "__fish_bun_using_subcommand repl" -s l --long loader -x -d "Parse files with custom loader"
complete -c bun -n "__fish_bun_using_subcommand repl" --long jsx-factory -x -d "Function called when compiling JSX elements"
complete -c bun -n "__fish_bun_using_subcommand repl" --long jsx-fragment -x -d "Function called when compiling JSX fragments"
complete -c bun -n "__fish_bun_using_subcommand repl" --long jsx-import-source -x -d "Module for importing jsx/jsxs factory"
complete -c bun -n "__fish_bun_using_subcommand repl" --long jsx-runtime -x -a "automatic\tAutomatic JSX runtime\tclassic\tClassic JSX runtime" -d "JSX runtime mode"
complete -c bun -n "__fish_bun_using_subcommand repl" --long env-file -F -d "Load environment variables from file"
complete -c bun -n "__fish_bun_using_subcommand repl" --long cwd -F -d "Path to resolve files from"
complete -c bun -n "__fish_bun_using_subcommand repl" -s c --long config -F -d "Path to Bun config file"
complete -c bun -n "__fish_bun_using_subcommand repl" --long unhandled-rejections -x -a "strict\tStrict mode\tthrow\tThrow errors\twarn\tWarn\tnone\tIgnore\twarn-with-error-code\tWarn and exit" -d "Unhandled rejection behavior"
complete -c bun -n "__fish_bun_using_subcommand repl" --long console-depth -x -d "Default depth for console.log inspection"
complete -c bun -n "__fish_bun_using_subcommand repl" --long user-agent -x -d "Default User-Agent for HTTP requests"

# Boolean flags
complete -c bun -n "__fish_bun_using_subcommand repl" --long silent -d "Don't print script command"
complete -c bun -n "__fish_bun_using_subcommand repl" -s b --long bun -d "Use Bun runtime instead of Node.js"
complete -c bun -n "__fish_bun_using_subcommand repl" --long no-orphans -d "Exit when parent dies"
complete -c bun -n "__fish_bun_using_subcommand repl" --long workspaces -d "Run in all workspace packages"
complete -c bun -n "__fish_bun_using_subcommand repl" --long parallel -d "Run scripts concurrently"
complete -c bun -n "__fish_bun_using_subcommand repl" --long sequential -d "Run scripts sequentially"
complete -c bun -n "__fish_bun_using_subcommand repl" --long no-exit-on-error -d "Continue on script failure"
complete -c bun -n "__fish_bun_using_subcommand repl" --long watch -d "Restart on file change"
complete -c bun -n "__fish_bun_using_subcommand repl" --long hot -d "Enable auto reload"
complete -c bun -n "__fish_bun_using_subcommand repl" --long no-clear-screen -d "Don't clear terminal on reload"
complete -c bun -n "__fish_bun_using_subcommand repl" --long smol -d "Use less memory, collect more often"
complete -c bun -n "__fish_bun_using_subcommand repl" --long interactive -d "Start Node.js-compatible REPL"
complete -c bun -n "__fish_bun_using_subcommand repl" --long cpu-prof -d "Write CPU profile on exit"
complete -c bun -n "__fish_bun_using_subcommand repl" --long cpu-prof-md -d "Output CPU profile in markdown"
complete -c bun -n "__fish_bun_using_subcommand repl" --long heap-prof -d "Write heap profile on exit"
complete -c bun -n "__fish_bun_using_subcommand repl" --long heap-prof-md -d "Generate markdown heap profile"
complete -c bun -n "__fish_bun_using_subcommand repl" --long if-present -d "Exit gracefully if entrypoint missing"
complete -c bun -n "__fish_bun_using_subcommand repl" --long no-install -d "Disable auto install"
complete -c bun -n "__fish_bun_using_subcommand repl" -s i -d "Auto-install dependencies"
complete -c bun -n "__fish_bun_using_subcommand repl" --long prefer-offline -d "Skip staleness checks, resolve from disk"
complete -c bun -n "__fish_bun_using_subcommand repl" --long prefer-latest -d "Use latest matching versions"
complete -c bun -n "__fish_bun_using_subcommand repl" --long experimental-http2-fetch -d "Offer h2 in fetch() TLS ALPN"
complete -c bun -n "__fish_bun_using_subcommand repl" --long experimental-http3-fetch -d "Upgrade to HTTP/3 on Alt-Svc header"
complete -c bun -n "__fish_bun_using_subcommand repl" --long insecure-http-parser -d "Accept invalid HTTP headers"
complete -c bun -n "__fish_bun_using_subcommand repl" --long experimental-stream-iter -d "Enable stream/iter API"
complete -c bun -n "__fish_bun_using_subcommand repl" --long expose-gc -d "Expose gc() on global"
complete -c bun -n "__fish_bun_using_subcommand repl" --long no-deprecation -d "Suppress deprecation warnings"
complete -c bun -n "__fish_bun_using_subcommand repl" --long throw-deprecation -d "Deprecation warnings as errors"
complete -c bun -n "__fish_bun_using_subcommand repl" --long no-warnings -d "Silence all warnings"
complete -c bun -n "__fish_bun_using_subcommand repl" --long trace-warnings -d "Show stack traces on warnings"
complete -c bun -n "__fish_bun_using_subcommand repl" --long trace-deprecation -d "Show stack traces on deprecations"
complete -c bun -n "__fish_bun_using_subcommand repl" --long pending-deprecation -d "Emit pending deprecation warnings"
complete -c bun -n "__fish_bun_using_subcommand repl" --long zero-fill-buffers -d "Zero-fill Buffer.allocUnsafe()"
complete -c bun -n "__fish_bun_using_subcommand repl" --long use-system-ca -d "Use system CA store"
complete -c bun -n "__fish_bun_using_subcommand repl" --long use-openssl-ca -d "Use OpenSSL CA store"
complete -c bun -n "__fish_bun_using_subcommand repl" --long use-bundled-ca -d "Use bundled CA store"
complete -c bun -n "__fish_bun_using_subcommand repl" --long tls-min-v1.0 -d "TLS minimum v1.0"
complete -c bun -n "__fish_bun_using_subcommand repl" --long tls-min-v1.1 -d "TLS minimum v1.1"
complete -c bun -n "__fish_bun_using_subcommand repl" --long tls-min-v1.2 -d "TLS minimum v1.2"
complete -c bun -n "__fish_bun_using_subcommand repl" --long tls-min-v1.3 -d "TLS minimum v1.3"
complete -c bun -n "__fish_bun_using_subcommand repl" --long tls-max-v1.2 -d "TLS maximum v1.2"
complete -c bun -n "__fish_bun_using_subcommand repl" --long tls-max-v1.3 -d "TLS maximum v1.3"
complete -c bun -n "__fish_bun_using_subcommand repl" --long redis-preconnect -d "Preconnect to $REDIS_URL"
complete -c bun -n "__fish_bun_using_subcommand repl" --long sql-preconnect -d "Preconnect to PostgreSQL"
complete -c bun -n "__fish_bun_using_subcommand repl" --long no-addons -d "Disable process.dlopen"
complete -c bun -n "__fish_bun_using_subcommand repl" --long no-macros -d "Disable macros in bundler/transpiler"
complete -c bun -n "__fish_bun_using_subcommand repl" --long jsx-side-effects -d "Treat JSX as side effects"
complete -c bun -n "__fish_bun_using_subcommand repl" --long ignore-dce-annotations -d "Ignore @__PURE__ annotations"
complete -c bun -n "__fish_bun_using_subcommand repl" --long no-env-file -d "Skip .env file loading"
complete -c bun -n "__fish_bun_using_subcommand repl" -s h --long help -d "Display help"
