complete -c cheat -l init -d 'Write a default config file to stdout'
complete -c cheat -s a -l all -d 'Search among all cheatpaths'
complete -c cheat -s c -l colorize -d 'Colorize output'
complete -c cheat -s d -l directories -d 'List cheatsheet directories'
complete -c cheat -s e -d '--edit=<cheatsheet>  Edit <cheatsheet>'
complete -c cheat -s l -l list -d 'List cheatsheets'
complete -c cheat -s p -d '--path=<name>        Return only sheets found on cheatpath <name>'
complete -c cheat -s r -l regex -d 'Treat search <phrase> as a regex'
complete -c cheat -s s -d '--search=<phrase>    Search cheatsheets for <phrase>'
complete -c cheat -s t -d '--tag=<tag>          Return only sheets matching <tag>'
complete -c cheat -s T -l tags -d 'List all tags in use'
complete -c cheat -n __fish_no_arguments -s v -l version -d 'Print the version number'
complete -c cheat -l conf -d 'Display the config file path'
