complete -f -c crev -n __fish_use_subcommand -a bundle -d 'Bundle your project into a single file'
complete -c crev -n '__fish_seen_subcommand_from bundle' -s h -l help -d 'help for bundle'
complete -c crev -n '__fish_seen_subcommand_from bundle' -l ignore-ext -d 'strings    Comma-separated file extensions to ignore. Ex .txt,.md'
complete -c crev -n '__fish_seen_subcommand_from bundle' -l ignore-pre -d 'strings    Comma-separated prefixes of file and dir names to ignore. Ex tests,readme'
complete -c crev -n '__fish_seen_subcommand_from bundle' -l include-ext -d 'strings   Comma-separated file extensions to include. Ex .go,.py,.js'
complete -f -c crev -n __fish_use_subcommand -a init -d 'Initialize a default configuration file'
complete -c crev -n '__fish_seen_subcommand_from init' -s h -l help -d 'help for init'
complete -f -c crev -n __fish_use_subcommand -a review -d 'Let an AI review your crev-project.txt'
complete -c crev -n '__fish_seen_subcommand_from review' -l crev_api_key -d 'string   Your Code AI Review API key'
complete -c crev -n '__fish_seen_subcommand_from review' -s h -l help -d 'help for review'
complete -c crev -s h -l help -d 'help for crev'
complete -c crev -n __fish_no_arguments -s v -l version -d 'version for crev'
complete -c crev -n '__fish_seen_subcommand_from bundle' -s h -l help -d 'help for bundle'
complete -c crev -n '__fish_seen_subcommand_from bundle' -l ignore-ext -d 'strings    Comma-separated file extensions to ignore. Ex .txt,.md'
complete -c crev -n '__fish_seen_subcommand_from bundle' -l ignore-pre -d 'strings    Comma-separated prefixes of file and dir names to ignore. Ex tests,readme'
complete -c crev -n '__fish_seen_subcommand_from bundle' -l include-ext -d 'strings   Comma-separated file extensions to include. Ex .go,.py,.js'
complete -c crev -n '__fish_seen_subcommand_from init' -s h -l help -d 'help for init'
complete -c crev -n '__fish_seen_subcommand_from review' -l crev_api_key -d 'string   Your Code AI Review API key'
complete -c crev -n '__fish_seen_subcommand_from review' -s h -l help -d 'help for review'
