complete -c croc -s git -d 'to respect your .gitignore'
complete -f -c croc -n __fish_use_subcommand -a send -d 'send file(s), or folder (see options with croc send -h)'
complete -f -c croc -n __fish_use_subcommand -a relay -d 'start your own relay (optional)'
complete -f -c croc -n __fish_use_subcommand -a help -d 'Shows a list of commands or help for one command'
complete -c croc -l internal-dns -d 'use a built-in DNS stub resolver rather than the host operating system (default: false)'
complete -c croc -l classic -d 'toggle between the classic mode (insecure due to local attack vector) and new mode (secure) (default: false)'
complete -c croc -l remember -d 'save these settings to reuse next time (default: false)'
complete -c croc -l debug -d 'toggle debug mode (default: false)'
complete -c croc -l yes -d 'automatically agree to all prompts (default: false)'
complete -c croc -l stdout -d 'redirect file to stdout (default: false)'
complete -c croc -l no-compress -d 'disable compression (default: false)'
complete -c croc -l ask -d 'make sure sender and recipient are prompted (default: false)'
complete -c croc -l local -d 'force to use only local connections (default: false)'
complete -c croc -l ignore-stdin -d 'ignore piped stdin (default: false)'
complete -c croc -l overwrite -d 'do not prompt to overwrite or resume (default: false)'
complete -c croc -l testing -d 'flag for testing purposes (default: false)'
complete -c croc -l multicast -d 'value       multicast address to use for local discovery (default: "239.255.255.250")'
complete -c croc -l curve -d 'value           choose an encryption curve (p521, p256, p384, siec) (default: "p256")'
complete -c croc -l ip -d 'value              set sender ip if known e.g. 10.0.0.1:9009, [::1]:9009'
complete -c croc -l relay -d 'value           address of the relay (default: "168.119.238.198:9009") [$CROC_RELAY]'
complete -c croc -l relay6 -d 'value          ipv6 address of the relay (default: "[2a01:4f8:1c1c:7804::1]:9009") [$CROC_RELAY6]'
complete -c croc -l out -d 'value             specify an output folder to receive the file (default: ".")'
complete -c croc -l pass -d 'value            password for the relay (default: "pass123") [$CROC_PASS]'
complete -c croc -l socks5 -d 'value          add a socks5 proxy [$SOCKS5_PROXY]'
complete -c croc -l connect -d 'value         add a http proxy [$HTTP_PROXY]'
complete -c croc -l throttleUpload -d 'value  Throttle the upload speed e.g. 500k'
complete -c croc -s h -l help -d 'show help (default: false)'
complete -c croc -n __fish_no_arguments -s v -l version -d 'print the version (default: false)'
