complete -c datafusion-cli -s b -l batch-size -d '<BATCH_SIZE>'
complete -c datafusion-cli -s c -l command -d '<COMMAND>...'
complete -c datafusion-cli -s f -l file -d '<FILE>...'
complete -c datafusion-cli -l format -d '<FORMAT>'
complete -c datafusion-cli -s m -l memory-limit -d '<MEMORY_LIMIT>'
complete -c datafusion-cli -l maxrows -d '<MAXROWS>'
complete -c datafusion-cli -l mem-pool-type -d '<MEM_POOL_TYPE>'
complete -c datafusion-cli -s p -l data-path -d '<DATA_PATH>'
complete -c datafusion-cli -s r -l rc -d '<RC>...'
