complete -c datafusion -s b -l batch-size -d '<BATCH_SIZE>'
complete -c datafusion -s c -l command -d '<COMMAND>...'
complete -c datafusion -s f -l file -d '<FILE>...'
complete -c datafusion -l format -d '<FORMAT>'
complete -c datafusion -s m -l memory-limit -d '<MEMORY_LIMIT>'
complete -c datafusion -l maxrows -d '<MAXROWS>'
complete -c datafusion -l mem-pool-type -d '<MEM_POOL_TYPE>'
complete -c datafusion -s p -l data-path -d '<DATA_PATH>'
complete -c datafusion -s r -l rc -d '<RC>...'
