complete -c dateseq -l help -d '-h, --help    Print help and exit'
complete -c dateseq -l version -d '-V, --version    Print version and exit'
complete -c dateseq -l quiet -d '-q, --quiet    Suppress message about date/time and duration parser errors and fix-ups'
complete -c dateseq -l format -d '-f, --format=STRING    Output format. This can either be a specifier string or the name of a calendar'
complete -c dateseq -l input-format -d '-i, --input-format=STRING...    Input format, can be used multiple times'
complete -c dateseq -l backslash-escapes -d '-e, --backslash-escapes    Enable interpretation of backslash escapes in the output and input format specifier strings'
complete -c dateseq -l locale -d '--locale=LOCALE    Format results according to LOCALE, this would only affect month and weekday names'
complete -c dateseq -l from-locale -d '--from-locale=LOCALE    Interpret dates on stdin or the command line as coming from the locale LOCALE'
complete -c dateseq -l skip -d '--skip=STRING...    Skip weekdays specified by STRING'
complete -c dateseq -l alt-inc -d '--alt-inc=STRING    Alternative increment to use when a date is hit that is skipped'
complete -c dateseq -l compute-from-last -d '--compute-from-last    Compute a start value from LAST using INCREMENT'
complete -c dateseq -n __fish_no_arguments -s h -l help -d 'Print help'
complete -c dateseq -n __fish_no_arguments -s V -l version -d 'Print version'
