complete -c dfc -s a -d 'print all mounted filesystem'
complete -c dfc -s b -d 'do not show the graph bar'
complete -c dfc -s c -d 'choose color mode. Read the manpage for details'
complete -c dfc -s d -d 'show used size'
complete -c dfc -s e -d 'export to specified format. Read the manpage for details'
complete -c dfc -s f -d 'disable auto-adjust mode (force display)'
complete -c dfc -s h -d 'print this message'
complete -c dfc -s i -d 'info about inodes'
complete -c dfc -s l -d 'only show information about locally mounted file systems'
complete -c dfc -s m -d 'use metric (SI unit)'
complete -c dfc -s M -d 'do not print "mounted on"'
complete -c dfc -s n -d 'do not print header'
complete -c dfc -s o -d 'show mount flags'
complete -c dfc -s p -d 'filter by file system name. Read the manpage for details'
complete -c dfc -s q -d 'sort the output. Read the manpage for details'
complete -c dfc -s s -d 'sum the total usage'
complete -c dfc -s t -d 'filter by file system type. Read the manpage for details'
complete -c dfc -s T -d 'show filesystem type'
complete -c dfc -s u -d 'choose the unit in which to show the values. Read the manpage for details'
complete -c dfc -s v -d 'print program version'
complete -c dfc -s w -d 'use a wider bar'
complete -c dfc -s W -d 'wide filename (un truncate)'
