complete -c ditto -s h -l help -d 'print full usage'
complete -c ditto -s v -d 'print a status line for each source copied'
complete -c ditto -s V -d 'print a status line for every file copied'
complete -c ditto -s X -d 'do not descend into directories with a'
complete -c ditto -s c -d 'create an archive at dst'
complete -c ditto -s x -d 'src(s) are archives'
complete -c ditto -s z -d 'Use gzip when compressing a CPIO archive'
complete -c ditto -s j -d 'Use bzip2 when compressing a CPIO archive'
complete -c ditto -s k -d 'create the archive in the PKZip format'
complete -c ditto -l keepParent -d 'Embed the parent directory name of src in the'
complete -c ditto -l arch -d 'archVal                 fat files will be thinned to archVal'
complete -c ditto -l bom -d 'bomFile                  only objects present in index bom are copied'
complete -c ditto -l lang -d '<lang>                  filter the index bom based on language'
complete -c ditto -l outBom -d 'bomFile               create an output bom representing the paths'
complete -c ditto -l rsrc -d 'preserve resource data'
complete -c ditto -l norsrc -d 'do not preserve resource data'
complete -c ditto -l extattr -d 'preserve extended attributes'
complete -c ditto -l noextattr -d 'do not preserve extended attributes'
complete -c ditto -l qtn -d 'preserve quarantine information'
complete -c ditto -l noqtn -d 'do not preserve quarantine information'
complete -c ditto -l acl -d 'preserve Access Control Lists (ACLs)'
complete -c ditto -l noacl -d 'do not preserve ACLs'
complete -c ditto -l sequesterRsrc -d 'copy resources via polite __MACOSX directory'
complete -c ditto -l zlibCompressionLevel -d "<num>   use compression level 'num' when creating"
complete -c ditto -l password -d 'request password for reading from encrypted'
complete -c ditto -l hfsCompression -d 'compress files at destination if appropriate'
complete -c ditto -l nohfsCompression -d 'do not compress files at destination'
complete -c ditto -l preserveHFSCompression -d 'preserve filesystem compression when copying'
complete -c ditto -l nopreserveHFSCompression -d 'do not preserve filesystem compression'
complete -c ditto -l nocache -d 'do not use filesystem cache for reads/writes'
complete -c ditto -l nonAtomicCopies -d 'do not perform atomic copies when replacing'
complete -c ditto -l segmentLargeFiles -d 'when copying files to a CPIO archive, segment'
complete -c ditto -l persistRootless -d 'persist the SF_RESTRICTED flag or the'
complete -c ditto -l nopersistRootless -d 'do not persist the SF_RESTRICTED flag or'
complete -c ditto -l keepBinaries -d 'set aside the original Mach-O binary when it'
complete -c ditto -l keepBinariesList -d '<path>      record kept binaries in a text file at the'
complete -c ditto -l keepBinariesPattern -d '<regex>  only keep files that match the specified'
complete -c ditto -l clone -d 'attempt to clone files when copying'
complete -c ditto -l noclone -d 'do not attempt to clone files'
complete -c ditto -l rsrc -d 'preserve resource data'
complete -c ditto -l extattr -d 'preserve extended attributes'
complete -c ditto -l qtn -d 'preserve quarantine information'
complete -c ditto -l acl -d 'preserve Access Control Lists (ACLs)'
complete -c ditto -l preserveHFSCompression -d 'preserve filesystem compression when copying'
complete -c ditto -l persistRootless -d 'persist the SF_RESTRICTED flag or the'
