complete -c duckdb -o append -d "append the database to the end of the file"
complete -c duckdb -o ascii -d "set output mode to ascii"
complete -c duckdb -o bail -d "stop after hitting an error"
complete -c duckdb -o batch -d "force batch I/O"
complete -c duckdb -o box -d "set output mode to box"
complete -c duckdb -o column -d "set output mode to 'column'"
complete -c duckdb -o cmd -d "COMMAND         run \"COMMAND\" before reading stdin"
complete -c duckdb -s c -d "COMMAND           run \"COMMAND\" and exit"
complete -c duckdb -o csv -d "set output mode to csv"
complete -c duckdb -o echo -d "print commands before execution"
complete -c duckdb -o init -d "FILENAME       read/process named file"
complete -c duckdb -o help -d "show this message"
complete -c duckdb -o html -d "set output mode to HTML"
complete -c duckdb -o interactive -d "force interactive I/O"
complete -c duckdb -o json -d "set output mode to json"
complete -c duckdb -o line -d "set output mode to line"
complete -c duckdb -o list -d "set output mode to list"
complete -c duckdb -o markdown -d "set output mode to markdown"
complete -c duckdb -o newline -d "SEP set output row separator. Default: n"
complete -c duckdb -o nofollow -d "refuse to open symbolic links to database files"
complete -c duckdb -o no-stdin -d "exit after processing options instead of reading stdin"
complete -c duckdb -o nullvalue -d "TEXT set text string for NULL values. Default ''"
complete -c duckdb -o quote -d "set output mode to quote"
complete -c duckdb -o readonly -d "open the database read-only"
complete -c duckdb -s s -d "COMMAND           run \"COMMAND\" and exit"
complete -c duckdb -o separator -d "SEP set output column separator. Default: '|'"
complete -c duckdb -o stats -d "print memory stats before each finalize"
complete -c duckdb -o table -d "set output mode to 'table'"
complete -c duckdb -o unredacted -d "allow printing unredacted secrets"
complete -c duckdb -o unsigned -d "allow loading of unsigned extensions"
complete -c duckdb -o version -d "show DuckDB version"
