complete -c eget -l pre-release -d 'include pre-releases when fetching the latest version'
complete -c eget -l source -d 'download the source code for the target repo instead of a release'
complete -c eget -l all -d 'extract all candidate files'
complete -c eget -s q -l quiet -d 'only print essential output'
complete -c eget -s d -l download-only -d 'stop after downloading the asset (no extraction)'
complete -c eget -l upgrade-only -d 'only download if release is more recent than current version'
complete -c eget -l sha256 -d 'show the SHA-256 hash of the downloaded asset'
complete -c eget -l rate -d 'show GitHub API rate limiting information'
complete -c eget -s r -l remove -d 'remove the given file from $EGET_BIN or the current directory'
complete -c eget -n __fish_no_arguments -s v -l version -d 'show version information'
complete -c eget -s h -l help -d 'show this help message'
complete -c eget -s D -l download-all -d 'download all projects defined in the config file'
complete -c eget -s k -l disable-ssl -d 'disable SSL verification for download requests'
