complete -c esbuild -l bundle -d 'Bundle all dependencies into the output files'
complete -c esbuild -l define -d 'Substitute K with V while parsing'
complete -c esbuild -l external -d 'Exclude module M from the bundle (can use * wildcards)'
complete -c esbuild -l format -d 'Output format (iife | cjs | esm, no default when not'
complete -c esbuild -l loader -d 'Use loader L to load file extension X, where L is'
complete -c esbuild -l minify -d 'Minify the output (sets all --minify-* flags)'
complete -c esbuild -l outdir -d 'The output directory (for multiple entry points)'
complete -c esbuild -l outfile -d 'The output file (for one entry point)'
complete -c esbuild -l packages -d 'Set to "external" to avoid bundling any package'
complete -c esbuild -l platform -d 'Platform target (browser | node | neutral,'
complete -c esbuild -l serve -d 'Start a local HTTP server on this host for outputs'
complete -c esbuild -l sourcemap -d 'Emit a source map'
complete -c esbuild -l splitting -d 'Enable code splitting (currently only for esm)'
complete -c esbuild -l target -d 'Environment target (e.g. es2017, chrome58, firefox57,'
complete -c esbuild -l watch -d 'Watch mode: rebuild on file system changes (stops when'
complete -c esbuild -l allow-overwrite -d 'Allow output files to overwrite input files'
complete -c esbuild -l analyze -d 'Print a report about the contents of the bundle'
complete -c esbuild -l asset-names -d 'Path template to use for "file" loader files'
complete -c esbuild -l banner -d 'Text to be prepended to each output file of type T'
complete -c esbuild -l certfile -d 'Certificate for serving HTTPS (see also "--keyfile")'
complete -c esbuild -l charset8 -d 'Do not escape UTF-8 code points'
complete -c esbuild -l chunk-names -d 'Path template to use for code splitting chunks'
complete -c esbuild -l color -d 'Force use of color terminal escapes (true | false)'
complete -c esbuild -l drop -d 'Remove certain constructs (console | debugger)'
complete -c esbuild -l drop-labels -d 'Remove labeled statements with these label names'
complete -c esbuild -l entry-names -d 'Path template to use for entry point output paths'
complete -c esbuild -l footer -d 'Text to be appended to each output file of type T'
complete -c esbuild -l global-name -d 'The name of the global for the IIFE format'
complete -c esbuild -l ignore-annotations -d 'Enable this to work with packages that have'
complete -c esbuild -l inject -d 'Import the file F into all input files and'
complete -c esbuild -l jsx-dev -d "Use React's automatic runtime in development mode"
complete -c esbuild -l jsx-factory -d 'What to use for JSX instead of React.createElement'
complete -c esbuild -l jsx-fragment -d 'What to use for JSX instead of React.Fragment'
complete -c esbuild -l jsx-import-source -d 'Override the package name for the automatic runtime'
complete -c esbuild -l jsx-side-effects -d 'Do not remove unused JSX expressions'
complete -c esbuild -l jsx -d 'Set to "automatic" to use React\'s automatic runtime'
complete -c esbuild -l keep-names -d 'Preserve "name" on functions and classes'
complete -c esbuild -l keyfile -d 'Key for serving HTTPS (see also "--certfile")'
complete -c esbuild -l legal-comments -d 'Where to place legal comments (none | inline |'
complete -c esbuild -l line-limit -d 'Lines longer than this will be wrap onto a new line'
complete -c esbuild -l log-level -d 'Disable logging (verbose | debug | info | warning |'
complete -c esbuild -l log-limit -d 'Maximum message count or 0 to disable (default 6)'
complete -c esbuild -l log-override -d 'Use log level Y for log messages with identifier X'
complete -c esbuild -l main-fields -d 'Override the main file order in package.json'
complete -c esbuild -l mangle-cache -d 'Save "mangle props" decisions to a JSON file'
complete -c esbuild -l mangle-props -d 'Rename all properties matching a regular expression'
complete -c esbuild -l mangle-quoted -d 'Enable renaming of quoted properties (true | false)'
complete -c esbuild -l metafile -d 'Write metadata about the build to a JSON file'
complete -c esbuild -l minify-whitespace -d 'Remove whitespace in output files'
complete -c esbuild -l minify-identifiers -d 'Shorten identifiers in output files'
complete -c esbuild -l minify-syntax -d 'Use equivalent but shorter syntax in output files'
complete -c esbuild -l out-extension -d 'Use a custom output extension instead of ".js"'
complete -c esbuild -l outbase -d 'The base path used to determine entry point output'
complete -c esbuild -l preserve-symlinks -d 'Disable symlink resolution for module lookup'
complete -c esbuild -l public-path -d 'Set the base URL for the "file" loader'
complete -c esbuild -l pure -d 'Mark the name N as a pure function for tree shaking'
complete -c esbuild -l reserve-props -d 'Do not mangle these properties'
complete -c esbuild -l resolve-extensions -d 'A comma-separated list of implicit extensions'
complete -c esbuild -l serve-fallback -d "Serve this HTML page when the request doesn't match"
complete -c esbuild -l servedir -d 'What to serve in addition to generated output files'
complete -c esbuild -l source-root -d 'Sets the "sourceRoot" field in generated source maps'
complete -c esbuild -l sourcefile -d 'Set the source file for the source map (for stdin)'
complete -c esbuild -l sourcemapernal -d 'Do not link to the source map with a comment'
complete -c esbuild -l sourcemapine -d 'Emit the source map with an inline data URL'
complete -c esbuild -l sources-contentse -d 'Omit "sourcesContent" in generated source maps'
complete -c esbuild -l supported -d 'Consider syntax F to be supported (true | false)'
complete -c esbuild -l tree-shaking -d 'Force tree shaking on or off (false | true)'
complete -c esbuild -l tsconfig -d 'Use this tsconfig.json file instead of other ones'
complete -c esbuild -l tsconfig-raw -d 'Override all tsconfig.json files with this string'
complete -c esbuild -n __fish_no_arguments -l version -d 'Print the current version (0.25.1) and exit'
