complete -c esno -s h -l help -d 'Show help'
complete -c esno -l no-cache -d 'Disable caching'
complete -c esno -l tsconfig -d '<string>        Custom tsconfig.json path'
complete -c esno -n __fish_no_arguments -s v -l version -d 'Show version'
complete -c esno -l allow-addons -d 'allow use of addons when any'
complete -c esno -l allow-child-process -d 'allow use of child process when any'
complete -c esno -l allow-worker -d 'allow worker threads when any'
complete -c esno -l build-snapshot -d 'Generate a snapshot blob when the'
complete -c esno -s c -l check -d 'syntax check script without executing'
complete -c esno -l completion-bash -d 'print source-able bash completion'
complete -c esno -l cpu-prof -d 'Start the V8 CPU profiler on start up,'
complete -c esno -l enable-etw-stack-walking -d 'provides heap data to ETW Windows'
complete -c esno -l enable-fips -d 'enable FIPS crypto at startup'
complete -c esno -l enable-source-maps -d 'Source Map V3 support for stack traces'
complete -c esno -l experimental-permission -d 'enable the permission system'
complete -c esno -l experimental-require-module -d 'is true,'
complete -c esno -l experimental-vm-modules -d 'experimental ES Module support in vm'
complete -c esno -l experimental-wasm-modules -d 'experimental ES Module support for'
complete -c esno -l force-context-aware -d 'disable loading non-context-aware'
complete -c esno -l force-fips -d 'force FIPS crypto (cannot be disabled)'
complete -c esno -l frozen-intrinsics -d 'experimental frozen intrinsics support'
complete -c esno -l heap-prof -d 'Start the V8 heap profiler on start up,'
complete -c esno -s h -l help -d 'print node command line options'
complete -c esno -l insecure-http-parser -d 'use an insecure HTTP parser that'
complete -c esno -s i -l interactive -d 'always enter the REPL even if stdin'
complete -c esno -l jitless -d 'disable runtime allocation of'
complete -c esno -l no-addons -d 'disable loading native addons'
complete -c esno -l no-deprecation -d 'silence deprecation warnings'
complete -c esno -l no-experimental-fetch -d 'experimental Fetch API'
complete -c esno -l no-experimental-websocket -d 'experimental WebSocket API'
complete -c esno -l no-global-search-paths -d 'disable global module search paths'
complete -c esno -l no-warnings -d 'silence all process warnings'
complete -c esno -l node-memory-debug -d 'Run with extra debug checks for memory'
complete -c esno -l openssl-legacy-provider -d 'enable OpenSSL 3.0 legacy provider'
complete -c esno -l openssl-shared-config -d 'enable OpenSSL shared configuration'
complete -c esno -l pending-deprecation -d 'emit pending deprecation warnings'
complete -c esno -l preserve-symlinks -d 'preserve symbolic links when resolving'
complete -c esno -l preserve-symlinks-main -d 'preserve symbolic links when resolving'
complete -c esno -s p -l print -d '[...]           evaluate script and print result'
complete -c esno -l prof -d 'Generate V8 profiler output.'
complete -c esno -l prof-process -d 'process V8 profiler output generated'
complete -c esno -l report-compact -d 'output compact single-line JSON'
complete -c esno -l report-exclude-network -d 'exclude network interface diagnostics.'
complete -c esno -l report-on-fatalerror -d 'generate diagnostic report on fatal'
complete -c esno -l report-on-signal -d 'generate diagnostic report upon'
complete -c esno -l report-uncaught-exception -d 'generate diagnostic report on uncaught'
complete -c esno -l test -d 'launch test runner on startup'
complete -c esno -l test-force-exit -d 'force test runner to exit upon'
complete -c esno -l test-only -d run\ tests\ with\ \'only\'\ option\ set
complete -c esno -l throw-deprecation -d 'throw an exception on deprecations'
complete -c esno -l trace-atomics-wait -d '(deprecated) trace Atomics.wait()'
complete -c esno -l trace-deprecation -d 'show stack traces on deprecations'
complete -c esno -l trace-exit -d 'show stack trace when an environment'
complete -c esno -l trace-promises -d 'show stack traces on promise'
complete -c esno -l trace-sigint -d 'enable printing JavaScript stacktrace'
complete -c esno -l trace-sync-io -d 'show stack trace when use of sync IO is'
complete -c esno -l trace-tls -d 'prints TLS packet trace information to'
complete -c esno -l trace-uncaught -d 'show stack traces for the `throw`'
complete -c esno -l trace-warnings -d 'show stack traces on process warnings'
complete -c esno -l track-heap-objects -d 'track heap object allocations for heap'
complete -c esno -l use-bundled-ca -d 'use bundled CA store'
complete -c esno -l use-openssl-ca -d use\ OpenSSL\'s\ default\ CA\ store
complete -c esno -l v8-options -d 'print V8 command line options'
complete -c esno -n __fish_no_arguments -s v -l version -d 'print Node.js version'
complete -c esno -l watch -d 'run in watch mode'
complete -c esno -l watch-preserve-output -d 'preserve outputs on watch mode restart'
complete -c esno -l zero-fill-buffers -d 'automatically zero-fill all newly'
