complete -c extract_msg -s h -l help -d 'show this help message and exit'
complete -c extract_msg -l json -d 'Changes to write output files as json.'
complete -c extract_msg -l file-logging -d 'Enables file logging. Implies --verbose level 1.'
complete -c extract_msg -s v -l verbose -d 'Turns on console logging. Specify more than once for'
complete -c extract_msg -l log -d 'LOG             Set the path to write the file log to.'
complete -c extract_msg -l config -d 'CONFIGPATH   Set the path to load the logging config from.'
complete -c extract_msg -l out -d 'OUTPATH         Set the folder to use for the program output.'
complete -c extract_msg -l use-filename -d 'Sets whether the name of each output is based on the'
complete -c extract_msg -l dump-stdout -d 'Tells the program to dump the message body (plain'
complete -c extract_msg -l html -d 'Sets whether the output should be HTML. If this is not'
complete -c extract_msg -l pdf -d 'Saves the body as a PDF. If this is not possible, will'
complete -c extract_msg -l wk-path -d 'WKPATH      Overrides the path for finding wkhtmltopdf.'
complete -c extract_msg -l wk-options -d '[WKOPTIONS ...]'
complete -c extract_msg -l prepared-html -d 'When used in conjunction with --html, sets whether the'
complete -c extract_msg -l charset -d 'CHARSET     Character set to use for the prepared HTML in the'
complete -c extract_msg -l raw -d 'Sets whether the output should be raw. If this is not'
complete -c extract_msg -l rtf -d 'Sets whether the output should be RTF. If this is not'
complete -c extract_msg -l allow-fallback -d 'Tells the program to fallback to a different save type'
complete -c extract_msg -l zip -d 'ZIP             Path to use for saving to a zip file.'
complete -c extract_msg -l save-header -d 'Store the header in a separate file.'
complete -c extract_msg -l attachments-only -d 'Specify to only save attachments from an MSG file.'
complete -c extract_msg -l skip-hidden -d 'Skips any attachment marked as hidden (usually ones'
complete -c extract_msg -l no-folders -d 'Stores everything in the location specified by --out.'
complete -c extract_msg -l skip-embedded -d 'Skips all embedded MSG files when saving attachments.'
complete -c extract_msg -l extract-embedded -d 'Extracts the embedded MSG files as MSG files instead'
complete -c extract_msg -l overwrite-existing -d 'Disables filename conflict resolution code for'
complete -c extract_msg -l out-name -d 'OUTNAME    Name to be used with saving the file output. Cannot be'
complete -c extract_msg -l ignore-rtfde -d 'Ignores all errors thrown from RTFDE when trying to'
complete -c extract_msg -l progress -d 'Shows what file the program is currently working on'
complete -c extract_msg -s s -l stdin -d 'Read file from stdin (only works with one file at a'
