complete -f -c fclones -n __fish_use_subcommand -a group -d 'Produce a list of groups of identical files'
complete -c fclones -n '__fish_seen_subcommand_from group' -s q -l quiet -d 'Suppress progress reporting'
complete -c fclones -n '__fish_seen_subcommand_from group' -s h -l help -d 'Print help'
complete -c fclones -n __fish_no_arguments -s V -l version -d 'Print version'
complete -f -c fclones -n __fish_use_subcommand -a link -d 'Replace redundant files with links'
complete -c fclones -n '__fish_seen_subcommand_from link' -s q -l quiet -d 'Suppress progress reporting'
complete -c fclones -n '__fish_seen_subcommand_from link' -s h -l help -d 'Print help'
complete -c fclones -n __fish_no_arguments -s V -l version -d 'Print version'
complete -f -c fclones -n __fish_use_subcommand -a dedupe -d 'Deduplicate file data using native filesystem deduplication capabilities'
complete -c fclones -n '__fish_seen_subcommand_from dedupe' -s q -l quiet -d 'Suppress progress reporting'
complete -c fclones -n '__fish_seen_subcommand_from dedupe' -s h -l help -d 'Print help'
complete -c fclones -n __fish_no_arguments -s V -l version -d 'Print version'
complete -f -c fclones -n __fish_use_subcommand -a remove -d 'Remove redundant files'
complete -c fclones -n '__fish_seen_subcommand_from remove' -s q -l quiet -d 'Suppress progress reporting'
complete -c fclones -n '__fish_seen_subcommand_from remove' -s h -l help -d 'Print help'
complete -c fclones -n __fish_no_arguments -s V -l version -d 'Print version'
complete -f -c fclones -n __fish_use_subcommand -a move -d 'Move redundant files to the given directory'
complete -c fclones -n '__fish_seen_subcommand_from move' -s q -l quiet -d 'Suppress progress reporting'
complete -c fclones -n '__fish_seen_subcommand_from move' -s h -l help -d 'Print help'
complete -c fclones -n __fish_no_arguments -s V -l version -d 'Print version'
complete -f -c fclones -n __fish_use_subcommand -a help -d 'Print this message or the help of the given subcommand(s)'
complete -c fclones -n '__fish_seen_subcommand_from help' -s q -l quiet -d 'Suppress progress reporting'
complete -c fclones -n '__fish_seen_subcommand_from help' -s h -l help -d 'Print help'
complete -c fclones -n __fish_no_arguments -s V -l version -d 'Print version'
complete -c fclones -s q -l quiet -d 'Suppress progress reporting'
complete -c fclones -s h -l help -d 'Print help'
complete -c fclones -n __fish_no_arguments -s V -l version -d 'Print version'
