complete -c fish_gencomp -s h -l help -d 'show this help message and exit'
complete -c fish_gencomp -s c -d 'CLEANUP_IN, --cleanup-in CLEANUP_IN'
complete -c fish_gencomp -s d -d 'DIRECTORY, --directory DIRECTORY'
complete -c fish_gencomp -s k -l keep -d 'Whether to keep files in the target directory'
complete -c fish_gencomp -s m -l manpath -d 'Whether to use manpath'
complete -c fish_gencomp -s p -l progress -d 'Whether to show progress'
complete -c fish_gencomp -s s -l stdout -d 'Write the completions to stdout'
complete -c fish_gencomp -s v -d '{0,1,2}, --verbose {0,1,2}'
complete -c fish_gencomp -s z -l deroff-only -d 'Whether to just deroff'
