complete -c flatterer -l web -d 'Load web based version'
complete -c flatterer -l csv -d 'Output CSV files, default true'
complete -c flatterer -l nocsv -d 'no Output CSV files, default true'
complete -c flatterer -l xlsx -d 'Output XLSX file, default false'
complete -c flatterer -l noxlsx -d 'no Output XLSX file, default false'
complete -c flatterer -l sqlite -d 'Output sqlite.db file, default false'
complete -c flatterer -l nosqlite -d 'no Output sqlite.db file, default false'
complete -c flatterer -l parquet -d 'Output directory of parquet files, default false'
complete -c flatterer -l noparquet -d 'no Output directory of parquet files, default false'
complete -c flatterer -l postgres -d 'TEXT             Connection string to postgres. If supplied will'
complete -c flatterer -l sqlite-path -d 'TEXT          Output sqlite file to this file'
complete -c flatterer -s d -l pushdown -d 'TEXT         Object keys and values, with this key name, will'
complete -c flatterer -s n -l no-link -d 'Do not create `_link` fields'
complete -c flatterer -s m -l main-table-name -d 'TEXT  Name of main table, defaults to name of the file'
complete -c flatterer -s p -l path -d 'TEXT             Key name of where json array starts, default top'
complete -c flatterer -s j -l ndjson -d 'Is file a new line delemited JSON file, default'
complete -c flatterer -l json-stream -d 'File contains stream of json object, default'
complete -c flatterer -l force -d 'Delete output directory if it exists, then run'
complete -c flatterer -s f -l fields -d 'TEXT           fields.csv file to use'
complete -c flatterer -s o -l only-fields -d 'Only output fields in fields.csv file'
complete -c flatterer -s b -l tables -d 'TEXT           tables.csv file to use'
complete -c flatterer -s l -l only-tables -d 'Only output tables in tables.csv file'
complete -c flatterer -s i -l inline-one-to-one -d 'If array only has single item for all objects'
complete -c flatterer -s y -l arrays-new-table -d 'Always treat arrays as new tables, even when'
complete -c flatterer -s s -l schema -d 'TEXT           JSONSchema file or URL to determine field order'
complete -c flatterer -s t -l table-prefix -d 'TEXT     Prefix to add to all table names'
complete -c flatterer -s a -l path-separator -d 'TEXT   Seperator to denote new path within the input'
complete -c flatterer -s h -l schema-titles -d 'TEXT    Use titles from JSONSchema in the given way.'
complete -c flatterer -s w -l preview -d 'INTEGER       Only output this `preview` amount of lines in'
complete -c flatterer -l threads -d 'INTEGER           Number of threads, default 1, 0 means use number'
complete -c flatterer -l json-path -d 'TEXT            JSON path within each object to use to filter'
complete -c flatterer -l postgres-schema -d 'TEXT      When loading to postgres, put all tables into'
complete -c flatterer -l evolve -d 'When loading to postgres or sqlite, evolve'
complete -c flatterer -l drop -d 'When loading to postgres or sqlite, drop table'
complete -c flatterer -l truncate -d 'When loading to postgres or sqlite, truncate the'
complete -c flatterer -l id-prefix -d 'TEXT            Prefix for all `_link` id fields'
complete -c flatterer -l stats -d 'Produce stats about the data in the'
complete -c flatterer -l help -d 'Show this message and exit.'
