complete -c ghfs -l prefix -d '<value>  serve files under URL path instead of /'
complete -c ghfs -l default-sort -d '<value> EnvVar: GHFS_DEFAULT_SORT Default: /n default sort for files and directories Available sort key:'
complete -c ghfs -l user -d '<value>  user info: <username>:<password>'
complete -c ghfs -l user-base64 -d '<value>  user info: <username>:<base64-password>'
complete -c ghfs -l user-md5 -d '<value>  user info: <username>:<md5-password>'
complete -c ghfs -l user-sha1 -d '<value>  user info: <username>:<sha1-password>'
complete -c ghfs -l user-sha256 -d '<value>  user info: <username>:<sha256-password>'
complete -c ghfs -l user-sha512 -d '<value>  user info: <username>:<sha512-password>'
complete -c ghfs -l global-auth -d 'EnvVar: GHFS_GLOBAL_AUTH require Basic Auth for all directories'
complete -c ghfs -l auth -d '<value>  url path that require Basic Auth'
complete -c ghfs -l auth-user -d '<value>  url path that require Basic Auth for specific users, <sep><url-path>[<sep><user>]'
complete -c ghfs -l auth-dir -d '<value>  file system path that require Basic Auth'
complete -c ghfs -l auth-dir-user -d '<value>  file system path that require Basic Auth for specific users, <sep><fs-path>[<sep><user>]'
complete -c ghfs -l index -d '<value>  Default: / url path that allow directory index'
complete -c ghfs -l index-user -d '<value>  url path that allow index files for specific users, <sep><url-path>[<sep><user>]'
complete -c ghfs -l index-dir -d '<value>  file system path that allow index files'
complete -c ghfs -l index-dir-user -d '<value>  file system path that allow index files for specific users, <sep><fs-path>[<sep><user>]'
complete -c ghfs -l upload-user -d '<value>  url path that allow upload files for specific users, <sep><url-path>[<sep><user>]'
complete -c ghfs -l upload-dir-user -d '<value>  file system path that allow upload files for specific users, <sep><fs-path>[<sep><user>]'
complete -c ghfs -l global-mkdir -d 'allow mkdir files for all url paths'
complete -c ghfs -l mkdir -d '<value>  url path that allow mkdir files'
complete -c ghfs -l mkdir-user -d '<value>  url path that allow mkdir files for specific users, <sep><url-path>[<sep><user>]'
complete -c ghfs -l mkdir-dir -d '<value>  file system path that allow mkdir files'
complete -c ghfs -l mkdir-dir-user -d '<value>  file system path that allow mkdir files for specific users, <sep><fs-path>[<sep><user>]'
complete -c ghfs -l global-delete -d 'allow delete files for all url paths'
complete -c ghfs -l delete -d '<value>  url path that allow delete files'
complete -c ghfs -l delete-user -d '<value>  url path that allow delete files for specific users, <sep><url-path>[<sep><user>]'
complete -c ghfs -l delete-dir -d '<value>  file system path that allow delete files'
complete -c ghfs -l delete-dir-user -d '<value>  file system path that allow delete files for specific users, <sep><fs-path>[<sep><user>]'
complete -c ghfs -l archive -d '<value>  url path that enable download as archive for specific directories'
complete -c ghfs -l archive-user -d '<value>  url path that allow archive files for specific users, <sep><url-path>[<sep><user>]'
complete -c ghfs -l archive-dir -d '<value>  file system path that enable download as archive for specific directories'
complete -c ghfs -l archive-dir-user -d '<value>  file system path that allow archive files for specific users, <sep><fs-path>[<sep><user>]'
complete -c ghfs -l global-cors -d 'EnvVar: GHFS_GLOBAL_CORS enable CORS headers for all directories'
complete -c ghfs -l cors -d '<value>  url path that enable CORS headers'
complete -c ghfs -l cors-dir -d '<value>  file system path that enable CORS headers'
complete -c ghfs -l global-restrict-access -d '<value>  EnvVar: GHFS_GLOBAL_RESTRICT_ACCESS restrict access to all url paths from current host, with optional extra allow list'
complete -c ghfs -l restrict-access -d '<value>  restrict access to specific url paths from current host, with optional extra allow list, <sep><url-path>[<sep><allowed-host>]'
complete -c ghfs -l restrict-access-dir -d '<value>  restrict access to specific file system paths from current host, with optional extra allow list, <sep><fs-path>[<sep><allowed-host>]'
complete -c ghfs -l global-header -d '<value>  EnvVar: GHFS_GLOBAL_HEADER custom headers for all url paths, e.g. <name>:<value>'
complete -c ghfs -l header -d '<value>  url path for custom headers, <sep><url><sep><name><sep><value>'
complete -c ghfs -l header-dir -d '<value>  file system path for custom headers, <sep><dir><sep><name><sep><value>'
complete -c ghfs -l listen-plain -d '<value>  EnvVar: GHFS_LISTEN_PLAIN address and port to listen, force plain http protocol'
complete -c ghfs -l listen-tls -d '<value>  EnvVar: GHFS_LISTEN_TLS address and port to listen, force https protocol'
complete -c ghfs -l hostname -d '<value>  hostname for the virtual host'
complete -c ghfs -l theme -d '<value> EnvVar: GHFS_THEME external theme file'
complete -c ghfs -l theme-dir -d '<value> EnvVar: GHFS_THEME_DIR external theme directory'
complete -c ghfs -l hsts -d '<value> EnvVar: GHFS_HSTS enable HSTS(HTTP Strict Transport Security)'
complete -c ghfs -l to-https -d '<value> EnvVar: GHFS_TO_HTTPS redirect http:// to https://, with optional target port'
complete -c ghfs -l config -d '<value> EnvVar: GHFS_CONFIG external config file'
complete -c ghfs -n __fish_no_arguments -l version -d 'print version'
