complete -c gifski -s o -l output -d '<a.gif>'
complete -c gifski -s r -l fps -d '<num>'
complete -c gifski -l fast-forward -d '<x>'
complete -c gifski -s Q -l quality -d '<1-100>'
complete -c gifski -l motion-quality -d '<1-100>'
complete -c gifski -l lossy-quality -d '<1-100>'
complete -c gifski -s W -l width -d '<px>'
complete -c gifski -s H -l height -d '<px>'
complete -c gifski -l repeat -d '<num>'
complete -c gifski -l fixed-color -d '<RGBHEX>'
complete -c gifski -l matte -d '<RGBHEX>'
