complete -c gman -s d -l debug -d 'emit debugging messages'
complete -c gman -s D -l default -d 'reset all options to their default values'
complete -c gman -s f -l whatis -d 'equivalent to whatis'
complete -c gman -s k -l apropos -d 'equivalent to apropos'
complete -c gman -s K -l global-apropos -d 'search for text in all pages'
complete -c gman -s l -l local-file -d 'interpret PAGE argument(s) as local filename(s)'
complete -c gman -s c -l catman -d 'used by catman to reformat out of date cat pages'
complete -c gman -s i -l ignore-case -d 'look for pages case-insensitively (default)'
complete -c gman -s I -l match-case -d 'look for pages case-sensitively'
complete -c gman -l regex -d 'show all pages matching regex'
complete -c gman -l wildcard -d 'show all pages matching wildcard'
complete -c gman -l names-only -d 'make --regex and --wildcard match page names only,'
complete -c gman -s a -l all -d 'find all matching manual pages'
complete -c gman -s u -l update -d 'force a cache consistency check'
complete -c gman -l no-subpages -d "don't try subpages, e.g. 'man foo bar' => 'man"
complete -c gman -s 7 -l ascii -d 'display ASCII translation of certain latin1 chars'
complete -c gman -s t -l troff -d 'use groff to format pages'
complete -c gman -s X -d '= -TX75, -X100 = -TX100, -X100-12 = -TX100-12'
complete -c gman -s Z -l ditroff -d 'use groff and force it to produce ditroff'
complete -c gman -l usage -d 'give a short usage message'
