complete -c gmv -s b -d 'like --backup but does not accept an argument'
complete -c gmv -l debug -d 'explain how a file is copied.  Implies -v'
complete -c gmv -l exchange -d 'exchange source and destination'
complete -c gmv -s f -l force -d 'do not prompt before overwriting'
complete -c gmv -s i -l interactive -d 'prompt before overwrite'
complete -c gmv -s n -l no-clobber -d 'do not overwrite an existing file'
complete -c gmv -l no-copy -d 'do not copy if renaming fails'
complete -c gmv -l strip-trailing-slashes -d 'remove any trailing slashes from each SOURCE'
complete -c gmv -s T -l no-target-directory -d 'treat DEST as a normal file'
complete -c gmv -s u -d 'equivalent to --update[=older].  See below'
complete -c gmv -s v -l verbose -d 'explain what is being done'
complete -c gmv -s Z -l context -d 'set SELinux security context of destination'
complete -c gmv -l help -d 'display this help and exit'
complete -c gmv -n __fish_no_arguments -l version -d 'output version information and exit'
