complete -c guru -l openai-api-key -d '<openai-api-key>'
complete -c guru -l socks5 -d '<socks5>          set the socks5 proxy(default="")'
complete -c guru -l timeout -d '<timeout>        the timeout duration for a request(default=180s)'
complete -c guru -l system -d '<system>          the optional system prompt for initializing the'
complete -c guru -s p -l prompt -d '<prompt>          the prompt to use(default="")'
complete -c guru -s f -l file -d '<file>              send the file content after sending the text(if'
complete -c guru -s v -l verbose -d 'print verbose messages'
complete -c guru -l stdin -d read\ from\ stdin,\ works\ as\ \'-f\ --\'
complete -c guru -l pin -d 'pin the initial messages'
complete -c guru -l last -d 'continue the last session'
complete -c guru -s e -l executor -d '<executor>      execute what the ai returned using the executor.'
complete -c guru -l feedback -d 'feedback the output of executor'
complete -c guru -s 1 -l oneshot -d 'avoid maintaining the context, submit the user'
complete -c guru -s n -l non-interactive -d 'chat in none interactive mode'
complete -c guru -l disable-auto-shrink -d 'disable auto shrink messages when tokens limit'
complete -c guru -l dir -d '<dir>                the guru directory(default=~/.guru)'
complete -c guru -s s -l session-id -d '<session-id>  the session id(default="")'
complete -c guru -l renderer -d '<renderer>      the render type, can be text, markdown, json(default=markdown)'
complete -c guru -s h -l help -d 'help for the command'
complete -c guru -s c -l conf -d '<conf>              path of the configuration file'
