complete -c hevi -s h -d 'Print this help message'
complete -c hevi -l help -d 'Print this help message'
complete -c hevi -s v -d 'Print version information'
complete -c hevi -n __fish_no_arguments -l version -d 'Print version information'
complete -c hevi -l color -d 'Enable or disable output coloring'
complete -c hevi -l no-color -d 'Enable or disable output coloring'
complete -c hevi -l lowercase -d 'Switch between lowercase and uppercase hex'
complete -c hevi -l uppercase -d 'Switch between lowercase and uppercase hex'
complete -c hevi -l size -d 'Enable or disable showing the size at the end'
complete -c hevi -l no-size -d 'Enable or disable showing the size at the end'
complete -c hevi -l offset -d 'Enable or disable the offset at the left'
complete -c hevi -l no-offset -d 'Enable or disable the offset at the left'
complete -c hevi -l ascii -d 'Enable or disable the ASCII output'
complete -c hevi -l no-ascii -d 'Enable or disable the ASCII output'
complete -c hevi -l skip-lines -d 'Enable or disable skipping of identical lines'
complete -c hevi -l no-skip-lines -d 'Enable or disable skipping of identical lines'
complete -c hevi -l raw -d 'Output in raw format (disables most features)'
complete -c hevi -l show-palette -d 'Print the color palette being used'
complete -c hevi -l parser -d 'Specify the parser to use. Available parsers:'
