complete -c htmlext -s x -l hext -d '<file>           Add Hext from file'
complete -c htmlext -s i -l html -d '<file>           Add HTML from file'
complete -c htmlext -s s -l str -d '<string>          Add Hext from string'
complete -c htmlext -s c -l compact -d 'Print one JSON object per line'
complete -c htmlext -s p -l pretty -d 'Pretty-print JSON'
complete -c htmlext -s a -l array -d 'Wrap results in a JSON array'
complete -c htmlext -s f -l filter -d '<key>          Print values whose name matches <key>'
complete -c htmlext -s l -l lint -d 'Do Hext syntax check'
complete -c htmlext -s m -l max-searches -d '<amount> Abort after this many searches. The default is'
complete -c htmlext -s h -l help -d 'Print this help message'
complete -c htmlext -n __fish_no_arguments -s V -l version -d 'Print info and version'
