complete -c htmlq -s B -l detect-base -d 'Try to detect the base URL from the <base> tag in the document. If not found, default to'
complete -c htmlq -s h -l help -d 'Prints help information'
complete -c htmlq -s w -l ignore-whitespace -d 'When printing text nodes, ignore those that consist entirely of whitespace'
complete -c htmlq -s p -l pretty -d 'Pretty-print the serialised output'
complete -c htmlq -s t -l text -d 'Output only the contents of text nodes inside selected elements'
complete -c htmlq -n __fish_no_arguments -s V -l version -d 'Prints version information'
complete -c htmlq -s a -l attribute -d '<attribute>         Only return this attribute (if present) from selected elements'
complete -c htmlq -s b -l base -d '<base>                   Use this URL as the base for links'
complete -c htmlq -s f -l filename -d '<FILE>               The input file. Defaults to stdin'
complete -c htmlq -s o -l output -d '<FILE>                 The output file. Defaults to stdout'
complete -c htmlq -s r -l remove-nodes -d '<SELECTOR>...    Remove nodes matching this expression before output. May be specified multiple'
