complete -c http-server -s p -l port -d 'Port to use. If 0, look for open port. [8080]'
complete -c http-server -s a -d 'Address to use [0.0.0.0]'
complete -c http-server -s d -d 'Show directory listings [true]'
complete -c http-server -s i -d 'Display autoIndex [true]'
complete -c http-server -s g -l gzip -d 'Serve gzip files when possible [false]'
complete -c http-server -s b -l brotli -d 'Serve brotli files when possible [false]'
complete -c http-server -s e -l ext -d 'Default file extension if none supplied [none]'
complete -c http-server -s s -l silent -d 'Suppress log messages from output'
complete -c http-server -s o -d '[path]    Open browser window after starting the server.'
complete -c http-server -s c -d 'Cache time (max-age) in seconds [3600], e.g. -c10 for 10 seconds.'
complete -c http-server -s t -d 'Connections timeout in seconds [120], e.g. -t60 for 1 minute.'
complete -c http-server -s U -l utc -d 'Use UTC time format in log messages.'
complete -c http-server -l log-ip -d "Enable logging of the client's IP address"
complete -c http-server -s P -l proxy -d 'Fallback proxy if the request cannot be resolved. e.g.: http://someurl.com'
complete -c http-server -l proxy-options -d 'Pass options to proxy using nested dotted objects. e.g.: --proxy-options.secure false'
complete -c http-server -l username -d 'Username for basic authentication [none]'
complete -c http-server -l password -d 'Password for basic authentication [none]'
complete -c http-server -s S -l tls -d '--ssl   Enable secure request serving with TLS/SSL (HTTPS)'
complete -c http-server -s C -l cert -d 'Path to TLS cert file (default: cert.pem)'
complete -c http-server -s K -l key -d 'Path to TLS key file (default: key.pem)'
complete -c http-server -s r -l robots -d 'Respond to /robots.txt [User-agent: *\\nDisallow: /]'
complete -c http-server -l no-dotfiles -d 'Do not show dotfiles'
complete -c http-server -l mimetypes -d 'Path to a .types file for custom mimetype definition'
complete -c http-server -s h -l help -d 'Print this list and exit.'
complete -c http-server -n __fish_no_arguments -s v -l version -d 'Print the version and exit.'
