complete -c imagecat -s h -l help -d 'Display help message'
complete -c imagecat -s p -l print -d 'Enable printing of filename or URL after each image'
complete -c imagecat -s n -l no-print -d 'Disable printing of filename or URL after each image'
complete -c imagecat -s u -l url -d 'Interpret following filename arguments as remote URLs'
complete -c imagecat -s f -l file -d 'Interpret following filename arguments as regular Files'
complete -c imagecat -s t -l type -d 'file-type            Provides a type hint'
complete -c imagecat -s r -l preserve-aspect-ratio -d 'When scaling image preserve its original aspect ratio'
complete -c imagecat -s s -l stretch -d 'Stretch image to specified width and height (this option is opposite to -r)'
complete -c imagecat -s W -l width -d 'N                   Set image width to N character cells, pixels or percent (see below)'
complete -c imagecat -s H -l height -d 'N                  Set image height to N character cells, pixels or percent (see below)'
