complete -c jj -s v -d 'value             Edit JSON key path value'
complete -c jj -s p -d 'Make json pretty, keypath is optional'
complete -c jj -s u -d 'Make json ugly, keypath is optional'
complete -c jj -s r -d 'Use raw values, otherwise types are auto-detected'
complete -c jj -s n -d 'Do not output color or extra formatting'
complete -c jj -s O -d 'Performance boost for value updates'
complete -c jj -s D -d 'Delete the value at the specified key path'
complete -c jj -s l -d 'Output array values on multiple lines'
complete -c jj -s i -d 'infile            Use input file instead of stdin'
complete -c jj -s o -d 'outfile           Use output file instead of stdout'
