complete -c json2csv -n __fish_no_arguments -s V -l version -d 'output the version number'
complete -c json2csv -s i -l input -d '<input>                 Path and name of the incoming json file.'
complete -c json2csv -s o -l output -d '<output>               Path and name of the resulting csv file.'
complete -c json2csv -s c -l config -d '<path>                 Specify a file with a valid JSON'
complete -c json2csv -s n -l ndjson -d 'Treat the input as NewLine-Delimited'
complete -c json2csv -s s -l no-streaming -d 'Process the whole JSON array in memory'
complete -c json2csv -s f -l fields -d '<fields>               List of fields to process. Defaults to'
complete -c json2csv -s v -l default-value -d '<defaultValue>  Default value to use for missing fields.'
complete -c json2csv -s q -l quote -d '<quote>                 Character(s) to use as quote mark.'
complete -c json2csv -s Q -l escaped-quote -d '<escapedQuote>  Character(s) to use as a escaped quote.'
complete -c json2csv -s d -l delimiter -d '<delimiter>         Character(s) to use as delimiter.'
complete -c json2csv -s e -l eol -d '<eol>                     Character(s) to use as End-of-Line for'
complete -c json2csv -s E -l excel-strings -d 'Wraps string data to force Excel to'
complete -c json2csv -s H -l no-header -d 'Disable the column name header.'
complete -c json2csv -s a -l include-empty-rows -d 'Includes empty rows in the resulting CSV'
complete -c json2csv -s b -l with-bom -d 'Includes BOM character at the beginning'
complete -c json2csv -s p -l pretty -d 'Print output as a pretty table. Use only'
complete -c json2csv -l unwind -d '[paths]                    Creates multiple rows from a single JSON'
complete -c json2csv -l unwind-blank -d 'When unwinding, blank out instead of'
complete -c json2csv -l flatten-objects -d 'Flatten nested objects. Defaults to'
complete -c json2csv -l flatten-arrays -d 'Flatten nested arrays. Defaults to false.'
complete -c json2csv -l flatten-separator -d '<separator>     Flattened keys separator. Defaults to'
complete -c json2csv -s h -l help -d 'display help for command'
