complete -c lazygit -s h -l help -d 'Displays help with available flag, subcommand, and positional value parameters.'
complete -c lazygit -s p -l path -d 'Path of git repo. (equivalent to --work-tree=<path> --git-dir=<path>/.git/)'
complete -c lazygit -s f -l filter -d 'Path to filter on in `git log -- <path>`. When in filter mode, the commits, reflog, and stash are filtered based on the given path, and some operations are restricted'
complete -c lazygit -n __fish_no_arguments -s v -l version -d 'Print the current version'
complete -c lazygit -s d -l debug -d 'Run in debug mode with logging (see --logs flag below). Use the LOG_LEVEL env var to set the log level (debug/info/warn/error)'
complete -c lazygit -s l -l logs -d 'Tail lazygit logs (intended to be used when `lazygit --debug` is called in a separate terminal tab)'
complete -c lazygit -l profile -d 'Start the profiler and serve it on http port 6060. See CONTRIBUTING.md for more info.'
complete -c lazygit -s c -l config -d 'Print the default config'
complete -c lazygit -s cd -d '--print-config-dir   Print the config directory'
complete -c lazygit -s ucd -d '--use-config-dir     override default config directory with provided directory'
complete -c lazygit -s w -l work-tree -d 'equivalent of the --work-tree git argument'
complete -c lazygit -s g -l git-dir -d 'equivalent of the --git-dir git argument'
complete -c lazygit -s ucf -d '--use-config-file    Comma separated list to custom config file(s)'
