complete -c lizard -s 10...-19 -d ': compression method fastLZ4 = 16-bit bytewise codewords'
complete -c lizard -s 20...-29 -d ': compression method LIZv1 = 24-bit bytewise codewords'
complete -c lizard -s 30...-39 -d ': compression method fastLZ4 + Huffman'
complete -c lizard -s 40...-49 -d ': compression method LIZv1 + Huffman'
complete -c lizard -s d -d ': decompression (default for .liz extension)'
complete -c lizard -s z -d ': force compression'
complete -c lizard -s f -d ': overwrite output without prompting'
complete -c lizard -l rm -d ': remove source file(s) after successful de/compression'
complete -c lizard -s V -d ': display Version number and exit'
complete -c lizard -s v -d ': verbose mode'
complete -c lizard -s q -d ': suppress warnings; specify twice to suppress errors too'
complete -c lizard -s c -d ': force write to standard output, even if it is the console'
complete -c lizard -s t -d ': test compressed file integrity'
complete -c lizard -s m -d ': multiple input files (implies automatic output filenames)'
complete -c lizard -s r -d ': operate recursively on directories (sets also -m)'
complete -c lizard -s BD -d ': Block dependency (improve compression ratio)'
complete -c lizard -l no-frame-crc -d ': disable stream checksum (default:enabled)'
complete -c lizard -l content-size -d ': compressed frame includes original size (default:not present)'
