complete -f -c log -n __fish_use_subcommand -a collect -d 'gather system logs into a log archive'
complete -c log -n '__fish_seen_subcommand_from collect' -l device -d 'Collect logs from first device found'
complete -c log -n '__fish_seen_subcommand_from collect' -l device-name -d '<name>          Collect logs from device with the given name'
complete -c log -n '__fish_seen_subcommand_from collect' -l device-udid -d '<UDID>          Collect logs from device with the given UDID'
complete -c log -n '__fish_seen_subcommand_from collect' -l last -d '<num>[m|h|d]           Collect logs starting <num>[m|h|d] ago'
complete -c log -n '__fish_seen_subcommand_from collect' -l output -d '<path>               Output log archive to the given path'
complete -c log -n '__fish_seen_subcommand_from collect' -l size -d '<num>[k|m]             Limit log collection to the given size'
complete -c log -n '__fish_seen_subcommand_from collect' -l start -d '<time>                Collect logs starting at the given time'
complete -c log -n '__fish_seen_subcommand_from collect' -l predicate -d '<predicate>       Collect logs using a given predicate'
complete -f -c log -n __fish_use_subcommand -a config -d 'view/change logging system settings'
complete -c log -n '__fish_seen_subcommand_from config' -l category -d '<name>             Get/set settings for a given category'
complete -c log -n '__fish_seen_subcommand_from config' -l mode -d '<modes>                Enable given modes'
complete -c log -n '__fish_seen_subcommand_from config' -l process -d '<pid> | <name>      Get/set settings for a given process'
complete -c log -n '__fish_seen_subcommand_from config' -l reset -d 'Reset settings to defaults'
complete -c log -n '__fish_seen_subcommand_from config' -l status -d 'Show current settings'
complete -c log -n '__fish_seen_subcommand_from config' -l subsystem -d '<name>            Get/set settings for a given subsystem'
complete -f -c log -n __fish_use_subcommand -a erase -d 'delete system logging data'
complete -c log -n '__fish_seen_subcommand_from erase' -l all -d 'Erase all log data'
complete -c log -n '__fish_seen_subcommand_from erase' -l ttl -d 'Erase log data marked with a time-to-live'
complete -f -c log -n __fish_use_subcommand -a repack -d 'repack a log archive using a predicate'
complete -c log -n '__fish_seen_subcommand_from repack' -l archive -d '<archive>           Archive to be repacked'
complete -c log -n '__fish_seen_subcommand_from repack' -l no-timeout -d 'Remove the default timeout (5 Mins) for repacking'
complete -c log -n '__fish_seen_subcommand_from repack' -l fatal-warnings -d 'Treat all warnings as errors and stop repacking'
complete -c log -n '__fish_seen_subcommand_from repack' -l predicate -d '<predicate>       Include events matching a predicate'
complete -c log -n '__fish_seen_subcommand_from repack' -l verbose -d 'Include extra output for debugging'
complete -c log -n '__fish_seen_subcommand_from repack' -l mutate -d "Mutates logarchive 'in-place' without copying it"
complete -c log -n '__fish_seen_subcommand_from repack' -l skip-uuid-purge -d 'Skip purging unused UUIDs from the resulting archive'
complete -f -c log -n __fish_use_subcommand -a show -d 'view/search system logs'
complete -c log -n '__fish_seen_subcommand_from show' -l debug -d 'are specified.'
complete -c log -n '__fish_seen_subcommand_from show' -l color -d '<mode>                Control color output (valid: auto, always, none)'
complete -c log -n '__fish_seen_subcommand_from show' -l end -d '<date>                  Display events up to the given end date'
complete -c log -n '__fish_seen_subcommand_from show' -l last -d '<num>[m|h|d]           Display recent events up to the given limit'
complete -c log -n '__fish_seen_subcommand_from show' -l predicate -d '<predicate>       Filter events using the given predicate'
complete -c log -n '__fish_seen_subcommand_from show' -l process -d '<pid> | <process>   Filter events using the specified process'
complete -c log -n '__fish_seen_subcommand_from show' -l source -d 'Annotate output with source file and line-number'
complete -c log -n '__fish_seen_subcommand_from show' -l start -d '<date>                Display events from the given start date'
complete -c log -n '__fish_seen_subcommand_from show' -l style -d '<style>               Output format (valid: default, syslog, json, ndjson, compact)'
complete -c log -n '__fish_seen_subcommand_from show' -l timezone -d 'local | <tz>       Use the given timezone when displaying event timestamps'
complete -c log -n '__fish_seen_subcommand_from show' -l mach-continuous-time -d 'Print mach continuous time timestamps rather than walltime'
complete -c log -n '__fish_seen_subcommand_from show' -l unreliable -d 'Annotate output with whether the log was emitted unreliably'
complete -f -c log -n __fish_use_subcommand -a stream -d 'watch live system logs'
complete -c log -n '__fish_seen_subcommand_from stream' -l color -d '<mode>                  Control color output (valid: auto, always, none)'
complete -c log -n '__fish_seen_subcommand_from stream' -l level -d 'default | info | debug  Include events at, and below, the given level'
complete -c log -n '__fish_seen_subcommand_from stream' -l predicate -d '<predicate>         Filter events using the given predicate'
complete -c log -n '__fish_seen_subcommand_from stream' -l process -d '<pid> | <process>     Stream events from the specified process'
complete -c log -n '__fish_seen_subcommand_from stream' -l user -d '<uid> | <user>           Stream events from the specified user'
complete -c log -n '__fish_seen_subcommand_from stream' -l source -d 'Annotate output with source file and line-number'
complete -c log -n '__fish_seen_subcommand_from stream' -l style -d '<style>                 Output format (valid: default, syslog, json, ndjson, compact)'
complete -c log -n '__fish_seen_subcommand_from stream' -l timeout -d '<num>[m|h|d]          Terminate streaming after timeout has elapsed'
complete -c log -n '__fish_seen_subcommand_from stream' -l type -d 'activity | log | trace   Limit streaming to a given event type'
complete -c log -n '__fish_seen_subcommand_from stream' -l mach-continuous-time -d 'Print mach continuous time timestamps rather than walltime'
complete -c log -n '__fish_seen_subcommand_from stream' -l unreliable -d 'Annotate output with whether the log was emitted unreliably'
complete -c log -n '__fish_seen_subcommand_from stream' -l ignore-dropped -d "Don't output anything for dropped messages while streaming"
complete -f -c log -n __fish_use_subcommand -a stats -d 'show system logging statistics'
complete -c log -n '__fish_seen_subcommand_from stats' -l archive -d '<archive>           Display statistics from the given log archive'
complete -c log -n '__fish_seen_subcommand_from stats' -l count -d '<count> | all         Limit output to <count> rows per section (default: 5)'
complete -c log -n '__fish_seen_subcommand_from stats' -l sort -d '<sort-mode>            Sort output by number of events, or number of bytes'
complete -c log -n '__fish_seen_subcommand_from stats' -l last -d '<num>[m|h|d] | boot    Display statistics for event up to the given limit'
complete -c log -n '__fish_seen_subcommand_from stats' -l start -d '<date>                Display statistics for events from the given start date'
complete -c log -n '__fish_seen_subcommand_from stats' -l end -d '<date>                  Display statistics for events up to the given end date'
complete -c log -n '__fish_seen_subcommand_from stats' -l style -d 'human | json          Control the output style of the requested content'
complete -c log -n '__fish_seen_subcommand_from stats' -l overview -d 'Display statistics for the entire log archive (default)'
complete -c log -n '__fish_seen_subcommand_from stats' -l per-book -d 'Display statistics per log book in the archive'
complete -c log -n '__fish_seen_subcommand_from stats' -l per-file -d 'Display statistics per file in the archive'
complete -c log -n '__fish_seen_subcommand_from stats' -l sender -d '<sender>             Display statistics for a given sender in the archive'
complete -c log -n '__fish_seen_subcommand_from stats' -l process -d '<process>           Display statistics for a given process in the archive'
complete -c log -n '__fish_seen_subcommand_from stats' -l predicate -d '<predicate>       Display statistics for all events in the archive that'
