complete -c lynx -s accept_all_cookies
complete -c lynx -s anonymous -d 'apply restrictions for anonymous account,'
complete -c lynx -s base -d 'prepend a request URL comment and BASE tag to text/html'
complete -c lynx -s book -d 'use the bookmark page as the startfile (off)'
complete -c lynx -s buried_news -d 'toggles scanning of news articles for buried references (on)'
complete -c lynx -s case -d 'enable case sensitive user searching (off)'
complete -c lynx -s center -d 'toggle center alignment in HTML TABLE (off)'
complete -c lynx -s child -d 'exit on left-arrow in startfile, and disable save to disk'
complete -c lynx -s child_relaxed -d 'exit on left-arrow in startfile (allows save to disk)'
complete -c lynx -s collapse_br_tags -d 'toggles collapsing of BR tags (on)'
complete -c lynx -s cookies -d 'toggles handling of Set-Cookie headers (on)'
complete -c lynx -s core -d 'toggles forced core dumps on fatal errors (off)'
complete -c lynx -s crawl -d 'with -traversal, output each page to a file'
complete -c lynx -s curses_pads -d 'uses curses pad feature to support left/right shifting (on)'
complete -c lynx -s debug_partial -d 'incremental display stages with MessageSecs delay (off)'
complete -c lynx -s default_colors -d 'use terminal default foreground/background colors (on)'
complete -c lynx -s dont_wrap_pre -d inhibit\ wrapping\ of\ text\ in\ \<pre\>\ when\ -dump\'ing\ and
complete -c lynx -s dump -d 'dump the first file to stdout and exit'
complete -c lynx -s emacskeys -d 'enable emacs-like key movement (off)'
complete -c lynx -s enable_scrollback
complete -c lynx -s force_empty_hrefless_a
complete -c lynx -s force_html -d 'forces the first document to be interpreted as HTML (off)'
complete -c lynx -s force_secure -d 'toggles forcing of the secure flag for SSL cookies (off)'
complete -c lynx -s forms_options -d 'toggles forms-based vs old-style options menu (on)'
complete -c lynx -s from -d 'toggle transmission of From headers (on)'
complete -c lynx -s ftp -d 'disable ftp access (off)'
complete -c lynx -s get_data -d 'user data for get forms, read from stdin,'
complete -c lynx -s head -d 'send a HEAD request (off)'
complete -c lynx -s help -d 'print this usage message'
complete -c lynx -s historical -d toggles\ use\ of\ \'\>\'\ or\ \'--\>\'\ as\ terminator\ for\ comments\ \(off\)
complete -c lynx -s html5_charsets -d 'toggles use of HTML5 charset replacements (off)'
complete -c lynx -s image_links -d 'toggles inclusion of links for all images (off)'
complete -c lynx -s ismap -d 'toggles inclusion of ISMAP links when client-side'
complete -c lynx -s justify -d 'do justification of text (off)'
complete -c lynx -s list_inline -d 'with -dump, forces it to show links inline with text (off)'
complete -c lynx -s listonly -d 'with -dump, forces it to show only the list of links (off)'
complete -c lynx -s localhost -d 'disable URLs that point to remote hosts (off)'
complete -c lynx -s mime_header -d 'include mime headers and force source dump'
complete -c lynx -s minimal -d 'toggles minimal versus valid comment parsing (on)'
complete -c lynx -s nobold -d 'disable bold video-attribute'
complete -c lynx -s nobrowse -d 'disable directory browsing'
complete -c lynx -s nocc -d 'disable Cc: prompts for self copies of mailings (off)'
complete -c lynx -s nocolor -d 'turn off color support'
complete -c lynx -s nofilereferer -d 'disable transmission of Referer headers for file URLs (on)'
complete -c lynx -s nolist -d 'disable the link list feature in dumps (off)'
complete -c lynx -s nolog -d 'disable mailing of error messages to document owners (on)'
complete -c lynx -s nomargins -d 'disable the right/left margins in the default'
complete -c lynx -s nomore -d 'disable -more- string in statusline messages'
complete -c lynx -s nonrestarting_sigwinch
complete -c lynx -s nonumbers -d 'disable the link/form numbering feature in dumps (off)'
complete -c lynx -s nopause -d 'disable forced pauses for statusline messages'
complete -c lynx -s noprint -d 'disable some print functions, like -restrictions=print (off)'
complete -c lynx -s noredir -d don\'t\ follow\ Location:\ redirection\ \(off\)
complete -c lynx -s noreferer -d 'disable transmission of Referer headers (off)'
complete -c lynx -s noreverse -d 'disable reverse video-attribute'
complete -c lynx -s nostatus -d 'disable the miscellaneous information messages (off)'
complete -c lynx -s notitle -d 'disable the title at the top of each page (off)'
complete -c lynx -s nounderline -d 'disable underline video-attribute'
complete -c lynx -s number_fields -d 'force numbering of links as well as form input fields (off)'
complete -c lynx -s number_links -d 'force numbering of links (off)'
complete -c lynx -s partial -d 'toggles display partial pages while downloading (on)'
complete -c lynx -s partial_thres -d '[=NUMBER]'
complete -c lynx -s passive_ftp -d 'toggles passive ftp connection (on)'
complete -c lynx -s popup -d 'toggles handling of single-choice SELECT options via'
complete -c lynx -s post_data -d 'user data for post forms, read from stdin,'
complete -c lynx -s preparsed -d 'show parsed text/html with -source and in source view'
complete -c lynx -s prettysrc -d 'do syntax highlighting and hyperlink handling in source'
complete -c lynx -s print -d 'enable print functions (DEFAULT), opposite of -noprint (on)'
complete -c lynx -s pseudo_inlines -d 'toggles pseudo-ALTs for inlines with no ALT string (on)'
complete -c lynx -s raw -d 'toggles default setting of 8-bit character translations'
complete -c lynx -s realm -d 'restricts access to URLs in the starting realm (off)'
complete -c lynx -s reload -d 'flushes the cache on a proxy server'
complete -c lynx -s resubmit_posts -d 'toggles forced resubmissions (no-cache) of forms with'
complete -f -c lynx -n __fish_use_subcommand -a -rlogin -d 'disable rlogins (off)'
complete -f -c lynx -n __fish_use_subcommand -a -scrollbar -d 'toggles showing scrollbar (off)'
complete -f -c lynx -n __fish_use_subcommand -a -scrollbar_arrow -d 'toggles showing arrows at ends of the scrollbar (on)'
complete -f -c lynx -n __fish_use_subcommand -a -selective -d 'require .www_browsable files to browse directories'
complete -f -c lynx -n __fish_use_subcommand -a -session -d 'FILENAME resumes from specified file on startup and'
complete -f -c lynx -n __fish_use_subcommand -a saves -d 'session to that file on exit'
complete -f -c lynx -n __fish_use_subcommand -a -sessionin -d FILENAME
complete -f -c lynx -n __fish_use_subcommand -a resumes -d 'session from specified file'
complete -f -c lynx -n __fish_use_subcommand -a -sessionout -d FILENAME
complete -f -c lynx -n __fish_use_subcommand -a saves -d 'session to specified file'
complete -f -c lynx -n __fish_use_subcommand -a -short_url -d 'enables examination of beginning and end of long URL in'
complete -f -c lynx -n __fish_use_subcommand -a status -d 'line (off)'
complete -f -c lynx -n __fish_use_subcommand -a -show_cfg -d Show\ `LYNX.CFG\'\ setting\ \(off\)
complete -f -c lynx -n __fish_use_subcommand -a -show_cursor -d 'toggles hiding of the cursor in the lower right corner (on)'
complete -f -c lynx -n __fish_use_subcommand -a -show_rate -d 'toggles display of transfer rate (on)'
complete -f -c lynx -n __fish_use_subcommand -a -soft_dquotes -d 'toggles emulation of the old Netscape and Mosaic'
complete -f -c lynx -n __fish_use_subcommand -a bug -d which\ treated\ \'\>\'\ as\ a\ co-terminator\ for
complete -f -c lynx -n __fish_use_subcommand -a double-quotes -d 'and tags (off)'
complete -f -c lynx -n __fish_use_subcommand -a -source -d 'dump the source of the first file to stdout and exit'
complete -f -c lynx -n __fish_use_subcommand -a -stack_dump -d 'disable SIGINT cleanup handler (off)'
complete -f -c lynx -n __fish_use_subcommand -a -startfile_ok -d 'allow non-http startfile and homepage with -validate (off)'
complete -f -c lynx -n __fish_use_subcommand -a -stderr -d 'write warning messages to standard error when -dump'
complete -f -c lynx -n __fish_use_subcommand -a or -d '-source is used (off)'
complete -f -c lynx -n __fish_use_subcommand -a -stdin -d 'read startfile from standard input (off)'
complete -f -c lynx -n __fish_use_subcommand -a -tagsoup -d 'use TagSoup rather than SortaSGML parser (off)'
complete -f -c lynx -n __fish_use_subcommand -a -telnet -d 'disable telnets (off)'
complete -f -c lynx -n __fish_use_subcommand -a -term -d 'TERM        set terminal type to TERM'
complete -f -c lynx -n __fish_use_subcommand -a -tlog -d 'toggles use of a Lynx Trace Log for the current'
complete -f -c lynx -n __fish_use_subcommand -a session -d '(on)'
complete -f -c lynx -n __fish_use_subcommand -a -tna -d 'turn on "Textfields Need Activation" mode (off)'
complete -f -c lynx -n __fish_use_subcommand -a -trace -d 'turns on Lynx trace mode (off)'
complete -f -c lynx -n __fish_use_subcommand -a -trace_mask -d 'customize Lynx trace mode (0)'
complete -f -c lynx -n __fish_use_subcommand -a -traversal -d 'traverse all http links derived from startfile'
complete -f -c lynx -n __fish_use_subcommand -a -trim_blank_lines -d ''
complete -f -c lynx -n __fish_use_subcommand -a toggle -d 'trimming of leading/trailing/collapsed-br blank lines (on)'
complete -f -c lynx -n __fish_use_subcommand -a -trim_input_fields -d ''
complete -f -c lynx -n __fish_use_subcommand -a trim -d 'input text/textarea fields in forms (off)'
complete -f -c lynx -n __fish_use_subcommand -a -underline_links -d 'toggles use of underline/bold attribute for links (off)'
complete -f -c lynx -n __fish_use_subcommand -a -underscore -d 'toggles use of _underline_ format in dumps (off)'
complete -f -c lynx -n __fish_use_subcommand -a -unique_urls -d 'toggles use of unique-urls setting for -dump and -listonly options (off)'
complete -f -c lynx -n __fish_use_subcommand -a -use_mouse -d 'turn on mouse support (off)'
complete -f -c lynx -n __fish_use_subcommand -a -useragent -d 'Name   set alternate Lynx User-Agent header'
complete -f -c lynx -n __fish_use_subcommand -a -validate -d 'accept only http URLs (meant for validation)'
complete -f -c lynx -n __fish_use_subcommand -a implies -d 'more restrictions than -anonymous, but'
complete -f -c lynx -n __fish_use_subcommand -a goto -d 'is allowed for http and https (off)'
complete -f -c lynx -n __fish_use_subcommand -a -verbose -d 'toggles [LINK], [IMAGE] and [INLINE] comments'
complete -f -c lynx -n __fish_use_subcommand -a with -d 'filenames of these images (on)'
complete -f -c lynx -n __fish_use_subcommand -a -version -d 'print Lynx version information'
complete -f -c lynx -n __fish_use_subcommand -a -vikeys -d 'enable vi-like key movement (off)'
complete -f -c lynx -n __fish_use_subcommand -a -width -d 'NUMBER     screen width for formatting of dumps (default is 80)'
complete -f -c lynx -n __fish_use_subcommand -a -with_backspaces -d 'emit backspaces in output if -dumping or -crawling'
complete -c lynx -s xhtml_parsing -d 'enable XHTML 1.0 parsing (off)'
