complete -c lz5 -s 10...-19 -d ': compression method fastLZ4 = 16-bit bytewise codewords'
complete -c lz5 -s 20...-29 -d ': compression method LZ5v2 = 24-bit bytewise codewords'
complete -c lz5 -s 30...-39 -d ': compression method fastLZ4 + Huffman'
complete -c lz5 -s 40...-49 -d ': compression method LZ5v2 + Huffman'
complete -c lz5 -s d -d ': decompression (default for .lz5 extension)'
complete -c lz5 -s z -d ': force compression'
complete -c lz5 -s f -d ': overwrite output without prompting'
complete -c lz5 -l rm -d ': remove source file(s) after successful de/compression'
complete -c lz5 -s V -d ': display Version number and exit'
complete -c lz5 -s v -d ': verbose mode'
complete -c lz5 -s q -d ': suppress warnings; specify twice to suppress errors too'
complete -c lz5 -s c -d ': force write to standard output, even if it is the console'
complete -c lz5 -s t -d ': test compressed file integrity'
complete -c lz5 -s m -d ': multiple input files (implies automatic output filenames)'
complete -c lz5 -s r -d ': operate recursively on directories (sets also -m)'
complete -c lz5 -s BD -d ': Block dependency (improve compression ratio)'
complete -c lz5 -l no-frame-crc -d ': disable stream checksum (default:enabled)'
complete -c lz5 -l content-size -d ': compressed frame includes original size (default:not present)'
