complete -c markdown-crawler -s h -l help -d 'show this help message and exit'
complete -c markdown-crawler -l max-depth -d 'MAX_DEPTH, -d MAX_DEPTH'
complete -c markdown-crawler -l num-threads -d 'NUM_THREADS, -t NUM_THREADS'
complete -c markdown-crawler -l base-dir -d 'BASE_DIR, -b BASE_DIR'
complete -c markdown-crawler -s e -l debug -d 'Enable debug mode'
complete -c markdown-crawler -l target-content -d 'TARGET_CONTENT, -c TARGET_CONTENT'
complete -c markdown-crawler -l target-links -d 'TARGET_LINKS, -l TARGET_LINKS'
complete -c markdown-crawler -l valid-paths -d 'VALID_PATHS, -v VALID_PATHS'
complete -c markdown-crawler -s m -l domain-match -d 'Crawl only links that match the base domain'
complete -c markdown-crawler -s i -l links -d 'Enable the conversion of links in the markdown output'
