complete -c mycli -s h -l host -d 'TEXT                 Host address of the database.'
complete -c mycli -s P -l port -d 'INTEGER              Port number to use for connection. Honors'
complete -c mycli -s u -l user -d 'TEXT                 User name to connect to the database.'
complete -c mycli -s S -l socket -d 'TEXT               The socket file to use for connection.'
complete -c mycli -s p -l password -d 'TEXT             Password to connect to the database.'
complete -c mycli -l pass -d 'TEXT                     Password to connect to the database.'
complete -c mycli -l ssh-user -d 'TEXT                 User name to connect to ssh server.'
complete -c mycli -l ssh-host -d 'TEXT                 Host name to connect to ssh server.'
complete -c mycli -l ssh-port -d 'INTEGER              Port to connect to ssh server.'
complete -c mycli -l ssh-password -d 'TEXT             Password to connect to ssh server.'
complete -c mycli -l ssh-key-filename -d 'TEXT         Private key filename (identify file) for the'
complete -c mycli -l ssh-config-path -d 'TEXT          Path to ssh configuration.'
complete -c mycli -l ssh-config-host -d 'TEXT          Host to connect to ssh server reading from'
complete -c mycli -l ssl -d 'Enable SSL for connection (automatically'
complete -c mycli -l ssl-ca -d 'PATH                   CA file in PEM format.'
complete -c mycli -l ssl-capath -d 'TEXT               CA directory.'
complete -c mycli -l ssl-cert -d 'PATH                 X509 cert in PEM format.'
complete -c mycli -l ssl-key -d 'PATH                  X509 key in PEM format.'
complete -c mycli -l ssl-cipher -d 'TEXT               SSL cipher to use.'
complete -c mycli -l tls-version -d '[TLSv1|TLSv1.1|TLSv1.2|TLSv1.3]'
complete -c mycli -l ssl-verify-server-cert -d Verify\ server\'s\ \"Common\ Name\"\ in\ its\ cert
complete -c mycli -n __fish_no_arguments -s V -l version -d Output\ mycli\'s\ version.
complete -c mycli -s v -l verbose -d 'Verbose output.'
complete -c mycli -s D -l database -d 'TEXT             Database to use.'
complete -c mycli -s d -l dsn -d 'TEXT                  Use DSN configured into the [alias_dsn]'
complete -c mycli -l list-dsn -d 'list of DSN configured into the [alias_dsn]'
complete -c mycli -l list-ssh-config -d 'list ssh configurations in the ssh config'
complete -c mycli -s R -l prompt -d TEXT\ \ \ \ \ \ \ \ \ \ \ \ \ \ \ Prompt\ format\ \(Default:\ \"\\t\ \\u@\\h:\\d\>\ \"\).
complete -c mycli -s l -l logfile -d 'FILENAME          Log every query and its results to a file.'
complete -c mycli -l defaults-group-suffix -d 'TEXT    Read MySQL config groups with the specified'
complete -c mycli -l defaults-file -d 'PATH            Only read MySQL options from the given file.'
complete -c mycli -l myclirc -d 'PATH                  Location of myclirc file.'
complete -c mycli -l auto-vertical-output -d 'Automatically switch to vertical output mode'
complete -c mycli -s t -l table -d 'Display batch output in table format.'
complete -c mycli -l csv -d 'Display batch output in CSV format.'
complete -c mycli -l warn -d '/ --no-warn              Warn before running a destructive query.'
complete -c mycli -l local-infile -d 'BOOLEAN          Enable/disable LOAD DATA LOCAL INFILE.'
complete -c mycli -s g -l login-path -d 'TEXT           Read this path from the login file.'
complete -c mycli -s e -l execute -d 'TEXT              Execute command and quit.'
complete -c mycli -l init-command -d 'TEXT             SQL statement to execute after connecting.'
complete -c mycli -l charset -d 'TEXT                  Character set for MySQL session.'
complete -c mycli -l password-file -d 'PATH            File or FIFO path containing the password to'
complete -c mycli -l help -d 'Show this message and exit.'
