complete -c open -s a -d 'Opens with the specified application.'
complete -c open -l arch -d 'ARCH Open with the given cpu architecture type and subtype.'
complete -c open -s b -d 'Opens with the specified application bundle identifier.'
complete -c open -s e -d 'Opens with TextEdit.'
complete -c open -s t -d 'Opens with default text editor.'
complete -c open -s f -d 'Reads input from standard input and opens with TextEdit.'
complete -c open -s F -l fresh -d 'Launches the app fresh, that is, without restoring windows. Saved persistent state is lost, excluding Untitled documents.'
complete -c open -s R -l reveal -d 'Selects in the Finder instead of opening.'
complete -c open -s W -l wait-apps -d 'Blocks until the used applications are closed (even if they were already running).'
complete -c open -l args -d "All remaining arguments are passed in argv to the application's main() function instead of opened."
complete -c open -s n -l new -d 'Open a new instance of the application even if one is already running.'
complete -c open -s j -l hide -d 'Launches the app hidden.'
complete -c open -s g -l background -d 'Does not bring the application to the foreground.'
complete -c open -s h -l header -d 'Searches header file locations for headers matching the given filenames, and opens them.'
complete -c open -s s -d 'For -h, the SDK to use; if supplied, only SDKs whose names contain the argument value are searched.'
complete -c open -s u -l url -d 'URL Open this URL, even if it matches exactly a filepath'
complete -c open -s i -l stdin -d 'PATH Launches the application with stdin connected to PATH; defaults to /dev/null'
complete -c open -s o -l stdout -d 'PATH Launches the application with /dev/stdout connected to PATH;'
complete -c open -l stderr -d 'PATH Launches the application with /dev/stderr connected to PATH to'
complete -c open -l env -d 'VAR Add an enviroment variable to the launched process, where VAR is formatted AAA=foo or just AAA for a null string value.'
