#string replace -a -- {} pkgutil  {} --help
complete -c pkgutil -l help -d 'Show this usage guide'
complete -c pkgutil -s v -l verbose -d 'Show contextual information and format for easy reading'
complete -c pkgutil -s f -l force -d 'Perform all operations without asking for confirmation'
complete -c pkgutil -l volume -d 'PATH          Perform all operations on the specified volume'
complete -c pkgutil -l edit-pkg -d 'PKGID       Adjust properties of package PKGID using --learn PATH'
complete -c pkgutil -l only-files -d 'List only files (not directories) in --files listing'
complete -c pkgutil -l only-dirs -d 'List only directories (not files) in --files listing'
complete -c pkgutil -l regexp -d 'Try all PKGID arguments as regular expressions'
complete -f -c pkgutil -n __fish_use_subcommand -a --pkgs -d '--packages     List all currently installed package IDs on --volume'
complete -f -c pkgutil -n __fish_use_subcommand -a --pkgs-plist -d 'List all package IDs on --volume in plist format'
complete -f -c pkgutil -n __fish_use_subcommand -a --pkgs -d 'REGEXP          List package IDs on --volume that match REGEXP'
complete -f -c pkgutil -n __fish_use_subcommand -a --groups -d 'List all GROUPIDs on --volume'
complete -f -c pkgutil -n __fish_use_subcommand -a --groups-plist -d 'List all GROUPIDs on --volume in plist format'
complete -f -c pkgutil -n __fish_use_subcommand -a --group-pkgs -d 'GROUPID   List all PKGIDs in GROUPID'
complete -f -c pkgutil -n __fish_use_subcommand -a --files -d 'PKGID          List files installed by the specified package'
complete -f -c pkgutil -n __fish_use_subcommand -a --lsbom -d PKGID\ \ \ \ \ \ \ \ \ \ List\ files\ in\ the\ same\ format\ as\ \'lsbom\ -s\'
complete -f -c pkgutil -n __fish_use_subcommand -a --pkg-groups -d 'PKGID     List all GROUPIDs that PKGID is a member of'
complete -f -c pkgutil -n __fish_use_subcommand -a --export-plist -d 'PKGID   Print all info about PKGID in plist format'
complete -f -c pkgutil -n __fish_use_subcommand -a --pkg-info -d 'PKGID       Show metadata about PKGID'
complete -f -c pkgutil -n __fish_use_subcommand -a --pkg-info-plist -d 'PKGID Show metadata about PKGID in plist format'
complete -f -c pkgutil -n __fish_use_subcommand -a --file-info -d 'PATH       Show metadata known about PATH'
complete -f -c pkgutil -n __fish_use_subcommand -a --file-info-plist -d 'PATH Show metadata known about PATH in plist format'
complete -f -c pkgutil -n __fish_use_subcommand -a --forget -d 'PKGID         Discard receipt data for the specified package'
complete -f -c pkgutil -n __fish_use_subcommand -a --learn -d 'PATH           Update --edit-pkg PKGID with actual metadata from PATH'
complete -f -c pkgutil -n __fish_use_subcommand -a --expand -d 'PKG DIR       Expand the flat package PKG to DIR'
complete -f -c pkgutil -n __fish_use_subcommand -a --flatten -d 'DIR PKG      Flatten the files at DIR as PKG'
complete -f -c pkgutil -n __fish_use_subcommand -a --bom -d 'PATH             Extract any Bom files from the pkg at PATH into /tmp'
complete -f -c pkgutil -n __fish_use_subcommand -a --payload-files -d 'PATH   List the paths archived within the (m)pkg at PATH'
complete -f -c pkgutil -n __fish_use_subcommand -a --check-signature -d 'PATH Validate the signature of the pkg at PATH and print certificate information'
