complete -c portless -l script -d '<name> Run a specific package.json script (default: dev)'
complete -c portless -s p -l port -d '<number> Port for the proxy (default: 443, or 80 with --no-tls)'
complete -c portless -l no-tls -d 'Disable HTTPS (use plain HTTP on port 80)'
complete -c portless -l https -d 'Enable HTTPS (default, accepted for compatibility)'
complete -c portless -l lan -d 'Enable LAN mode (mDNS .local, for real device testing)'
complete -c portless -l ip -d '<address> Pin a specific LAN IP (disables auto-follow; use with --lan)'
complete -c portless -l cert -d '<path> Use a custom TLS certificate'
complete -c portless -l key -d '<path> Use a custom TLS private key'
complete -c portless -l foreground -d 'Run proxy in foreground (for debugging)'
complete -c portless -l tld -d '<tld> Use a custom TLD instead of .localhost (e.g. test, dev)'
complete -c portless -l wildcard -d 'Allow unregistered subdomains to fall back to parent route'
complete -c portless -l state-dir -d '<path> Use a custom state directory with service install'
complete -c portless -l app-port -d '<number> Use a fixed port for the app (skip auto-assignment)'
complete -c portless -l tailscale -d 'Share the app on your Tailscale network (tailnet)'
complete -c portless -l funnel -d 'Share the app publicly via Tailscale Funnel'
complete -c portless -l ngrok -d 'Share the app publicly via ngrok'
complete -c portless -l force -d 'Kill the existing process and take over its route'
complete -c portless -l name -d '<name> Use <name> as the app name (bypasses subcommand dispatch)'
