complete -c psql -s l -l list -d 'list available databases, then exit'
complete -c psql -n __fish_no_arguments -s V -l version -d 'output version information, then exit'
complete -c psql -s X -l no-psqlrc -d 'do not read startup file (~/.psqlrc)'
complete -c psql -s 1 -d '("one"), --single-transaction'
complete -c psql -s a -l echo-all -d 'echo all input from script'
complete -c psql -s b -l echo-errors -d 'echo failed commands'
complete -c psql -s e -l echo-queries -d 'echo commands sent to server'
complete -c psql -s E -l echo-hidden -d 'display queries that internal commands generate'
complete -c psql -s n -l no-readline -d 'disable enhanced command line editing (readline)'
complete -c psql -s q -l quiet -d 'run quietly (no messages, only query output)'
complete -c psql -s s -l single-step -d 'single-step mode (confirm each query)'
complete -c psql -s S -l single-line -d 'single-line mode (end of line terminates SQL command)'
complete -c psql -s A -l no-align -d 'unaligned table output mode'
complete -c psql -l csv -d 'CSV (Comma-Separated Values) table output mode'
complete -c psql -s H -l html -d 'HTML table output mode'
complete -c psql -s t -l tuples-only -d 'print rows only'
complete -c psql -s x -l expanded -d 'turn on expanded table output'
complete -c psql -s w -l no-password -d 'never prompt for password'
complete -c psql -s W -l password -d 'force password prompt (should happen automatically)'
