# Fish completion for reader
complete -c reader -f
complete -c reader -f -n "__fish_use_subcommand" -a read_csv -d "Read data using read_csv"
complete -c reader -f -n "__fish_use_subcommand" -a read_json -d "Read data using read_json"
complete -c reader -f -n "__fish_use_subcommand" -a read_ndjson -d "Read data using read_ndjson"
complete -c reader -f -n "__fish_use_subcommand" -a read_parquet -d "Read data using read_parquet"
complete -c reader -f -n "__fish_use_subcommand" -a read_xlsx -d "Read data using read_xlsx"
complete -c reader -f -n "__fish_use_subcommand" -a read_lance -d "Read data using read_lance"
complete -c reader -f -n "__fish_use_subcommand" -a read_vortex -d "Read data using read_vortex"
complete -c reader -f -n "__fish_use_subcommand" -a osmium_read -d "Read data using osmium_read"
complete -c reader -f -n "__fish_use_subcommand" -a fish_completion -d "Generate Fish shell completion script"
complete -c reader -f -n "__fish_use_subcommand" -a list_extensions -d "List functions that auto-load extensions"
complete -c reader -f -n "__fish_seen_subcommand_from read_csv" -l all-varchar -d "[read_csv] Skip type detection and assume all columns are of type VARCHAR"
complete -c reader -f -n "__fish_seen_subcommand_from read_csv" -l allow-quoted-nulls -d "[read_csv] Allow the conversion of quoted values to NULL values"
complete -c reader -f -n "__fish_seen_subcommand_from read_csv" -l auto-detect -d "[read_csv] Auto detect CSV parameters"
complete -c reader -f -n "__fish_seen_subcommand_from read_csv" -l auto-type-candidates -d "[read_csv] Types that the sniffer uses when detecting column types"
complete -c reader -f -n "__fish_seen_subcommand_from read_csv" -l buffer-size -d "[read_csv] Size of the buffers used to read files, in bytes"
complete -c reader -f -n "__fish_seen_subcommand_from read_csv" -l columns -d "[read_csv] Column names and types, as a struct (e"
complete -c reader -f -n "__fish_seen_subcommand_from read_csv" -l comment -d "[read_csv] Character used to initiate comments"
complete -c reader -f -n "__fish_seen_subcommand_from read_csv" -l dateformat -d "[read_csv] Date format used when parsing dates"
complete -c reader -f -n "__fish_seen_subcommand_from read_csv" -l decimal-separator -d "[read_csv] Decimal separator for numbers"
complete -c reader -f -n "__fish_seen_subcommand_from read_csv" -l delim -d "[read_csv] Delimiter character used to separate columns"
complete -c reader -f -n "__fish_seen_subcommand_from read_csv" -l dtypes -d "[read_csv] Alias for types"
complete -c reader -f -n "__fish_seen_subcommand_from read_csv" -l encoding -a "utf-8 utf-16 latin-1" -d "[read_csv] Encoding used by the CSV file"
complete -c reader -f -n "__fish_seen_subcommand_from read_csv" -l escape -d "[read_csv] String used to escape the quote character within quoted values"
complete -c reader -f -n "__fish_seen_subcommand_from read_csv" -l filename -d "[read_csv] Add path of the containing file to each row to a column named 'filename'"
complete -c reader -f -n "__fish_seen_subcommand_from read_csv" -l force-not-null -d "[read_csv] Do not match values in the specified columns against the NULL string"
complete -c reader -f -n "__fish_seen_subcommand_from read_csv" -l header -d "[read_csv] First line of each file contains the column names"
complete -c reader -f -n "__fish_seen_subcommand_from read_csv" -l hive-partitioning -d "[read_csv] Whether or not to interpret the path as a Hive partitioned path"
complete -c reader -f -n "__fish_seen_subcommand_from read_csv" -l ignore-errors -d "[read_csv] Ignore any parsing errors encountered"
complete -c reader -f -n "__fish_seen_subcommand_from read_csv" -l max-line-size -d "[read_csv] Maximum line size, in bytes"
complete -c reader -f -n "__fish_seen_subcommand_from read_csv" -l maximum-line-size -d "[read_csv] Alias for max_line_size"
complete -c reader -f -n "__fish_seen_subcommand_from read_csv" -l names -d "[read_csv] Column names, as a list"
complete -c reader -f -n "__fish_seen_subcommand_from read_csv" -l new-line -a "\r \n \r\n" -d "[read_csv] New line character(s)"
complete -c reader -f -n "__fish_seen_subcommand_from read_csv" -l normalize-names -d "[read_csv] Normalize column names"
complete -c reader -f -n "__fish_seen_subcommand_from read_csv" -l null-padding -d "[read_csv] Pad the remaining columns on the right with NULL values when a line lacks columns"
complete -c reader -f -n "__fish_seen_subcommand_from read_csv" -l nullstr -d "[read_csv] Strings that represent a NULL value"
complete -c reader -f -n "__fish_seen_subcommand_from read_csv" -l parallel -d "[read_csv] Use the parallel CSV reader"
complete -c reader -f -n "__fish_seen_subcommand_from read_csv" -l quote -d "[read_csv] String used to quote values"
complete -c reader -f -n "__fish_seen_subcommand_from read_csv" -l rejects-limit -d "[read_csv] Upper limit on the number of faulty lines per file that are recorded in the rejects table"
complete -c reader -f -n "__fish_seen_subcommand_from read_csv" -l rejects-scan -d "[read_csv] Name of the temporary table where information on faulty scans is stored"
complete -c reader -f -n "__fish_seen_subcommand_from read_csv" -l rejects-table -d "[read_csv] Name of the temporary table where information on faulty lines is stored"
complete -c reader -f -n "__fish_seen_subcommand_from read_csv" -l sample-size -d "[read_csv] Number of sample lines for auto detection of parameters"
complete -c reader -f -n "__fish_seen_subcommand_from read_csv" -l sep -d "[read_csv] Delimiter character used to separate columns"
complete -c reader -f -n "__fish_seen_subcommand_from read_csv" -l skip -d "[read_csv] Number of lines to skip at the start of each file"
complete -c reader -f -n "__fish_seen_subcommand_from read_csv" -l store-rejects -d "[read_csv] Skip any lines with errors and store them in the rejects table"
complete -c reader -f -n "__fish_seen_subcommand_from read_csv" -l strict-mode -d "[read_csv] Enforces the strictness level of the CSV Reader"
complete -c reader -f -n "__fish_seen_subcommand_from read_csv" -l thousands -d "[read_csv] Character used to identify thousands separators in numeric values"
complete -c reader -f -n "__fish_seen_subcommand_from read_csv" -l timestampformat -d "[read_csv] Timestamp format used when parsing timestamps"
complete -c reader -f -n "__fish_seen_subcommand_from read_csv" -l types -d "[read_csv] Column types, as either a list (by position) or a struct (by name)"
complete -c reader -f -n "__fish_seen_subcommand_from read_csv" -l union-by-name -d "[read_csv] Align columns from different files by column name instead of position"
complete -c reader -f -n "__fish_seen_subcommand_from read_json" -l auto-detect -d "[read_json] Whether to auto-detect the names of the keys and data types"
complete -c reader -f -n "__fish_seen_subcommand_from read_json" -l columns -d "[read_json] A struct that specifies the key names and value types (e"
complete -c reader -f -n "__fish_seen_subcommand_from read_json" -l convert-strings-to-integers -d "[read_json] Convert strings representing integer values to numerical type"
complete -c reader -f -n "__fish_seen_subcommand_from read_json" -l dateformat -d "[read_json] Date format used when parsing dates"
complete -c reader -f -n "__fish_seen_subcommand_from read_json" -l field-appearance-threshold -d "[read_json] Threshold for field appearance ratio"
complete -c reader -f -n "__fish_seen_subcommand_from read_json" -l format -a "auto newline_delimited array parquet csv tsv json jsonl arrow" -d "[read_json] JSON format ('auto', 'unstructured', 'newline_delimited', 'array')"
complete -c reader -f -n "__fish_seen_subcommand_from read_json" -l ignore-errors -d "[read_json] Ignore parse errors (only possible when format is 'newline_delimited')"
complete -c reader -f -n "__fish_seen_subcommand_from read_json" -l map-inference-threshold -d "[read_json] Threshold for number of columns before inferring MAP type instead of STRUCT"
complete -c reader -f -n "__fish_seen_subcommand_from read_json" -l maximum-depth -d "[read_json] Maximum nesting depth for automatic schema detection"
complete -c reader -f -n "__fish_seen_subcommand_from read_json" -l maximum-object-size -d "[read_json] Maximum size of a JSON object (in bytes)"
complete -c reader -f -n "__fish_seen_subcommand_from read_json" -l maximum-sample-files -d "[read_json] Maximum number of JSON files sampled for auto-detection"
complete -c reader -f -n "__fish_seen_subcommand_from read_json" -l records -d "[read_json] Whether JSON contains records that should be unpacked into columns ('auto', 'true', 'false')"
complete -c reader -f -n "__fish_seen_subcommand_from read_json" -l sample-size -d "[read_json] Number of sample objects for automatic type detection"
complete -c reader -f -n "__fish_seen_subcommand_from read_json" -l timestampformat -d "[read_json] Timestamp format used when parsing timestamps"
complete -c reader -f -n "__fish_seen_subcommand_from read_json" -l union-by-name -d "[read_json] Whether the schemas of multiple JSON files should be unified"
complete -c reader -f -n "__fish_seen_subcommand_from read_ndjson" -l auto-detect -d "[read_ndjson] Whether to auto-detect the names of the keys and data types"
complete -c reader -f -n "__fish_seen_subcommand_from read_ndjson" -l columns -d "[read_ndjson] A struct that specifies the key names and value types (e"
complete -c reader -f -n "__fish_seen_subcommand_from read_ndjson" -l convert-strings-to-integers -d "[read_ndjson] Convert strings representing integer values to numerical type"
complete -c reader -f -n "__fish_seen_subcommand_from read_ndjson" -l dateformat -d "[read_ndjson] Date format used when parsing dates"
complete -c reader -f -n "__fish_seen_subcommand_from read_ndjson" -l field-appearance-threshold -d "[read_ndjson] Threshold for field appearance ratio"
complete -c reader -f -n "__fish_seen_subcommand_from read_ndjson" -l format -a "auto newline_delimited array parquet csv tsv json jsonl arrow" -d "[read_ndjson] JSON format ('auto', 'unstructured', 'newline_delimited', 'array')"
complete -c reader -f -n "__fish_seen_subcommand_from read_ndjson" -l ignore-errors -d "[read_ndjson] Ignore parse errors"
complete -c reader -f -n "__fish_seen_subcommand_from read_ndjson" -l map-inference-threshold -d "[read_ndjson] Threshold for number of columns before inferring MAP type"
complete -c reader -f -n "__fish_seen_subcommand_from read_ndjson" -l maximum-depth -d "[read_ndjson] Maximum nesting depth for schema detection"
complete -c reader -f -n "__fish_seen_subcommand_from read_ndjson" -l maximum-object-size -d "[read_ndjson] Maximum size of a JSON object (in bytes)"
complete -c reader -f -n "__fish_seen_subcommand_from read_ndjson" -l maximum-sample-files -d "[read_ndjson] Maximum number of JSON files sampled for auto-detection"
complete -c reader -f -n "__fish_seen_subcommand_from read_ndjson" -l records -d "[read_ndjson] Whether JSON contains records ('auto', 'true', 'false')"
complete -c reader -f -n "__fish_seen_subcommand_from read_ndjson" -l sample-size -d "[read_ndjson] Number of sample objects for detection"
complete -c reader -f -n "__fish_seen_subcommand_from read_ndjson" -l timestampformat -d "[read_ndjson] Timestamp format used when parsing timestamps"
complete -c reader -f -n "__fish_seen_subcommand_from read_ndjson" -l union-by-name -d "[read_ndjson] Whether the schemas of multiple JSON files should be unified"
complete -c reader -f -n "__fish_seen_subcommand_from read_parquet" -l binary-as-string -d "[read_parquet] Load binary columns as strings (for legacy Parquet files)"
complete -c reader -f -n "__fish_seen_subcommand_from read_parquet" -l encryption-config -d "[read_parquet] Configuration for Parquet encryption"
complete -c reader -f -n "__fish_seen_subcommand_from read_parquet" -l file-row-number -d "[read_parquet] Whether to include the file_row_number column"
complete -c reader -f -n "__fish_seen_subcommand_from read_parquet" -l filename -d "[read_parquet] Whether to include filename column"
complete -c reader -f -n "__fish_seen_subcommand_from read_parquet" -l hive-partitioning -d "[read_parquet] Whether or not to interpret the path as a Hive partitioned path"
complete -c reader -f -n "__fish_seen_subcommand_from read_parquet" -l schema -d "[read_parquet] Read Parquet file with supplied schema (requires field IDs)"
complete -c reader -f -n "__fish_seen_subcommand_from read_parquet" -l union-by-name -d "[read_parquet] Union multiple schemas by name"
complete -c reader -f -n "__fish_seen_subcommand_from read_xlsx" -l all-varchar -d "[read_xlsx] Read all cells as VARCHARs"
complete -c reader -f -n "__fish_seen_subcommand_from read_xlsx" -l header -d "[read_xlsx] Treat first row as column names"
complete -c reader -f -n "__fish_seen_subcommand_from read_xlsx" -l range -d "[read_xlsx] Range of cells to read (e"
complete -c reader -f -n "__fish_seen_subcommand_from read_xlsx" -l sheet -d "[read_xlsx] Name of the sheet to read"
complete -c reader -f -n "commandline -opc | string match -rg '\\.csv\$'" -l all-varchar -d "[read_csv] Skip type detection and assume all columns are of type VARCHAR"
complete -c reader -f -n "commandline -opc | string match -rg '\\.csv\$'" -l allow-quoted-nulls -d "[read_csv] Allow the conversion of quoted values to NULL values"
complete -c reader -f -n "commandline -opc | string match -rg '\\.csv\$'" -l auto-detect -d "[read_csv] Auto detect CSV parameters"
complete -c reader -f -n "commandline -opc | string match -rg '\\.csv\$'" -l auto-type-candidates -d "[read_csv] Types that the sniffer uses when detecting column types"
complete -c reader -f -n "commandline -opc | string match -rg '\\.csv\$'" -l buffer-size -d "[read_csv] Size of the buffers used to read files, in bytes"
complete -c reader -f -n "commandline -opc | string match -rg '\\.csv\$'" -l columns -d "[read_csv] Column names and types, as a struct (e"
complete -c reader -f -n "commandline -opc | string match -rg '\\.csv\$'" -l comment -d "[read_csv] Character used to initiate comments"
complete -c reader -f -n "commandline -opc | string match -rg '\\.csv\$'" -l dateformat -d "[read_csv] Date format used when parsing dates"
complete -c reader -f -n "commandline -opc | string match -rg '\\.csv\$'" -l decimal-separator -d "[read_csv] Decimal separator for numbers"
complete -c reader -f -n "commandline -opc | string match -rg '\\.csv\$'" -l delim -d "[read_csv] Delimiter character used to separate columns"
complete -c reader -f -n "commandline -opc | string match -rg '\\.csv\$'" -l dtypes -d "[read_csv] Alias for types"
complete -c reader -f -n "commandline -opc | string match -rg '\\.csv\$'" -l encoding -a "utf-8 utf-16 latin-1" -d "[read_csv] Encoding used by the CSV file"
complete -c reader -f -n "commandline -opc | string match -rg '\\.csv\$'" -l escape -d "[read_csv] String used to escape the quote character within quoted values"
complete -c reader -f -n "commandline -opc | string match -rg '\\.csv\$'" -l filename -d "[read_csv] Add path of the containing file to each row to a column named 'filename'"
complete -c reader -f -n "commandline -opc | string match -rg '\\.csv\$'" -l force-not-null -d "[read_csv] Do not match values in the specified columns against the NULL string"
complete -c reader -f -n "commandline -opc | string match -rg '\\.csv\$'" -l header -d "[read_csv] First line of each file contains the column names"
complete -c reader -f -n "commandline -opc | string match -rg '\\.csv\$'" -l hive-partitioning -d "[read_csv] Whether or not to interpret the path as a Hive partitioned path"
complete -c reader -f -n "commandline -opc | string match -rg '\\.csv\$'" -l ignore-errors -d "[read_csv] Ignore any parsing errors encountered"
complete -c reader -f -n "commandline -opc | string match -rg '\\.csv\$'" -l max-line-size -d "[read_csv] Maximum line size, in bytes"
complete -c reader -f -n "commandline -opc | string match -rg '\\.csv\$'" -l maximum-line-size -d "[read_csv] Alias for max_line_size"
complete -c reader -f -n "commandline -opc | string match -rg '\\.csv\$'" -l names -d "[read_csv] Column names, as a list"
complete -c reader -f -n "commandline -opc | string match -rg '\\.csv\$'" -l new-line -a "\r \n \r\n" -d "[read_csv] New line character(s)"
complete -c reader -f -n "commandline -opc | string match -rg '\\.csv\$'" -l normalize-names -d "[read_csv] Normalize column names"
complete -c reader -f -n "commandline -opc | string match -rg '\\.csv\$'" -l null-padding -d "[read_csv] Pad the remaining columns on the right with NULL values when a line lacks columns"
complete -c reader -f -n "commandline -opc | string match -rg '\\.csv\$'" -l nullstr -d "[read_csv] Strings that represent a NULL value"
complete -c reader -f -n "commandline -opc | string match -rg '\\.csv\$'" -l parallel -d "[read_csv] Use the parallel CSV reader"
complete -c reader -f -n "commandline -opc | string match -rg '\\.csv\$'" -l quote -d "[read_csv] String used to quote values"
complete -c reader -f -n "commandline -opc | string match -rg '\\.csv\$'" -l rejects-limit -d "[read_csv] Upper limit on the number of faulty lines per file that are recorded in the rejects table"
complete -c reader -f -n "commandline -opc | string match -rg '\\.csv\$'" -l rejects-scan -d "[read_csv] Name of the temporary table where information on faulty scans is stored"
complete -c reader -f -n "commandline -opc | string match -rg '\\.csv\$'" -l rejects-table -d "[read_csv] Name of the temporary table where information on faulty lines is stored"
complete -c reader -f -n "commandline -opc | string match -rg '\\.csv\$'" -l sample-size -d "[read_csv] Number of sample lines for auto detection of parameters"
complete -c reader -f -n "commandline -opc | string match -rg '\\.csv\$'" -l sep -d "[read_csv] Delimiter character used to separate columns"
complete -c reader -f -n "commandline -opc | string match -rg '\\.csv\$'" -l skip -d "[read_csv] Number of lines to skip at the start of each file"
complete -c reader -f -n "commandline -opc | string match -rg '\\.csv\$'" -l store-rejects -d "[read_csv] Skip any lines with errors and store them in the rejects table"
complete -c reader -f -n "commandline -opc | string match -rg '\\.csv\$'" -l strict-mode -d "[read_csv] Enforces the strictness level of the CSV Reader"
complete -c reader -f -n "commandline -opc | string match -rg '\\.csv\$'" -l thousands -d "[read_csv] Character used to identify thousands separators in numeric values"
complete -c reader -f -n "commandline -opc | string match -rg '\\.csv\$'" -l timestampformat -d "[read_csv] Timestamp format used when parsing timestamps"
complete -c reader -f -n "commandline -opc | string match -rg '\\.csv\$'" -l types -d "[read_csv] Column types, as either a list (by position) or a struct (by name)"
complete -c reader -f -n "commandline -opc | string match -rg '\\.csv\$'" -l union-by-name -d "[read_csv] Align columns from different files by column name instead of position"
complete -c reader -f -n "commandline -opc | string match -rg '\\.txt\$'" -l all-varchar -d "[read_csv] Skip type detection and assume all columns are of type VARCHAR"
complete -c reader -f -n "commandline -opc | string match -rg '\\.txt\$'" -l allow-quoted-nulls -d "[read_csv] Allow the conversion of quoted values to NULL values"
complete -c reader -f -n "commandline -opc | string match -rg '\\.txt\$'" -l auto-detect -d "[read_csv] Auto detect CSV parameters"
complete -c reader -f -n "commandline -opc | string match -rg '\\.txt\$'" -l auto-type-candidates -d "[read_csv] Types that the sniffer uses when detecting column types"
complete -c reader -f -n "commandline -opc | string match -rg '\\.txt\$'" -l buffer-size -d "[read_csv] Size of the buffers used to read files, in bytes"
complete -c reader -f -n "commandline -opc | string match -rg '\\.txt\$'" -l columns -d "[read_csv] Column names and types, as a struct (e"
complete -c reader -f -n "commandline -opc | string match -rg '\\.txt\$'" -l comment -d "[read_csv] Character used to initiate comments"
complete -c reader -f -n "commandline -opc | string match -rg '\\.txt\$'" -l dateformat -d "[read_csv] Date format used when parsing dates"
complete -c reader -f -n "commandline -opc | string match -rg '\\.txt\$'" -l decimal-separator -d "[read_csv] Decimal separator for numbers"
complete -c reader -f -n "commandline -opc | string match -rg '\\.txt\$'" -l delim -d "[read_csv] Delimiter character used to separate columns"
complete -c reader -f -n "commandline -opc | string match -rg '\\.txt\$'" -l dtypes -d "[read_csv] Alias for types"
complete -c reader -f -n "commandline -opc | string match -rg '\\.txt\$'" -l encoding -a "utf-8 utf-16 latin-1" -d "[read_csv] Encoding used by the CSV file"
complete -c reader -f -n "commandline -opc | string match -rg '\\.txt\$'" -l escape -d "[read_csv] String used to escape the quote character within quoted values"
complete -c reader -f -n "commandline -opc | string match -rg '\\.txt\$'" -l filename -d "[read_csv] Add path of the containing file to each row to a column named 'filename'"
complete -c reader -f -n "commandline -opc | string match -rg '\\.txt\$'" -l force-not-null -d "[read_csv] Do not match values in the specified columns against the NULL string"
complete -c reader -f -n "commandline -opc | string match -rg '\\.txt\$'" -l header -d "[read_csv] First line of each file contains the column names"
complete -c reader -f -n "commandline -opc | string match -rg '\\.txt\$'" -l hive-partitioning -d "[read_csv] Whether or not to interpret the path as a Hive partitioned path"
complete -c reader -f -n "commandline -opc | string match -rg '\\.txt\$'" -l ignore-errors -d "[read_csv] Ignore any parsing errors encountered"
complete -c reader -f -n "commandline -opc | string match -rg '\\.txt\$'" -l max-line-size -d "[read_csv] Maximum line size, in bytes"
complete -c reader -f -n "commandline -opc | string match -rg '\\.txt\$'" -l maximum-line-size -d "[read_csv] Alias for max_line_size"
complete -c reader -f -n "commandline -opc | string match -rg '\\.txt\$'" -l names -d "[read_csv] Column names, as a list"
complete -c reader -f -n "commandline -opc | string match -rg '\\.txt\$'" -l new-line -a "\r \n \r\n" -d "[read_csv] New line character(s)"
complete -c reader -f -n "commandline -opc | string match -rg '\\.txt\$'" -l normalize-names -d "[read_csv] Normalize column names"
complete -c reader -f -n "commandline -opc | string match -rg '\\.txt\$'" -l null-padding -d "[read_csv] Pad the remaining columns on the right with NULL values when a line lacks columns"
complete -c reader -f -n "commandline -opc | string match -rg '\\.txt\$'" -l nullstr -d "[read_csv] Strings that represent a NULL value"
complete -c reader -f -n "commandline -opc | string match -rg '\\.txt\$'" -l parallel -d "[read_csv] Use the parallel CSV reader"
complete -c reader -f -n "commandline -opc | string match -rg '\\.txt\$'" -l quote -d "[read_csv] String used to quote values"
complete -c reader -f -n "commandline -opc | string match -rg '\\.txt\$'" -l rejects-limit -d "[read_csv] Upper limit on the number of faulty lines per file that are recorded in the rejects table"
complete -c reader -f -n "commandline -opc | string match -rg '\\.txt\$'" -l rejects-scan -d "[read_csv] Name of the temporary table where information on faulty scans is stored"
complete -c reader -f -n "commandline -opc | string match -rg '\\.txt\$'" -l rejects-table -d "[read_csv] Name of the temporary table where information on faulty lines is stored"
complete -c reader -f -n "commandline -opc | string match -rg '\\.txt\$'" -l sample-size -d "[read_csv] Number of sample lines for auto detection of parameters"
complete -c reader -f -n "commandline -opc | string match -rg '\\.txt\$'" -l sep -d "[read_csv] Delimiter character used to separate columns"
complete -c reader -f -n "commandline -opc | string match -rg '\\.txt\$'" -l skip -d "[read_csv] Number of lines to skip at the start of each file"
complete -c reader -f -n "commandline -opc | string match -rg '\\.txt\$'" -l store-rejects -d "[read_csv] Skip any lines with errors and store them in the rejects table"
complete -c reader -f -n "commandline -opc | string match -rg '\\.txt\$'" -l strict-mode -d "[read_csv] Enforces the strictness level of the CSV Reader"
complete -c reader -f -n "commandline -opc | string match -rg '\\.txt\$'" -l thousands -d "[read_csv] Character used to identify thousands separators in numeric values"
complete -c reader -f -n "commandline -opc | string match -rg '\\.txt\$'" -l timestampformat -d "[read_csv] Timestamp format used when parsing timestamps"
complete -c reader -f -n "commandline -opc | string match -rg '\\.txt\$'" -l types -d "[read_csv] Column types, as either a list (by position) or a struct (by name)"
complete -c reader -f -n "commandline -opc | string match -rg '\\.txt\$'" -l union-by-name -d "[read_csv] Align columns from different files by column name instead of position"
complete -c reader -f -n "commandline -opc | string match -rg '\\.tsv\$'" -l all-varchar -d "[read_csv] Skip type detection and assume all columns are of type VARCHAR"
complete -c reader -f -n "commandline -opc | string match -rg '\\.tsv\$'" -l allow-quoted-nulls -d "[read_csv] Allow the conversion of quoted values to NULL values"
complete -c reader -f -n "commandline -opc | string match -rg '\\.tsv\$'" -l auto-detect -d "[read_csv] Auto detect CSV parameters"
complete -c reader -f -n "commandline -opc | string match -rg '\\.tsv\$'" -l auto-type-candidates -d "[read_csv] Types that the sniffer uses when detecting column types"
complete -c reader -f -n "commandline -opc | string match -rg '\\.tsv\$'" -l buffer-size -d "[read_csv] Size of the buffers used to read files, in bytes"
complete -c reader -f -n "commandline -opc | string match -rg '\\.tsv\$'" -l columns -d "[read_csv] Column names and types, as a struct (e"
complete -c reader -f -n "commandline -opc | string match -rg '\\.tsv\$'" -l comment -d "[read_csv] Character used to initiate comments"
complete -c reader -f -n "commandline -opc | string match -rg '\\.tsv\$'" -l dateformat -d "[read_csv] Date format used when parsing dates"
complete -c reader -f -n "commandline -opc | string match -rg '\\.tsv\$'" -l decimal-separator -d "[read_csv] Decimal separator for numbers"
complete -c reader -f -n "commandline -opc | string match -rg '\\.tsv\$'" -l delim -d "[read_csv] Delimiter character used to separate columns"
complete -c reader -f -n "commandline -opc | string match -rg '\\.tsv\$'" -l dtypes -d "[read_csv] Alias for types"
complete -c reader -f -n "commandline -opc | string match -rg '\\.tsv\$'" -l encoding -a "utf-8 utf-16 latin-1" -d "[read_csv] Encoding used by the CSV file"
complete -c reader -f -n "commandline -opc | string match -rg '\\.tsv\$'" -l escape -d "[read_csv] String used to escape the quote character within quoted values"
complete -c reader -f -n "commandline -opc | string match -rg '\\.tsv\$'" -l filename -d "[read_csv] Add path of the containing file to each row to a column named 'filename'"
complete -c reader -f -n "commandline -opc | string match -rg '\\.tsv\$'" -l force-not-null -d "[read_csv] Do not match values in the specified columns against the NULL string"
complete -c reader -f -n "commandline -opc | string match -rg '\\.tsv\$'" -l header -d "[read_csv] First line of each file contains the column names"
complete -c reader -f -n "commandline -opc | string match -rg '\\.tsv\$'" -l hive-partitioning -d "[read_csv] Whether or not to interpret the path as a Hive partitioned path"
complete -c reader -f -n "commandline -opc | string match -rg '\\.tsv\$'" -l ignore-errors -d "[read_csv] Ignore any parsing errors encountered"
complete -c reader -f -n "commandline -opc | string match -rg '\\.tsv\$'" -l max-line-size -d "[read_csv] Maximum line size, in bytes"
complete -c reader -f -n "commandline -opc | string match -rg '\\.tsv\$'" -l maximum-line-size -d "[read_csv] Alias for max_line_size"
complete -c reader -f -n "commandline -opc | string match -rg '\\.tsv\$'" -l names -d "[read_csv] Column names, as a list"
complete -c reader -f -n "commandline -opc | string match -rg '\\.tsv\$'" -l new-line -a "\r \n \r\n" -d "[read_csv] New line character(s)"
complete -c reader -f -n "commandline -opc | string match -rg '\\.tsv\$'" -l normalize-names -d "[read_csv] Normalize column names"
complete -c reader -f -n "commandline -opc | string match -rg '\\.tsv\$'" -l null-padding -d "[read_csv] Pad the remaining columns on the right with NULL values when a line lacks columns"
complete -c reader -f -n "commandline -opc | string match -rg '\\.tsv\$'" -l nullstr -d "[read_csv] Strings that represent a NULL value"
complete -c reader -f -n "commandline -opc | string match -rg '\\.tsv\$'" -l parallel -d "[read_csv] Use the parallel CSV reader"
complete -c reader -f -n "commandline -opc | string match -rg '\\.tsv\$'" -l quote -d "[read_csv] String used to quote values"
complete -c reader -f -n "commandline -opc | string match -rg '\\.tsv\$'" -l rejects-limit -d "[read_csv] Upper limit on the number of faulty lines per file that are recorded in the rejects table"
complete -c reader -f -n "commandline -opc | string match -rg '\\.tsv\$'" -l rejects-scan -d "[read_csv] Name of the temporary table where information on faulty scans is stored"
complete -c reader -f -n "commandline -opc | string match -rg '\\.tsv\$'" -l rejects-table -d "[read_csv] Name of the temporary table where information on faulty lines is stored"
complete -c reader -f -n "commandline -opc | string match -rg '\\.tsv\$'" -l sample-size -d "[read_csv] Number of sample lines for auto detection of parameters"
complete -c reader -f -n "commandline -opc | string match -rg '\\.tsv\$'" -l sep -d "[read_csv] Delimiter character used to separate columns"
complete -c reader -f -n "commandline -opc | string match -rg '\\.tsv\$'" -l skip -d "[read_csv] Number of lines to skip at the start of each file"
complete -c reader -f -n "commandline -opc | string match -rg '\\.tsv\$'" -l store-rejects -d "[read_csv] Skip any lines with errors and store them in the rejects table"
complete -c reader -f -n "commandline -opc | string match -rg '\\.tsv\$'" -l strict-mode -d "[read_csv] Enforces the strictness level of the CSV Reader"
complete -c reader -f -n "commandline -opc | string match -rg '\\.tsv\$'" -l thousands -d "[read_csv] Character used to identify thousands separators in numeric values"
complete -c reader -f -n "commandline -opc | string match -rg '\\.tsv\$'" -l timestampformat -d "[read_csv] Timestamp format used when parsing timestamps"
complete -c reader -f -n "commandline -opc | string match -rg '\\.tsv\$'" -l types -d "[read_csv] Column types, as either a list (by position) or a struct (by name)"
complete -c reader -f -n "commandline -opc | string match -rg '\\.tsv\$'" -l union-by-name -d "[read_csv] Align columns from different files by column name instead of position"
complete -c reader -f -n "commandline -opc | string match -rg '\\.json\$'" -l auto-detect -d "[read_json] Whether to auto-detect the names of the keys and data types"
complete -c reader -f -n "commandline -opc | string match -rg '\\.json\$'" -l columns -d "[read_json] A struct that specifies the key names and value types (e"
complete -c reader -f -n "commandline -opc | string match -rg '\\.json\$'" -l convert-strings-to-integers -d "[read_json] Convert strings representing integer values to numerical type"
complete -c reader -f -n "commandline -opc | string match -rg '\\.json\$'" -l dateformat -d "[read_json] Date format used when parsing dates"
complete -c reader -f -n "commandline -opc | string match -rg '\\.json\$'" -l field-appearance-threshold -d "[read_json] Threshold for field appearance ratio"
complete -c reader -f -n "commandline -opc | string match -rg '\\.json\$'" -l format -a "auto newline_delimited array parquet csv tsv json jsonl arrow" -d "[read_json] JSON format ('auto', 'unstructured', 'newline_delimited', 'array')"
complete -c reader -f -n "commandline -opc | string match -rg '\\.json\$'" -l ignore-errors -d "[read_json] Ignore parse errors (only possible when format is 'newline_delimited')"
complete -c reader -f -n "commandline -opc | string match -rg '\\.json\$'" -l map-inference-threshold -d "[read_json] Threshold for number of columns before inferring MAP type instead of STRUCT"
complete -c reader -f -n "commandline -opc | string match -rg '\\.json\$'" -l maximum-depth -d "[read_json] Maximum nesting depth for automatic schema detection"
complete -c reader -f -n "commandline -opc | string match -rg '\\.json\$'" -l maximum-object-size -d "[read_json] Maximum size of a JSON object (in bytes)"
complete -c reader -f -n "commandline -opc | string match -rg '\\.json\$'" -l maximum-sample-files -d "[read_json] Maximum number of JSON files sampled for auto-detection"
complete -c reader -f -n "commandline -opc | string match -rg '\\.json\$'" -l records -d "[read_json] Whether JSON contains records that should be unpacked into columns ('auto', 'true', 'false')"
complete -c reader -f -n "commandline -opc | string match -rg '\\.json\$'" -l sample-size -d "[read_json] Number of sample objects for automatic type detection"
complete -c reader -f -n "commandline -opc | string match -rg '\\.json\$'" -l timestampformat -d "[read_json] Timestamp format used when parsing timestamps"
complete -c reader -f -n "commandline -opc | string match -rg '\\.json\$'" -l union-by-name -d "[read_json] Whether the schemas of multiple JSON files should be unified"
complete -c reader -f -n "commandline -opc | string match -rg '\\.jsonl\$'" -l auto-detect -d "[read_ndjson] Whether to auto-detect the names of the keys and data types"
complete -c reader -f -n "commandline -opc | string match -rg '\\.jsonl\$'" -l columns -d "[read_ndjson] A struct that specifies the key names and value types (e"
complete -c reader -f -n "commandline -opc | string match -rg '\\.jsonl\$'" -l convert-strings-to-integers -d "[read_ndjson] Convert strings representing integer values to numerical type"
complete -c reader -f -n "commandline -opc | string match -rg '\\.jsonl\$'" -l dateformat -d "[read_ndjson] Date format used when parsing dates"
complete -c reader -f -n "commandline -opc | string match -rg '\\.jsonl\$'" -l field-appearance-threshold -d "[read_ndjson] Threshold for field appearance ratio"
complete -c reader -f -n "commandline -opc | string match -rg '\\.jsonl\$'" -l format -a "auto newline_delimited array parquet csv tsv json jsonl arrow" -d "[read_ndjson] JSON format ('auto', 'unstructured', 'newline_delimited', 'array')"
complete -c reader -f -n "commandline -opc | string match -rg '\\.jsonl\$'" -l ignore-errors -d "[read_ndjson] Ignore parse errors"
complete -c reader -f -n "commandline -opc | string match -rg '\\.jsonl\$'" -l map-inference-threshold -d "[read_ndjson] Threshold for number of columns before inferring MAP type"
complete -c reader -f -n "commandline -opc | string match -rg '\\.jsonl\$'" -l maximum-depth -d "[read_ndjson] Maximum nesting depth for schema detection"
complete -c reader -f -n "commandline -opc | string match -rg '\\.jsonl\$'" -l maximum-object-size -d "[read_ndjson] Maximum size of a JSON object (in bytes)"
complete -c reader -f -n "commandline -opc | string match -rg '\\.jsonl\$'" -l maximum-sample-files -d "[read_ndjson] Maximum number of JSON files sampled for auto-detection"
complete -c reader -f -n "commandline -opc | string match -rg '\\.jsonl\$'" -l records -d "[read_ndjson] Whether JSON contains records ('auto', 'true', 'false')"
complete -c reader -f -n "commandline -opc | string match -rg '\\.jsonl\$'" -l sample-size -d "[read_ndjson] Number of sample objects for detection"
complete -c reader -f -n "commandline -opc | string match -rg '\\.jsonl\$'" -l timestampformat -d "[read_ndjson] Timestamp format used when parsing timestamps"
complete -c reader -f -n "commandline -opc | string match -rg '\\.jsonl\$'" -l union-by-name -d "[read_ndjson] Whether the schemas of multiple JSON files should be unified"
complete -c reader -f -n "commandline -opc | string match -rg '\\.ndjson\$'" -l auto-detect -d "[read_ndjson] Whether to auto-detect the names of the keys and data types"
complete -c reader -f -n "commandline -opc | string match -rg '\\.ndjson\$'" -l columns -d "[read_ndjson] A struct that specifies the key names and value types (e"
complete -c reader -f -n "commandline -opc | string match -rg '\\.ndjson\$'" -l convert-strings-to-integers -d "[read_ndjson] Convert strings representing integer values to numerical type"
complete -c reader -f -n "commandline -opc | string match -rg '\\.ndjson\$'" -l dateformat -d "[read_ndjson] Date format used when parsing dates"
complete -c reader -f -n "commandline -opc | string match -rg '\\.ndjson\$'" -l field-appearance-threshold -d "[read_ndjson] Threshold for field appearance ratio"
complete -c reader -f -n "commandline -opc | string match -rg '\\.ndjson\$'" -l format -a "auto newline_delimited array parquet csv tsv json jsonl arrow" -d "[read_ndjson] JSON format ('auto', 'unstructured', 'newline_delimited', 'array')"
complete -c reader -f -n "commandline -opc | string match -rg '\\.ndjson\$'" -l ignore-errors -d "[read_ndjson] Ignore parse errors"
complete -c reader -f -n "commandline -opc | string match -rg '\\.ndjson\$'" -l map-inference-threshold -d "[read_ndjson] Threshold for number of columns before inferring MAP type"
complete -c reader -f -n "commandline -opc | string match -rg '\\.ndjson\$'" -l maximum-depth -d "[read_ndjson] Maximum nesting depth for schema detection"
complete -c reader -f -n "commandline -opc | string match -rg '\\.ndjson\$'" -l maximum-object-size -d "[read_ndjson] Maximum size of a JSON object (in bytes)"
complete -c reader -f -n "commandline -opc | string match -rg '\\.ndjson\$'" -l maximum-sample-files -d "[read_ndjson] Maximum number of JSON files sampled for auto-detection"
complete -c reader -f -n "commandline -opc | string match -rg '\\.ndjson\$'" -l records -d "[read_ndjson] Whether JSON contains records ('auto', 'true', 'false')"
complete -c reader -f -n "commandline -opc | string match -rg '\\.ndjson\$'" -l sample-size -d "[read_ndjson] Number of sample objects for detection"
complete -c reader -f -n "commandline -opc | string match -rg '\\.ndjson\$'" -l timestampformat -d "[read_ndjson] Timestamp format used when parsing timestamps"
complete -c reader -f -n "commandline -opc | string match -rg '\\.ndjson\$'" -l union-by-name -d "[read_ndjson] Whether the schemas of multiple JSON files should be unified"
complete -c reader -f -n "commandline -opc | string match -rg '\\.parquet\$'" -l binary-as-string -d "[read_parquet] Load binary columns as strings (for legacy Parquet files)"
complete -c reader -f -n "commandline -opc | string match -rg '\\.parquet\$'" -l encryption-config -d "[read_parquet] Configuration for Parquet encryption"
complete -c reader -f -n "commandline -opc | string match -rg '\\.parquet\$'" -l file-row-number -d "[read_parquet] Whether to include the file_row_number column"
complete -c reader -f -n "commandline -opc | string match -rg '\\.parquet\$'" -l filename -d "[read_parquet] Whether to include filename column"
complete -c reader -f -n "commandline -opc | string match -rg '\\.parquet\$'" -l hive-partitioning -d "[read_parquet] Whether or not to interpret the path as a Hive partitioned path"
complete -c reader -f -n "commandline -opc | string match -rg '\\.parquet\$'" -l schema -d "[read_parquet] Read Parquet file with supplied schema (requires field IDs)"
complete -c reader -f -n "commandline -opc | string match -rg '\\.parquet\$'" -l union-by-name -d "[read_parquet] Union multiple schemas by name"
complete -c reader -f -n "commandline -opc | string match -rg '\\.xlsx\$'" -l all-varchar -d "[read_xlsx] Read all cells as VARCHARs"
complete -c reader -f -n "commandline -opc | string match -rg '\\.xlsx\$'" -l header -d "[read_xlsx] Treat first row as column names"
complete -c reader -f -n "commandline -opc | string match -rg '\\.xlsx\$'" -l range -d "[read_xlsx] Range of cells to read (e"
complete -c reader -f -n "commandline -opc | string match -rg '\\.xlsx\$'" -l sheet -d "[read_xlsx] Name of the sheet to read"
complete -c reader -f -n "commandline -opc | string match -rq -- '--to=.*?(\\.csv|\\.tsv|\\.txt)'" -l compression -a "uncompressed brotli gzip snappy lz4 lz4_raw zstd auto none" -d "COPY [csv] Compression type: auto, none, gzip, zstd, snappy, brotli, lz4"
complete -c reader -f -n "commandline -opc | string match -rq -- '--to=.*?(\\.parquet)'" -l compression -a "uncompressed brotli gzip snappy lz4 lz4_raw zstd auto none" -d "COPY [parquet] Compression type: auto, none, gzip, zstd, snappy, brotli, lz4"
complete -c reader -f -n "commandline -opc | string match -rq -- '--to=.*?(\\.json|\\.jsonl|\\.ndjson)'" -l compression -a "uncompressed brotli gzip snappy lz4 lz4_raw zstd auto none" -d "COPY [json] Compression type: auto, none, gzip, zstd, snappy, brotli, lz4"
complete -c reader -f -n "commandline -opc | string match -rq -- '--to=.*?(\\.csv|\\.tsv|\\.txt)'" -l dateformat -d "COPY [csv] Date format for writing dates"
complete -c reader -f -n "commandline -opc | string match -rq -- '--to=.*?(\\.json|\\.jsonl|\\.ndjson)'" -l dateformat -d "COPY [json] Date format for writing dates"
complete -c reader -f -n "commandline -opc | string match -rq -- '--to=.*?(\\.csv|\\.tsv|\\.txt)'" -l delim -d "COPY [csv] Delimiter character to separate columns"
complete -c reader -f -n "commandline -opc | string match -rq -- '--to=.*?(\\.csv|\\.tsv|\\.txt)'" -l sep -d "COPY [csv] Alias for delim"
complete -c reader -f -n "commandline -opc | string match -rq -- '--to=.*?(\\.csv|\\.tsv|\\.txt)'" -l escape -d "COPY [csv] Character before a quote character within quoted values"
complete -c reader -f -n "commandline -opc | string match -rq -- '--to=.*?(\\.csv|\\.tsv|\\.txt)'" -l force-quote -d "COPY [csv] List of columns to always add quotes to"
complete -c reader -f -n "commandline -opc | string match -rq -- '--to=.*?(\\.csv|\\.tsv|\\.txt)'" -l header -d "COPY [csv] Whether to write a header for the CSV file"
complete -c reader -f -n "commandline -opc | string match -rq -- '--to=.*?(\\.csv|\\.tsv|\\.txt)'" -l nullstr -d "COPY [csv] String to represent NULL value"
complete -c reader -f -n "commandline -opc | string match -rq -- '--to=.*?(\\.csv|\\.tsv|\\.txt)'" -l prefix -d "COPY [csv] Prefix string for CSV file"
complete -c reader -f -n "commandline -opc | string match -rq -- '--to=.*?(\\.csv|\\.tsv|\\.txt)'" -l suffix -d "COPY [csv] Suffix string for CSV file"
complete -c reader -f -n "commandline -opc | string match -rq -- '--to=.*?(\\.csv|\\.tsv|\\.txt)'" -l quote -d "COPY [csv] Quoting character for data values"
complete -c reader -f -n "commandline -opc | string match -rq -- '--to=.*?(\\.csv|\\.tsv|\\.txt)'" -l timestampformat -d "COPY [csv] Timestamp format for writing"
complete -c reader -f -n "commandline -opc | string match -rq -- '--to=.*?(\\.json|\\.jsonl|\\.ndjson)'" -l timestampformat -d "COPY [json] Timestamp format for writing"
complete -c reader -f -n "commandline -opc | string match -rq -- '--to=.*?(\\.parquet)'" -l compression-level -d "COPY [parquet] Compression level 1-22 (only for zstd)"
complete -c reader -f -n "commandline -opc | string match -rq -- '--to=.*?(\\.parquet)'" -l field-ids -d "COPY [parquet] Field ID for each column"
complete -c reader -f -n "commandline -opc | string match -rq -- '--to=.*?(\\.parquet)'" -l row-group-size-bytes -d "COPY [parquet] Target size of each row group in bytes"
complete -c reader -f -n "commandline -opc | string match -rq -- '--to=.*?(\\.parquet)'" -l row-group-size -d "COPY [parquet] Target number of rows per row group"
complete -c reader -f -n "commandline -opc | string match -rq -- '--to=.*?(\\.parquet)'" -l row-groups-per-file -d "COPY [parquet] Create new file after N row groups"
complete -c reader -f -n "commandline -opc | string match -rq -- '--to=.*?(\\.json|\\.jsonl|\\.ndjson)'" -l array -d "COPY [json] Write JSON array of records (true) or newline-delimited (false)"
complete -c reader -f -n "commandline -opc | string match -rq -- '--to|--format'" -l format -a "auto newline_delimited array parquet csv tsv json jsonl arrow" -d "COPY [all] Explicit format: parquet, csv, json, arrow, jsonl"
complete -c reader -f -n "commandline -opc | string match -rq -- '--to|--format'" -l use-tmp-file -d "COPY [all] Write to temp file first to prevent broken overwrites"
complete -c reader -f -n "commandline -opc | string match -rq -- '--to|--format'" -l overwrite-or-ignore -d "COPY [all] Allow overwriting files (with partition_by)"
complete -c reader -f -n "commandline -opc | string match -rq -- '--to|--format'" -l overwrite -d "COPY [all] Remove existing files in targeted directories"
complete -c reader -f -n "commandline -opc | string match -rq -- '--to|--format'" -l append -d "COPY [all] Regenerate path if file exists (with partition_by)"
complete -c reader -f -n "commandline -opc | string match -rq -- '--to|--format'" -l filename-pattern -d "COPY [all] Pattern for filename, can use {uuid} or {id}"
complete -c reader -f -n "commandline -opc | string match -rq -- '--to|--format'" -l file-extension -d "COPY [all] File extension for generated files"
complete -c reader -f -n "commandline -opc | string match -rq -- '--to|--format'" -l per-thread-output -d "COPY [all] Generate one file per thread"
complete -c reader -f -n "commandline -opc | string match -rq -- '--to|--format'" -l file-size-bytes -d "COPY [all] Max file size before creating new file (e"
complete -c reader -f -n "commandline -opc | string match -rq -- '--to|--format'" -l partition-by -d "COPY [all] Columns to partition by using Hive scheme"
complete -c reader -f -n "commandline -opc | string match -rq -- '--to|--format'" -l return-files -d "COPY [all] Include created filepaths in query result"
complete -c reader -f -n "commandline -opc | string match -rq -- '--to|--format'" -l write-partition-columns -d "COPY [all] Write partition columns into files"
complete -c reader -F -l to -d "Export result to a file (CSV, JSON, Parquet)" -r
complete -c reader -f -l format -d "Output format (csv, tsv, json, jsonl, parquet) to stdout" -r -a "csv tsv json jsonl parquet"

function __fish_reader_complete_columns
    set -l tokens (commandline -opc)
    set -l cur (commandline -ct)

    # Find all data files (multiple positional args)
    set -l files
    for tok in $tokens
        if string match -qr '\.(csv|tsv|txt|json|jsonl|ndjson|parquet|xlsx|lance|vortex)$' -- $tok
            set -a files $tok
        end
    end
    test (count $files) -eq 0 && return

    # Join files with comma for reader
    set -l file (string join ',' $files)

    # Get the last part after comma
    set -l prefix ""
    set -l partial ""
    if string match -q '*,*' -- $cur
        set prefix (string replace -r ',[^,]*$' ',' -- $cur)
        set partial (string replace -r '.*,' '' -- $cur)
    else
        set partial $cur
    end

    # Check if partial ends with dot (nested field access)
    if string match -qr '\w+\.$' -- $partial
        # Show all nested children for this prefix
        set -l nested_prefix (string replace -r '\.$' '' -- $partial)
        for col in (reader _complete_columns $file $nested_prefix 2>/dev/null)
            set -l name (string split -m1 \t $col)[1]
            set -l desc (string split -m1 \t $col)[2]
            printf "%s%s\t%s\n" $prefix $name $desc
        end
    else if test -n "$partial"
        # Partial input, use sql_auto_complete for functions/columns
        for row in (reader _complete_sql $file $partial 2>/dev/null)
            set -l name (string split -m1 \t $row)[1]
            set -l typ (string split -m1 \t $row)[2]
            printf "%s%s\t%s\n" $prefix $name $typ
        end
    else
        # No input yet, show columns with stats
        for col in (reader _complete_columns $file 2>/dev/null)
            set -l name (string split -m1 \t $col)[1]
            set -l desc (string split -m1 \t $col)[2]
            printf "%s%s\t%s\n" $prefix $name $desc
        end
    end
end
complete -c reader -f -k -n "not commandline -opc | string match -rq -- '--to|--format'" -l select -s s -d "Select specific columns" -r -a "(__fish_reader_complete_columns)"
complete -c reader -f -k -n "not commandline -opc | string match -rq -- '--to|--format'" -l exclude -d "Exclude columns (SELECT * EXCLUDE (cols))" -r -a "(__fish_reader_complete_columns)"
complete -c reader -f -k -n "not commandline -opc | string match -rq -- '--to|--format'" -l where -d "Filter rows with a WHERE clause" -r -a "(__fish_reader_complete_columns)"
complete -c reader -f -n "not commandline -opc | string match -rq -- '--to|--format'" -l join -s j -d "Join with another table (cumulative)" -r
complete -c reader -f -n "not commandline -opc | string match -rq -- '--to|--format'" -l left-join -d "LEFT JOIN with another table" -r
complete -c reader -f -n "not commandline -opc | string match -rq -- '--to|--format'" -l right-join -d "RIGHT JOIN with another table" -r
complete -c reader -f -n "not commandline -opc | string match -rq -- '--to|--format'" -l inner-join -d "INNER JOIN with another table" -r
complete -c reader -f -n "not commandline -opc | string match -rq -- '--to|--format'" -l outer-join -d "OUTER JOIN with another table" -r
complete -c reader -f -n "not commandline -opc | string match -rq -- '--to|--format'" -l cross-join -d "CROSS JOIN with another table" -r
complete -c reader -f -n "not commandline -opc | string match -rq -- '--to|--format'" -l natural-join -d "NATURAL JOIN with another table" -r
complete -c reader -f -n "not commandline -opc | string match -rq -- '--to|--format'" -l anti-join -d "ANTI JOIN with another table" -r
complete -c reader -f -n "not commandline -opc | string match -rq -- '--to|--format'" -l semi-join -d "SEMI JOIN with another table" -r
complete -c reader -f -n "not commandline -opc | string match -rq -- '--to|--format'" -l full-join -d "FULL JOIN with another table" -r
complete -c reader -f -n "not commandline -opc | string match -rq -- '--to|--format'" -l positional-join -d "POSITIONAL JOIN with another table" -r
complete -c reader -f -k -n "not commandline -opc | string match -rq -- '--to|--format'" -l on -d "Join condition for ON clause (used with --join)" -r -a "(__fish_reader_complete_columns)"
complete -c reader -f -k -n "not commandline -opc | string match -rq -- '--to|--format'" -l using -d "Join column(s) for USING clause (used with --join)" -r -a "(__fish_reader_complete_columns)"
complete -c reader -f -k -n "not commandline -opc | string match -rq -- '--to|--format'" -l distinct -s d -d "Select distinct rows based on a column" -r -a "(__fish_reader_complete_columns)"
complete -c reader -f -n "not commandline -opc | string match -rq -- '--to|--format'" -l sample -d "Sample N rows from the result" -r
complete -c reader -f -k -n "not commandline -opc | string match -rq -- '--to|--format'" -l sort -d "Sort result by columns (ORDER BY)" -r -a "(__fish_reader_complete_columns)"
complete -c reader -f -k -n "not commandline -opc | string match -rq -- '--to|--format'" -l order-by -d "Sort result by columns (ORDER BY)" -r -a "(__fish_reader_complete_columns)"
complete -c reader -f -k -n "not commandline -opc | string match -rq -- '--to|--format'" -l group-by -s g -d "Group result by columns (GROUP BY)" -r -a "(__fish_reader_complete_columns)"
complete -c reader -f -k -n "not commandline -opc | string match -rq -- '--to|--format'" -l having -d "Filter groups with a HAVING clause" -r -a "(__fish_reader_complete_columns)"
complete -c reader -f -k -n "not commandline -opc | string match -rq -- '--to|--format'" -l count-by -d "Count rows grouped by column" -r -a "(__fish_reader_complete_columns)"
complete -c reader -f -n "not commandline -opc | string match -rq -- '--to|--format'" -l summarize -d "Show summary statistics of the result"
complete -c reader -f -n "not commandline -opc | string match -rq -- '--to|--format'" -l analyze -d "Pretty per-column analysis with enum counts & bars"
complete -c reader -f -n "not commandline -opc | string match -rq -- '--to|--format'" -l sample-size -d "Number of lines to scan for auto-detection" -r
complete -c reader -f -n "not commandline -opc | string match -rq -- '--to|--format'" -l limit -s l -d "Limit the number of rows returned" -r
complete -c reader -f -n "not commandline -opc | string match -rq -- '--to|--format'" -l union-by-name -d "Whether to union files by name"
complete -c reader -f -n "not commandline -opc | string match -rq -- '--to|--format'" -l ignore-errors -d "Whether to ignore errors"
complete -c reader -f -n "not commandline -opc | string match -rq -- '--to|--format'" -l help -d "Show help message"
complete -c reader -f -n "not commandline -opc | string match -rq -- '--to|--format'" -s h -d "Show help message"
complete -c reader -f -n "not commandline -opc | string match -rq -- '--to|--format'" -l mode -s m -a "box line json csv markdown" -d "Output format"
complete -c reader -f -n "not commandline -opc | string match -rq -- '--to|--format'" -l tui -s t -d "Open result in tablens TUI"
complete -c reader -f -n "not commandline -opc | string match -rq -- '--to|--format'" -l with -d "Add a CTE (Common Table Expression)" -r
complete -c reader -f -n "not commandline -opc | string match -rq -- '--to|--format'" -l pipe -d "Pipe result through another query (chainable)" -r
complete -c reader -f -n "not commandline -opc | string match -rq -- '--to|--format'" -l no-truncate -d "Do not truncate output to terminal width"
complete -c reader -F
