complete -c rehype -s e -d '--ext <extensions>                  specify extensions'
complete -c rehype -l file-path -d '<path>                  specify path to process as'
complete -c rehype -s f -d '--frail                             exit with 1 on warnings'
complete -c rehype -s h -d '--help                              output usage information'
complete -c rehype -s i -d '--ignore-path <path>                specify ignore file'
complete -c rehype -l ignore-path-resolve-from -d 'cwd|dir  resolve patterns in `ignore-path` from its directory or cwd'
complete -c rehype -l ignore-pattern -d '<globs>            specify ignore patterns'
complete -c rehype -l inspect -d 'output formatted syntax tree'
complete -c rehype -s o -d '--output [path]                     specify output location'
complete -c rehype -s q -d '--quiet                             output only warnings and errors'
complete -c rehype -s r -d '--rc-path <path>                    specify configuration file'
complete -c rehype -l report -d '<reporter>                 specify reporter'
complete -c rehype -s s -d '--setting <settings>                specify settings'
complete -c rehype -s S -d '--silent                            output only errors'
complete -c rehype -l silently-ignore -d 'do not fail when given ignored files'
complete -c rehype -s t -d '--tree                              specify input and output as syntax tree'
complete -c rehype -l tree-in -d 'specify input as syntax tree'
complete -c rehype -l tree-out -d 'output syntax tree'
complete -c rehype -s u -d '--use <plugins>                     use plugins'
complete -c rehype -l verbose -d 'report extra info for messages'
complete -c rehype -s v -d '--version                           output version number'
complete -c rehype -s w -d '--watch                             watch for changes and reprocess'
