complete -c remix -s h -l help -d 'Print this help message and exit'
complete -c remix -n __fish_no_arguments -s v -l version -d 'Print the CLI version and exit'
complete -c remix -l no-color -d 'Disable ANSI colors in console output'
complete -c remix -l assetsInlineLimit -d 'Static asset base64 inline threshold in bytes (default: 4096) (number)'
complete -c remix -l clearScreen -d 'Allow/disable clear screen when logging (boolean)'
complete -c remix -s c -l config -d 'Use specified config file (string)'
complete -c remix -l emptyOutDir -d Force\ empty\ outDir\ when\ it\'s\ outside\ of\ root\ \(boolean\)
complete -c remix -s l -l logLevel -d 'Info | warn | error | silent (string)'
complete -c remix -l minify -d 'Enable/disable minification, or specify minifier to use (default: "esbuild") (boolean | "terser" | "esbuild")'
complete -c remix -s m -l mode -d 'Set env mode (string)'
complete -c remix -l profile -d 'Start built-in Node.js inspector'
complete -c remix -l sourcemapClient -d 'Output source maps for client build (default: false) (boolean | "inline" | "hidden")'
complete -c remix -l sourcemapServer -d 'Output source maps for server build (default: false) (boolean | "inline" | "hidden")'
complete -c remix -l sourcemap -d 'Generate source maps for production'
complete -c remix -l clearScreen -d 'Allow/disable clear screen when logging (boolean)'
complete -c remix -s c -l config -d 'Use specified config file (string)'
complete -c remix -l cors -d 'Enable CORS (boolean)'
complete -c remix -l force -d 'Force the optimizer to ignore the cache and re-bundle (boolean)'
complete -c remix -l host -d 'Specify hostname (string)'
complete -c remix -s l -l logLevel -d 'Info | warn | error | silent (string)'
complete -c remix -s m -l mode -d 'Set env mode (string)'
complete -c remix -l open -d 'Open browser on startup (boolean | string)'
complete -c remix -l port -d 'Specify port (number)'
complete -c remix -l profile -d 'Start built-in Node.js inspector'
complete -c remix -l strictPort -d 'Exit if specified port is already in use (boolean)'
complete -c remix -s c -l command -d 'Command used to run your app server'
complete -c remix -l manual -d 'Enable manual mode'
complete -c remix -l port -d 'Port for the dev server. Default: any open port'
complete -c remix -l tls-key -d 'Path to TLS key (key.pem)'
complete -c remix -l tls-cert -d 'Path to TLS certificate (cert.pem)'
complete -c remix -l no-delete -d 'Skip deleting the `remix.init` script'
complete -c remix -s c -l config -d 'Use specified Vite config file (string)'
complete -c remix -l json -d 'Print the routes as JSON'
complete -c remix -s c -l config -d 'Use specified Vite config file (string)'
complete -c remix -l no-typescript -d 'Generate plain JavaScript files'
