complete -c repomix -n __fish_no_arguments -s v -l version -d 'show version information'
complete -c repomix -s o -l output -d '<file>                specify the output file name'
complete -c repomix -l stdout -d 'output to stdout instead of writing to a'
complete -c repomix -l style -d '<type>                     specify the output style (xml, markdown,'
complete -c repomix -l parsable-style -d 'by escaping and formatting, ensure the'
complete -c repomix -l compress -d 'perform code compression to reduce token'
complete -c repomix -l output-show-line-numbers -d 'add line numbers to each line in the output'
complete -c repomix -l copy -d 'copy generated output to system clipboard'
complete -c repomix -l no-file-summary -d 'disable file summary section output'
complete -c repomix -l no-directory-structure -d 'disable directory structure section output'
complete -c repomix -l no-files -d 'disable files content output (metadata-only'
complete -c repomix -l remove-comments -d 'remove comments'
complete -c repomix -l remove-empty-lines -d 'remove empty lines'
complete -c repomix -l header-text -d '<text>               specify the header text'
complete -c repomix -l instruction-file-path -d '<path>     path to a file containing detailed custom'
complete -c repomix -l include-empty-directories -d 'include empty directories in the output'
complete -c repomix -l no-git-sort-by-changes -d 'disable sorting files by git change count'
complete -c repomix -l include-diffs -d 'include git diffs in the output (includes'
complete -c repomix -l include -d '<patterns>               list of include patterns (comma-separated)'
complete -c repomix -s i -l ignore -d '<patterns>            additional ignore patterns'
complete -c repomix -l no-gitignore -d 'disable .gitignore file usage'
complete -c repomix -l no-default-patterns -d 'disable default patterns'
complete -c repomix -l remote -d '<url>                     process a remote Git repository'
complete -c repomix -l remote-branch -d '<name>             specify the remote branch name, tag, or'
complete -c repomix -s c -l config -d '<path>                path to a custom config file'
complete -c repomix -l init -d 'initialize a new repomix.config.json file'
complete -c repomix -l global -d 'use global configuration (only applicable'
complete -c repomix -l no-security-check -d 'disable security check'
complete -c repomix -l token-count-encoding -d '<encoding>  specify token count encoding (e.g.,'
complete -c repomix -l mcp -d 'run as a MCP server'
complete -c repomix -l top-files-len -d '<number>           specify the number of top files to display'
complete -c repomix -l verbose -d 'enable verbose logging for detailed output'
complete -c repomix -l quiet -d 'disable all output to stdout'
complete -c repomix -s h -l help -d 'display help for command'
