# Print an optspec for argparse to handle cmd's options that are independent of any subcommand.
function __fish_rsmultigit_global_optspecs
	string join \n terse no-header no-output v/verbose print-not no-stop short-circuit j/jobs= h/help V/version
end

function __fish_rsmultigit_needs_command
	# Figure out if the current invocation already has a command.
	set -l cmd (commandline -opc)
	set -e cmd[1]
	argparse -s (__fish_rsmultigit_global_optspecs) -- $cmd 2>/dev/null
	or return
	if set -q argv[1]
		# Also print the command, so this can be used to figure out what it is.
		echo $argv[1]
		return 1
	end
	return 0
end

function __fish_rsmultigit_using_subcommand
	set -l cmd (__fish_rsmultigit_needs_command)
	test -z "$cmd"
	and return 1
	contains -- $cmd[1] $argv
end

complete -c rsmultigit -n "__fish_rsmultigit_needs_command" -s j -l jobs -d 'Number of parallel workers (default: 1; use 0 for num_cpus)' -r
complete -c rsmultigit -n "__fish_rsmultigit_needs_command" -l terse -d 'Terse output'
complete -c rsmultigit -n "__fish_rsmultigit_needs_command" -l no-header -d 'Suppress the [project] header line printed before per-project output'
complete -c rsmultigit -n "__fish_rsmultigit_needs_command" -l no-output -d 'Suppress command output'
complete -c rsmultigit -n "__fish_rsmultigit_needs_command" -s v -l verbose -d 'Verbose output (print all projects, even when no action is taken)'
complete -c rsmultigit -n "__fish_rsmultigit_needs_command" -l print-not -d 'Print repos that do NOT match (invert selection)'
complete -c rsmultigit -n "__fish_rsmultigit_needs_command" -l no-stop -d 'Do not stop on errors'
complete -c rsmultigit -n "__fish_rsmultigit_needs_command" -l short-circuit -d 'Stop at the first negative result instead of processing everything. Off by default. Currently honoured by `check-same`, which exits as soon as one rule is broken instead of evaluating the remaining rules'
complete -c rsmultigit -n "__fish_rsmultigit_needs_command" -s h -l help -d 'Print help'
complete -c rsmultigit -n "__fish_rsmultigit_needs_command" -s V -l version -d 'Print version'
complete -c rsmultigit -n "__fish_rsmultigit_needs_command" -f -a "age" -d 'Show the age of the last commit per repo'
complete -c rsmultigit -n "__fish_rsmultigit_needs_command" -f -a "authors" -d 'Show unique commit authors per repo'
complete -c rsmultigit -n "__fish_rsmultigit_needs_command" -f -a "blame" -d 'Run git blame on a file across all repositories'
complete -c rsmultigit -n "__fish_rsmultigit_needs_command" -f -a "branch" -d 'Branch operations'
complete -c rsmultigit -n "__fish_rsmultigit_needs_command" -f -a "build" -d 'Build projects'
complete -c rsmultigit -n "__fish_rsmultigit_needs_command" -f -a "checkout" -d 'Checkout a branch across all repositories'
complete -c rsmultigit -n "__fish_rsmultigit_needs_command" -f -a "check-same" -d 'Check that files declared in ~/.config/rsmultigit/config.toml are identical across repos'
complete -c rsmultigit -n "__fish_rsmultigit_needs_command" -f -a "clean" -d 'Clean repositories'
complete -c rsmultigit -n "__fish_rsmultigit_needs_command" -f -a "commit" -d 'Commit all changes across all repositories'
complete -c rsmultigit -n "__fish_rsmultigit_needs_command" -f -a "complete" -d 'Generate shell completion scripts'
complete -c rsmultigit -n "__fish_rsmultigit_needs_command" -f -a "config" -d 'Show a git config value across all repos'
complete -c rsmultigit -n "__fish_rsmultigit_needs_command" -f -a "config-example" -d 'Print a sample rsmultigit config.toml to stdout. Redirect to ~/.config/rsmultigit/config.toml to bootstrap a new install'
complete -c rsmultigit -n "__fish_rsmultigit_needs_command" -f -a "count" -d 'Count repositories matching a condition'
complete -c rsmultigit -n "__fish_rsmultigit_needs_command" -f -a "diff" -d 'Show diff for all repositories'
complete -c rsmultigit -n "__fish_rsmultigit_needs_command" -f -a "dirty" -d 'Show dirty repositories'
complete -c rsmultigit -n "__fish_rsmultigit_needs_command" -f -a "fetch" -d 'Fetch from origin for all repositories'
complete -c rsmultigit -n "__fish_rsmultigit_needs_command" -f -a "gc" -d 'Run git garbage collection'
complete -c rsmultigit -n "__fish_rsmultigit_needs_command" -f -a "grep" -d 'Grep across all repositories'
complete -c rsmultigit -n "__fish_rsmultigit_needs_command" -f -a "last-tag" -d 'Show the most recent tag per repo'
complete -c rsmultigit -n "__fish_rsmultigit_needs_command" -f -a "list-repos" -d 'Print the path of every configured repo, one per line (no header by default). Pass --verbose to also emit the [project] header for each entry'
complete -c rsmultigit -n "__fish_rsmultigit_needs_command" -f -a "list-checks" -d 'Print the name of every check rule defined in the config, one per line. Intended for use in shell-completion scripts. All rules are listed, including those with `enabled = false`'
complete -c rsmultigit -n "__fish_rsmultigit_needs_command" -f -a "log" -d 'Show recent commits'
complete -c rsmultigit -n "__fish_rsmultigit_needs_command" -f -a "prune" -d 'Prune stale remote-tracking branches'
complete -c rsmultigit -n "__fish_rsmultigit_needs_command" -f -a "pull" -d 'Pull all repositories'
complete -c rsmultigit -n "__fish_rsmultigit_needs_command" -f -a "push" -d 'Push all repositories'
complete -c rsmultigit -n "__fish_rsmultigit_needs_command" -f -a "remote" -d 'Show remote URLs'
complete -c rsmultigit -n "__fish_rsmultigit_needs_command" -f -a "reset" -d 'Reset operations'
complete -c rsmultigit -n "__fish_rsmultigit_needs_command" -f -a "run" -d 'Run an arbitrary command across all repositories'
complete -c rsmultigit -n "__fish_rsmultigit_needs_command" -f -a "size" -d 'Show the size of the .git directory per repo'
complete -c rsmultigit -n "__fish_rsmultigit_needs_command" -f -a "stash" -d 'Stash operations'
complete -c rsmultigit -n "__fish_rsmultigit_needs_command" -f -a "status" -d 'Show status of repositories'
complete -c rsmultigit -n "__fish_rsmultigit_needs_command" -f -a "submodule-update" -d 'Update submodules recursively'
complete -c rsmultigit -n "__fish_rsmultigit_needs_command" -f -a "tag" -d 'List tags'
complete -c rsmultigit -n "__fish_rsmultigit_needs_command" -f -a "version" -d 'Print version information'
complete -c rsmultigit -n "__fish_rsmultigit_needs_command" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand age" -s j -l jobs -d 'Number of parallel workers (default: 1; use 0 for num_cpus)' -r
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand age" -l terse -d 'Terse output'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand age" -l no-header -d 'Suppress the [project] header line printed before per-project output'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand age" -l no-output -d 'Suppress command output'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand age" -s v -l verbose -d 'Verbose output (print all projects, even when no action is taken)'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand age" -l print-not -d 'Print repos that do NOT match (invert selection)'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand age" -l no-stop -d 'Do not stop on errors'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand age" -l short-circuit -d 'Stop at the first negative result instead of processing everything. Off by default. Currently honoured by `check-same`, which exits as soon as one rule is broken instead of evaluating the remaining rules'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand age" -s h -l help -d 'Print help'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand authors" -s j -l jobs -d 'Number of parallel workers (default: 1; use 0 for num_cpus)' -r
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand authors" -l terse -d 'Terse output'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand authors" -l no-header -d 'Suppress the [project] header line printed before per-project output'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand authors" -l no-output -d 'Suppress command output'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand authors" -s v -l verbose -d 'Verbose output (print all projects, even when no action is taken)'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand authors" -l print-not -d 'Print repos that do NOT match (invert selection)'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand authors" -l no-stop -d 'Do not stop on errors'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand authors" -l short-circuit -d 'Stop at the first negative result instead of processing everything. Off by default. Currently honoured by `check-same`, which exits as soon as one rule is broken instead of evaluating the remaining rules'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand authors" -s h -l help -d 'Print help'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand blame" -s j -l jobs -d 'Number of parallel workers (default: 1; use 0 for num_cpus)' -r
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand blame" -l terse -d 'Terse output'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand blame" -l no-header -d 'Suppress the [project] header line printed before per-project output'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand blame" -l no-output -d 'Suppress command output'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand blame" -s v -l verbose -d 'Verbose output (print all projects, even when no action is taken)'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand blame" -l print-not -d 'Print repos that do NOT match (invert selection)'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand blame" -l no-stop -d 'Do not stop on errors'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand blame" -l short-circuit -d 'Stop at the first negative result instead of processing everything. Off by default. Currently honoured by `check-same`, which exits as soon as one rule is broken instead of evaluating the remaining rules'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand blame" -s h -l help -d 'Print help'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand branch" -s j -l jobs -d 'Number of parallel workers (default: 1; use 0 for num_cpus)' -r
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand branch" -l terse -d 'Terse output'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand branch" -l no-header -d 'Suppress the [project] header line printed before per-project output'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand branch" -l no-output -d 'Suppress command output'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand branch" -s v -l verbose -d 'Verbose output (print all projects, even when no action is taken)'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand branch" -l print-not -d 'Print repos that do NOT match (invert selection)'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand branch" -l no-stop -d 'Do not stop on errors'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand branch" -l short-circuit -d 'Stop at the first negative result instead of processing everything. Off by default. Currently honoured by `check-same`, which exits as soon as one rule is broken instead of evaluating the remaining rules'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand branch" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand build" -s j -l jobs -d 'Number of parallel workers (default: 1; use 0 for num_cpus)' -r
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand build" -l terse -d 'Terse output'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand build" -l no-header -d 'Suppress the [project] header line printed before per-project output'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand build" -l no-output -d 'Suppress command output'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand build" -s v -l verbose -d 'Verbose output (print all projects, even when no action is taken)'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand build" -l print-not -d 'Print repos that do NOT match (invert selection)'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand build" -l no-stop -d 'Do not stop on errors'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand build" -l short-circuit -d 'Stop at the first negative result instead of processing everything. Off by default. Currently honoured by `check-same`, which exits as soon as one rule is broken instead of evaluating the remaining rules'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand build" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand checkout" -s j -l jobs -d 'Number of parallel workers (default: 1; use 0 for num_cpus)' -r
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand checkout" -l terse -d 'Terse output'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand checkout" -l no-header -d 'Suppress the [project] header line printed before per-project output'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand checkout" -l no-output -d 'Suppress command output'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand checkout" -s v -l verbose -d 'Verbose output (print all projects, even when no action is taken)'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand checkout" -l print-not -d 'Print repos that do NOT match (invert selection)'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand checkout" -l no-stop -d 'Do not stop on errors'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand checkout" -l short-circuit -d 'Stop at the first negative result instead of processing everything. Off by default. Currently honoured by `check-same`, which exits as soon as one rule is broken instead of evaluating the remaining rules'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand checkout" -s h -l help -d 'Print help'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand check-same" -l checks -d 'Run only the listed check rules (space- or repeat-separated). Listed names override `enabled = false`. Unknown names are a hard error' -r
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand check-same" -l checks-re -d 'Run only check rules whose name matches one of the given regular expressions (unanchored, like grep; use ^...$ to match a full name). Combines with --checks. Matched rules override `enabled = false`. A pattern matching no check name is a hard error' -r
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand check-same" -s j -l jobs -d 'Number of parallel workers (default: 1; use 0 for num_cpus)' -r
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand check-same" -l only-failed -d 'Print only failing checks, suppressing the `ok` lines that passing checks print by default. (--terse implies this: its output is a machine-readable list of failing rule names.)'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand check-same" -l diff -d 'Show a unified diff between representative files of mismatching groups. With 2 groups this runs automatically; with 3+ groups it prompts interactively and offers to diff further pairs'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand check-same" -l copy -d 'Interactively copy one group\'s content over another\'s. Prompts for the "from" and "to" groups, then overwrites every file in the "to" group with the content of a representative file from the "from" group. Always exits 0 on success, regardless of whether mismatches remain'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand check-same" -l allow-empty -d 'Treat a rule that matches no files at all as passing. By default such a rule fails: catching 0 files almost always means a stale `select`/`path`, not a healthy check'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand check-same" -l fix-missing -d 'Interactively create missing files in repos that violate a rule\'s `must_have = true` requirement. Prompts for which content group to seed from, then writes the file (creating parent directories as needed). Always exits 0 on success'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand check-same" -l terse -d 'Terse output'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand check-same" -l no-header -d 'Suppress the [project] header line printed before per-project output'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand check-same" -l no-output -d 'Suppress command output'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand check-same" -s v -l verbose -d 'Verbose output (print all projects, even when no action is taken)'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand check-same" -l print-not -d 'Print repos that do NOT match (invert selection)'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand check-same" -l no-stop -d 'Do not stop on errors'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand check-same" -l short-circuit -d 'Stop at the first negative result instead of processing everything. Off by default. Currently honoured by `check-same`, which exits as soon as one rule is broken instead of evaluating the remaining rules'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand check-same" -s h -l help -d 'Print help'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand clean" -s j -l jobs -d 'Number of parallel workers (default: 1; use 0 for num_cpus)' -r
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand clean" -l terse -d 'Terse output'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand clean" -l no-header -d 'Suppress the [project] header line printed before per-project output'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand clean" -l no-output -d 'Suppress command output'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand clean" -s v -l verbose -d 'Verbose output (print all projects, even when no action is taken)'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand clean" -l print-not -d 'Print repos that do NOT match (invert selection)'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand clean" -l no-stop -d 'Do not stop on errors'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand clean" -l short-circuit -d 'Stop at the first negative result instead of processing everything. Off by default. Currently honoured by `check-same`, which exits as soon as one rule is broken instead of evaluating the remaining rules'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand clean" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand commit" -s m -l message -d 'Commit message' -r
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand commit" -s j -l jobs -d 'Number of parallel workers (default: 1; use 0 for num_cpus)' -r
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand commit" -l terse -d 'Terse output'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand commit" -l no-header -d 'Suppress the [project] header line printed before per-project output'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand commit" -l no-output -d 'Suppress command output'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand commit" -s v -l verbose -d 'Verbose output (print all projects, even when no action is taken)'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand commit" -l print-not -d 'Print repos that do NOT match (invert selection)'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand commit" -l no-stop -d 'Do not stop on errors'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand commit" -l short-circuit -d 'Stop at the first negative result instead of processing everything. Off by default. Currently honoured by `check-same`, which exits as soon as one rule is broken instead of evaluating the remaining rules'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand commit" -s h -l help -d 'Print help'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand complete" -s j -l jobs -d 'Number of parallel workers (default: 1; use 0 for num_cpus)' -r
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand complete" -l terse -d 'Terse output'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand complete" -l no-header -d 'Suppress the [project] header line printed before per-project output'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand complete" -l no-output -d 'Suppress command output'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand complete" -s v -l verbose -d 'Verbose output (print all projects, even when no action is taken)'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand complete" -l print-not -d 'Print repos that do NOT match (invert selection)'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand complete" -l no-stop -d 'Do not stop on errors'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand complete" -l short-circuit -d 'Stop at the first negative result instead of processing everything. Off by default. Currently honoured by `check-same`, which exits as soon as one rule is broken instead of evaluating the remaining rules'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand complete" -s h -l help -d 'Print help'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand config" -s j -l jobs -d 'Number of parallel workers (default: 1; use 0 for num_cpus)' -r
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand config" -l terse -d 'Terse output'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand config" -l no-header -d 'Suppress the [project] header line printed before per-project output'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand config" -l no-output -d 'Suppress command output'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand config" -s v -l verbose -d 'Verbose output (print all projects, even when no action is taken)'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand config" -l print-not -d 'Print repos that do NOT match (invert selection)'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand config" -l no-stop -d 'Do not stop on errors'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand config" -l short-circuit -d 'Stop at the first negative result instead of processing everything. Off by default. Currently honoured by `check-same`, which exits as soon as one rule is broken instead of evaluating the remaining rules'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand config" -s h -l help -d 'Print help'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand config-example" -s j -l jobs -d 'Number of parallel workers (default: 1; use 0 for num_cpus)' -r
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand config-example" -l terse -d 'Terse output'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand config-example" -l no-header -d 'Suppress the [project] header line printed before per-project output'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand config-example" -l no-output -d 'Suppress command output'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand config-example" -s v -l verbose -d 'Verbose output (print all projects, even when no action is taken)'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand config-example" -l print-not -d 'Print repos that do NOT match (invert selection)'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand config-example" -l no-stop -d 'Do not stop on errors'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand config-example" -l short-circuit -d 'Stop at the first negative result instead of processing everything. Off by default. Currently honoured by `check-same`, which exits as soon as one rule is broken instead of evaluating the remaining rules'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand config-example" -s h -l help -d 'Print help'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand count" -s j -l jobs -d 'Number of parallel workers (default: 1; use 0 for num_cpus)' -r
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand count" -l terse -d 'Terse output'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand count" -l no-header -d 'Suppress the [project] header line printed before per-project output'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand count" -l no-output -d 'Suppress command output'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand count" -s v -l verbose -d 'Verbose output (print all projects, even when no action is taken)'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand count" -l print-not -d 'Print repos that do NOT match (invert selection)'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand count" -l no-stop -d 'Do not stop on errors'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand count" -l short-circuit -d 'Stop at the first negative result instead of processing everything. Off by default. Currently honoured by `check-same`, which exits as soon as one rule is broken instead of evaluating the remaining rules'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand count" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand diff" -s j -l jobs -d 'Number of parallel workers (default: 1; use 0 for num_cpus)' -r
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand diff" -l terse -d 'Terse output'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand diff" -l no-header -d 'Suppress the [project] header line printed before per-project output'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand diff" -l no-output -d 'Suppress command output'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand diff" -s v -l verbose -d 'Verbose output (print all projects, even when no action is taken)'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand diff" -l print-not -d 'Print repos that do NOT match (invert selection)'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand diff" -l no-stop -d 'Do not stop on errors'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand diff" -l short-circuit -d 'Stop at the first negative result instead of processing everything. Off by default. Currently honoured by `check-same`, which exits as soon as one rule is broken instead of evaluating the remaining rules'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand diff" -s h -l help -d 'Print help'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand dirty" -s j -l jobs -d 'Number of parallel workers (default: 1; use 0 for num_cpus)' -r
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand dirty" -l terse -d 'Terse output'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand dirty" -l no-header -d 'Suppress the [project] header line printed before per-project output'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand dirty" -l no-output -d 'Suppress command output'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand dirty" -s v -l verbose -d 'Verbose output (print all projects, even when no action is taken)'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand dirty" -l print-not -d 'Print repos that do NOT match (invert selection)'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand dirty" -l no-stop -d 'Do not stop on errors'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand dirty" -l short-circuit -d 'Stop at the first negative result instead of processing everything. Off by default. Currently honoured by `check-same`, which exits as soon as one rule is broken instead of evaluating the remaining rules'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand dirty" -s h -l help -d 'Print help'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand fetch" -s j -l jobs -d 'Number of parallel workers (default: 1; use 0 for num_cpus)' -r
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand fetch" -l terse -d 'Terse output'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand fetch" -l no-header -d 'Suppress the [project] header line printed before per-project output'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand fetch" -l no-output -d 'Suppress command output'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand fetch" -s v -l verbose -d 'Verbose output (print all projects, even when no action is taken)'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand fetch" -l print-not -d 'Print repos that do NOT match (invert selection)'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand fetch" -l no-stop -d 'Do not stop on errors'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand fetch" -l short-circuit -d 'Stop at the first negative result instead of processing everything. Off by default. Currently honoured by `check-same`, which exits as soon as one rule is broken instead of evaluating the remaining rules'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand fetch" -s h -l help -d 'Print help'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand gc" -s j -l jobs -d 'Number of parallel workers (default: 1; use 0 for num_cpus)' -r
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand gc" -l terse -d 'Terse output'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand gc" -l no-header -d 'Suppress the [project] header line printed before per-project output'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand gc" -l no-output -d 'Suppress command output'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand gc" -s v -l verbose -d 'Verbose output (print all projects, even when no action is taken)'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand gc" -l print-not -d 'Print repos that do NOT match (invert selection)'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand gc" -l no-stop -d 'Do not stop on errors'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand gc" -l short-circuit -d 'Stop at the first negative result instead of processing everything. Off by default. Currently honoured by `check-same`, which exits as soon as one rule is broken instead of evaluating the remaining rules'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand gc" -s h -l help -d 'Print help'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand grep" -s j -l jobs -d 'Number of parallel workers (default: 1; use 0 for num_cpus)' -r
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand grep" -s l -l files -d 'Only show filenames'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand grep" -l terse -d 'Terse output'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand grep" -l no-header -d 'Suppress the [project] header line printed before per-project output'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand grep" -l no-output -d 'Suppress command output'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand grep" -s v -l verbose -d 'Verbose output (print all projects, even when no action is taken)'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand grep" -l print-not -d 'Print repos that do NOT match (invert selection)'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand grep" -l no-stop -d 'Do not stop on errors'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand grep" -l short-circuit -d 'Stop at the first negative result instead of processing everything. Off by default. Currently honoured by `check-same`, which exits as soon as one rule is broken instead of evaluating the remaining rules'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand grep" -s h -l help -d 'Print help'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand last-tag" -s j -l jobs -d 'Number of parallel workers (default: 1; use 0 for num_cpus)' -r
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand last-tag" -l terse -d 'Terse output'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand last-tag" -l no-header -d 'Suppress the [project] header line printed before per-project output'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand last-tag" -l no-output -d 'Suppress command output'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand last-tag" -s v -l verbose -d 'Verbose output (print all projects, even when no action is taken)'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand last-tag" -l print-not -d 'Print repos that do NOT match (invert selection)'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand last-tag" -l no-stop -d 'Do not stop on errors'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand last-tag" -l short-circuit -d 'Stop at the first negative result instead of processing everything. Off by default. Currently honoured by `check-same`, which exits as soon as one rule is broken instead of evaluating the remaining rules'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand last-tag" -s h -l help -d 'Print help'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand list-repos" -s j -l jobs -d 'Number of parallel workers (default: 1; use 0 for num_cpus)' -r
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand list-repos" -l terse -d 'Terse output'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand list-repos" -l no-header -d 'Suppress the [project] header line printed before per-project output'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand list-repos" -l no-output -d 'Suppress command output'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand list-repos" -s v -l verbose -d 'Verbose output (print all projects, even when no action is taken)'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand list-repos" -l print-not -d 'Print repos that do NOT match (invert selection)'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand list-repos" -l no-stop -d 'Do not stop on errors'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand list-repos" -l short-circuit -d 'Stop at the first negative result instead of processing everything. Off by default. Currently honoured by `check-same`, which exits as soon as one rule is broken instead of evaluating the remaining rules'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand list-repos" -s h -l help -d 'Print help'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand list-checks" -s j -l jobs -d 'Number of parallel workers (default: 1; use 0 for num_cpus)' -r
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand list-checks" -l terse -d 'Terse output'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand list-checks" -l no-header -d 'Suppress the [project] header line printed before per-project output'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand list-checks" -l no-output -d 'Suppress command output'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand list-checks" -s v -l verbose -d 'Verbose output (print all projects, even when no action is taken)'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand list-checks" -l print-not -d 'Print repos that do NOT match (invert selection)'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand list-checks" -l no-stop -d 'Do not stop on errors'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand list-checks" -l short-circuit -d 'Stop at the first negative result instead of processing everything. Off by default. Currently honoured by `check-same`, which exits as soon as one rule is broken instead of evaluating the remaining rules'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand list-checks" -s h -l help -d 'Print help'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand log" -l count -d 'Number of commits to show' -r
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand log" -s j -l jobs -d 'Number of parallel workers (default: 1; use 0 for num_cpus)' -r
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand log" -l terse -d 'Terse output'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand log" -l no-header -d 'Suppress the [project] header line printed before per-project output'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand log" -l no-output -d 'Suppress command output'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand log" -s v -l verbose -d 'Verbose output (print all projects, even when no action is taken)'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand log" -l print-not -d 'Print repos that do NOT match (invert selection)'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand log" -l no-stop -d 'Do not stop on errors'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand log" -l short-circuit -d 'Stop at the first negative result instead of processing everything. Off by default. Currently honoured by `check-same`, which exits as soon as one rule is broken instead of evaluating the remaining rules'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand log" -s h -l help -d 'Print help'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand prune" -s j -l jobs -d 'Number of parallel workers (default: 1; use 0 for num_cpus)' -r
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand prune" -l terse -d 'Terse output'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand prune" -l no-header -d 'Suppress the [project] header line printed before per-project output'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand prune" -l no-output -d 'Suppress command output'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand prune" -s v -l verbose -d 'Verbose output (print all projects, even when no action is taken)'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand prune" -l print-not -d 'Print repos that do NOT match (invert selection)'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand prune" -l no-stop -d 'Do not stop on errors'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand prune" -l short-circuit -d 'Stop at the first negative result instead of processing everything. Off by default. Currently honoured by `check-same`, which exits as soon as one rule is broken instead of evaluating the remaining rules'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand prune" -s h -l help -d 'Print help'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand pull" -s j -l jobs -d 'Number of parallel workers (default: 1; use 0 for num_cpus)' -r
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand pull" -l quiet -d 'Pass --quiet to git pull'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand pull" -l terse -d 'Terse output'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand pull" -l no-header -d 'Suppress the [project] header line printed before per-project output'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand pull" -l no-output -d 'Suppress command output'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand pull" -s v -l verbose -d 'Verbose output (print all projects, even when no action is taken)'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand pull" -l print-not -d 'Print repos that do NOT match (invert selection)'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand pull" -l no-stop -d 'Do not stop on errors'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand pull" -l short-circuit -d 'Stop at the first negative result instead of processing everything. Off by default. Currently honoured by `check-same`, which exits as soon as one rule is broken instead of evaluating the remaining rules'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand pull" -s h -l help -d 'Print help'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand push" -s j -l jobs -d 'Number of parallel workers (default: 1; use 0 for num_cpus)' -r
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand push" -l terse -d 'Terse output'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand push" -l no-header -d 'Suppress the [project] header line printed before per-project output'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand push" -l no-output -d 'Suppress command output'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand push" -s v -l verbose -d 'Verbose output (print all projects, even when no action is taken)'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand push" -l print-not -d 'Print repos that do NOT match (invert selection)'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand push" -l no-stop -d 'Do not stop on errors'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand push" -l short-circuit -d 'Stop at the first negative result instead of processing everything. Off by default. Currently honoured by `check-same`, which exits as soon as one rule is broken instead of evaluating the remaining rules'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand push" -s h -l help -d 'Print help'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand remote" -s j -l jobs -d 'Number of parallel workers (default: 1; use 0 for num_cpus)' -r
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand remote" -l terse -d 'Terse output'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand remote" -l no-header -d 'Suppress the [project] header line printed before per-project output'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand remote" -l no-output -d 'Suppress command output'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand remote" -s v -l verbose -d 'Verbose output (print all projects, even when no action is taken)'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand remote" -l print-not -d 'Print repos that do NOT match (invert selection)'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand remote" -l no-stop -d 'Do not stop on errors'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand remote" -l short-circuit -d 'Stop at the first negative result instead of processing everything. Off by default. Currently honoured by `check-same`, which exits as soon as one rule is broken instead of evaluating the remaining rules'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand remote" -s h -l help -d 'Print help'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand reset" -s j -l jobs -d 'Number of parallel workers (default: 1; use 0 for num_cpus)' -r
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand reset" -l terse -d 'Terse output'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand reset" -l no-header -d 'Suppress the [project] header line printed before per-project output'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand reset" -l no-output -d 'Suppress command output'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand reset" -s v -l verbose -d 'Verbose output (print all projects, even when no action is taken)'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand reset" -l print-not -d 'Print repos that do NOT match (invert selection)'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand reset" -l no-stop -d 'Do not stop on errors'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand reset" -l short-circuit -d 'Stop at the first negative result instead of processing everything. Off by default. Currently honoured by `check-same`, which exits as soon as one rule is broken instead of evaluating the remaining rules'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand reset" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand run" -s j -l jobs -d 'Number of parallel workers (default: 1; use 0 for num_cpus)' -r
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand run" -l terse -d 'Terse output'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand run" -l no-header -d 'Suppress the [project] header line printed before per-project output'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand run" -l no-output -d 'Suppress command output'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand run" -s v -l verbose -d 'Verbose output (print all projects, even when no action is taken)'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand run" -l print-not -d 'Print repos that do NOT match (invert selection)'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand run" -l no-stop -d 'Do not stop on errors'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand run" -l short-circuit -d 'Stop at the first negative result instead of processing everything. Off by default. Currently honoured by `check-same`, which exits as soon as one rule is broken instead of evaluating the remaining rules'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand run" -s h -l help -d 'Print help'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand size" -s j -l jobs -d 'Number of parallel workers (default: 1; use 0 for num_cpus)' -r
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand size" -l terse -d 'Terse output'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand size" -l no-header -d 'Suppress the [project] header line printed before per-project output'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand size" -l no-output -d 'Suppress command output'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand size" -s v -l verbose -d 'Verbose output (print all projects, even when no action is taken)'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand size" -l print-not -d 'Print repos that do NOT match (invert selection)'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand size" -l no-stop -d 'Do not stop on errors'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand size" -l short-circuit -d 'Stop at the first negative result instead of processing everything. Off by default. Currently honoured by `check-same`, which exits as soon as one rule is broken instead of evaluating the remaining rules'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand size" -s h -l help -d 'Print help'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand stash" -s j -l jobs -d 'Number of parallel workers (default: 1; use 0 for num_cpus)' -r
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand stash" -l terse -d 'Terse output'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand stash" -l no-header -d 'Suppress the [project] header line printed before per-project output'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand stash" -l no-output -d 'Suppress command output'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand stash" -s v -l verbose -d 'Verbose output (print all projects, even when no action is taken)'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand stash" -l print-not -d 'Print repos that do NOT match (invert selection)'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand stash" -l no-stop -d 'Do not stop on errors'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand stash" -l short-circuit -d 'Stop at the first negative result instead of processing everything. Off by default. Currently honoured by `check-same`, which exits as soon as one rule is broken instead of evaluating the remaining rules'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand stash" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand status" -s j -l jobs -d 'Number of parallel workers (default: 1; use 0 for num_cpus)' -r
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand status" -l terse -d 'Terse output'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand status" -l no-header -d 'Suppress the [project] header line printed before per-project output'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand status" -l no-output -d 'Suppress command output'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand status" -s v -l verbose -d 'Verbose output (print all projects, even when no action is taken)'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand status" -l print-not -d 'Print repos that do NOT match (invert selection)'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand status" -l no-stop -d 'Do not stop on errors'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand status" -l short-circuit -d 'Stop at the first negative result instead of processing everything. Off by default. Currently honoured by `check-same`, which exits as soon as one rule is broken instead of evaluating the remaining rules'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand status" -s h -l help -d 'Print help'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand submodule-update" -s j -l jobs -d 'Number of parallel workers (default: 1; use 0 for num_cpus)' -r
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand submodule-update" -l terse -d 'Terse output'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand submodule-update" -l no-header -d 'Suppress the [project] header line printed before per-project output'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand submodule-update" -l no-output -d 'Suppress command output'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand submodule-update" -s v -l verbose -d 'Verbose output (print all projects, even when no action is taken)'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand submodule-update" -l print-not -d 'Print repos that do NOT match (invert selection)'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand submodule-update" -l no-stop -d 'Do not stop on errors'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand submodule-update" -l short-circuit -d 'Stop at the first negative result instead of processing everything. Off by default. Currently honoured by `check-same`, which exits as soon as one rule is broken instead of evaluating the remaining rules'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand submodule-update" -s h -l help -d 'Print help'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand tag" -s j -l jobs -d 'Number of parallel workers (default: 1; use 0 for num_cpus)' -r
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand tag" -l terse -d 'Terse output'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand tag" -l no-header -d 'Suppress the [project] header line printed before per-project output'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand tag" -l no-output -d 'Suppress command output'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand tag" -s v -l verbose -d 'Verbose output (print all projects, even when no action is taken)'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand tag" -l print-not -d 'Print repos that do NOT match (invert selection)'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand tag" -l no-stop -d 'Do not stop on errors'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand tag" -l short-circuit -d 'Stop at the first negative result instead of processing everything. Off by default. Currently honoured by `check-same`, which exits as soon as one rule is broken instead of evaluating the remaining rules'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand tag" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand version" -s j -l jobs -d 'Number of parallel workers (default: 1; use 0 for num_cpus)' -r
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand version" -l terse -d 'Terse output'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand version" -l no-header -d 'Suppress the [project] header line printed before per-project output'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand version" -l no-output -d 'Suppress command output'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand version" -s v -l verbose -d 'Verbose output (print all projects, even when no action is taken)'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand version" -l print-not -d 'Print repos that do NOT match (invert selection)'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand version" -l no-stop -d 'Do not stop on errors'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand version" -l short-circuit -d 'Stop at the first negative result instead of processing everything. Off by default. Currently honoured by `check-same`, which exits as soon as one rule is broken instead of evaluating the remaining rules'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand version" -s h -l help -d 'Print help'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand help; and not __fish_seen_subcommand_from age authors blame branch build checkout check-same clean commit complete config config-example count diff dirty fetch gc grep last-tag list-repos list-checks log prune pull push remote reset run size stash status submodule-update tag version help" -f -a "age" -d 'Show the age of the last commit per repo'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand help; and not __fish_seen_subcommand_from age authors blame branch build checkout check-same clean commit complete config config-example count diff dirty fetch gc grep last-tag list-repos list-checks log prune pull push remote reset run size stash status submodule-update tag version help" -f -a "authors" -d 'Show unique commit authors per repo'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand help; and not __fish_seen_subcommand_from age authors blame branch build checkout check-same clean commit complete config config-example count diff dirty fetch gc grep last-tag list-repos list-checks log prune pull push remote reset run size stash status submodule-update tag version help" -f -a "blame" -d 'Run git blame on a file across all repositories'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand help; and not __fish_seen_subcommand_from age authors blame branch build checkout check-same clean commit complete config config-example count diff dirty fetch gc grep last-tag list-repos list-checks log prune pull push remote reset run size stash status submodule-update tag version help" -f -a "branch" -d 'Branch operations'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand help; and not __fish_seen_subcommand_from age authors blame branch build checkout check-same clean commit complete config config-example count diff dirty fetch gc grep last-tag list-repos list-checks log prune pull push remote reset run size stash status submodule-update tag version help" -f -a "build" -d 'Build projects'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand help; and not __fish_seen_subcommand_from age authors blame branch build checkout check-same clean commit complete config config-example count diff dirty fetch gc grep last-tag list-repos list-checks log prune pull push remote reset run size stash status submodule-update tag version help" -f -a "checkout" -d 'Checkout a branch across all repositories'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand help; and not __fish_seen_subcommand_from age authors blame branch build checkout check-same clean commit complete config config-example count diff dirty fetch gc grep last-tag list-repos list-checks log prune pull push remote reset run size stash status submodule-update tag version help" -f -a "check-same" -d 'Check that files declared in ~/.config/rsmultigit/config.toml are identical across repos'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand help; and not __fish_seen_subcommand_from age authors blame branch build checkout check-same clean commit complete config config-example count diff dirty fetch gc grep last-tag list-repos list-checks log prune pull push remote reset run size stash status submodule-update tag version help" -f -a "clean" -d 'Clean repositories'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand help; and not __fish_seen_subcommand_from age authors blame branch build checkout check-same clean commit complete config config-example count diff dirty fetch gc grep last-tag list-repos list-checks log prune pull push remote reset run size stash status submodule-update tag version help" -f -a "commit" -d 'Commit all changes across all repositories'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand help; and not __fish_seen_subcommand_from age authors blame branch build checkout check-same clean commit complete config config-example count diff dirty fetch gc grep last-tag list-repos list-checks log prune pull push remote reset run size stash status submodule-update tag version help" -f -a "complete" -d 'Generate shell completion scripts'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand help; and not __fish_seen_subcommand_from age authors blame branch build checkout check-same clean commit complete config config-example count diff dirty fetch gc grep last-tag list-repos list-checks log prune pull push remote reset run size stash status submodule-update tag version help" -f -a "config" -d 'Show a git config value across all repos'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand help; and not __fish_seen_subcommand_from age authors blame branch build checkout check-same clean commit complete config config-example count diff dirty fetch gc grep last-tag list-repos list-checks log prune pull push remote reset run size stash status submodule-update tag version help" -f -a "config-example" -d 'Print a sample rsmultigit config.toml to stdout. Redirect to ~/.config/rsmultigit/config.toml to bootstrap a new install'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand help; and not __fish_seen_subcommand_from age authors blame branch build checkout check-same clean commit complete config config-example count diff dirty fetch gc grep last-tag list-repos list-checks log prune pull push remote reset run size stash status submodule-update tag version help" -f -a "count" -d 'Count repositories matching a condition'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand help; and not __fish_seen_subcommand_from age authors blame branch build checkout check-same clean commit complete config config-example count diff dirty fetch gc grep last-tag list-repos list-checks log prune pull push remote reset run size stash status submodule-update tag version help" -f -a "diff" -d 'Show diff for all repositories'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand help; and not __fish_seen_subcommand_from age authors blame branch build checkout check-same clean commit complete config config-example count diff dirty fetch gc grep last-tag list-repos list-checks log prune pull push remote reset run size stash status submodule-update tag version help" -f -a "dirty" -d 'Show dirty repositories'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand help; and not __fish_seen_subcommand_from age authors blame branch build checkout check-same clean commit complete config config-example count diff dirty fetch gc grep last-tag list-repos list-checks log prune pull push remote reset run size stash status submodule-update tag version help" -f -a "fetch" -d 'Fetch from origin for all repositories'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand help; and not __fish_seen_subcommand_from age authors blame branch build checkout check-same clean commit complete config config-example count diff dirty fetch gc grep last-tag list-repos list-checks log prune pull push remote reset run size stash status submodule-update tag version help" -f -a "gc" -d 'Run git garbage collection'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand help; and not __fish_seen_subcommand_from age authors blame branch build checkout check-same clean commit complete config config-example count diff dirty fetch gc grep last-tag list-repos list-checks log prune pull push remote reset run size stash status submodule-update tag version help" -f -a "grep" -d 'Grep across all repositories'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand help; and not __fish_seen_subcommand_from age authors blame branch build checkout check-same clean commit complete config config-example count diff dirty fetch gc grep last-tag list-repos list-checks log prune pull push remote reset run size stash status submodule-update tag version help" -f -a "last-tag" -d 'Show the most recent tag per repo'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand help; and not __fish_seen_subcommand_from age authors blame branch build checkout check-same clean commit complete config config-example count diff dirty fetch gc grep last-tag list-repos list-checks log prune pull push remote reset run size stash status submodule-update tag version help" -f -a "list-repos" -d 'Print the path of every configured repo, one per line (no header by default). Pass --verbose to also emit the [project] header for each entry'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand help; and not __fish_seen_subcommand_from age authors blame branch build checkout check-same clean commit complete config config-example count diff dirty fetch gc grep last-tag list-repos list-checks log prune pull push remote reset run size stash status submodule-update tag version help" -f -a "list-checks" -d 'Print the name of every check rule defined in the config, one per line. Intended for use in shell-completion scripts. All rules are listed, including those with `enabled = false`'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand help; and not __fish_seen_subcommand_from age authors blame branch build checkout check-same clean commit complete config config-example count diff dirty fetch gc grep last-tag list-repos list-checks log prune pull push remote reset run size stash status submodule-update tag version help" -f -a "log" -d 'Show recent commits'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand help; and not __fish_seen_subcommand_from age authors blame branch build checkout check-same clean commit complete config config-example count diff dirty fetch gc grep last-tag list-repos list-checks log prune pull push remote reset run size stash status submodule-update tag version help" -f -a "prune" -d 'Prune stale remote-tracking branches'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand help; and not __fish_seen_subcommand_from age authors blame branch build checkout check-same clean commit complete config config-example count diff dirty fetch gc grep last-tag list-repos list-checks log prune pull push remote reset run size stash status submodule-update tag version help" -f -a "pull" -d 'Pull all repositories'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand help; and not __fish_seen_subcommand_from age authors blame branch build checkout check-same clean commit complete config config-example count diff dirty fetch gc grep last-tag list-repos list-checks log prune pull push remote reset run size stash status submodule-update tag version help" -f -a "push" -d 'Push all repositories'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand help; and not __fish_seen_subcommand_from age authors blame branch build checkout check-same clean commit complete config config-example count diff dirty fetch gc grep last-tag list-repos list-checks log prune pull push remote reset run size stash status submodule-update tag version help" -f -a "remote" -d 'Show remote URLs'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand help; and not __fish_seen_subcommand_from age authors blame branch build checkout check-same clean commit complete config config-example count diff dirty fetch gc grep last-tag list-repos list-checks log prune pull push remote reset run size stash status submodule-update tag version help" -f -a "reset" -d 'Reset operations'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand help; and not __fish_seen_subcommand_from age authors blame branch build checkout check-same clean commit complete config config-example count diff dirty fetch gc grep last-tag list-repos list-checks log prune pull push remote reset run size stash status submodule-update tag version help" -f -a "run" -d 'Run an arbitrary command across all repositories'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand help; and not __fish_seen_subcommand_from age authors blame branch build checkout check-same clean commit complete config config-example count diff dirty fetch gc grep last-tag list-repos list-checks log prune pull push remote reset run size stash status submodule-update tag version help" -f -a "size" -d 'Show the size of the .git directory per repo'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand help; and not __fish_seen_subcommand_from age authors blame branch build checkout check-same clean commit complete config config-example count diff dirty fetch gc grep last-tag list-repos list-checks log prune pull push remote reset run size stash status submodule-update tag version help" -f -a "stash" -d 'Stash operations'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand help; and not __fish_seen_subcommand_from age authors blame branch build checkout check-same clean commit complete config config-example count diff dirty fetch gc grep last-tag list-repos list-checks log prune pull push remote reset run size stash status submodule-update tag version help" -f -a "status" -d 'Show status of repositories'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand help; and not __fish_seen_subcommand_from age authors blame branch build checkout check-same clean commit complete config config-example count diff dirty fetch gc grep last-tag list-repos list-checks log prune pull push remote reset run size stash status submodule-update tag version help" -f -a "submodule-update" -d 'Update submodules recursively'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand help; and not __fish_seen_subcommand_from age authors blame branch build checkout check-same clean commit complete config config-example count diff dirty fetch gc grep last-tag list-repos list-checks log prune pull push remote reset run size stash status submodule-update tag version help" -f -a "tag" -d 'List tags'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand help; and not __fish_seen_subcommand_from age authors blame branch build checkout check-same clean commit complete config config-example count diff dirty fetch gc grep last-tag list-repos list-checks log prune pull push remote reset run size stash status submodule-update tag version help" -f -a "version" -d 'Print version information'
complete -c rsmultigit -n "__fish_rsmultigit_using_subcommand help; and not __fish_seen_subcommand_from age authors blame branch build checkout check-same clean commit complete config config-example count diff dirty fetch gc grep last-tag list-repos list-checks log prune pull push remote reset run size stash status submodule-update tag version help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
