complete -c schnauzer -s p -l path -d '<FILE> - Path to file'
complete -c schnauzer -s h -l help -d '- Help'
complete -c schnauzer -s a -l arch -d '<NAME> - Filter architecture by name. Supported archs: x86_64, x86_64h, arm64 and arm64e'
complete -c schnauzer -l short -d '- Display only identifying fields'
complete -c schnauzer -l noidx -d -\ Don\'t\ display\ indices\ of\ items
complete -c schnauzer -s p -l path -d '<FILE> - Path to file'
complete -c schnauzer -s h -l help -d '- Help'
complete -c schnauzer -s a -l arch -d '<NAME> - Filter architecture by name. Supported archs: x86_64, x86_64h, arm64 and arm64e'
complete -c schnauzer -l short -d '- Display only identifying fields'
complete -c schnauzer -l noidx -d -\ Don\'t\ display\ indices\ of\ items
complete -c schnauzer -s p -l path -d '<FILE> - Path to file'
complete -c schnauzer -s h -l help -d '- Help'
complete -c schnauzer -s a -l arch -d '<NAME> - Filter architecture by name. Supported archs: x86_64, x86_64h, arm64 and arm64e'
complete -c schnauzer -l short -d '- Display only identifying fields'
complete -c schnauzer -l noidx -d -\ Don\'t\ display\ indices\ of\ items
complete -c schnauzer -s p -l path -d '<FILE> - Path to file'
complete -c schnauzer -s h -l help -d '- Help'
complete -c schnauzer -s a -l arch -d '<NAME> - Filter architecture by name. Supported archs: x86_64, x86_64h, arm64 and arm64e'
complete -c schnauzer -l segs -d '- Display only segments'
complete -c schnauzer -l sects -d '- Display only sections'
complete -c schnauzer -l short -d '- Display only identifying fields'
complete -c schnauzer -l noidx -d -\ Don\'t\ display\ indices\ of\ items
complete -c schnauzer -s p -l path -d '<FILE> - Path to file'
complete -c schnauzer -s h -l help -d '- Help'
complete -c schnauzer -s a -l arch -d '<NAME> - Filter architecture by name. Supported archs: x86_64, x86_64h, arm64 and arm64e'
complete -c schnauzer -s p -l path -d '<FILE> - Path to file'
complete -c schnauzer -s h -l help -d '- Help'
complete -c schnauzer -s a -l arch -d '<NAME> - Filter architecture by name. Supported archs: x86_64, x86_64h, arm64 and arm64e'
complete -c schnauzer -l short -d '- Display only identifying fields'
complete -c schnauzer -l noidx -d -\ Don\'t\ display\ indices\ of\ items
complete -c schnauzer -s p -l path -d '<FILE> - Path to file'
complete -c schnauzer -s h -l help -d '- Help'
complete -c schnauzer -s a -l arch -d '<NAME> - Filter architecture by name. Supported archs: x86_64, x86_64h, arm64 and arm64e'
complete -c schnauzer -s p -l path -d '<FILE> - Path to file'
complete -c schnauzer -s h -l help -d '- Help'
complete -c schnauzer -s a -l arch -d '<NAME> - Filter architecture by name. Supported archs: x86_64, x86_64h, arm64 and arm64e'
complete -c schnauzer -l short -d '- Display only identifying fields'
complete -c schnauzer -l noidx -d -\ Don\'t\ display\ indices\ of\ items
complete -c schnauzer -s p -l path -d '<FILE> - Path to file'
complete -c schnauzer -s h -l help -d '- Help'
complete -c schnauzer -s a -l arch -d '<NAME> - Filter architecture by name. Supported archs: x86_64, x86_64h, arm64 and arm64e'
complete -c schnauzer -s s -l sect -d '<segname sectname> - Section to display'
