complete -c scrubcsv -s h -l help -d 'Prints help information'
complete -c scrubcsv -s q -l quiet -d 'Do not print performance information'
complete -c scrubcsv -l replace-newlines -d 'Replace LF and CRLF sequences in values with spaces. This should improve'
complete -c scrubcsv -l trim-whitespace -d 'Remove whitespace at beginning and end of each cell'
complete -c scrubcsv -n __fish_no_arguments -s V -l version -d 'Prints version information'
complete -c scrubcsv -l clean-column-names -d '<CLEANER_TYPE>'
complete -c scrubcsv -s d -l delimiter -d '<CHAR>'
complete -c scrubcsv -l drop-row-if-null -d '<COL>...'
complete -c scrubcsv -s n -l null -d '<NULL_REGEX>'
complete -c scrubcsv -l quote -d '<CHAR>'
complete -c scrubcsv -l reserve-column-names -d '<reserve-column-names>'
