# searchfs
# Autogenerated from man page /me/.local/share/man/man1/searchfs.1
complete -c searchfs -s l -d 'List all mounted filesystems that support catalog search'
complete -c searchfs -s v -d 'Specify volume to search, either by mount path (e. g'
complete -c searchfs -s d -d 'Match directories only'
complete -c searchfs -s f -d 'Match files only'
complete -c searchfs -s e -d 'Exact filename matches only'
complete -c searchfs -s s -d 'Case sensitive matching'
complete -c searchfs -s p -d 'Don\'t match file system objects that are inside a package'
complete -c searchfs -s i -d 'Don\'t match invisible file system objects (that is, objects with the Finder a…'
complete -c searchfs -s x -d 'Don\'t match any file system objects that are within an "inappropriate" direct…'
complete -c searchfs -s n -d 'Show all file system objects that do *not* match the search term'
complete -c searchfs -s m -d 'Terminate when the specified number of matching items has been found'
complete -c searchfs -s o -d 'Print program version and exit'
complete -c searchfs -s h -d 'Print usage and exit'


