complete -c "shot-scraper" -l "version" -d "Show the version and exit."
complete -c "shot-scraper" -l "help" -d "Show this message and exit."
complete -f -c "shot-scraper" -n "__fish_use_subcommand" -a "shot" -d "Take a single screenshot of a page or portion of a page."
complete -f -c "shot-scraper" -n "__fish_use_subcommand" -a "accessibility" -d "Dump the Chromium accessibility tree for the specifed page"
complete -f -c "shot-scraper" -n "__fish_use_subcommand" -a "auth" -d "Open a browser so user can manually authenticate with..."
complete -f -c "shot-scraper" -n "__fish_use_subcommand" -a "har" -d "Record a HAR file for the specified page"
complete -f -c "shot-scraper" -n "__fish_use_subcommand" -a "html" -d "Output the final HTML of the specified page"
complete -f -c "shot-scraper" -n "__fish_use_subcommand" -a "install" -d "Install the Playwright browser needed by this tool."
complete -f -c "shot-scraper" -n "__fish_use_subcommand" -a "javascript" -d "Execute JavaScript against the page and return the..."
complete -f -c "shot-scraper" -n "__fish_use_subcommand" -a "multi" -d "Take multiple screenshots, defined by a YAML file"
complete -f -c "shot-scraper" -n "__fish_use_subcommand" -a "pdf" -d "Create a PDF of the specified page"
complete -c "shot-scraper" -n "__fish_seen_subcommand_from shot" -l "version" -d "Show the version and exit."
complete -c "shot-scraper" -n "__fish_seen_subcommand_from shot" -l "help" -d "Show this message and exit."
complete -c "shot-scraper" -n "__fish_seen_subcommand_from accessibility" -l "version" -d "Show the version and exit."
complete -c "shot-scraper" -n "__fish_seen_subcommand_from accessibility" -l "help" -d "Show this message and exit."
complete -c "shot-scraper" -n "__fish_seen_subcommand_from auth" -l "version" -d "Show the version and exit."
complete -c "shot-scraper" -n "__fish_seen_subcommand_from auth" -l "help" -d "Show this message and exit."
complete -c "shot-scraper" -n "__fish_seen_subcommand_from har" -l "version" -d "Show the version and exit."
complete -c "shot-scraper" -n "__fish_seen_subcommand_from har" -l "help" -d "Show this message and exit."
complete -c "shot-scraper" -n "__fish_seen_subcommand_from html" -l "version" -d "Show the version and exit."
complete -c "shot-scraper" -n "__fish_seen_subcommand_from html" -l "help" -d "Show this message and exit."
complete -c "shot-scraper" -n "__fish_seen_subcommand_from install" -l "version" -d "Show the version and exit."
complete -c "shot-scraper" -n "__fish_seen_subcommand_from install" -l "help" -d "Show this message and exit."
complete -c "shot-scraper" -n "__fish_seen_subcommand_from javascript" -l "version" -d "Show the version and exit."
complete -c "shot-scraper" -n "__fish_seen_subcommand_from javascript" -l "help" -d "Show this message and exit."
complete -c "shot-scraper" -n "__fish_seen_subcommand_from multi" -l "version" -d "Show the version and exit."
complete -c "shot-scraper" -n "__fish_seen_subcommand_from multi" -l "help" -d "Show this message and exit."
complete -c "shot-scraper" -n "__fish_seen_subcommand_from pdf" -l "version" -d "Show the version and exit."
complete -c "shot-scraper" -n "__fish_seen_subcommand_from pdf" -l "help" -d "Show this message and exit."
complete -c "shot-scraper" -n "__fish_seen_subcommand_from shot" -s "a" -l "auth" -d "Path to JSON authentication context file"
complete -c "shot-scraper" -n "__fish_seen_subcommand_from shot" -s "w" -l "width" -d "Width of browser window, defaults to 1280"
complete -c "shot-scraper" -n "__fish_seen_subcommand_from shot" -s "h" -l "height" -d "Height of browser window and shot - defaults to the full height of the page"
complete -c "shot-scraper" -n "__fish_seen_subcommand_from shot" -s "o" -l "output"
complete -c "shot-scraper" -n "__fish_seen_subcommand_from shot" -s "s" -l "selector" -d "Take shot of first element matching this CSS selector"
complete -c "shot-scraper" -n "__fish_seen_subcommand_from shot" -l "selector-all" -d "Take shot of all elements matching this CSS selector"
complete -c "shot-scraper" -n "__fish_seen_subcommand_from shot" -l "js-selector" -d "Take shot of first element matching this JS (el) expression"
complete -c "shot-scraper" -n "__fish_seen_subcommand_from shot" -l "js-selector-all" -d "Take shot of all elements matching this JS (el) expression"
complete -c "shot-scraper" -n "__fish_seen_subcommand_from shot" -s "p" -l "padding" -d "When using selectors, add this much padding in pixels"
complete -c "shot-scraper" -n "__fish_seen_subcommand_from shot" -s "j" -l "javascript" -d "Execute this JS prior to taking the shot"
complete -c "shot-scraper" -n "__fish_seen_subcommand_from shot" -l "scale-factor" -d "Device scale factor. Cannot be used together with '--retina'."
complete -c "shot-scraper" -n "__fish_seen_subcommand_from shot" -l "retina" -d "Use device scale factor of 2. Cannot be used together with '--scale-factor'."
complete -c "shot-scraper" -n "__fish_seen_subcommand_from shot" -l "omit-background" -d "Omit the default browser background from the shot, making it possible take advantage of transparency. Does not work with JPEGs or when using --quality."
complete -c "shot-scraper" -n "__fish_seen_subcommand_from shot" -l "quality" -d "Save as JPEG with this quality, e.g. 80"
complete -c "shot-scraper" -n "__fish_seen_subcommand_from shot" -l "wait" -d "Wait this many milliseconds before taking the screenshot"
complete -c "shot-scraper" -n "__fish_seen_subcommand_from shot" -l "wait-for" -d "Wait until this JS expression returns true"
complete -c "shot-scraper" -n "__fish_seen_subcommand_from shot" -l "timeout" -d "Wait this many milliseconds before failing"
complete -c "shot-scraper" -n "__fish_seen_subcommand_from shot" -s "i" -l "interactive" -d "Interact with the page in a browser before taking the shot"
complete -c "shot-scraper" -n "__fish_seen_subcommand_from shot" -l "devtools" -d "Interact mode with developer tools"
complete -c "shot-scraper" -n "__fish_seen_subcommand_from shot" -l "log-requests" -d "Log details of all requests to this file"
complete -c "shot-scraper" -n "__fish_seen_subcommand_from shot" -l "log-console" -d "Write console.log() to stderr"
complete -c "shot-scraper" -n "__fish_seen_subcommand_from shot" -s "b" -l "browser" -d "Which browser to use" -xa "chromium firefox webkit chrome chrome-beta"
complete -c "shot-scraper" -n "__fish_seen_subcommand_from shot" -l "browser-arg" -d "Additional arguments to pass to the browser"
complete -c "shot-scraper" -n "__fish_seen_subcommand_from shot" -l "user-agent" -d "User-Agent header to use"
complete -c "shot-scraper" -n "__fish_seen_subcommand_from shot" -l "reduced-motion" -d "Emulate 'prefers-reduced-motion' media feature"
complete -c "shot-scraper" -n "__fish_seen_subcommand_from shot" -l "fail" -d "Fail with an error code if a page returns an HTTP error"
complete -c "shot-scraper" -n "__fish_seen_subcommand_from shot" -l "skip" -d "Skip pages that return HTTP errors"
complete -c "shot-scraper" -n "__fish_seen_subcommand_from shot" -l "bypass-csp" -d "Bypass Content-Security-Policy"
complete -c "shot-scraper" -n "__fish_seen_subcommand_from shot" -l "silent" -d "Do not output any messages"
complete -c "shot-scraper" -n "__fish_seen_subcommand_from shot" -l "auth-password" -d "Password for HTTP Basic authentication"
complete -c "shot-scraper" -n "__fish_seen_subcommand_from shot" -l "auth-username" -d "Username for HTTP Basic authentication"
complete -c "shot-scraper" -n "__fish_seen_subcommand_from shot" -l "help" -d "Show this message and exit."
complete -c "shot-scraper" -n "__fish_seen_subcommand_from accessibility" -s "a" -l "auth" -d "Path to JSON authentication context file"
complete -c "shot-scraper" -n "__fish_seen_subcommand_from accessibility" -s "o" -l "output"
complete -c "shot-scraper" -n "__fish_seen_subcommand_from accessibility" -s "j" -l "javascript" -d "Execute this JS prior to taking the snapshot"
complete -c "shot-scraper" -n "__fish_seen_subcommand_from accessibility" -l "timeout" -d "Wait this many milliseconds before failing"
complete -c "shot-scraper" -n "__fish_seen_subcommand_from accessibility" -l "log-console" -d "Write console.log() to stderr"
complete -c "shot-scraper" -n "__fish_seen_subcommand_from accessibility" -l "fail" -d "Fail with an error code if a page returns an HTTP error"
complete -c "shot-scraper" -n "__fish_seen_subcommand_from accessibility" -l "skip" -d "Skip pages that return HTTP errors"
complete -c "shot-scraper" -n "__fish_seen_subcommand_from accessibility" -l "bypass-csp" -d "Bypass Content-Security-Policy"
complete -c "shot-scraper" -n "__fish_seen_subcommand_from accessibility" -l "auth-password" -d "Password for HTTP Basic authentication"
complete -c "shot-scraper" -n "__fish_seen_subcommand_from accessibility" -l "auth-username" -d "Username for HTTP Basic authentication"
complete -c "shot-scraper" -n "__fish_seen_subcommand_from accessibility" -l "help" -d "Show this message and exit."
complete -c "shot-scraper" -n "__fish_seen_subcommand_from auth" -s "b" -l "browser" -d "Which browser to use" -xa "chromium firefox webkit chrome chrome-beta"
complete -c "shot-scraper" -n "__fish_seen_subcommand_from auth" -l "browser-arg" -d "Additional arguments to pass to the browser"
complete -c "shot-scraper" -n "__fish_seen_subcommand_from auth" -l "user-agent" -d "User-Agent header to use"
complete -c "shot-scraper" -n "__fish_seen_subcommand_from auth" -l "devtools" -d "Open browser DevTools"
complete -c "shot-scraper" -n "__fish_seen_subcommand_from auth" -l "log-console" -d "Write console.log() to stderr"
complete -c "shot-scraper" -n "__fish_seen_subcommand_from auth" -l "help" -d "Show this message and exit."
complete -c "shot-scraper" -n "__fish_seen_subcommand_from har" -s "z" -l "zip" -d "Save as a .har.zip file"
complete -c "shot-scraper" -n "__fish_seen_subcommand_from har" -s "a" -l "auth" -d "Path to JSON authentication context file"
complete -c "shot-scraper" -n "__fish_seen_subcommand_from har" -s "o" -l "output" -d "HAR filename"
complete -c "shot-scraper" -n "__fish_seen_subcommand_from har" -l "wait" -d "Wait this many milliseconds before taking the screenshot"
complete -c "shot-scraper" -n "__fish_seen_subcommand_from har" -l "wait-for" -d "Wait until this JS expression returns true"
complete -c "shot-scraper" -n "__fish_seen_subcommand_from har" -s "j" -l "javascript" -d "Execute this JavaScript on the page"
complete -c "shot-scraper" -n "__fish_seen_subcommand_from har" -l "timeout" -d "Wait this many milliseconds before failing"
complete -c "shot-scraper" -n "__fish_seen_subcommand_from har" -l "log-console" -d "Write console.log() to stderr"
complete -c "shot-scraper" -n "__fish_seen_subcommand_from har" -l "fail" -d "Fail with an error code if a page returns an HTTP error"
complete -c "shot-scraper" -n "__fish_seen_subcommand_from har" -l "skip" -d "Skip pages that return HTTP errors"
complete -c "shot-scraper" -n "__fish_seen_subcommand_from har" -l "bypass-csp" -d "Bypass Content-Security-Policy"
complete -c "shot-scraper" -n "__fish_seen_subcommand_from har" -l "auth-password" -d "Password for HTTP Basic authentication"
complete -c "shot-scraper" -n "__fish_seen_subcommand_from har" -l "auth-username" -d "Username for HTTP Basic authentication"
complete -c "shot-scraper" -n "__fish_seen_subcommand_from har" -l "help" -d "Show this message and exit."
complete -c "shot-scraper" -n "__fish_seen_subcommand_from html" -s "a" -l "auth" -d "Path to JSON authentication context file"
complete -c "shot-scraper" -n "__fish_seen_subcommand_from html" -s "o" -l "output"
complete -c "shot-scraper" -n "__fish_seen_subcommand_from html" -s "j" -l "javascript" -d "Execute this JS prior to saving the HTML"
complete -c "shot-scraper" -n "__fish_seen_subcommand_from html" -s "s" -l "selector" -d "Return outerHTML of first element matching this CSS selector"
complete -c "shot-scraper" -n "__fish_seen_subcommand_from html" -l "wait" -d "Wait this many milliseconds before taking the snapshot"
complete -c "shot-scraper" -n "__fish_seen_subcommand_from html" -l "log-console" -d "Write console.log() to stderr"
complete -c "shot-scraper" -n "__fish_seen_subcommand_from html" -s "b" -l "browser" -d "Which browser to use" -xa "chromium firefox webkit chrome chrome-beta"
complete -c "shot-scraper" -n "__fish_seen_subcommand_from html" -l "browser-arg" -d "Additional arguments to pass to the browser"
complete -c "shot-scraper" -n "__fish_seen_subcommand_from html" -l "user-agent" -d "User-Agent header to use"
complete -c "shot-scraper" -n "__fish_seen_subcommand_from html" -l "fail" -d "Fail with an error code if a page returns an HTTP error"
complete -c "shot-scraper" -n "__fish_seen_subcommand_from html" -l "skip" -d "Skip pages that return HTTP errors"
complete -c "shot-scraper" -n "__fish_seen_subcommand_from html" -l "bypass-csp" -d "Bypass Content-Security-Policy"
complete -c "shot-scraper" -n "__fish_seen_subcommand_from html" -l "silent" -d "Do not output any messages"
complete -c "shot-scraper" -n "__fish_seen_subcommand_from html" -l "auth-password" -d "Password for HTTP Basic authentication"
complete -c "shot-scraper" -n "__fish_seen_subcommand_from html" -l "auth-username" -d "Username for HTTP Basic authentication"
complete -c "shot-scraper" -n "__fish_seen_subcommand_from html" -l "help" -d "Show this message and exit."
complete -c "shot-scraper" -n "__fish_seen_subcommand_from install" -s "b" -l "browser" -d "Which browser to install" -xa "chromium firefox webkit chrome chrome-beta"
complete -c "shot-scraper" -n "__fish_seen_subcommand_from install" -l "help" -d "Show this message and exit."
complete -c "shot-scraper" -n "__fish_seen_subcommand_from javascript" -s "i" -l "input" -d "Read input JavaScript from this file or use gh:username/script to load from github.com/username/shot-scraper-scripts/script.js"
complete -c "shot-scraper" -n "__fish_seen_subcommand_from javascript" -s "a" -l "auth" -d "Path to JSON authentication context file"
complete -c "shot-scraper" -n "__fish_seen_subcommand_from javascript" -s "o" -l "output" -d "Save output JSON to this file"
complete -c "shot-scraper" -n "__fish_seen_subcommand_from javascript" -s "r" -l "raw" -d "Output JSON strings as raw text"
complete -c "shot-scraper" -n "__fish_seen_subcommand_from javascript" -s "b" -l "browser" -d "Which browser to use" -xa "chromium firefox webkit chrome chrome-beta"
complete -c "shot-scraper" -n "__fish_seen_subcommand_from javascript" -l "browser-arg" -d "Additional arguments to pass to the browser"
complete -c "shot-scraper" -n "__fish_seen_subcommand_from javascript" -l "user-agent" -d "User-Agent header to use"
complete -c "shot-scraper" -n "__fish_seen_subcommand_from javascript" -l "reduced-motion" -d "Emulate 'prefers-reduced-motion' media feature"
complete -c "shot-scraper" -n "__fish_seen_subcommand_from javascript" -l "log-console" -d "Write console.log() to stderr"
complete -c "shot-scraper" -n "__fish_seen_subcommand_from javascript" -l "fail" -d "Fail with an error code if a page returns an HTTP error"
complete -c "shot-scraper" -n "__fish_seen_subcommand_from javascript" -l "skip" -d "Skip pages that return HTTP errors"
complete -c "shot-scraper" -n "__fish_seen_subcommand_from javascript" -l "bypass-csp" -d "Bypass Content-Security-Policy"
complete -c "shot-scraper" -n "__fish_seen_subcommand_from javascript" -l "auth-password" -d "Password for HTTP Basic authentication"
complete -c "shot-scraper" -n "__fish_seen_subcommand_from javascript" -l "auth-username" -d "Username for HTTP Basic authentication"
complete -c "shot-scraper" -n "__fish_seen_subcommand_from javascript" -l "help" -d "Show this message and exit."
complete -c "shot-scraper" -n "__fish_seen_subcommand_from multi" -s "a" -l "auth" -d "Path to JSON authentication context file"
complete -c "shot-scraper" -n "__fish_seen_subcommand_from multi" -l "scale-factor" -d "Device scale factor. Cannot be used together with '--retina'."
complete -c "shot-scraper" -n "__fish_seen_subcommand_from multi" -l "retina" -d "Use device scale factor of 2. Cannot be used together with '--scale-factor'."
complete -c "shot-scraper" -n "__fish_seen_subcommand_from multi" -l "timeout" -d "Wait this many milliseconds before failing"
complete -c "shot-scraper" -n "__fish_seen_subcommand_from multi" -s "n" -l "no-clobber" -d "Skip images that already exist"
complete -c "shot-scraper" -n "__fish_seen_subcommand_from multi" -s "o" -l "output" -d "Just take shots matching these output files"
complete -c "shot-scraper" -n "__fish_seen_subcommand_from multi" -s "b" -l "browser" -d "Which browser to use" -xa "chromium firefox webkit chrome chrome-beta"
complete -c "shot-scraper" -n "__fish_seen_subcommand_from multi" -l "browser-arg" -d "Additional arguments to pass to the browser"
complete -c "shot-scraper" -n "__fish_seen_subcommand_from multi" -l "user-agent" -d "User-Agent header to use"
complete -c "shot-scraper" -n "__fish_seen_subcommand_from multi" -l "reduced-motion" -d "Emulate 'prefers-reduced-motion' media feature"
complete -c "shot-scraper" -n "__fish_seen_subcommand_from multi" -l "log-console" -d "Write console.log() to stderr"
complete -c "shot-scraper" -n "__fish_seen_subcommand_from multi" -l "fail" -d "Fail with an error code if a page returns an HTTP error"
complete -c "shot-scraper" -n "__fish_seen_subcommand_from multi" -l "skip" -d "Skip pages that return HTTP errors"
complete -c "shot-scraper" -n "__fish_seen_subcommand_from multi" -l "silent" -d "Do not output any messages"
complete -c "shot-scraper" -n "__fish_seen_subcommand_from multi" -l "auth-password" -d "Password for HTTP Basic authentication"
complete -c "shot-scraper" -n "__fish_seen_subcommand_from multi" -l "auth-username" -d "Username for HTTP Basic authentication"
complete -c "shot-scraper" -n "__fish_seen_subcommand_from multi" -l "leave-server" -d "Leave servers running when script finishes"
complete -c "shot-scraper" -n "__fish_seen_subcommand_from multi" -l "har" -d "Save all requests to trace.har file"
complete -c "shot-scraper" -n "__fish_seen_subcommand_from multi" -l "har-zip" -d "Save all requests to trace.har.zip file"
complete -c "shot-scraper" -n "__fish_seen_subcommand_from multi" -l "har-file" -d "Path to HAR file to save all requests"
complete -c "shot-scraper" -n "__fish_seen_subcommand_from multi" -l "help" -d "Show this message and exit."
complete -c "shot-scraper" -n "__fish_seen_subcommand_from pdf" -s "a" -l "auth" -d "Path to JSON authentication context file"
complete -c "shot-scraper" -n "__fish_seen_subcommand_from pdf" -s "o" -l "output"
complete -c "shot-scraper" -n "__fish_seen_subcommand_from pdf" -s "j" -l "javascript" -d "Execute this JS prior to creating the PDF"
complete -c "shot-scraper" -n "__fish_seen_subcommand_from pdf" -l "wait" -d "Wait this many milliseconds before taking the screenshot"
complete -c "shot-scraper" -n "__fish_seen_subcommand_from pdf" -l "wait-for" -d "Wait until this JS expression returns true"
complete -c "shot-scraper" -n "__fish_seen_subcommand_from pdf" -l "timeout" -d "Wait this many milliseconds before failing"
complete -c "shot-scraper" -n "__fish_seen_subcommand_from pdf" -l "media-screen" -d "Use screen rather than print styles"
complete -c "shot-scraper" -n "__fish_seen_subcommand_from pdf" -l "landscape" -d "Use landscape orientation"
complete -c "shot-scraper" -n "__fish_seen_subcommand_from pdf" -l "format" -d "Which standard paper size to use" -xa "letter legal tabloid ledger a0 a1 a2 a3 a4 a5 a6"
complete -c "shot-scraper" -n "__fish_seen_subcommand_from pdf" -l "width" -d "PDF width including units, e.g. 10cm"
complete -c "shot-scraper" -n "__fish_seen_subcommand_from pdf" -l "height" -d "PDF height including units, e.g. 10cm"
complete -c "shot-scraper" -n "__fish_seen_subcommand_from pdf" -l "scale" -d "Scale of the webpage rendering [0.1<=x<=2.0]"
complete -c "shot-scraper" -n "__fish_seen_subcommand_from pdf" -l "print-background" -d "Print background graphics"
complete -c "shot-scraper" -n "__fish_seen_subcommand_from pdf" -l "log-console" -d "Write console.log() to stderr"
complete -c "shot-scraper" -n "__fish_seen_subcommand_from pdf" -l "fail" -d "Fail with an error code if a page returns an HTTP error"
complete -c "shot-scraper" -n "__fish_seen_subcommand_from pdf" -l "skip" -d "Skip pages that return HTTP errors"
complete -c "shot-scraper" -n "__fish_seen_subcommand_from pdf" -l "bypass-csp" -d "Bypass Content-Security-Policy"
complete -c "shot-scraper" -n "__fish_seen_subcommand_from pdf" -l "silent" -d "Do not output any messages"
complete -c "shot-scraper" -n "__fish_seen_subcommand_from pdf" -l "auth-password" -d "Password for HTTP Basic authentication"
complete -c "shot-scraper" -n "__fish_seen_subcommand_from pdf" -l "auth-username" -d "Username for HTTP Basic authentication"
complete -c "shot-scraper" -n "__fish_seen_subcommand_from pdf" -l "help" -d "Show this message and exit."