complete -c sn -s h -l help -d 'Prints help information'
complete -c sn -n __fish_no_arguments -s V -l version -d 'Prints version information'
complete -c sn -n __fish_no_arguments -s V -l version -d 'Prints version information'
complete -c sn -n __fish_no_arguments -s V -l version -d 'Prints version information'
complete -c sn -n __fish_no_arguments -s V -l version -d 'Prints version information'
complete -c sn -n __fish_no_arguments -s V -l version -d 'Prints version information'
complete -c sn -n __fish_no_arguments -s V -l version -d 'Prints version information'
complete -c sn -n __fish_no_arguments -s V -l version -d 'Prints version information'
complete -c sn -n __fish_no_arguments -s V -l version -d 'Prints version information'
complete -c sn -n __fish_no_arguments -s V -l version -d 'Prints version information'
