complete -c sourcekit-lsp -l configuration -d '<configuration>'
complete -c sourcekit-lsp -s Xcc -d '<Xcc>              Pass flag through to all C compiler invocations'
complete -c sourcekit-lsp -s Xcxx -d '<Xcxx>            Pass flag through to all C++ compiler invocations'
complete -c sourcekit-lsp -s Xlinker -d '<Xlinker>      Pass flag through to all linker invocations'
complete -c sourcekit-lsp -s Xswiftc -d '<Xswiftc>      Pass flag through to all Swift compiler invocations'
complete -c sourcekit-lsp -s Xclangd -d '<Xclangd>      Pass options to clangd command-line'
complete -c sourcekit-lsp -s index-store-path -d '<index-store-path>'
complete -c sourcekit-lsp -s index-db-path -d '<index-db-path>'
complete -c sourcekit-lsp -s index-prefix-map -d '<index-prefix-map>'
complete -c sourcekit-lsp -l default-workspace-type -d '<default-workspace-type>'
complete -c sourcekit-lsp -l compilation-db-search-path -d '<compilation-db-search-path>'
complete -c sourcekit-lsp -l generated-files-path -d '<generated-files-path>'
complete -c sourcekit-lsp -l experimental-feature -d '<experimental-feature>'
complete -c sourcekit-lsp -s h -l help -d 'Show help information.'
complete -f -c sourcekit-lsp -n __fish_use_subcommand -a developers -d 'of sourcekit-lsp'
complete -c sourcekit-lsp -n '__fish_seen_subcommand_from developers' -l configuration -d '<configuration>'
complete -c sourcekit-lsp -n '__fish_seen_subcommand_from developers' -s Xcc -d '<Xcc>              Pass flag through to all C compiler invocations'
complete -c sourcekit-lsp -n '__fish_seen_subcommand_from developers' -s Xcxx -d '<Xcxx>            Pass flag through to all C++ compiler invocations'
complete -c sourcekit-lsp -n '__fish_seen_subcommand_from developers' -s Xlinker -d '<Xlinker>      Pass flag through to all linker invocations'
complete -c sourcekit-lsp -n '__fish_seen_subcommand_from developers' -s Xswiftc -d '<Xswiftc>      Pass flag through to all Swift compiler invocations'
complete -c sourcekit-lsp -n '__fish_seen_subcommand_from developers' -s Xclangd -d '<Xclangd>      Pass options to clangd command-line'
complete -c sourcekit-lsp -n '__fish_seen_subcommand_from developers' -s index-store-path -d '<index-store-path>'
complete -c sourcekit-lsp -n '__fish_seen_subcommand_from developers' -s index-db-path -d '<index-db-path>'
complete -c sourcekit-lsp -n '__fish_seen_subcommand_from developers' -s index-prefix-map -d '<index-prefix-map>'
complete -c sourcekit-lsp -n '__fish_seen_subcommand_from developers' -l default-workspace-type -d '<default-workspace-type>'
complete -c sourcekit-lsp -n '__fish_seen_subcommand_from developers' -l compilation-db-search-path -d '<compilation-db-search-path>'
complete -c sourcekit-lsp -n '__fish_seen_subcommand_from developers' -l generated-files-path -d '<generated-files-path>'
complete -c sourcekit-lsp -n '__fish_seen_subcommand_from developers' -l experimental-feature -d '<experimental-feature>'
complete -c sourcekit-lsp -n '__fish_seen_subcommand_from developers' -s h -l help -d 'Show help information.'
