complete -c terser -n __fish_no_arguments -s V -l version -d 'output the version number'
complete -c terser -s p -l parse -d '<options>                    Specify parser options.'
complete -c terser -s c -l compress -d '[options]                 Enable compressor/specify compressor options.'
complete -c terser -s m -l mangle -d '[options]                   Mangle names/specify mangler options.'
complete -c terser -l mangle-props -d '[options]                 Mangle properties/specify mangler options.'
complete -c terser -s f -l format -d '[options]                   Format options.'
complete -c terser -s b -l beautify -d '[options]                 Alias for --format.'
complete -c terser -s o -l output -d '<file>                      Output file (default STDOUT).'
complete -c terser -l comments -d '[filter]                      Preserve copyright comments in the output.'
complete -c terser -l config-file -d '<file>                     Read minify() options from JSON file.'
complete -c terser -s d -l define -d '<expr>[=value]              Global definitions.'
complete -c terser -l ecma -d '<version>                         Specify ECMAScript release: 5, 2015, 2016 or 2017...'
complete -c terser -s e -l enclose -d '[arg[,...][:value[,...]]]  Embed output in a big function with configurable arguments and values.'
complete -c terser -l ie8 -d 'Support non-standard Internet Explorer 8.'
complete -c terser -l keep-classnames -d 'Do not mangle/drop class names.'
complete -c terser -l keep-fnames -d 'Do not mangle/drop function names. Useful for code relying on Function.prototype.name.'
complete -c terser -l module -d 'Input is an ES6 module'
complete -c terser -l name-cache -d '<file>                      File to hold mangled name mappings.'
complete -c terser -l rename -d 'Force symbol expansion.'
complete -c terser -l no-rename -d 'Disable symbol expansion.'
complete -c terser -l safari10 -d 'Support non-standard Safari 10.'
complete -c terser -l source-map -d '[options]                   Enable source map/specify source map options.'
complete -c terser -l timings -d 'Display operations run time on STDERR.'
complete -c terser -l toplevel -d 'Compress and/or mangle variables in toplevel scope.'
complete -c terser -l wrap -d '<name>                            Embed everything as a function with “exports” corresponding to “name” globally.'
complete -c terser -s h -l help -d 'output usage information'
