complete -c tidy -s output -d '<file>, -o <file>  write output to the specified <file>'
complete -c tidy -s config -d '<file>             set configuration options from the specified'
complete -c tidy -s file -d '<file>, -f <file>    write errors and warnings to the specified <file>'
complete -c tidy -s wrap -d '<column>, -w         wrap text at the specified <column>. 0 is assumed'
complete -c tidy -s omit -d 'omit optional start tags and end tags'
complete -c tidy -s xml -d 'specify the input is well formed XML'
complete -c tidy -s ashtml -d 'force XHTML to well formed HTML'
complete -c tidy -s access -d '<level>            do additional accessibility checks (<level> = 0,'
complete -c tidy -s raw -d 'output values above 127 without conversion to'
complete -c tidy -s ascii -d 'use ISO-8859-1 for input, US-ASCII for output'
complete -c tidy -s latin0 -d 'use ISO-8859-15 for input, US-ASCII for output'
complete -c tidy -s latin1 -d 'use ISO-8859-1 for both input and output'
complete -c tidy -s iso2022 -d 'use ISO-2022 for both input and output'
complete -c tidy -s utf8 -d 'use UTF-8 for both input and output'
complete -c tidy -s mac -d 'use MacRoman for input, US-ASCII for output'
complete -c tidy -s win1252 -d 'use Windows-1252 for input, US-ASCII for output'
complete -c tidy -s ibm858 -d 'use IBM-858 (CP850+Euro) for input, US-ASCII for'
complete -c tidy -s utf16le -d 'use UTF-16LE for both input and output'
complete -c tidy -s utf16be -d 'use UTF-16BE for both input and output'
complete -c tidy -s utf16 -d 'use UTF-16 for both input and output'
complete -c tidy -s big5 -d 'use Big5 for both input and output'
complete -c tidy -s shiftjis -d 'use Shift_JIS for both input and output'
complete -c tidy -s help-config -d 'list all configuration options'
complete -c tidy -s help-env -d 'show information about the environment and runtime'
complete -c tidy -s show-config -d 'list the current configuration settings'
complete -c tidy -s export-config -d 'list the current configuration settings, suitable'
complete -c tidy -s export-default-config -d 'list the default configuration settings, suitable'
complete -c tidy -s help-option -d '<option>      show a description of the <option>'
complete -c tidy -s language -d \<lang\>\ \ \ \ \ \ \ \ \ \ \ set\ Tidy\'s\ output\ language\ to\ \<lang\>.\ Specify
complete -c tidy -s xml-help -d 'list the command line options in XML format'
complete -c tidy -s xml-config -d 'list all configuration options in XML format'
complete -c tidy -s xml-strings -d output\ all\ of\ Tidy\'s\ strings\ in\ XML\ format
complete -c tidy -s xml-error-strings -d 'output error constants and strings in XML format'
complete -c tidy -s xml-options-strings -d 'output option descriptions in XML format'
complete -c tidy -s config -d '<file> directive, or in one or more files specific to your'
