#string replace -a -- {} tldr  {} --help
complete -c tldr -s l -l list -d 'List all commands in the cache'
complete -c tldr -s f -l render -d '<FILE>          Render a specific markdown file'
complete -c tldr -s p -l platform -d '<PLATFORM>    Override the operating system [possible values: linux, macos,'
complete -c tldr -s L -l language -d '<LANGUAGE>    Override the language'
complete -c tldr -s u -l update -d 'Update the local cache'
complete -c tldr -l no-auto-update -d 'If auto update is configured, disable it for this run'
complete -c tldr -s c -l clear-cache -d 'Clear the local cache'
complete -c tldr -l pager -d 'Use a pager to page output'
complete -c tldr -s r -l raw -d 'Display the raw markdown instead of rendering it'
complete -c tldr -s q -l quiet -d 'Suppress informational messages'
complete -c tldr -l show-paths -d 'Show file and directory paths used by tealdeer'
complete -c tldr -l seed-config -d 'Create a basic config'
complete -c tldr -l color -d '<WHEN>           Control whether to use color [possible values: always, auto, never]'
complete -c tldr -n __fish_no_arguments -s v -l version -d 'Print the version'
complete -c tldr -s h -l help -d 'Print help information'
