complete -c trafilatura -l explore -d '[EXPLORE] | --probe [PROBE]] [--archived]'
complete -c trafilatura -s h -l help -d 'show this help message and exit'
complete -c trafilatura -s v -l verbose -d 'increase logging verbosity (-v or -vv)'
complete -c trafilatura -n __fish_no_arguments -l version -d 'show version information and exit'
complete -c trafilatura -s i -d 'INPUT_FILE, --input-file INPUT_FILE'
complete -c trafilatura -l input-dir -d INPUT_DIR
complete -c trafilatura -s u -d 'URL, --URL URL     custom URL download'
complete -c trafilatura -l parallel -d 'PARALLEL   specify a number of cores/threads for downloads and/or'
complete -c trafilatura -s b -d 'BLACKLIST, --blacklist BLACKLIST'
complete -c trafilatura -l list -d 'display a list of URLs without downloading them'
complete -c trafilatura -s o -d 'OUTPUT_DIR, --output-dir OUTPUT_DIR'
complete -c trafilatura -l backup-dir -d BACKUP_DIR
complete -c trafilatura -l keep-dirs -d 'keep input directory structure and file names'
complete -c trafilatura -l feed -d '[FEED]         look for feeds and/or pass a feed URL as input'
complete -c trafilatura -l sitemap -d '[SITEMAP]   look for sitemaps for the given website and/or enter a'
complete -c trafilatura -l crawl -d '[CRAWL]       crawl a fixed number of pages within a website'
complete -c trafilatura -l explore -d '[EXPLORE]   explore the given websites (combination of sitemap and'
complete -c trafilatura -l probe -d '[PROBE]       probe for extractable content (works best with target'
complete -c trafilatura -l archived -d 'try to fetch URLs from the Internet Archive if'
complete -c trafilatura -l url-filter -d 'URL_FILTER [URL_FILTER ...]'
complete -c trafilatura -s f -l fast -d 'fast (without fallback detection)'
complete -c trafilatura -l formatting -d 'include text formatting (bold, italic, etc.)'
complete -c trafilatura -l links -d 'include links along with their targets (experimental)'
complete -c trafilatura -l images -d 'include image sources in output (experimental)'
complete -c trafilatura -l no-comments -d "don't output any comments"
complete -c trafilatura -l no-tables -d "don't output any table elements"
complete -c trafilatura -l only-with-metadata -d 'only output those documents with title, URL and date'
complete -c trafilatura -l with-metadata -d 'extract and add metadata to the output'
complete -c trafilatura -l target-language -d TARGET_LANGUAGE
complete -c trafilatura -l deduplicate -d 'filter out duplicate documents and sections'
complete -c trafilatura -l config-file -d CONFIG_FILE
complete -c trafilatura -l precision -d 'favor extraction precision (less noise, possibly less'
complete -c trafilatura -l recall -d 'favor extraction recall (more text, possibly more'
complete -c trafilatura -l output-format -d '{csv,json,html,markdown,txt,xml,xmltei}'
complete -c trafilatura -l csv -d 'shorthand for CSV output'
complete -c trafilatura -l html -d 'shorthand for HTML output'
complete -c trafilatura -l json -d 'shorthand for JSON output'
complete -c trafilatura -l markdown -d 'shorthand for MD output'
complete -c trafilatura -l xml -d 'shorthand for XML output'
complete -c trafilatura -l xmltei -d 'shorthand for XML TEI output'
complete -c trafilatura -l validate-tei -d 'validate XML TEI output'
