complete -c tsc-bundle -l outFile -d 'Outputs the bundle with the give filepath.'
complete -c tsc-bundle -l target -d 'Sets the ES Target for the bundle.'
complete -c tsc-bundle -l exportAs -d 'Exports bundle exports as a global variable.'
complete -c tsc-bundle -l importAs -d 'Imports global variable as a module (namespace).'
complete -c tsc-bundle -l importAsDefault -d 'Imports global variable as a module (default).'
complete -c tsc-bundle -l entryPoint -d 'Overrides the default entry point for the bundle.'
complete -c tsc-bundle -l transform -d 'Applies a transform to the bundle.'
complete -c tsc-bundle -l watch -d 'Starts the compiler in watch mode.'
complete -c tsc-bundle -l debug -d 'Prints debug information.'
