complete -c unpigz -s 0 -d 'to -9, -11        Compression level (level 11, zopfli, is much slower)'
complete -c unpigz -s A -l alias -d 'xxx      Use xxx as the name for any --zip entry from stdin'
complete -c unpigz -s b -l blocksize -d 'mmm  Set compression block size to mmmK (default 128K)'
complete -c unpigz -s c -l stdout -d "Write all processed output to stdout (won't delete)"
complete -c unpigz -s C -l comment -d 'ccc    Put comment ccc in the gzip or zip header'
complete -c unpigz -s d -l decompress -d 'Decompress the compressed input'
complete -c unpigz -s f -l force -d 'Force overwrite, compress .gz, links, and to terminal'
complete -c unpigz -s F -d '--first          Do iterations first, before block split for -11'
complete -c unpigz -s h -l help -d 'Display a help screen and quit'
complete -c unpigz -s H -l huffman -d 'Use only Huffman coding for compression'
complete -c unpigz -s i -l independent -d 'Compress blocks independently for damage recovery'
complete -c unpigz -s I -l iterations -d 'n   Number of iterations for -11 optimization'
complete -c unpigz -s J -l maxsplits -d 'n    Maximum number of split blocks for -11'
complete -c unpigz -s k -l keep -d 'Do not delete original file after processing'
complete -c unpigz -s K -l zip -d 'Compress to PKWare zip (.zip) single entry format'
complete -c unpigz -s l -l list -d 'List the contents of the compressed input'
complete -c unpigz -s L -l license -d 'Display the pigz license and quit'
complete -c unpigz -s m -l no-time -d 'Do not store or restore mod time'
complete -c unpigz -s M -l time -d 'Store or restore mod time'
complete -c unpigz -s n -l no-name -d 'Do not store or restore file name or mod time'
complete -c unpigz -s N -l name -d 'Store or restore file name and mod time'
complete -c unpigz -s O -d '--oneblock       Do not split into smaller blocks for -11'
complete -c unpigz -s p -l processes -d 'n    Allow up to n compression threads (default is the'
complete -c unpigz -s q -l quiet -d 'Print no messages, even on error'
complete -c unpigz -s r -l recursive -d 'Process the contents of all subdirectories'
complete -c unpigz -s R -l rsyncable -d 'Input-determined block locations for rsync'
complete -c unpigz -s S -l suffix -d '.sss    Use suffix .sss instead of .gz (for compression)'
complete -c unpigz -s t -l test -d 'Test the integrity of the compressed input'
complete -c unpigz -s U -l rle -d 'Use run-length encoding for compression'
complete -c unpigz -s v -l verbose -d 'Provide more verbose output'
complete -c unpigz -s V -d '--version        Show the version of pigz'
complete -c unpigz -s Y -d '--synchronous    Force output file write to permanent storage'
complete -c unpigz -s z -l zlib -d 'Compress to zlib (.zz) instead of gzip format'
