#string replace -a -- {} vite  {} --help
complete -c vite -l host -d '[host]           [string] specify hostname'
complete -c vite -l port -d '<port>           [number] specify port'
complete -c vite -l open -d '[path]           [boolean | string] open browser on startup'
complete -c vite -l cors -d '[boolean] enable CORS'
complete -c vite -l strictPort -d '[boolean] exit if specified port is already in use'
complete -c vite -l force -d '[boolean] force the optimizer to ignore the cache and re-bundle'
complete -c vite -s c -l config -d '<file>     [string] use specified config file'
complete -c vite -l base -d '<path>           [string] public base path (default: /)'
complete -c vite -s l -l logLevel -d '<level>  [string] info | warn | error | silent'
complete -c vite -l clearScreen -d '[boolean] allow/disable clear screen when logging'
complete -c vite -s d -l debug -d '[feat]      [string | boolean] show debug logs'
complete -c vite -s f -l filter -d '<filter>   [string] filter debug logs'
complete -c vite -s m -l mode -d '<mode>       [string] set env mode'
complete -c vite -s h -l help -d 'Display this message'
complete -c vite -n __fish_no_arguments -s v -l version -d 'Display version number'
