complete -f -c vonage -n __fish_use_subcommand -a apps -d 'manage your Vonage applications'
complete -f -c vonage -n __fish_use_subcommand -a balance -d 'display your Vonage account balance'
complete -f -c vonage -n __fish_use_subcommand -a config -d 'Display Vonage CLI configuration'
complete -f -c vonage -n __fish_use_subcommand -a help -d 'Display help for vonage.'
complete -f -c vonage -n __fish_use_subcommand -a jwt -d 'generate a Vonage JWT token'
complete -f -c vonage -n __fish_use_subcommand -a numberinsight -d 'get details about a phone number'
complete -f -c vonage -n __fish_use_subcommand -a numbers -d 'manage your Vonage numbers'
complete -c vonage -n '__fish_seen_subcommand_from numbers' -s x -l extended -d 'show extra columns'
complete -c vonage -n '__fish_seen_subcommand_from numbers' -l no-header -d 'hide table header from output'
complete -f -c vonage -n __fish_use_subcommand -a plugins -d 'List installed plugins.'
complete -c vonage -n '__fish_seen_subcommand_from plugins' -l core -d 'Show core plugins.'
complete -f -c vonage -n __fish_use_subcommand -a sms -d 'Send a simple SMS.'
