complete -c w3m -s t -d 'tab           set tab width'
complete -c w3m -s r -d 'ignore backspace effect'
complete -c w3m -s l -d 'line          # of preserved line (default 10000)'
complete -c w3m -s I -d 'charset       document charset'
complete -c w3m -s O -d 'charset       display/output charset'
complete -c w3m -s B -d 'load bookmark'
complete -c w3m -s bookmark -d 'file   specify bookmark file'
complete -c w3m -s T -d 'type          specify content-type'
complete -c w3m -s m -d 'internet message mode'
complete -c w3m -s v -d 'visual startup mode'
complete -c w3m -s M -d 'monochrome display'
complete -c w3m -s N -d 'open URL of command line on each new tab'
complete -c w3m -s F -d 'automatically render frames'
complete -c w3m -s cols -d 'width      specify column width (used with -dump)'
complete -c w3m -s ppc -d 'count       specify the number of pixels per character (4.0...32.0)'
complete -c w3m -s dump -d 'dump formatted page into stdout'
complete -c w3m -s dump_head -d 'dump response of HEAD request into stdout'
complete -c w3m -s dump_source -d 'dump page source into stdout'
complete -c w3m -s dump_both -d 'dump HEAD and source into stdout'
complete -c w3m -s dump_extra -d 'dump HEAD, source, and extra information into stdout'
complete -c w3m -s post -d 'file       use POST method with file content'
complete -c w3m -s header -d 'string   insert string as a header'
complete -c w3m -s num -d 'show line number'
complete -c w3m -s no-proxy -d don\'t\ use\ proxy
complete -c w3m -s 4 -d 'IPv4 only (-o dns_order=4)'
complete -c w3m -s 6 -d 'IPv6 only (-o dns_order=6)'
complete -c w3m -s no-mouse -d don\'t\ use\ mouse
complete -c w3m -s cookie -d use\ cookie\ \(-no-cookie:\ don\'t\ use\ cookie\)
complete -c w3m -s graph -d 'use DEC special graphics for border of table and menu'
complete -c w3m -s no-graph -d 'use ASCII character for border of table and menu'
complete -c w3m -s s -d 'squeeze multiple blank lines'
complete -c w3m -s W -d 'toggle search wrap mode'
complete -c w3m -s X -d don\'t\ use\ termcap\ init/deinit
complete -c w3m -s o -d 'opt=value     assign value to config option'
complete -c w3m -s show-option -d 'print all config options'
complete -c w3m -s config -d 'file     specify config file'
complete -c w3m -s help -d 'print this usage message'
complete -c w3m -s version -d 'print w3m version'
complete -c w3m -s reqlog -d 'write request logfile'
complete -c w3m -s debug -d 'DO NOT USE'
