complete -c webfont -l config -d 'Path to a specific configuration file (JSON, YAML, or CommonJS)'
complete -c webfont -s f -l fontName -d 'The font family name you want, default: "webfont".'
complete -c webfont -s h -l help -d 'Output usage information.'
complete -c webfont -n __fish_no_arguments -s v -l version -d 'Output the version number.'
complete -c webfont -s r -l formats -d 'Only this formats generate.'
complete -c webfont -s d -l dest -d 'Destination for generated fonts.'
complete -c webfont -s m -l dest-create -d 'Create destination directory if it does not exist.'
complete -c webfont -s t -l template -d "Type of template ('css', 'scss', 'styl') or path to custom template."
complete -c webfont -s s -l destTemplate -d 'Destination for generated template. If not passed used `dest` argument value.'
complete -c webfont -s c -l templateClassName -d 'Class name in css template.'
complete -c webfont -s p -l templateFontPath -d 'Font path in css template.'
complete -c webfont -s n -l templateFontName -d 'Font name in css template.'
complete -c webfont -l templateCacheString -d 'Specify cache string in scss/css template.'
complete -c webfont -l no-sort -d 'Keeps the files in the same order of entry'
complete -c webfont -l verbose -d 'Tell me everything!.'
complete -c webfont -l fontId -d 'The font id you want, default as "--fontName".'
complete -c webfont -l fontStyle -d 'The font style you want.'
complete -c webfont -l fontWeight -d 'The font weight you want.'
complete -c webfont -l fixedWidth -d 'Creates a monospace font of the width of the largest input icon.'
complete -c webfont -l centerHorizontally -d 'Calculate the bounds of a glyph and center it horizontally.'
complete -c webfont -l normalize -d 'Normalize icons by scaling them to the height of the highest icon.'
complete -c webfont -l fontHeight -d 'The outputted font height [MAX(icons.height)].'
complete -c webfont -l round -d 'Setup the SVG path rounding [10e12].'
complete -c webfont -l descent -d 'The font descent [0].'
complete -c webfont -l ascent -d 'The font ascent [height - descent].'
complete -c webfont -l startUnicode -d 'The start unicode codepoint for files without prefix [0xEA01].'
complete -c webfont -l prependUnicode -d 'Prefix files with their automatically allocated unicode codepoint.'
complete -c webfont -l metadata -d 'Content of the metadata tag.'
complete -c webfont -l addHashInFontUrl -d 'Generated font url will be : [webfont].[ext]?v=[hash]'
