#!/usr/bin/env fish
# fish completion support for wmill v1.473.1

function __fish_wmill_using_command
  set -l cmds __wmill __wmill_init __wmill_app __wmill_app_push __wmill_flow __wmill_flow_push __wmill_flow_run __wmill_flow_generate_locks __wmill_flow_bootstrap __wmill_script __wmill_script_push __wmill_script_show __wmill_script_run __wmill_script_bootstrap __wmill_script_generate_metadata __wmill_workspace __wmill_workspace_switch __wmill_workspace_add __wmill_workspace_remove __wmill_workspace_whoami __wmill_resource __wmill_resource_push __wmill_user __wmill_user_add __wmill_user_remove __wmill_user_create_token __wmill_variable __wmill_variable_push __wmill_variable_add __wmill_hub __wmill_hub_pull __wmill_folder __wmill_folder_push __wmill_schedule __wmill_schedule_push __wmill_trigger __wmill_trigger_push __wmill_dev __wmill_sync __wmill_sync_pull __wmill_sync_push __wmill_instance __wmill_instance_add __wmill_instance_remove __wmill_instance_switch __wmill_instance_pull __wmill_instance_push __wmill_instance_whoami __wmill_worker_groups __wmill_worker_groups_pull __wmill_worker_groups_push __wmill_workers __wmill_queues __wmill_version __wmill_upgrade __wmill_completions __wmill_completions_bash __wmill_completions_fish __wmill_completions_zsh
  set -l words (commandline -opc)
  set -l cmd "_"
  for word in $words
    switch $word
      case '-*'
        continue
      case '*'
        set word (string replace -r -a '\W' '_' $word)
        set -l cmd_tmp $cmd"_$word"
        if contains $cmd_tmp $cmds
          set cmd $cmd_tmp
        end
    end
  end
  if test "$cmd" = "$argv[1]"
    return 0
  end
  return 1
end

complete -c wmill -n '__fish_wmill_using_command __wmill' -s h -l help -x -k -f -d 'Show this help.'
complete -c wmill -n '__fish_wmill_using_command __wmill' -s V -l version -x -k -f -d 'Show the version number for this program.'
complete -c wmill -n '__fish_wmill_using_command __wmill' -l workspace -k -f -r -a '(wmill completions complete string )' -d 'Specify the target workspace. This overrides the default workspace.'
complete -c wmill -n '__fish_wmill_using_command __wmill' -l debug -k -f -d 'Show debug/verbose logs'
complete -c wmill -n '__fish_wmill_using_command __wmill' -l show-diffs -k -f -d 'Show diff informations when syncing (may show sensitive informations)'
complete -c wmill -n '__fish_wmill_using_command __wmill' -l token -k -f -r -a '(wmill completions complete string )' -d 'Specify an API token. This will override any stored token.'
complete -c wmill -n '__fish_wmill_using_command __wmill' -l base-url -k -f -r -a '(wmill completions complete string )' -d 'Specify the base URL of the API. If used, --token and --workspace are required and no local remote/workspace already set will be used.'
complete -c wmill -n '__fish_wmill_using_command __wmill' -k -f -a init -d 'Bootstrap a windmill project with a wmill.yaml file'
complete -c wmill -n '__fish_wmill_using_command __wmill_init' -s h -l help -x -k -f -d 'Show this help.'
complete -c wmill -n '__fish_wmill_using_command __wmill_init' -l workspace -k -f -r -a '(wmill completions complete string init)' -d 'Specify the target workspace. This overrides the default workspace.'
complete -c wmill -n '__fish_wmill_using_command __wmill_init' -l debug -k -f -d 'Show debug/verbose logs'
complete -c wmill -n '__fish_wmill_using_command __wmill_init' -l show-diffs -k -f -d 'Show diff informations when syncing (may show sensitive informations)'
complete -c wmill -n '__fish_wmill_using_command __wmill_init' -l token -k -f -r -a '(wmill completions complete string init)' -d 'Specify an API token. This will override any stored token.'
complete -c wmill -n '__fish_wmill_using_command __wmill_init' -l base-url -k -f -r -a '(wmill completions complete string init)' -d 'Specify the base URL of the API. If used, --token and --workspace are required and no local remote/workspace already set will be used.'
complete -c wmill -n '__fish_wmill_using_command __wmill' -k -f -a app -d 'app related commands'
complete -c wmill -n '__fish_wmill_using_command __wmill_app' -s h -l help -x -k -f -d 'Show this help.'
complete -c wmill -n '__fish_wmill_using_command __wmill_app' -l workspace -k -f -r -a '(wmill completions complete string app)' -d 'Specify the target workspace. This overrides the default workspace.'
complete -c wmill -n '__fish_wmill_using_command __wmill_app' -l debug -k -f -d 'Show debug/verbose logs'
complete -c wmill -n '__fish_wmill_using_command __wmill_app' -l show-diffs -k -f -d 'Show diff informations when syncing (may show sensitive informations)'
complete -c wmill -n '__fish_wmill_using_command __wmill_app' -l token -k -f -r -a '(wmill completions complete string app)' -d 'Specify an API token. This will override any stored token.'
complete -c wmill -n '__fish_wmill_using_command __wmill_app' -l base-url -k -f -r -a '(wmill completions complete string app)' -d 'Specify the base URL of the API. If used, --token and --workspace are required and no local remote/workspace already set will be used.'
complete -c wmill -n '__fish_wmill_using_command __wmill_app' -k -f -a push -d 'push a local app'
complete -c wmill -n '__fish_wmill_using_command __wmill_app_push' -k -f -a '(wmill completions complete string app push)'
complete -c wmill -n '__fish_wmill_using_command __wmill_app_push' -s h -l help -x -k -f -d 'Show this help.'
complete -c wmill -n '__fish_wmill_using_command __wmill_app_push' -l workspace -k -f -r -a '(wmill completions complete string app push)' -d 'Specify the target workspace. This overrides the default workspace.'
complete -c wmill -n '__fish_wmill_using_command __wmill_app_push' -l debug -k -f -d 'Show debug/verbose logs'
complete -c wmill -n '__fish_wmill_using_command __wmill_app_push' -l show-diffs -k -f -d 'Show diff informations when syncing (may show sensitive informations)'
complete -c wmill -n '__fish_wmill_using_command __wmill_app_push' -l token -k -f -r -a '(wmill completions complete string app push)' -d 'Specify an API token. This will override any stored token.'
complete -c wmill -n '__fish_wmill_using_command __wmill_app_push' -l base-url -k -f -r -a '(wmill completions complete string app push)' -d 'Specify the base URL of the API. If used, --token and --workspace are required and no local remote/workspace already set will be used.'
complete -c wmill -n '__fish_wmill_using_command __wmill' -k -f -a flow -d 'flow related commands'
complete -c wmill -n '__fish_wmill_using_command __wmill_flow' -s h -l help -x -k -f -d 'Show this help.'
complete -c wmill -n '__fish_wmill_using_command __wmill_flow' -l workspace -k -f -r -a '(wmill completions complete string flow)' -d 'Specify the target workspace. This overrides the default workspace.'
complete -c wmill -n '__fish_wmill_using_command __wmill_flow' -l debug -k -f -d 'Show debug/verbose logs'
complete -c wmill -n '__fish_wmill_using_command __wmill_flow' -l show-diffs -k -f -d 'Show diff informations when syncing (may show sensitive informations)'
complete -c wmill -n '__fish_wmill_using_command __wmill_flow' -l token -k -f -r -a '(wmill completions complete string flow)' -d 'Specify an API token. This will override any stored token.'
complete -c wmill -n '__fish_wmill_using_command __wmill_flow' -l base-url -k -f -r -a '(wmill completions complete string flow)' -d 'Specify the base URL of the API. If used, --token and --workspace are required and no local remote/workspace already set will be used.'
complete -c wmill -n '__fish_wmill_using_command __wmill_flow' -l show-archived -k -f -d 'Enable archived scripts in output'
complete -c wmill -n '__fish_wmill_using_command __wmill_flow' -k -f -a push -d 'push a local flow spec. This overrides any remote versions.'
complete -c wmill -n '__fish_wmill_using_command __wmill_flow_push' -k -f -a '(wmill completions complete string flow push)'
complete -c wmill -n '__fish_wmill_using_command __wmill_flow_push' -s h -l help -x -k -f -d 'Show this help.'
complete -c wmill -n '__fish_wmill_using_command __wmill_flow_push' -l workspace -k -f -r -a '(wmill completions complete string flow push)' -d 'Specify the target workspace. This overrides the default workspace.'
complete -c wmill -n '__fish_wmill_using_command __wmill_flow_push' -l debug -k -f -d 'Show debug/verbose logs'
complete -c wmill -n '__fish_wmill_using_command __wmill_flow_push' -l show-diffs -k -f -d 'Show diff informations when syncing (may show sensitive informations)'
complete -c wmill -n '__fish_wmill_using_command __wmill_flow_push' -l token -k -f -r -a '(wmill completions complete string flow push)' -d 'Specify an API token. This will override any stored token.'
complete -c wmill -n '__fish_wmill_using_command __wmill_flow_push' -l base-url -k -f -r -a '(wmill completions complete string flow push)' -d 'Specify the base URL of the API. If used, --token and --workspace are required and no local remote/workspace already set will be used.'
complete -c wmill -n '__fish_wmill_using_command __wmill_flow' -k -f -a run -d 'run a flow by path.'
complete -c wmill -n '__fish_wmill_using_command __wmill_flow_run' -k -f -a '(wmill completions complete string flow run)'
complete -c wmill -n '__fish_wmill_using_command __wmill_flow_run' -s h -l help -x -k -f -d 'Show this help.'
complete -c wmill -n '__fish_wmill_using_command __wmill_flow_run' -l workspace -k -f -r -a '(wmill completions complete string flow run)' -d 'Specify the target workspace. This overrides the default workspace.'
complete -c wmill -n '__fish_wmill_using_command __wmill_flow_run' -l debug -k -f -d 'Show debug/verbose logs'
complete -c wmill -n '__fish_wmill_using_command __wmill_flow_run' -l show-diffs -k -f -d 'Show diff informations when syncing (may show sensitive informations)'
complete -c wmill -n '__fish_wmill_using_command __wmill_flow_run' -l token -k -f -r -a '(wmill completions complete string flow run)' -d 'Specify an API token. This will override any stored token.'
complete -c wmill -n '__fish_wmill_using_command __wmill_flow_run' -l base-url -k -f -r -a '(wmill completions complete string flow run)' -d 'Specify the base URL of the API. If used, --token and --workspace are required and no local remote/workspace already set will be used.'
complete -c wmill -n '__fish_wmill_using_command __wmill_flow_run' -s d -l data -k -f -r -a '(wmill completions complete string flow run)' -d 'Inputs specified as a JSON string or a file using @<filename> or stdin using @-.'
complete -c wmill -n '__fish_wmill_using_command __wmill_flow_run' -s s -l silent -k -f -d 'Do not ouput anything other then the final output. Useful for scripting.'
complete -c wmill -n '__fish_wmill_using_command __wmill_flow' -k -f -a generate-locks -d 're-generate the lock files of all inline scripts of all updated flows'
complete -c wmill -n '__fish_wmill_using_command __wmill_flow_generate_locks' -k -f -a '(__fish_complete_path)'
complete -c wmill -n '__fish_wmill_using_command __wmill_flow_generate_locks' -s h -l help -x -k -f -d 'Show this help.'
complete -c wmill -n '__fish_wmill_using_command __wmill_flow_generate_locks' -l workspace -k -f -r -a '(wmill completions complete string flow generate-locks)' -d 'Specify the target workspace. This overrides the default workspace.'
complete -c wmill -n '__fish_wmill_using_command __wmill_flow_generate_locks' -l debug -k -f -d 'Show debug/verbose logs'
complete -c wmill -n '__fish_wmill_using_command __wmill_flow_generate_locks' -l show-diffs -k -f -d 'Show diff informations when syncing (may show sensitive informations)'
complete -c wmill -n '__fish_wmill_using_command __wmill_flow_generate_locks' -l token -k -f -r -a '(wmill completions complete string flow generate-locks)' -d 'Specify an API token. This will override any stored token.'
complete -c wmill -n '__fish_wmill_using_command __wmill_flow_generate_locks' -l base-url -k -f -r -a '(wmill completions complete string flow generate-locks)' -d 'Specify the base URL of the API. If used, --token and --workspace are required and no local remote/workspace already set will be used.'
complete -c wmill -n '__fish_wmill_using_command __wmill_flow_generate_locks' -l yes -k -f -d 'Skip confirmation prompt'
complete -c wmill -n '__fish_wmill_using_command __wmill_flow_generate_locks' -s i -l includes -k -f -r -a '(__fish_complete_path)' -d 'Comma separated patterns to specify which file to take into account (among files that are compatible with windmill). Patterns can include * (any string until \'/\') and ** (any string)'
complete -c wmill -n '__fish_wmill_using_command __wmill_flow_generate_locks' -s e -l excludes -k -f -r -a '(__fish_complete_path)' -d 'Comma separated patterns to specify which file to NOT take into account.'
complete -c wmill -n '__fish_wmill_using_command __wmill_flow' -k -f -a bootstrap -d 'create a new empty flow'
complete -c wmill -n '__fish_wmill_using_command __wmill_flow_bootstrap' -k -f -a '(wmill completions complete string flow bootstrap)'
complete -c wmill -n '__fish_wmill_using_command __wmill_flow_bootstrap' -s h -l help -x -k -f -d 'Show this help.'
complete -c wmill -n '__fish_wmill_using_command __wmill_flow_bootstrap' -l workspace -k -f -r -a '(wmill completions complete string flow bootstrap)' -d 'Specify the target workspace. This overrides the default workspace.'
complete -c wmill -n '__fish_wmill_using_command __wmill_flow_bootstrap' -l debug -k -f -d 'Show debug/verbose logs'
complete -c wmill -n '__fish_wmill_using_command __wmill_flow_bootstrap' -l show-diffs -k -f -d 'Show diff informations when syncing (may show sensitive informations)'
complete -c wmill -n '__fish_wmill_using_command __wmill_flow_bootstrap' -l token -k -f -r -a '(wmill completions complete string flow bootstrap)' -d 'Specify an API token. This will override any stored token.'
complete -c wmill -n '__fish_wmill_using_command __wmill_flow_bootstrap' -l base-url -k -f -r -a '(wmill completions complete string flow bootstrap)' -d 'Specify the base URL of the API. If used, --token and --workspace are required and no local remote/workspace already set will be used.'
complete -c wmill -n '__fish_wmill_using_command __wmill_flow_bootstrap' -l summary -k -f -r -a '(wmill completions complete string flow bootstrap)' -d 'script summary'
complete -c wmill -n '__fish_wmill_using_command __wmill_flow_bootstrap' -l description -k -f -r -a '(wmill completions complete string flow bootstrap)' -d 'script description'
complete -c wmill -n '__fish_wmill_using_command __wmill' -k -f -a script -d 'script related commands'
complete -c wmill -n '__fish_wmill_using_command __wmill_script' -s h -l help -x -k -f -d 'Show this help.'
complete -c wmill -n '__fish_wmill_using_command __wmill_script' -l workspace -k -f -r -a '(wmill completions complete string script)' -d 'Specify the target workspace. This overrides the default workspace.'
complete -c wmill -n '__fish_wmill_using_command __wmill_script' -l debug -k -f -d 'Show debug/verbose logs'
complete -c wmill -n '__fish_wmill_using_command __wmill_script' -l show-diffs -k -f -d 'Show diff informations when syncing (may show sensitive informations)'
complete -c wmill -n '__fish_wmill_using_command __wmill_script' -l token -k -f -r -a '(wmill completions complete string script)' -d 'Specify an API token. This will override any stored token.'
complete -c wmill -n '__fish_wmill_using_command __wmill_script' -l base-url -k -f -r -a '(wmill completions complete string script)' -d 'Specify the base URL of the API. If used, --token and --workspace are required and no local remote/workspace already set will be used.'
complete -c wmill -n '__fish_wmill_using_command __wmill_script' -l show-archived -k -f -d 'Enable archived scripts in output'
complete -c wmill -n '__fish_wmill_using_command __wmill_script' -k -f -a push -d 'push a local script spec. This overrides any remote versions. Use the script file (.ts, .js, .py, .sh)'
complete -c wmill -n '__fish_wmill_using_command __wmill_script_push' -k -f -a '(__fish_complete_path)'
complete -c wmill -n '__fish_wmill_using_command __wmill_script_push' -s h -l help -x -k -f -d 'Show this help.'
complete -c wmill -n '__fish_wmill_using_command __wmill_script_push' -l workspace -k -f -r -a '(wmill completions complete string script push)' -d 'Specify the target workspace. This overrides the default workspace.'
complete -c wmill -n '__fish_wmill_using_command __wmill_script_push' -l debug -k -f -d 'Show debug/verbose logs'
complete -c wmill -n '__fish_wmill_using_command __wmill_script_push' -l show-diffs -k -f -d 'Show diff informations when syncing (may show sensitive informations)'
complete -c wmill -n '__fish_wmill_using_command __wmill_script_push' -l token -k -f -r -a '(wmill completions complete string script push)' -d 'Specify an API token. This will override any stored token.'
complete -c wmill -n '__fish_wmill_using_command __wmill_script_push' -l base-url -k -f -r -a '(wmill completions complete string script push)' -d 'Specify the base URL of the API. If used, --token and --workspace are required and no local remote/workspace already set will be used.'
complete -c wmill -n '__fish_wmill_using_command __wmill_script' -k -f -a show -d 'show a scripts content'
complete -c wmill -n '__fish_wmill_using_command __wmill_script_show' -k -f -a '(__fish_complete_path)'
complete -c wmill -n '__fish_wmill_using_command __wmill_script_show' -s h -l help -x -k -f -d 'Show this help.'
complete -c wmill -n '__fish_wmill_using_command __wmill_script_show' -l workspace -k -f -r -a '(wmill completions complete string script show)' -d 'Specify the target workspace. This overrides the default workspace.'
complete -c wmill -n '__fish_wmill_using_command __wmill_script_show' -l debug -k -f -d 'Show debug/verbose logs'
complete -c wmill -n '__fish_wmill_using_command __wmill_script_show' -l show-diffs -k -f -d 'Show diff informations when syncing (may show sensitive informations)'
complete -c wmill -n '__fish_wmill_using_command __wmill_script_show' -l token -k -f -r -a '(wmill completions complete string script show)' -d 'Specify an API token. This will override any stored token.'
complete -c wmill -n '__fish_wmill_using_command __wmill_script_show' -l base-url -k -f -r -a '(wmill completions complete string script show)' -d 'Specify the base URL of the API. If used, --token and --workspace are required and no local remote/workspace already set will be used.'
complete -c wmill -n '__fish_wmill_using_command __wmill_script' -k -f -a run -d 'run a script by path'
complete -c wmill -n '__fish_wmill_using_command __wmill_script_run' -k -f -a '(__fish_complete_path)'
complete -c wmill -n '__fish_wmill_using_command __wmill_script_run' -s h -l help -x -k -f -d 'Show this help.'
complete -c wmill -n '__fish_wmill_using_command __wmill_script_run' -l workspace -k -f -r -a '(wmill completions complete string script run)' -d 'Specify the target workspace. This overrides the default workspace.'
complete -c wmill -n '__fish_wmill_using_command __wmill_script_run' -l debug -k -f -d 'Show debug/verbose logs'
complete -c wmill -n '__fish_wmill_using_command __wmill_script_run' -l show-diffs -k -f -d 'Show diff informations when syncing (may show sensitive informations)'
complete -c wmill -n '__fish_wmill_using_command __wmill_script_run' -l token -k -f -r -a '(wmill completions complete string script run)' -d 'Specify an API token. This will override any stored token.'
complete -c wmill -n '__fish_wmill_using_command __wmill_script_run' -l base-url -k -f -r -a '(wmill completions complete string script run)' -d 'Specify the base URL of the API. If used, --token and --workspace are required and no local remote/workspace already set will be used.'
complete -c wmill -n '__fish_wmill_using_command __wmill_script_run' -s d -l data -k -f -r -a '(__fish_complete_path)' -d 'Inputs specified as a JSON string or a file using @<filename> or stdin using @-.'
complete -c wmill -n '__fish_wmill_using_command __wmill_script_run' -s s -l silent -k -f -d 'Do not output anything other then the final output. Useful for scripting.'
complete -c wmill -n '__fish_wmill_using_command __wmill_script' -k -f -a bootstrap -d 'create a new script'
complete -c wmill -n '__fish_wmill_using_command __wmill_script_bootstrap' -k -f -a '(__fish_complete_path)'
complete -c wmill -n '__fish_wmill_using_command __wmill_script_bootstrap' -s h -l help -x -k -f -d 'Show this help.'
complete -c wmill -n '__fish_wmill_using_command __wmill_script_bootstrap' -l workspace -k -f -r -a '(wmill completions complete string script bootstrap)' -d 'Specify the target workspace. This overrides the default workspace.'
complete -c wmill -n '__fish_wmill_using_command __wmill_script_bootstrap' -l debug -k -f -d 'Show debug/verbose logs'
complete -c wmill -n '__fish_wmill_using_command __wmill_script_bootstrap' -l show-diffs -k -f -d 'Show diff informations when syncing (may show sensitive informations)'
complete -c wmill -n '__fish_wmill_using_command __wmill_script_bootstrap' -l token -k -f -r -a '(wmill completions complete string script bootstrap)' -d 'Specify an API token. This will override any stored token.'
complete -c wmill -n '__fish_wmill_using_command __wmill_script_bootstrap' -l base-url -k -f -r -a '(wmill completions complete string script bootstrap)' -d 'Specify the base URL of the API. If used, --token and --workspace are required and no local remote/workspace already set will be used.'
complete -c wmill -n '__fish_wmill_using_command __wmill_script_bootstrap' -l summary -k -f -r -a '(wmill completions complete string script bootstrap)' -d 'script summary'
complete -c wmill -n '__fish_wmill_using_command __wmill_script_bootstrap' -l description -k -f -r -a '(wmill completions complete string script bootstrap)' -d 'script description'
complete -c wmill -n '__fish_wmill_using_command __wmill_script' -k -f -a generate-metadata -d 're-generate the metadata file updating the lock and the script schema (for flows, use `wmill flow generate-locks`)'
complete -c wmill -n '__fish_wmill_using_command __wmill_script_generate_metadata' -k -f -a '(__fish_complete_path)'
complete -c wmill -n '__fish_wmill_using_command __wmill_script_generate_metadata' -s h -l help -x -k -f -d 'Show this help.'
complete -c wmill -n '__fish_wmill_using_command __wmill_script_generate_metadata' -l workspace -k -f -r -a '(wmill completions complete string script generate-metadata)' -d 'Specify the target workspace. This overrides the default workspace.'
complete -c wmill -n '__fish_wmill_using_command __wmill_script_generate_metadata' -l debug -k -f -d 'Show debug/verbose logs'
complete -c wmill -n '__fish_wmill_using_command __wmill_script_generate_metadata' -l show-diffs -k -f -d 'Show diff informations when syncing (may show sensitive informations)'
complete -c wmill -n '__fish_wmill_using_command __wmill_script_generate_metadata' -l token -k -f -r -a '(wmill completions complete string script generate-metadata)' -d 'Specify an API token. This will override any stored token.'
complete -c wmill -n '__fish_wmill_using_command __wmill_script_generate_metadata' -l base-url -k -f -r -a '(wmill completions complete string script generate-metadata)' -d 'Specify the base URL of the API. If used, --token and --workspace are required and no local remote/workspace already set will be used.'
complete -c wmill -n '__fish_wmill_using_command __wmill_script_generate_metadata' -l yes -k -f -d 'Skip confirmation prompt'
complete -c wmill -n '__fish_wmill_using_command __wmill_script_generate_metadata' -l lock-only -k -f -d 're-generate only the lock'
complete -c wmill -n '__fish_wmill_using_command __wmill_script_generate_metadata' -l schema-only -k -f -d 're-generate only script schema'
complete -c wmill -n '__fish_wmill_using_command __wmill_script_generate_metadata' -s i -l includes -k -f -r -a '(__fish_complete_path)' -d 'Comma separated patterns to specify which file to take into account (among files that are compatible with windmill). Patterns can include * (any string until \'/\') and ** (any string)'
complete -c wmill -n '__fish_wmill_using_command __wmill_script_generate_metadata' -s e -l excludes -k -f -r -a '(__fish_complete_path)' -d 'Comma separated patterns to specify which file to NOT take into account.'
complete -c wmill -n '__fish_wmill_using_command __wmill' -k -f -a workspace -d 'workspace related commands'
complete -c wmill -n '__fish_wmill_using_command __wmill_workspace' -s h -l help -x -k -f -d 'Show this help.'
complete -c wmill -n '__fish_wmill_using_command __wmill_workspace' -l workspace -k -f -r -a '(wmill completions complete string workspace)' -d 'Specify the target workspace. This overrides the default workspace.'
complete -c wmill -n '__fish_wmill_using_command __wmill_workspace' -l debug -k -f -d 'Show debug/verbose logs'
complete -c wmill -n '__fish_wmill_using_command __wmill_workspace' -l show-diffs -k -f -d 'Show diff informations when syncing (may show sensitive informations)'
complete -c wmill -n '__fish_wmill_using_command __wmill_workspace' -l token -k -f -r -a '(wmill completions complete string workspace)' -d 'Specify an API token. This will override any stored token.'
complete -c wmill -n '__fish_wmill_using_command __wmill_workspace' -l base-url -k -f -r -a '(wmill completions complete string workspace)' -d 'Specify the base URL of the API. If used, --token and --workspace are required and no local remote/workspace already set will be used.'
complete -c wmill -n '__fish_wmill_using_command __wmill_workspace' -k -f -a switch -d 'Switch to another workspace'
complete -c wmill -n '__fish_wmill_using_command __wmill_workspace_switch' -k -f -a '(wmill completions complete workspace workspace switch)'
complete -c wmill -n '__fish_wmill_using_command __wmill_workspace_switch' -s h -l help -x -k -f -d 'Show this help.'
complete -c wmill -n '__fish_wmill_using_command __wmill_workspace_switch' -l workspace -k -f -r -a '(wmill completions complete string workspace switch)' -d 'Specify the target workspace. This overrides the default workspace.'
complete -c wmill -n '__fish_wmill_using_command __wmill_workspace_switch' -l debug -k -f -d 'Show debug/verbose logs'
complete -c wmill -n '__fish_wmill_using_command __wmill_workspace_switch' -l show-diffs -k -f -d 'Show diff informations when syncing (may show sensitive informations)'
complete -c wmill -n '__fish_wmill_using_command __wmill_workspace_switch' -l token -k -f -r -a '(wmill completions complete string workspace switch)' -d 'Specify an API token. This will override any stored token.'
complete -c wmill -n '__fish_wmill_using_command __wmill_workspace_switch' -l base-url -k -f -r -a '(wmill completions complete string workspace switch)' -d 'Specify the base URL of the API. If used, --token and --workspace are required and no local remote/workspace already set will be used.'
complete -c wmill -n '__fish_wmill_using_command __wmill_workspace' -k -f -a add -d 'Add a workspace'
complete -c wmill -n '__fish_wmill_using_command __wmill_workspace_add' -k -f -a '(wmill completions complete string workspace add)'
complete -c wmill -n '__fish_wmill_using_command __wmill_workspace_add' -s h -l help -x -k -f -d 'Show this help.'
complete -c wmill -n '__fish_wmill_using_command __wmill_workspace_add' -l workspace -k -f -r -a '(wmill completions complete string workspace add)' -d 'Specify the target workspace. This overrides the default workspace.'
complete -c wmill -n '__fish_wmill_using_command __wmill_workspace_add' -l debug -k -f -d 'Show debug/verbose logs'
complete -c wmill -n '__fish_wmill_using_command __wmill_workspace_add' -l show-diffs -k -f -d 'Show diff informations when syncing (may show sensitive informations)'
complete -c wmill -n '__fish_wmill_using_command __wmill_workspace_add' -l token -k -f -r -a '(wmill completions complete string workspace add)' -d 'Specify an API token. This will override any stored token.'
complete -c wmill -n '__fish_wmill_using_command __wmill_workspace_add' -l base-url -k -f -r -a '(wmill completions complete string workspace add)' -d 'Specify the base URL of the API. If used, --token and --workspace are required and no local remote/workspace already set will be used.'
complete -c wmill -n '__fish_wmill_using_command __wmill_workspace_add' -s c -l create -k -f -d 'Create the workspace if it does not exist'
complete -c wmill -n '__fish_wmill_using_command __wmill_workspace_add' -l create-workspace-name -k -f -r -a '(wmill completions complete string workspace add)' -d 'Specify the workspace name. Ignored if --create is not specified or the workspace already exists. Will default to the workspace id.'
complete -c wmill -n '__fish_wmill_using_command __wmill_workspace_add' -l create-username -k -f -r -a '(wmill completions complete string workspace add)' -d 'Specify your own username in the newly created workspace. Ignored if --create is not specified, the workspace already exists or automatic username creation is enabled on the instance.'
complete -c wmill -n '__fish_wmill_using_command __wmill_workspace' -k -f -a remove -d 'Remove a workspace'
complete -c wmill -n '__fish_wmill_using_command __wmill_workspace_remove' -k -f -a '(wmill completions complete string workspace remove)'
complete -c wmill -n '__fish_wmill_using_command __wmill_workspace_remove' -s h -l help -x -k -f -d 'Show this help.'
complete -c wmill -n '__fish_wmill_using_command __wmill_workspace_remove' -l workspace -k -f -r -a '(wmill completions complete string workspace remove)' -d 'Specify the target workspace. This overrides the default workspace.'
complete -c wmill -n '__fish_wmill_using_command __wmill_workspace_remove' -l debug -k -f -d 'Show debug/verbose logs'
complete -c wmill -n '__fish_wmill_using_command __wmill_workspace_remove' -l show-diffs -k -f -d 'Show diff informations when syncing (may show sensitive informations)'
complete -c wmill -n '__fish_wmill_using_command __wmill_workspace_remove' -l token -k -f -r -a '(wmill completions complete string workspace remove)' -d 'Specify an API token. This will override any stored token.'
complete -c wmill -n '__fish_wmill_using_command __wmill_workspace_remove' -l base-url -k -f -r -a '(wmill completions complete string workspace remove)' -d 'Specify the base URL of the API. If used, --token and --workspace are required and no local remote/workspace already set will be used.'
complete -c wmill -n '__fish_wmill_using_command __wmill_workspace' -k -f -a whoami -d 'Show the currently active user'
complete -c wmill -n '__fish_wmill_using_command __wmill_workspace_whoami' -s h -l help -x -k -f -d 'Show this help.'
complete -c wmill -n '__fish_wmill_using_command __wmill_workspace_whoami' -l workspace -k -f -r -a '(wmill completions complete string workspace whoami)' -d 'Specify the target workspace. This overrides the default workspace.'
complete -c wmill -n '__fish_wmill_using_command __wmill_workspace_whoami' -l debug -k -f -d 'Show debug/verbose logs'
complete -c wmill -n '__fish_wmill_using_command __wmill_workspace_whoami' -l show-diffs -k -f -d 'Show diff informations when syncing (may show sensitive informations)'
complete -c wmill -n '__fish_wmill_using_command __wmill_workspace_whoami' -l token -k -f -r -a '(wmill completions complete string workspace whoami)' -d 'Specify an API token. This will override any stored token.'
complete -c wmill -n '__fish_wmill_using_command __wmill_workspace_whoami' -l base-url -k -f -r -a '(wmill completions complete string workspace whoami)' -d 'Specify the base URL of the API. If used, --token and --workspace are required and no local remote/workspace already set will be used.'
complete -c wmill -n '__fish_wmill_using_command __wmill' -k -f -a resource -d 'resource related commands'
complete -c wmill -n '__fish_wmill_using_command __wmill_resource' -s h -l help -x -k -f -d 'Show this help.'
complete -c wmill -n '__fish_wmill_using_command __wmill_resource' -l workspace -k -f -r -a '(wmill completions complete string resource)' -d 'Specify the target workspace. This overrides the default workspace.'
complete -c wmill -n '__fish_wmill_using_command __wmill_resource' -l debug -k -f -d 'Show debug/verbose logs'
complete -c wmill -n '__fish_wmill_using_command __wmill_resource' -l show-diffs -k -f -d 'Show diff informations when syncing (may show sensitive informations)'
complete -c wmill -n '__fish_wmill_using_command __wmill_resource' -l token -k -f -r -a '(wmill completions complete string resource)' -d 'Specify an API token. This will override any stored token.'
complete -c wmill -n '__fish_wmill_using_command __wmill_resource' -l base-url -k -f -r -a '(wmill completions complete string resource)' -d 'Specify the base URL of the API. If used, --token and --workspace are required and no local remote/workspace already set will be used.'
complete -c wmill -n '__fish_wmill_using_command __wmill_resource' -k -f -a push -d 'push a local resource spec. This overrides any remote versions.'
complete -c wmill -n '__fish_wmill_using_command __wmill_resource_push' -k -f -a '(wmill completions complete string resource push)'
complete -c wmill -n '__fish_wmill_using_command __wmill_resource_push' -s h -l help -x -k -f -d 'Show this help.'
complete -c wmill -n '__fish_wmill_using_command __wmill_resource_push' -l workspace -k -f -r -a '(wmill completions complete string resource push)' -d 'Specify the target workspace. This overrides the default workspace.'
complete -c wmill -n '__fish_wmill_using_command __wmill_resource_push' -l debug -k -f -d 'Show debug/verbose logs'
complete -c wmill -n '__fish_wmill_using_command __wmill_resource_push' -l show-diffs -k -f -d 'Show diff informations when syncing (may show sensitive informations)'
complete -c wmill -n '__fish_wmill_using_command __wmill_resource_push' -l token -k -f -r -a '(wmill completions complete string resource push)' -d 'Specify an API token. This will override any stored token.'
complete -c wmill -n '__fish_wmill_using_command __wmill_resource_push' -l base-url -k -f -r -a '(wmill completions complete string resource push)' -d 'Specify the base URL of the API. If used, --token and --workspace are required and no local remote/workspace already set will be used.'
complete -c wmill -n '__fish_wmill_using_command __wmill' -k -f -a user -d 'user related commands'
complete -c wmill -n '__fish_wmill_using_command __wmill_user' -s h -l help -x -k -f -d 'Show this help.'
complete -c wmill -n '__fish_wmill_using_command __wmill_user' -l workspace -k -f -r -a '(wmill completions complete string user)' -d 'Specify the target workspace. This overrides the default workspace.'
complete -c wmill -n '__fish_wmill_using_command __wmill_user' -l debug -k -f -d 'Show debug/verbose logs'
complete -c wmill -n '__fish_wmill_using_command __wmill_user' -l show-diffs -k -f -d 'Show diff informations when syncing (may show sensitive informations)'
complete -c wmill -n '__fish_wmill_using_command __wmill_user' -l token -k -f -r -a '(wmill completions complete string user)' -d 'Specify an API token. This will override any stored token.'
complete -c wmill -n '__fish_wmill_using_command __wmill_user' -l base-url -k -f -r -a '(wmill completions complete string user)' -d 'Specify the base URL of the API. If used, --token and --workspace are required and no local remote/workspace already set will be used.'
complete -c wmill -n '__fish_wmill_using_command __wmill_user' -k -f -a add -d 'Create a user'
complete -c wmill -n '__fish_wmill_using_command __wmill_user_add' -k -f -a '(wmill completions complete string user add)'
complete -c wmill -n '__fish_wmill_using_command __wmill_user_add' -s h -l help -x -k -f -d 'Show this help.'
complete -c wmill -n '__fish_wmill_using_command __wmill_user_add' -l workspace -k -f -r -a '(wmill completions complete string user add)' -d 'Specify the target workspace. This overrides the default workspace.'
complete -c wmill -n '__fish_wmill_using_command __wmill_user_add' -l debug -k -f -d 'Show debug/verbose logs'
complete -c wmill -n '__fish_wmill_using_command __wmill_user_add' -l show-diffs -k -f -d 'Show diff informations when syncing (may show sensitive informations)'
complete -c wmill -n '__fish_wmill_using_command __wmill_user_add' -l token -k -f -r -a '(wmill completions complete string user add)' -d 'Specify an API token. This will override any stored token.'
complete -c wmill -n '__fish_wmill_using_command __wmill_user_add' -l base-url -k -f -r -a '(wmill completions complete string user add)' -d 'Specify the base URL of the API. If used, --token and --workspace are required and no local remote/workspace already set will be used.'
complete -c wmill -n '__fish_wmill_using_command __wmill_user_add' -l superadmin -k -f -d 'Specify to make the new user superadmin.'
complete -c wmill -n '__fish_wmill_using_command __wmill_user_add' -l company -k -f -r -a '(wmill completions complete string user add)' -d 'Specify to set the company of the new user.'
complete -c wmill -n '__fish_wmill_using_command __wmill_user_add' -l name -k -f -r -a '(wmill completions complete string user add)' -d 'Specify to set the name of the new user.'
complete -c wmill -n '__fish_wmill_using_command __wmill_user' -k -f -a remove -d 'Delete a user'
complete -c wmill -n '__fish_wmill_using_command __wmill_user_remove' -k -f -a '(wmill completions complete string user remove)'
complete -c wmill -n '__fish_wmill_using_command __wmill_user_remove' -s h -l help -x -k -f -d 'Show this help.'
complete -c wmill -n '__fish_wmill_using_command __wmill_user_remove' -l workspace -k -f -r -a '(wmill completions complete string user remove)' -d 'Specify the target workspace. This overrides the default workspace.'
complete -c wmill -n '__fish_wmill_using_command __wmill_user_remove' -l debug -k -f -d 'Show debug/verbose logs'
complete -c wmill -n '__fish_wmill_using_command __wmill_user_remove' -l show-diffs -k -f -d 'Show diff informations when syncing (may show sensitive informations)'
complete -c wmill -n '__fish_wmill_using_command __wmill_user_remove' -l token -k -f -r -a '(wmill completions complete string user remove)' -d 'Specify an API token. This will override any stored token.'
complete -c wmill -n '__fish_wmill_using_command __wmill_user_remove' -l base-url -k -f -r -a '(wmill completions complete string user remove)' -d 'Specify the base URL of the API. If used, --token and --workspace are required and no local remote/workspace already set will be used.'
complete -c wmill -n '__fish_wmill_using_command __wmill_user' -k -f -a create-token
complete -c wmill -n '__fish_wmill_using_command __wmill_user_create_token' -s h -l help -x -k -f -d 'Show this help.'
complete -c wmill -n '__fish_wmill_using_command __wmill_user_create_token' -l workspace -k -f -r -a '(wmill completions complete string user create-token)' -d 'Specify the target workspace. This overrides the default workspace.'
complete -c wmill -n '__fish_wmill_using_command __wmill_user_create_token' -l debug -k -f -d 'Show debug/verbose logs'
complete -c wmill -n '__fish_wmill_using_command __wmill_user_create_token' -l show-diffs -k -f -d 'Show diff informations when syncing (may show sensitive informations)'
complete -c wmill -n '__fish_wmill_using_command __wmill_user_create_token' -l token -k -f -r -a '(wmill completions complete string user create-token)' -d 'Specify an API token. This will override any stored token.'
complete -c wmill -n '__fish_wmill_using_command __wmill_user_create_token' -l base-url -k -f -r -a '(wmill completions complete string user create-token)' -d 'Specify the base URL of the API. If used, --token and --workspace are required and no local remote/workspace already set will be used.'
complete -c wmill -n '__fish_wmill_using_command __wmill_user_create_token' -l email -k -f -r -a '(wmill completions complete string user create-token)' -d 'Specify credentials to use for authentication. This will not be stored. It will only be used to exchange for a token with the API server, which will not be stored either.'
complete -c wmill -n '__fish_wmill_using_command __wmill_user_create_token' -l password -k -f -r -a '(wmill completions complete string user create-token)' -d 'Specify credentials to use for authentication. This will not be stored. It will only be used to exchange for a token with the API server, which will not be stored either.'
complete -c wmill -n '__fish_wmill_using_command __wmill' -k -f -a variable -d 'variable related commands'
complete -c wmill -n '__fish_wmill_using_command __wmill_variable' -s h -l help -x -k -f -d 'Show this help.'
complete -c wmill -n '__fish_wmill_using_command __wmill_variable' -l workspace -k -f -r -a '(wmill completions complete string variable)' -d 'Specify the target workspace. This overrides the default workspace.'
complete -c wmill -n '__fish_wmill_using_command __wmill_variable' -l debug -k -f -d 'Show debug/verbose logs'
complete -c wmill -n '__fish_wmill_using_command __wmill_variable' -l show-diffs -k -f -d 'Show diff informations when syncing (may show sensitive informations)'
complete -c wmill -n '__fish_wmill_using_command __wmill_variable' -l token -k -f -r -a '(wmill completions complete string variable)' -d 'Specify an API token. This will override any stored token.'
complete -c wmill -n '__fish_wmill_using_command __wmill_variable' -l base-url -k -f -r -a '(wmill completions complete string variable)' -d 'Specify the base URL of the API. If used, --token and --workspace are required and no local remote/workspace already set will be used.'
complete -c wmill -n '__fish_wmill_using_command __wmill_variable' -k -f -a push -d 'Push a local variable spec. This overrides any remote versions.'
complete -c wmill -n '__fish_wmill_using_command __wmill_variable_push' -k -f -a '(wmill completions complete string variable push)'
complete -c wmill -n '__fish_wmill_using_command __wmill_variable_push' -s h -l help -x -k -f -d 'Show this help.'
complete -c wmill -n '__fish_wmill_using_command __wmill_variable_push' -l workspace -k -f -r -a '(wmill completions complete string variable push)' -d 'Specify the target workspace. This overrides the default workspace.'
complete -c wmill -n '__fish_wmill_using_command __wmill_variable_push' -l debug -k -f -d 'Show debug/verbose logs'
complete -c wmill -n '__fish_wmill_using_command __wmill_variable_push' -l show-diffs -k -f -d 'Show diff informations when syncing (may show sensitive informations)'
complete -c wmill -n '__fish_wmill_using_command __wmill_variable_push' -l token -k -f -r -a '(wmill completions complete string variable push)' -d 'Specify an API token. This will override any stored token.'
complete -c wmill -n '__fish_wmill_using_command __wmill_variable_push' -l base-url -k -f -r -a '(wmill completions complete string variable push)' -d 'Specify the base URL of the API. If used, --token and --workspace are required and no local remote/workspace already set will be used.'
complete -c wmill -n '__fish_wmill_using_command __wmill_variable_push' -l plain-secrets -k -f -d 'Push secrets as plain text'
complete -c wmill -n '__fish_wmill_using_command __wmill_variable' -k -f -a add -d 'Create a new variable on the remote. This will update the variable if it already exists.'
complete -c wmill -n '__fish_wmill_using_command __wmill_variable_add' -k -f -a '(wmill completions complete string variable add)'
complete -c wmill -n '__fish_wmill_using_command __wmill_variable_add' -s h -l help -x -k -f -d 'Show this help.'
complete -c wmill -n '__fish_wmill_using_command __wmill_variable_add' -l workspace -k -f -r -a '(wmill completions complete string variable add)' -d 'Specify the target workspace. This overrides the default workspace.'
complete -c wmill -n '__fish_wmill_using_command __wmill_variable_add' -l debug -k -f -d 'Show debug/verbose logs'
complete -c wmill -n '__fish_wmill_using_command __wmill_variable_add' -l show-diffs -k -f -d 'Show diff informations when syncing (may show sensitive informations)'
complete -c wmill -n '__fish_wmill_using_command __wmill_variable_add' -l token -k -f -r -a '(wmill completions complete string variable add)' -d 'Specify an API token. This will override any stored token.'
complete -c wmill -n '__fish_wmill_using_command __wmill_variable_add' -l base-url -k -f -r -a '(wmill completions complete string variable add)' -d 'Specify the base URL of the API. If used, --token and --workspace are required and no local remote/workspace already set will be used.'
complete -c wmill -n '__fish_wmill_using_command __wmill_variable_add' -l plain-secrets -k -f -d 'Push secrets as plain text'
complete -c wmill -n '__fish_wmill_using_command __wmill_variable_add' -l public -k -f -d 'Legacy option, use --plain-secrets instead'
complete -c wmill -n '__fish_wmill_using_command __wmill' -k -f -a hub -d 'Hub related commands. EXPERIMENTAL. INTERNAL USE ONLY.'
complete -c wmill -n '__fish_wmill_using_command __wmill_hub' -s h -l help -x -k -f -d 'Show this help.'
complete -c wmill -n '__fish_wmill_using_command __wmill_hub' -l workspace -k -f -r -a '(wmill completions complete string hub)' -d 'Specify the target workspace. This overrides the default workspace.'
complete -c wmill -n '__fish_wmill_using_command __wmill_hub' -l debug -k -f -d 'Show debug/verbose logs'
complete -c wmill -n '__fish_wmill_using_command __wmill_hub' -l show-diffs -k -f -d 'Show diff informations when syncing (may show sensitive informations)'
complete -c wmill -n '__fish_wmill_using_command __wmill_hub' -l token -k -f -r -a '(wmill completions complete string hub)' -d 'Specify an API token. This will override any stored token.'
complete -c wmill -n '__fish_wmill_using_command __wmill_hub' -l base-url -k -f -r -a '(wmill completions complete string hub)' -d 'Specify the base URL of the API. If used, --token and --workspace are required and no local remote/workspace already set will be used.'
complete -c wmill -n '__fish_wmill_using_command __wmill_hub' -k -f -a pull -d 'pull any supported definitions. EXPERIMENTAL.'
complete -c wmill -n '__fish_wmill_using_command __wmill_hub_pull' -s h -l help -x -k -f -d 'Show this help.'
complete -c wmill -n '__fish_wmill_using_command __wmill_hub_pull' -l workspace -k -f -r -a '(wmill completions complete string hub pull)' -d 'Specify the target workspace. This overrides the default workspace.'
complete -c wmill -n '__fish_wmill_using_command __wmill_hub_pull' -l debug -k -f -d 'Show debug/verbose logs'
complete -c wmill -n '__fish_wmill_using_command __wmill_hub_pull' -l show-diffs -k -f -d 'Show diff informations when syncing (may show sensitive informations)'
complete -c wmill -n '__fish_wmill_using_command __wmill_hub_pull' -l token -k -f -r -a '(wmill completions complete string hub pull)' -d 'Specify an API token. This will override any stored token.'
complete -c wmill -n '__fish_wmill_using_command __wmill_hub_pull' -l base-url -k -f -r -a '(wmill completions complete string hub pull)' -d 'Specify the base URL of the API. If used, --token and --workspace are required and no local remote/workspace already set will be used.'
complete -c wmill -n '__fish_wmill_using_command __wmill' -k -f -a folder -d 'folder related commands'
complete -c wmill -n '__fish_wmill_using_command __wmill_folder' -s h -l help -x -k -f -d 'Show this help.'
complete -c wmill -n '__fish_wmill_using_command __wmill_folder' -l workspace -k -f -r -a '(wmill completions complete string folder)' -d 'Specify the target workspace. This overrides the default workspace.'
complete -c wmill -n '__fish_wmill_using_command __wmill_folder' -l debug -k -f -d 'Show debug/verbose logs'
complete -c wmill -n '__fish_wmill_using_command __wmill_folder' -l show-diffs -k -f -d 'Show diff informations when syncing (may show sensitive informations)'
complete -c wmill -n '__fish_wmill_using_command __wmill_folder' -l token -k -f -r -a '(wmill completions complete string folder)' -d 'Specify an API token. This will override any stored token.'
complete -c wmill -n '__fish_wmill_using_command __wmill_folder' -l base-url -k -f -r -a '(wmill completions complete string folder)' -d 'Specify the base URL of the API. If used, --token and --workspace are required and no local remote/workspace already set will be used.'
complete -c wmill -n '__fish_wmill_using_command __wmill_folder' -k -f -a push -d 'push a local folder spec. This overrides any remote versions.'
complete -c wmill -n '__fish_wmill_using_command __wmill_folder_push' -k -f -a '(wmill completions complete string folder push)'
complete -c wmill -n '__fish_wmill_using_command __wmill_folder_push' -s h -l help -x -k -f -d 'Show this help.'
complete -c wmill -n '__fish_wmill_using_command __wmill_folder_push' -l workspace -k -f -r -a '(wmill completions complete string folder push)' -d 'Specify the target workspace. This overrides the default workspace.'
complete -c wmill -n '__fish_wmill_using_command __wmill_folder_push' -l debug -k -f -d 'Show debug/verbose logs'
complete -c wmill -n '__fish_wmill_using_command __wmill_folder_push' -l show-diffs -k -f -d 'Show diff informations when syncing (may show sensitive informations)'
complete -c wmill -n '__fish_wmill_using_command __wmill_folder_push' -l token -k -f -r -a '(wmill completions complete string folder push)' -d 'Specify an API token. This will override any stored token.'
complete -c wmill -n '__fish_wmill_using_command __wmill_folder_push' -l base-url -k -f -r -a '(wmill completions complete string folder push)' -d 'Specify the base URL of the API. If used, --token and --workspace are required and no local remote/workspace already set will be used.'
complete -c wmill -n '__fish_wmill_using_command __wmill' -k -f -a schedule -d 'schedule related commands'
complete -c wmill -n '__fish_wmill_using_command __wmill_schedule' -s h -l help -x -k -f -d 'Show this help.'
complete -c wmill -n '__fish_wmill_using_command __wmill_schedule' -l workspace -k -f -r -a '(wmill completions complete string schedule)' -d 'Specify the target workspace. This overrides the default workspace.'
complete -c wmill -n '__fish_wmill_using_command __wmill_schedule' -l debug -k -f -d 'Show debug/verbose logs'
complete -c wmill -n '__fish_wmill_using_command __wmill_schedule' -l show-diffs -k -f -d 'Show diff informations when syncing (may show sensitive informations)'
complete -c wmill -n '__fish_wmill_using_command __wmill_schedule' -l token -k -f -r -a '(wmill completions complete string schedule)' -d 'Specify an API token. This will override any stored token.'
complete -c wmill -n '__fish_wmill_using_command __wmill_schedule' -l base-url -k -f -r -a '(wmill completions complete string schedule)' -d 'Specify the base URL of the API. If used, --token and --workspace are required and no local remote/workspace already set will be used.'
complete -c wmill -n '__fish_wmill_using_command __wmill_schedule' -k -f -a push -d 'push a local schedule spec. This overrides any remote versions.'
complete -c wmill -n '__fish_wmill_using_command __wmill_schedule_push' -k -f -a '(wmill completions complete string schedule push)'
complete -c wmill -n '__fish_wmill_using_command __wmill_schedule_push' -s h -l help -x -k -f -d 'Show this help.'
complete -c wmill -n '__fish_wmill_using_command __wmill_schedule_push' -l workspace -k -f -r -a '(wmill completions complete string schedule push)' -d 'Specify the target workspace. This overrides the default workspace.'
complete -c wmill -n '__fish_wmill_using_command __wmill_schedule_push' -l debug -k -f -d 'Show debug/verbose logs'
complete -c wmill -n '__fish_wmill_using_command __wmill_schedule_push' -l show-diffs -k -f -d 'Show diff informations when syncing (may show sensitive informations)'
complete -c wmill -n '__fish_wmill_using_command __wmill_schedule_push' -l token -k -f -r -a '(wmill completions complete string schedule push)' -d 'Specify an API token. This will override any stored token.'
complete -c wmill -n '__fish_wmill_using_command __wmill_schedule_push' -l base-url -k -f -r -a '(wmill completions complete string schedule push)' -d 'Specify the base URL of the API. If used, --token and --workspace are required and no local remote/workspace already set will be used.'
complete -c wmill -n '__fish_wmill_using_command __wmill' -k -f -a trigger -d 'trigger related commands'
complete -c wmill -n '__fish_wmill_using_command __wmill_trigger' -s h -l help -x -k -f -d 'Show this help.'
complete -c wmill -n '__fish_wmill_using_command __wmill_trigger' -l workspace -k -f -r -a '(wmill completions complete string trigger)' -d 'Specify the target workspace. This overrides the default workspace.'
complete -c wmill -n '__fish_wmill_using_command __wmill_trigger' -l debug -k -f -d 'Show debug/verbose logs'
complete -c wmill -n '__fish_wmill_using_command __wmill_trigger' -l show-diffs -k -f -d 'Show diff informations when syncing (may show sensitive informations)'
complete -c wmill -n '__fish_wmill_using_command __wmill_trigger' -l token -k -f -r -a '(wmill completions complete string trigger)' -d 'Specify an API token. This will override any stored token.'
complete -c wmill -n '__fish_wmill_using_command __wmill_trigger' -l base-url -k -f -r -a '(wmill completions complete string trigger)' -d 'Specify the base URL of the API. If used, --token and --workspace are required and no local remote/workspace already set will be used.'
complete -c wmill -n '__fish_wmill_using_command __wmill_trigger' -k -f -a push -d 'push a local trigger spec. This overrides any remote versions.'
complete -c wmill -n '__fish_wmill_using_command __wmill_trigger_push' -k -f -a '(wmill completions complete string trigger push)'
complete -c wmill -n '__fish_wmill_using_command __wmill_trigger_push' -s h -l help -x -k -f -d 'Show this help.'
complete -c wmill -n '__fish_wmill_using_command __wmill_trigger_push' -l workspace -k -f -r -a '(wmill completions complete string trigger push)' -d 'Specify the target workspace. This overrides the default workspace.'
complete -c wmill -n '__fish_wmill_using_command __wmill_trigger_push' -l debug -k -f -d 'Show debug/verbose logs'
complete -c wmill -n '__fish_wmill_using_command __wmill_trigger_push' -l show-diffs -k -f -d 'Show diff informations when syncing (may show sensitive informations)'
complete -c wmill -n '__fish_wmill_using_command __wmill_trigger_push' -l token -k -f -r -a '(wmill completions complete string trigger push)' -d 'Specify an API token. This will override any stored token.'
complete -c wmill -n '__fish_wmill_using_command __wmill_trigger_push' -l base-url -k -f -r -a '(wmill completions complete string trigger push)' -d 'Specify the base URL of the API. If used, --token and --workspace are required and no local remote/workspace already set will be used.'
complete -c wmill -n '__fish_wmill_using_command __wmill' -k -f -a dev -d 'Launch a dev server that will spawn a webserver with HMR'
complete -c wmill -n '__fish_wmill_using_command __wmill_dev' -s h -l help -x -k -f -d 'Show this help.'
complete -c wmill -n '__fish_wmill_using_command __wmill_dev' -l workspace -k -f -r -a '(wmill completions complete string dev)' -d 'Specify the target workspace. This overrides the default workspace.'
complete -c wmill -n '__fish_wmill_using_command __wmill_dev' -l debug -k -f -d 'Show debug/verbose logs'
complete -c wmill -n '__fish_wmill_using_command __wmill_dev' -l show-diffs -k -f -d 'Show diff informations when syncing (may show sensitive informations)'
complete -c wmill -n '__fish_wmill_using_command __wmill_dev' -l token -k -f -r -a '(wmill completions complete string dev)' -d 'Specify an API token. This will override any stored token.'
complete -c wmill -n '__fish_wmill_using_command __wmill_dev' -l base-url -k -f -r -a '(wmill completions complete string dev)' -d 'Specify the base URL of the API. If used, --token and --workspace are required and no local remote/workspace already set will be used.'
complete -c wmill -n '__fish_wmill_using_command __wmill_dev' -l includes -k -f -r -a '(wmill completions complete string dev)' -d 'Filter paths givena glob pattern or path'
complete -c wmill -n '__fish_wmill_using_command __wmill' -k -f -a sync -d 'sync local with a remote workspaces or the opposite (push or pull)'
complete -c wmill -n '__fish_wmill_using_command __wmill_sync' -s h -l help -x -k -f -d 'Show this help.'
complete -c wmill -n '__fish_wmill_using_command __wmill_sync' -l workspace -k -f -r -a '(wmill completions complete string sync)' -d 'Specify the target workspace. This overrides the default workspace.'
complete -c wmill -n '__fish_wmill_using_command __wmill_sync' -l debug -k -f -d 'Show debug/verbose logs'
complete -c wmill -n '__fish_wmill_using_command __wmill_sync' -l show-diffs -k -f -d 'Show diff informations when syncing (may show sensitive informations)'
complete -c wmill -n '__fish_wmill_using_command __wmill_sync' -l token -k -f -r -a '(wmill completions complete string sync)' -d 'Specify an API token. This will override any stored token.'
complete -c wmill -n '__fish_wmill_using_command __wmill_sync' -l base-url -k -f -r -a '(wmill completions complete string sync)' -d 'Specify the base URL of the API. If used, --token and --workspace are required and no local remote/workspace already set will be used.'
complete -c wmill -n '__fish_wmill_using_command __wmill_sync' -k -f -a pull -d 'Pull any remote changes and apply them locally.'
complete -c wmill -n '__fish_wmill_using_command __wmill_sync_pull' -s h -l help -x -k -f -d 'Show this help.'
complete -c wmill -n '__fish_wmill_using_command __wmill_sync_pull' -l workspace -k -f -r -a '(wmill completions complete string sync pull)' -d 'Specify the target workspace. This overrides the default workspace.'
complete -c wmill -n '__fish_wmill_using_command __wmill_sync_pull' -l debug -k -f -d 'Show debug/verbose logs'
complete -c wmill -n '__fish_wmill_using_command __wmill_sync_pull' -l show-diffs -k -f -d 'Show diff informations when syncing (may show sensitive informations)'
complete -c wmill -n '__fish_wmill_using_command __wmill_sync_pull' -l token -k -f -r -a '(wmill completions complete string sync pull)' -d 'Specify an API token. This will override any stored token.'
complete -c wmill -n '__fish_wmill_using_command __wmill_sync_pull' -l base-url -k -f -r -a '(wmill completions complete string sync pull)' -d 'Specify the base URL of the API. If used, --token and --workspace are required and no local remote/workspace already set will be used.'
complete -c wmill -n '__fish_wmill_using_command __wmill_sync_pull' -l yes -k -f -d 'Pull without needing confirmation'
complete -c wmill -n '__fish_wmill_using_command __wmill_sync_pull' -l plain-secrets -k -f -d 'Pull secrets as plain text'
complete -c wmill -n '__fish_wmill_using_command __wmill_sync_pull' -l json -k -f -d 'Use JSON instead of YAML'
complete -c wmill -n '__fish_wmill_using_command __wmill_sync_pull' -l skip-variables -k -f -d 'Skip syncing variables (including secrets)'
complete -c wmill -n '__fish_wmill_using_command __wmill_sync_pull' -l skip-secrets -k -f -d 'Skip syncing only secrets variables'
complete -c wmill -n '__fish_wmill_using_command __wmill_sync_pull' -l skip-resources -k -f -d 'Skip syncing  resources'
complete -c wmill -n '__fish_wmill_using_command __wmill_sync_pull' -l include-schedules -k -f -d 'Include syncing  schedules'
complete -c wmill -n '__fish_wmill_using_command __wmill_sync_pull' -l include-triggers -k -f -d 'Include syncing triggers'
complete -c wmill -n '__fish_wmill_using_command __wmill_sync_pull' -l include-users -k -f -d 'Include syncing users'
complete -c wmill -n '__fish_wmill_using_command __wmill_sync_pull' -l include-groups -k -f -d 'Include syncing groups'
complete -c wmill -n '__fish_wmill_using_command __wmill_sync_pull' -l include-settings -k -f -d 'Include syncing workspace settings'
complete -c wmill -n '__fish_wmill_using_command __wmill_sync_pull' -l include-key -k -f -d 'Include workspace encryption key'
complete -c wmill -n '__fish_wmill_using_command __wmill_sync_pull' -s i -l includes -k -f -r -a '(__fish_complete_path)' -d 'Comma separated patterns to specify which file to take into account (among files that are compatible with windmill). Patterns can include * (any string until \'/\') and ** (any string). Overrides wmill.yaml includes'
complete -c wmill -n '__fish_wmill_using_command __wmill_sync_pull' -s e -l excludes -k -f -r -a '(__fish_complete_path)' -d 'Comma separated patterns to specify which file to NOT take into account. Overrides wmill.yaml excludes'
complete -c wmill -n '__fish_wmill_using_command __wmill_sync_pull' -l extra-includes -k -f -r -a '(__fish_complete_path)' -d 'Comma separated patterns to specify which file to take into account (among files that are compatible with windmill). Patterns can include * (any string until \'/\') and ** (any string). Useful to still take wmill.yaml into account and act as a second pattern to satisfy'
complete -c wmill -n '__fish_wmill_using_command __wmill_sync' -k -f -a push -d 'Push any local changes and apply them remotely.'
complete -c wmill -n '__fish_wmill_using_command __wmill_sync_push' -s h -l help -x -k -f -d 'Show this help.'
complete -c wmill -n '__fish_wmill_using_command __wmill_sync_push' -l workspace -k -f -r -a '(wmill completions complete string sync push)' -d 'Specify the target workspace. This overrides the default workspace.'
complete -c wmill -n '__fish_wmill_using_command __wmill_sync_push' -l debug -k -f -d 'Show debug/verbose logs'
complete -c wmill -n '__fish_wmill_using_command __wmill_sync_push' -l show-diffs -k -f -d 'Show diff informations when syncing (may show sensitive informations)'
complete -c wmill -n '__fish_wmill_using_command __wmill_sync_push' -l token -k -f -r -a '(wmill completions complete string sync push)' -d 'Specify an API token. This will override any stored token.'
complete -c wmill -n '__fish_wmill_using_command __wmill_sync_push' -l base-url -k -f -r -a '(wmill completions complete string sync push)' -d 'Specify the base URL of the API. If used, --token and --workspace are required and no local remote/workspace already set will be used.'
complete -c wmill -n '__fish_wmill_using_command __wmill_sync_push' -l yes -k -f -d 'Push without needing confirmation'
complete -c wmill -n '__fish_wmill_using_command __wmill_sync_push' -l plain-secrets -k -f -d 'Push secrets as plain text'
complete -c wmill -n '__fish_wmill_using_command __wmill_sync_push' -l json -k -f -d 'Use JSON instead of YAML'
complete -c wmill -n '__fish_wmill_using_command __wmill_sync_push' -l skip-variables -k -f -d 'Skip syncing variables (including secrets)'
complete -c wmill -n '__fish_wmill_using_command __wmill_sync_push' -l skip-secrets -k -f -d 'Skip syncing only secrets variables'
complete -c wmill -n '__fish_wmill_using_command __wmill_sync_push' -l skip-resources -k -f -d 'Skip syncing  resources'
complete -c wmill -n '__fish_wmill_using_command __wmill_sync_push' -l include-schedules -k -f -d 'Include syncing schedules'
complete -c wmill -n '__fish_wmill_using_command __wmill_sync_push' -l include-triggers -k -f -d 'Include syncing triggers'
complete -c wmill -n '__fish_wmill_using_command __wmill_sync_push' -l include-users -k -f -d 'Include syncing users'
complete -c wmill -n '__fish_wmill_using_command __wmill_sync_push' -l include-groups -k -f -d 'Include syncing groups'
complete -c wmill -n '__fish_wmill_using_command __wmill_sync_push' -l include-settings -k -f -d 'Include syncing workspace settings'
complete -c wmill -n '__fish_wmill_using_command __wmill_sync_push' -l include-key -k -f -d 'Include workspace encryption key'
complete -c wmill -n '__fish_wmill_using_command __wmill_sync_push' -s i -l includes -k -f -r -a '(__fish_complete_path)' -d 'Comma separated patterns to specify which file to take into account (among files that are compatible with windmill). Patterns can include * (any string until \'/\') and ** (any string)'
complete -c wmill -n '__fish_wmill_using_command __wmill_sync_push' -s e -l excludes -k -f -r -a '(__fish_complete_path)' -d 'Comma separated patterns to specify which file to NOT take into account.'
complete -c wmill -n '__fish_wmill_using_command __wmill_sync_push' -l extra-includes -k -f -r -a '(__fish_complete_path)' -d 'Comma separated patterns to specify which file to take into account (among files that are compatible with windmill). Patterns can include * (any string until \'/\') and ** (any string). Useful to still take wmill.yaml into account and act as a second pattern to satisfy'
complete -c wmill -n '__fish_wmill_using_command __wmill_sync_push' -l message -k -f -r -a '(wmill completions complete string sync push)' -d 'Include a message that will be added to all scripts/flows/apps updated during this push'
complete -c wmill -n '__fish_wmill_using_command __wmill_sync_push' -l parallel -k -f -r -a '(wmill completions complete string sync push)' -d 'Number of changes to process in parallel'
complete -c wmill -n '__fish_wmill_using_command __wmill' -k -f -a instance -d 'sync local with a remote instance or the opposite (push or pull)'
complete -c wmill -n '__fish_wmill_using_command __wmill_instance' -s h -l help -x -k -f -d 'Show this help.'
complete -c wmill -n '__fish_wmill_using_command __wmill_instance' -l workspace -k -f -r -a '(wmill completions complete string instance)' -d 'Specify the target workspace. This overrides the default workspace.'
complete -c wmill -n '__fish_wmill_using_command __wmill_instance' -l debug -k -f -d 'Show debug/verbose logs'
complete -c wmill -n '__fish_wmill_using_command __wmill_instance' -l show-diffs -k -f -d 'Show diff informations when syncing (may show sensitive informations)'
complete -c wmill -n '__fish_wmill_using_command __wmill_instance' -l token -k -f -r -a '(wmill completions complete string instance)' -d 'Specify an API token. This will override any stored token.'
complete -c wmill -n '__fish_wmill_using_command __wmill_instance' -l base-url -k -f -r -a '(wmill completions complete string instance)' -d 'Specify the base URL of the API. If used, --token and --workspace are required and no local remote/workspace already set will be used.'
complete -c wmill -n '__fish_wmill_using_command __wmill_instance' -k -f -a add -d 'Add a new instance'
complete -c wmill -n '__fish_wmill_using_command __wmill_instance_add' -k -f -a '(wmill completions complete string instance add)'
complete -c wmill -n '__fish_wmill_using_command __wmill_instance_add' -s h -l help -x -k -f -d 'Show this help.'
complete -c wmill -n '__fish_wmill_using_command __wmill_instance_add' -l workspace -k -f -r -a '(wmill completions complete string instance add)' -d 'Specify the target workspace. This overrides the default workspace.'
complete -c wmill -n '__fish_wmill_using_command __wmill_instance_add' -l debug -k -f -d 'Show debug/verbose logs'
complete -c wmill -n '__fish_wmill_using_command __wmill_instance_add' -l show-diffs -k -f -d 'Show diff informations when syncing (may show sensitive informations)'
complete -c wmill -n '__fish_wmill_using_command __wmill_instance_add' -l token -k -f -r -a '(wmill completions complete string instance add)' -d 'Specify an API token. This will override any stored token.'
complete -c wmill -n '__fish_wmill_using_command __wmill_instance_add' -l base-url -k -f -r -a '(wmill completions complete string instance add)' -d 'Specify the base URL of the API. If used, --token and --workspace are required and no local remote/workspace already set will be used.'
complete -c wmill -n '__fish_wmill_using_command __wmill_instance' -k -f -a remove -d 'Remove an instance'
complete -c wmill -n '__fish_wmill_using_command __wmill_instance_remove' -k -f -a '(wmill completions complete instance instance remove)'
complete -c wmill -n '__fish_wmill_using_command __wmill_instance_remove' -s h -l help -x -k -f -d 'Show this help.'
complete -c wmill -n '__fish_wmill_using_command __wmill_instance_remove' -l workspace -k -f -r -a '(wmill completions complete string instance remove)' -d 'Specify the target workspace. This overrides the default workspace.'
complete -c wmill -n '__fish_wmill_using_command __wmill_instance_remove' -l debug -k -f -d 'Show debug/verbose logs'
complete -c wmill -n '__fish_wmill_using_command __wmill_instance_remove' -l show-diffs -k -f -d 'Show diff informations when syncing (may show sensitive informations)'
complete -c wmill -n '__fish_wmill_using_command __wmill_instance_remove' -l token -k -f -r -a '(wmill completions complete string instance remove)' -d 'Specify an API token. This will override any stored token.'
complete -c wmill -n '__fish_wmill_using_command __wmill_instance_remove' -l base-url -k -f -r -a '(wmill completions complete string instance remove)' -d 'Specify the base URL of the API. If used, --token and --workspace are required and no local remote/workspace already set will be used.'
complete -c wmill -n '__fish_wmill_using_command __wmill_instance' -k -f -a switch -d 'Switch the current instance'
complete -c wmill -n '__fish_wmill_using_command __wmill_instance_switch' -k -f -a '(wmill completions complete instance instance switch)'
complete -c wmill -n '__fish_wmill_using_command __wmill_instance_switch' -s h -l help -x -k -f -d 'Show this help.'
complete -c wmill -n '__fish_wmill_using_command __wmill_instance_switch' -l workspace -k -f -r -a '(wmill completions complete string instance switch)' -d 'Specify the target workspace. This overrides the default workspace.'
complete -c wmill -n '__fish_wmill_using_command __wmill_instance_switch' -l debug -k -f -d 'Show debug/verbose logs'
complete -c wmill -n '__fish_wmill_using_command __wmill_instance_switch' -l show-diffs -k -f -d 'Show diff informations when syncing (may show sensitive informations)'
complete -c wmill -n '__fish_wmill_using_command __wmill_instance_switch' -l token -k -f -r -a '(wmill completions complete string instance switch)' -d 'Specify an API token. This will override any stored token.'
complete -c wmill -n '__fish_wmill_using_command __wmill_instance_switch' -l base-url -k -f -r -a '(wmill completions complete string instance switch)' -d 'Specify the base URL of the API. If used, --token and --workspace are required and no local remote/workspace already set will be used.'
complete -c wmill -n '__fish_wmill_using_command __wmill_instance' -k -f -a pull -d 'Pull instance settings, users, configs, instance groups and overwrite local'
complete -c wmill -n '__fish_wmill_using_command __wmill_instance_pull' -s h -l help -x -k -f -d 'Show this help.'
complete -c wmill -n '__fish_wmill_using_command __wmill_instance_pull' -l workspace -k -f -r -a '(wmill completions complete string instance pull)' -d 'Specify the target workspace. This overrides the default workspace.'
complete -c wmill -n '__fish_wmill_using_command __wmill_instance_pull' -l debug -k -f -d 'Show debug/verbose logs'
complete -c wmill -n '__fish_wmill_using_command __wmill_instance_pull' -l show-diffs -k -f -d 'Show diff informations when syncing (may show sensitive informations)'
complete -c wmill -n '__fish_wmill_using_command __wmill_instance_pull' -l token -k -f -r -a '(wmill completions complete string instance pull)' -d 'Specify an API token. This will override any stored token.'
complete -c wmill -n '__fish_wmill_using_command __wmill_instance_pull' -l base-url -k -f -r -a '(wmill completions complete string instance pull)' -d 'Specify the base URL of the API. If used, --token and --workspace are required and no local remote/workspace already set will be used.'
complete -c wmill -n '__fish_wmill_using_command __wmill_instance_pull' -l yes -k -f -d 'Pull without needing confirmation'
complete -c wmill -n '__fish_wmill_using_command __wmill_instance_pull' -l skip-users -k -f -d 'Skip pulling users'
complete -c wmill -n '__fish_wmill_using_command __wmill_instance_pull' -l skip-settings -k -f -d 'Skip pulling settings'
complete -c wmill -n '__fish_wmill_using_command __wmill_instance_pull' -l skip-configs -k -f -d 'Skip pulling configs (worker groups and SMTP)'
complete -c wmill -n '__fish_wmill_using_command __wmill_instance_pull' -l skip-groups -k -f -d 'Skip pulling instance groups'
complete -c wmill -n '__fish_wmill_using_command __wmill_instance_pull' -l include-workspaces -k -f -d 'Also pull workspaces'
complete -c wmill -n '__fish_wmill_using_command __wmill_instance_pull' -l folder-per-instance -k -f -d 'Create a folder per instance'
complete -c wmill -n '__fish_wmill_using_command __wmill_instance_pull' -l instance -k -f -r -a '(wmill completions complete string instance pull)' -d 'Name of the instance to pull from, override the active instance'
complete -c wmill -n '__fish_wmill_using_command __wmill_instance_pull' -l prefix -k -f -r -a '(wmill completions complete string instance pull)' -d 'Prefix of the local workspaces to pull, used to create the folders when using --include-workspaces'
complete -c wmill -n '__fish_wmill_using_command __wmill_instance_pull' -l prefix-settings -k -f -d 'Store instance yamls inside prefixed folders when using --prefix and --folder-per-instance'
complete -c wmill -n '__fish_wmill_using_command __wmill_instance' -k -f -a push -d 'Push instance settings, users, configs, group and overwrite remote'
complete -c wmill -n '__fish_wmill_using_command __wmill_instance_push' -s h -l help -x -k -f -d 'Show this help.'
complete -c wmill -n '__fish_wmill_using_command __wmill_instance_push' -l workspace -k -f -r -a '(wmill completions complete string instance push)' -d 'Specify the target workspace. This overrides the default workspace.'
complete -c wmill -n '__fish_wmill_using_command __wmill_instance_push' -l debug -k -f -d 'Show debug/verbose logs'
complete -c wmill -n '__fish_wmill_using_command __wmill_instance_push' -l show-diffs -k -f -d 'Show diff informations when syncing (may show sensitive informations)'
complete -c wmill -n '__fish_wmill_using_command __wmill_instance_push' -l token -k -f -r -a '(wmill completions complete string instance push)' -d 'Specify an API token. This will override any stored token.'
complete -c wmill -n '__fish_wmill_using_command __wmill_instance_push' -l base-url -k -f -r -a '(wmill completions complete string instance push)' -d 'Specify the base URL of the API. If used, --token and --workspace are required and no local remote/workspace already set will be used.'
complete -c wmill -n '__fish_wmill_using_command __wmill_instance_push' -l yes -k -f -d 'Push without needing confirmation'
complete -c wmill -n '__fish_wmill_using_command __wmill_instance_push' -l skip-users -k -f -d 'Skip pushing users'
complete -c wmill -n '__fish_wmill_using_command __wmill_instance_push' -l skip-settings -k -f -d 'Skip pushing settings'
complete -c wmill -n '__fish_wmill_using_command __wmill_instance_push' -l skip-configs -k -f -d 'Skip pushing configs (worker groups and SMTP)'
complete -c wmill -n '__fish_wmill_using_command __wmill_instance_push' -l skip-groups -k -f -d 'Skip pushing instance groups'
complete -c wmill -n '__fish_wmill_using_command __wmill_instance_push' -l include-workspaces -k -f -d 'Also push workspaces'
complete -c wmill -n '__fish_wmill_using_command __wmill_instance_push' -l folder-per-instance -k -f -d 'Create a folder per instance'
complete -c wmill -n '__fish_wmill_using_command __wmill_instance_push' -l instance -k -f -r -a '(wmill completions complete string instance push)' -d 'Name of the instance to push to, override the active instance'
complete -c wmill -n '__fish_wmill_using_command __wmill_instance_push' -l prefix -k -f -r -a '(wmill completions complete string instance push)' -d 'Prefix of the local workspaces folders to push'
complete -c wmill -n '__fish_wmill_using_command __wmill_instance_push' -l prefix-settings -k -f -d 'Store instance yamls inside prefixed folders when using --prefix and --folder-per-instance'
complete -c wmill -n '__fish_wmill_using_command __wmill_instance' -k -f -a whoami -d 'Display information about the currently logged-in user'
complete -c wmill -n '__fish_wmill_using_command __wmill_instance_whoami' -s h -l help -x -k -f -d 'Show this help.'
complete -c wmill -n '__fish_wmill_using_command __wmill_instance_whoami' -l workspace -k -f -r -a '(wmill completions complete string instance whoami)' -d 'Specify the target workspace. This overrides the default workspace.'
complete -c wmill -n '__fish_wmill_using_command __wmill_instance_whoami' -l debug -k -f -d 'Show debug/verbose logs'
complete -c wmill -n '__fish_wmill_using_command __wmill_instance_whoami' -l show-diffs -k -f -d 'Show diff informations when syncing (may show sensitive informations)'
complete -c wmill -n '__fish_wmill_using_command __wmill_instance_whoami' -l token -k -f -r -a '(wmill completions complete string instance whoami)' -d 'Specify an API token. This will override any stored token.'
complete -c wmill -n '__fish_wmill_using_command __wmill_instance_whoami' -l base-url -k -f -r -a '(wmill completions complete string instance whoami)' -d 'Specify the base URL of the API. If used, --token and --workspace are required and no local remote/workspace already set will be used.'
complete -c wmill -n '__fish_wmill_using_command __wmill' -k -f -a worker-groups -d 'display worker groups, pull and push worker groups configs'
complete -c wmill -n '__fish_wmill_using_command __wmill_worker_groups' -s h -l help -x -k -f -d 'Show this help.'
complete -c wmill -n '__fish_wmill_using_command __wmill_worker_groups' -l workspace -k -f -r -a '(wmill completions complete string worker-groups)' -d 'Specify the target workspace. This overrides the default workspace.'
complete -c wmill -n '__fish_wmill_using_command __wmill_worker_groups' -l debug -k -f -d 'Show debug/verbose logs'
complete -c wmill -n '__fish_wmill_using_command __wmill_worker_groups' -l show-diffs -k -f -d 'Show diff informations when syncing (may show sensitive informations)'
complete -c wmill -n '__fish_wmill_using_command __wmill_worker_groups' -l token -k -f -r -a '(wmill completions complete string worker-groups)' -d 'Specify an API token. This will override any stored token.'
complete -c wmill -n '__fish_wmill_using_command __wmill_worker_groups' -l base-url -k -f -r -a '(wmill completions complete string worker-groups)' -d 'Specify the base URL of the API. If used, --token and --workspace are required and no local remote/workspace already set will be used.'
complete -c wmill -n '__fish_wmill_using_command __wmill_worker_groups' -k -f -a pull -d 'Pull worker groups (similar to `wmill instance pull --skip-users --skip-settings --skip-groups`)'
complete -c wmill -n '__fish_wmill_using_command __wmill_worker_groups_pull' -s h -l help -x -k -f -d 'Show this help.'
complete -c wmill -n '__fish_wmill_using_command __wmill_worker_groups_pull' -l workspace -k -f -r -a '(wmill completions complete string worker-groups pull)' -d 'Specify the target workspace. This overrides the default workspace.'
complete -c wmill -n '__fish_wmill_using_command __wmill_worker_groups_pull' -l debug -k -f -d 'Show debug/verbose logs'
complete -c wmill -n '__fish_wmill_using_command __wmill_worker_groups_pull' -l show-diffs -k -f -d 'Show diff informations when syncing (may show sensitive informations)'
complete -c wmill -n '__fish_wmill_using_command __wmill_worker_groups_pull' -l token -k -f -r -a '(wmill completions complete string worker-groups pull)' -d 'Specify an API token. This will override any stored token.'
complete -c wmill -n '__fish_wmill_using_command __wmill_worker_groups_pull' -l instance -k -f -d 'Name of the instance to push to, override the active instance'
complete -c wmill -n '__fish_wmill_using_command __wmill_worker_groups_pull' -l base-url -k -f -d 'Base url to be passed to the instance settings instead of the local one'
complete -c wmill -n '__fish_wmill_using_command __wmill_worker_groups_pull' -l yes -k -f -d 'Pull without needing confirmation'
complete -c wmill -n '__fish_wmill_using_command __wmill_worker_groups' -k -f -a push -d 'Push instance settings, users, configs, group and overwrite remote'
complete -c wmill -n '__fish_wmill_using_command __wmill_worker_groups_push' -s h -l help -x -k -f -d 'Show this help.'
complete -c wmill -n '__fish_wmill_using_command __wmill_worker_groups_push' -l workspace -k -f -r -a '(wmill completions complete string worker-groups push)' -d 'Specify the target workspace. This overrides the default workspace.'
complete -c wmill -n '__fish_wmill_using_command __wmill_worker_groups_push' -l debug -k -f -d 'Show debug/verbose logs'
complete -c wmill -n '__fish_wmill_using_command __wmill_worker_groups_push' -l show-diffs -k -f -d 'Show diff informations when syncing (may show sensitive informations)'
complete -c wmill -n '__fish_wmill_using_command __wmill_worker_groups_push' -l token -k -f -r -a '(wmill completions complete string worker-groups push)' -d 'Specify an API token. This will override any stored token.'
complete -c wmill -n '__fish_wmill_using_command __wmill_worker_groups_push' -l instance -k -f -r -a '(wmill completions complete string worker-groups push)' -d 'Name of the instance to push to, override the active instance'
complete -c wmill -n '__fish_wmill_using_command __wmill_worker_groups_push' -l base-url -k -f -r -a '(wmill completions complete string worker-groups push)' -d 'If used with --token, will be used as the base url for the instance'
complete -c wmill -n '__fish_wmill_using_command __wmill_worker_groups_push' -l yes -k -f -d 'Push without needing confirmation'
complete -c wmill -n '__fish_wmill_using_command __wmill' -k -f -a workers -d 'List all workers grouped by worker groups'
complete -c wmill -n '__fish_wmill_using_command __wmill_workers' -s h -l help -x -k -f -d 'Show this help.'
complete -c wmill -n '__fish_wmill_using_command __wmill_workers' -l workspace -k -f -r -a '(wmill completions complete string workers)' -d 'Specify the target workspace. This overrides the default workspace.'
complete -c wmill -n '__fish_wmill_using_command __wmill_workers' -l debug -k -f -d 'Show debug/verbose logs'
complete -c wmill -n '__fish_wmill_using_command __wmill_workers' -l show-diffs -k -f -d 'Show diff informations when syncing (may show sensitive informations)'
complete -c wmill -n '__fish_wmill_using_command __wmill_workers' -l token -k -f -r -a '(wmill completions complete string workers)' -d 'Specify an API token. This will override any stored token.'
complete -c wmill -n '__fish_wmill_using_command __wmill_workers' -l instance -k -f -r -a '(wmill completions complete string workers)' -d 'Name of the instance to push to, override the active instance'
complete -c wmill -n '__fish_wmill_using_command __wmill_workers' -l base-url -k -f -r -a '(wmill completions complete string workers)' -d 'If used with --token, will be used as the base url for the instance'
complete -c wmill -n '__fish_wmill_using_command __wmill' -k -f -a queues -d 'List all queues with their metrics'
complete -c wmill -n '__fish_wmill_using_command __wmill_queues' -k -f -a '(wmill completions complete string queues)'
complete -c wmill -n '__fish_wmill_using_command __wmill_queues' -s h -l help -x -k -f -d 'Show this help.'
complete -c wmill -n '__fish_wmill_using_command __wmill_queues' -l workspace -k -f -r -a '(wmill completions complete string queues)' -d 'Specify the target workspace. This overrides the default workspace.'
complete -c wmill -n '__fish_wmill_using_command __wmill_queues' -l debug -k -f -d 'Show debug/verbose logs'
complete -c wmill -n '__fish_wmill_using_command __wmill_queues' -l show-diffs -k -f -d 'Show diff informations when syncing (may show sensitive informations)'
complete -c wmill -n '__fish_wmill_using_command __wmill_queues' -l token -k -f -r -a '(wmill completions complete string queues)' -d 'Specify an API token. This will override any stored token.'
complete -c wmill -n '__fish_wmill_using_command __wmill_queues' -l instance -k -f -r -a '(wmill completions complete string queues)' -d 'Name of the instance to push to, override the active instance'
complete -c wmill -n '__fish_wmill_using_command __wmill_queues' -l base-url -k -f -r -a '(wmill completions complete string queues)' -d 'If used with --token, will be used as the base url for the instance'
complete -c wmill -n '__fish_wmill_using_command __wmill' -k -f -a version -d 'Show version information'
complete -c wmill -n '__fish_wmill_using_command __wmill_version' -s h -l help -x -k -f -d 'Show this help.'
complete -c wmill -n '__fish_wmill_using_command __wmill_version' -l workspace -k -f -r -a '(wmill completions complete string version)' -d 'Specify the target workspace. This overrides the default workspace.'
complete -c wmill -n '__fish_wmill_using_command __wmill_version' -l debug -k -f -d 'Show debug/verbose logs'
complete -c wmill -n '__fish_wmill_using_command __wmill_version' -l show-diffs -k -f -d 'Show diff informations when syncing (may show sensitive informations)'
complete -c wmill -n '__fish_wmill_using_command __wmill_version' -l token -k -f -r -a '(wmill completions complete string version)' -d 'Specify an API token. This will override any stored token.'
complete -c wmill -n '__fish_wmill_using_command __wmill_version' -l base-url -k -f -r -a '(wmill completions complete string version)' -d 'Specify the base URL of the API. If used, --token and --workspace are required and no local remote/workspace already set will be used.'
complete -c wmill -n '__fish_wmill_using_command __wmill' -k -f -a upgrade -d 'Upgrade wmill executable to latest or given version.'
complete -c wmill -n '__fish_wmill_using_command __wmill_upgrade' -s h -l help -x -k -f -d 'Show this help.'
complete -c wmill -n '__fish_wmill_using_command __wmill_upgrade' -s l -l list-versions -k -f -d 'Show available versions.'
complete -c wmill -n '__fish_wmill_using_command __wmill_upgrade' -l version -k -f -r -a '(wmill completions complete version upgrade)' -d 'The version to upgrade to.'
complete -c wmill -n '__fish_wmill_using_command __wmill_upgrade' -s f -l force -k -f -d 'Replace current installation even if not out-of-date.'
complete -c wmill -n '__fish_wmill_using_command __wmill_upgrade' -s v -l verbose -k -f -d 'Log verbose output.'
complete -c wmill -n '__fish_wmill_using_command __wmill_upgrade' -l no-spinner -k -f -d 'Disable spinner.'
complete -c wmill -n '__fish_wmill_using_command __wmill' -k -f -a completions -d 'Generate shell completions.'
complete -c wmill -n '__fish_wmill_using_command __wmill_completions' -s h -l help -x -k -f -d 'Show this help.'
complete -c wmill -n '__fish_wmill_using_command __wmill_completions' -k -f -a bash -d 'Generate shell completions for bash.'
complete -c wmill -n '__fish_wmill_using_command __wmill_completions_bash' -s h -l help -x -k -f -d 'Show this help.'
complete -c wmill -n '__fish_wmill_using_command __wmill_completions_bash' -s n -l name -k -f -r -a '(wmill completions complete string completions bash)' -d 'The name of the main command.'
complete -c wmill -n '__fish_wmill_using_command __wmill_completions' -k -f -a fish -d 'Generate shell completions for fish.'
complete -c wmill -n '__fish_wmill_using_command __wmill_completions_fish' -s h -l help -x -k -f -d 'Show this help.'
complete -c wmill -n '__fish_wmill_using_command __wmill_completions_fish' -s n -l name -k -f -r -a '(wmill completions complete string completions fish)' -d 'The name of the main command.'
complete -c wmill -n '__fish_wmill_using_command __wmill_completions' -k -f -a zsh -d 'Generate shell completions for zsh.'
complete -c wmill -n '__fish_wmill_using_command __wmill_completions_zsh' -s h -l help -x -k -f -d 'Show this help.'
complete -c wmill -n '__fish_wmill_using_command __wmill_completions_zsh' -s n -l name -k -f -r -a '(wmill completions complete string completions zsh)' -d 'The name of the main command.'
