complete -c xcodegen -l cache-path -d '<value>      Where the cache file will be loaded from and save to. Defaults to ~/.xcodegen/cache/{SPEC_PATH_HASH}'
complete -c xcodegen -s h -l help -d 'Show help information'
complete -c xcodegen -s n -l no-env -d 'Disable environment variable expansions'
complete -c xcodegen -l only-plists -d 'Generate only plist files'
complete -c xcodegen -s p -l project -d '<value>         The path to the directory where the project should be generated. Defaults to the directory the spec is in. The filename is defined in the project spec'
complete -c xcodegen -s r -l project-root -d '<value>    The path to the project root directory. Defaults to the directory containing the project spec.'
complete -c xcodegen -s q -l quiet -d 'Suppress all informational and success output'
complete -c xcodegen -s s -l spec -d '<value>            The path to the project spec file. Defaults to project.yml. (It is also possible to link to multiple spec files by comma separating them. Note that all other flags will be the same.)'
complete -c xcodegen -s c -l use-cache -d 'Use a cache for the xcodegen spec. This will prevent unnecessarily generating the project if nothing has changed'
