complete -f -c xcompress -n __fish_use_subcommand -a x -d 'Extract files with full path'
complete -f -c xcompress -n __fish_use_subcommand -a a -d 'Add files to archive. Excludes base directory from names (e.g. add /path/to/folder, you can always get the "folder" in the root of the archive file, instead of /path/to/folder)'
complete -f -c xcompress -n __fish_use_subcommand -a help -d 'Print this message or the help of the given subcommand(s)'
complete -c xcompress -s p -l password -d '[<PASSWORD>]'
complete -c xcompress -l compress-path -d '<COMPRESS_PATH>'
complete -c xcompress -l zip-path -d '<ZIP_PATH>'
complete -c xcompress -l unzip-path -d '<UNZIP_PATH>'
complete -c xcompress -l gzip-path -d '<GZIP_PATH>'
complete -c xcompress -l gnuzip-path -d '<GNUZIP_PATH>'
complete -c xcompress -l pigz-path -d '<PIGZ_PATH>'
complete -c xcompress -l bzip2-path -d '<BZIP2_PATH>'
complete -c xcompress -l bunzip2-path -d '<BUNZIP2_PATH>'
complete -c xcompress -l lbzip2-path -d '<LBZIP2_PATH>'
complete -c xcompress -l pbzip2-path -d '<PBZIP2_PATH>'
complete -c xcompress -l lzip-path -d '<LZIP_PATH>'
complete -c xcompress -l lunzip-path -d '<LUNZIP_PATH>'
complete -c xcompress -l plzip-path -d '<PLZIP_PATH>'
complete -c xcompress -l xz-path -d '<XZ_PATH>'
complete -c xcompress -l unxz-path -d '<UNXZ_PATH>'
complete -c xcompress -l pxz-path -d '<PXZ_PATH>'
complete -c xcompress -l lzma-path -d '<LZMA_PATH>'
complete -c xcompress -l unlzma-path -d '<UNLZMA_PATH>'
complete -c xcompress -l 7z-path -d '<7Z_PATH>'
complete -c xcompress -l tar-path -d '<TAR_PATH>'
complete -c xcompress -l rar-path -d '<RAR_PATH>'
complete -c xcompress -l unrar-path -d '<UNRAR_PATH>'
complete -c xcompress -l zstd-path -d '<ZSTD_PATH>'
complete -c xcompress -l unzstd-path -d '<UNZSTD_PATH>'
complete -c xcompress -l pzstd-path -d '<PZSTD_PATH>'
