complete -c xcrun -s h -l help -d 'show this help message and exit'
complete -c xcrun -n __fish_no_arguments -l version -d 'show the xcrun version'
complete -c xcrun -s v -l verbose -d 'show verbose logging output'
complete -c xcrun -l sdk -d '<sdk name>            find the tool for the given SDK name'
complete -c xcrun -l toolchain -d '<name>          find the tool for the given toolchain'
complete -c xcrun -s l -l log -d 'show commands to be executed (with --run)'
complete -c xcrun -s f -l find -d 'only find and print the tool path'
complete -c xcrun -s r -l run -d 'find and execute the tool (the default behavior)'
complete -c xcrun -s n -l no-cache -d 'do not use the lookup cache'
complete -c xcrun -s k -l kill-cache -d 'invalidate all existing cache entries'
complete -c xcrun -l show-sdk-path -d 'show selected SDK install path'
complete -c xcrun -l show-sdk-version -d 'show selected SDK version'
complete -c xcrun -l show-sdk-build-version -d 'show selected SDK build version'
complete -c xcrun -l show-sdk-platform-path -d 'show selected SDK platform path'
complete -c xcrun -l show-sdk-platform-version -d 'show selected SDK platform version'
