complete -f -c xctrace -n __fish_use_subcommand -a record -d 'Perform new recording using specified template'
complete -c xctrace -n '__fish_seen_subcommand_from record' -l output -d '<path>                        Output .trace file to the given path'
complete -c xctrace -n '__fish_seen_subcommand_from record' -l append-run -d 'Appends a new run to an existing trace file'
complete -c xctrace -n '__fish_seen_subcommand_from record' -l template -d '<path|name>                 Record using given trace template name or path' -x -a '(xcrun xctrace list templates)[2..]'
complete -c xctrace -n '__fish_seen_subcommand_from record' -l device -d '<name|UDID>                   Record on device with the given name or UDID'
complete -c xctrace -n '__fish_seen_subcommand_from record' -l instrument -d '<name>                    Add Instrument with the given name to the recording'
complete -c xctrace -n '__fish_seen_subcommand_from record' -l time-limit -d '<time[ms|s|m|h]>          Limit recording time to the specified value'
complete -c xctrace -n '__fish_seen_subcommand_from record' -l window -d '<duration[ms|s|m]>            Keep only events from the specified end time window'
complete -c xctrace -n '__fish_seen_subcommand_from record' -l package -d '<file>                       Load Instruments Package from given path for duration of the command'
complete -c xctrace -n '__fish_seen_subcommand_from record' -l all-processes -d 'Record all processes'
complete -c xctrace -n '__fish_seen_subcommand_from record' -l attach -d '<pid|name>                    Attach and record process with the given name or pid'
complete -c xctrace -n '__fish_seen_subcommand_from record' -l launch -d '-- command [arguments]        Launch process with the given name or path'
complete -c xctrace -n '__fish_seen_subcommand_from record' -l target-stdin -d '<name>                  Redirect standard input of the launched process'
complete -c xctrace -n '__fish_seen_subcommand_from record' -l target-stdout -d '<name>                 Redirect standard output of the launched process'
complete -c xctrace -n '__fish_seen_subcommand_from record' -l env -d '<VAR=value>                      Set specified environment variable for the launched process'
complete -c xctrace -n '__fish_seen_subcommand_from record' -l notify-tracing-started -d 'Send Darwin notification with this name when a recording has started'
complete -c xctrace -n '__fish_seen_subcommand_from record' -l no-prompt -d 'Skip any prompts that would be otherwise presented (like privacy warnings)'
complete -c xctrace -n '__fish_seen_subcommand_from record' -l quiet -d 'Make terminal ouput less verbose'
complete -f -c xctrace -n __fish_use_subcommand -a import -d 'Import file of a supported format into .trace file'
complete -c xctrace -n '__fish_seen_subcommand_from import' -l input -d '<file>                Create .trace file based on the file from given path'
complete -c xctrace -n '__fish_seen_subcommand_from import' -l output -d '<path>               Output .trace file to given path'
complete -c xctrace -n '__fish_seen_subcommand_from import' -l template -d '<path|name>        Import using given trace template name or path' -x -a '(xcrun xctrace list templates)[2..]'
complete -c xctrace -n '__fish_seen_subcommand_from import' -l instrument -d '<name>           Add Instrument with the given name to the import action'
complete -c xctrace -n '__fish_seen_subcommand_from import' -l package -d '<file>              Load Instruments Package from given path for duration of the command'
complete -c xctrace -n '__fish_seen_subcommand_from import' -l quiet -d 'Make terminal ouput less verbose'
complete -f -c xctrace -n __fish_use_subcommand -a export -d 'Export .trace file content to an external format'
complete -c xctrace -n '__fish_seen_subcommand_from export' -l input -d '<file>              Export data from the given .trace file'
complete -c xctrace -n '__fish_seen_subcommand_from export' -l output -d '<path>             Command output is written to the given path, if specified'
complete -c xctrace -n '__fish_seen_subcommand_from export' -l toc -d 'Present entities to export in the table of contents form'
complete -c xctrace -n '__fish_seen_subcommand_from export' -l xpath -d '<expression>        Choose elements to export using specified XPath expression'
complete -c xctrace -n '__fish_seen_subcommand_from export' -l har -d 'Export data as the HTTP Archive file'
complete -c xctrace -n '__fish_seen_subcommand_from export' -l quiet -d 'Make terminal ouput less verbose'
complete -f -c xctrace -n __fish_use_subcommand -a remodel -d 'Remodel .trace using currently installed modelers'
complete -c xctrace -n '__fish_seen_subcommand_from remodel' -l input -d '<file>          Remodel data from the given .trace file'
complete -c xctrace -n '__fish_seen_subcommand_from remodel' -l output -d '<path>         Output remodeled .trace file to given path'
complete -c xctrace -n '__fish_seen_subcommand_from remodel' -l package -d '<file>        Load Instruments Package from given path for duration of the command'
complete -c xctrace -n '__fish_seen_subcommand_from remodel' -l quiet -d 'Make terminal ouput less verbose'
complete -f -c xctrace -n __fish_use_subcommand -a symbolicate -d 'Symbolicate .trace file using specified dSYM'
complete -c xctrace -n '__fish_seen_subcommand_from symbolicate' -l input -d '<file>         Symbolicate addresses in given .trace file'
complete -c xctrace -n '__fish_seen_subcommand_from symbolicate' -l output -d '<path>        Output symbolicated .trace file to the given path'
complete -c xctrace -n '__fish_seen_subcommand_from symbolicate' -l dsym -d '<path>          Use dSYM from given path as source of symbol data'
complete -c xctrace -n '__fish_seen_subcommand_from symbolicate' -l quiet -d 'Make terminal ouput less verbose'
complete -f -c xctrace -n __fish_use_subcommand -a list -d '[devices|templates|instruments]        List capabilities of the current running environment'
complete -c xctrace -n '__fish_seen_subcommand_from list' -l quiet -d 'Make terminal ouput less verbose'
complete -f -c xctrace -n __fish_use_subcommand -a version -d 'Print version of the tool'
complete -c xctrace -n '__fish_seen_subcommand_from version' -l quiet -d 'Make terminal ouput less verbose'
complete -c xctrace -n '__fish_seen_subcommand_from record' -l output -d '<path>                        Output .trace file to the given path'
complete -c xctrace -n '__fish_seen_subcommand_from record' -l append-run -d 'Appends a new run to an existing trace file'
complete -c xctrace -n '__fish_seen_subcommand_from record' -l template -d '<path|name>                 Record using given trace template name or path'
complete -c xctrace -n '__fish_seen_subcommand_from record' -l device -d '<name|UDID>                   Record on device with the given name or UDID'
complete -c xctrace -n '__fish_seen_subcommand_from record' -l instrument -d '<name>                    Add Instrument with the given name to the recording'
complete -c xctrace -n '__fish_seen_subcommand_from record' -l time-limit -d '<time[ms|s|m|h]>          Limit recording time to the specified value'
complete -c xctrace -n '__fish_seen_subcommand_from record' -l window -d '<duration[ms|s|m]>            Keep only events from the specified end time window'
complete -c xctrace -n '__fish_seen_subcommand_from record' -l package -d '<file>                       Load Instruments Package from given path for duration of the command'
complete -c xctrace -n '__fish_seen_subcommand_from record' -l all-processes -d 'Record all processes'
complete -c xctrace -n '__fish_seen_subcommand_from record' -l attach -d '<pid|name>                    Attach and record process with the given name or pid'
complete -c xctrace -n '__fish_seen_subcommand_from record' -l launch -d '-- command [arguments]        Launch process with the given name or path'
complete -c xctrace -n '__fish_seen_subcommand_from record' -l target-stdin -d '<name>                  Redirect standard input of the launched process'
complete -c xctrace -n '__fish_seen_subcommand_from record' -l target-stdout -d '<name>                 Redirect standard output of the launched process'
complete -c xctrace -n '__fish_seen_subcommand_from record' -l env -d '<VAR=value>                      Set specified environment variable for the launched process'
complete -c xctrace -n '__fish_seen_subcommand_from record' -l notify-tracing-started -d 'Send Darwin notification with this name when a recording has started'
complete -c xctrace -n '__fish_seen_subcommand_from record' -l no-prompt -d 'Skip any prompts that would be otherwise presented (like privacy warnings)'
complete -c xctrace -n '__fish_seen_subcommand_from record' -l quiet -d 'Make terminal ouput less verbose'
complete -c xctrace -n '__fish_seen_subcommand_from import' -l input -d '<file>                Create .trace file based on the file from given path'
complete -c xctrace -n '__fish_seen_subcommand_from import' -l output -d '<path>               Output .trace file to given path'
complete -c xctrace -n '__fish_seen_subcommand_from import' -l template -d '<path|name>        Import using given trace template name or path'
complete -c xctrace -n '__fish_seen_subcommand_from import' -l instrument -d '<name>           Add Instrument with the given name to the import action'
complete -c xctrace -n '__fish_seen_subcommand_from import' -l package -d '<file>              Load Instruments Package from given path for duration of the command'
complete -c xctrace -n '__fish_seen_subcommand_from import' -l quiet -d 'Make terminal ouput less verbose'
complete -c xctrace -n '__fish_seen_subcommand_from export' -l input -d '<file>              Export data from the given .trace file'
complete -c xctrace -n '__fish_seen_subcommand_from export' -l output -d '<path>             Command output is written to the given path, if specified'
complete -c xctrace -n '__fish_seen_subcommand_from export' -l toc -d 'Present entities to export in the table of contents form'
complete -c xctrace -n '__fish_seen_subcommand_from export' -l xpath -d '<expression>        Choose elements to export using specified XPath expression'
complete -c xctrace -n '__fish_seen_subcommand_from export' -l har -d 'Export data as the HTTP Archive file'
complete -c xctrace -n '__fish_seen_subcommand_from export' -l quiet -d 'Make terminal ouput less verbose'
complete -c xctrace -n '__fish_seen_subcommand_from symbolicate' -l input -d '<file>         Symbolicate addresses in given .trace file'
complete -c xctrace -n '__fish_seen_subcommand_from symbolicate' -l output -d '<path>        Output symbolicated .trace file to the given path'
complete -c xctrace -n '__fish_seen_subcommand_from symbolicate' -l dsym -d '<path>          Use dSYM from given path as source of symbol data'
complete -c xctrace -n '__fish_seen_subcommand_from symbolicate' -l quiet -d 'Make terminal ouput less verbose'
complete -c xctrace -n '__fish_seen_subcommand_from remodel' -l input -d '<file>          Remodel data from the given .trace file'
complete -c xctrace -n '__fish_seen_subcommand_from remodel' -l output -d '<path>         Output remodeled .trace file to given path'
complete -c xctrace -n '__fish_seen_subcommand_from remodel' -l package -d '<file>        Load Instruments Package from given path for duration of the command'
complete -c xctrace -n '__fish_seen_subcommand_from remodel' -l quiet -d 'Make terminal ouput less verbose'
complete -c xctrace -n '__fish_seen_subcommand_from list' -l quiet -d 'Make terminal ouput less verbose'
