complete -c xlsx2csv -s h -l help -d 'show this help message and exit'
complete -c xlsx2csv -n __fish_no_arguments -s v -l version -d "show program's version number and exit"
complete -c xlsx2csv -s a -l all -d 'export all sheets'
complete -c xlsx2csv -s c -d 'OUTPUTENCODING, --outputencoding OUTPUTENCODING'
complete -c xlsx2csv -s d -d 'DELIMITER, --delimiter DELIMITER'
complete -c xlsx2csv -s e -l escape -d 'Escape \\r\\n\\t characters'
complete -c xlsx2csv -s E -d 'EXCLUDE_SHEET_PATTERN [EXCLUDE_SHEET_PATTERN ...], --exclude_sheet_pattern EXCLUDE_SHEET_PATTERN [EXCLUDE_SHEET_PATTERN ...]'
complete -c xlsx2csv -s f -d 'DATEFORMAT, --dateformat DATEFORMAT'
complete -c xlsx2csv -s t -d 'TIMEFORMAT, --timeformat TIMEFORMAT'
complete -c xlsx2csv -l floatformat -d FLOATFORMAT
complete -c xlsx2csv -l sci-float -d 'force scientific notation to float'
complete -c xlsx2csv -s I -d 'INCLUDE_SHEET_PATTERN [INCLUDE_SHEET_PATTERN ...], --include_sheet_pattern INCLUDE_SHEET_PATTERN [INCLUDE_SHEET_PATTERN ...]'
complete -c xlsx2csv -l ignore-formats -d 'IGNORE_FORMATS [IGNORE_FORMATS ...]'
complete -c xlsx2csv -s l -d 'LINETERMINATOR, --lineterminator LINETERMINATOR'
complete -c xlsx2csv -s m -l merge-cells -d 'merge cells'
complete -c xlsx2csv -s n -d 'SHEETNAME, --sheetname SHEETNAME'
complete -c xlsx2csv -s i -l ignoreempty -d 'skip empty lines'
complete -c xlsx2csv -l skipemptycolumns -d 'skip trailing empty columns'
complete -c xlsx2csv -s p -d 'SHEETDELIMITER, --sheetdelimiter SHEETDELIMITER'
complete -c xlsx2csv -s q -d 'QUOTING, --quoting QUOTING'
complete -c xlsx2csv -s s -d 'SHEETID, --sheet SHEETID'
