complete -c xq -s f -l from-file -d '<file>               Read query from a file instead of arg'
complete -c xq -l input-format -d '<INPUT_FORMAT>    Specify input format [default: json] [possible values: json, yaml]'
complete -c xq -l json-input -d 'Read input as json values'
complete -c xq -l yaml-input -d 'Read input as yaml values'
complete -c xq -s R -l raw-input -d 'Treat each line of input will be supplied to the filter as a string. When used with --slurp, the whole input text will be supplied to the filter as a single string'
complete -c xq -s n -l null-input -d 'Single null is supplied to the program. The original input can still be read via input/0 and inputs/0'
complete -c xq -s s -l slurp -d 'Read input values into an array'
complete -c xq -l output-format -d '<OUTPUT_FORMAT>  Specify output format [default: json] [possible values: json, yaml]'
complete -c xq -l json-output -d 'Write output as json values'
complete -c xq -l yaml-output -d 'Write output as yaml values'
complete -c xq -s r -l raw-output -d 'Output raw string if the output value was a string'
complete -c xq -s c -l compact-output -d 'Compact output'
complete -c xq -s C -l color-output -d 'Colorize output where possible (currently only JSON is supported)'
complete -c xq -s M -l monochrome-output -d 'Do not colorize output'
complete -c xq -s h -l help -d 'Print help'
complete -c xq -n __fish_no_arguments -s V -l version -d 'Print version'
