complete -c yabai -l load-sa -d 'Install and load the scripting-addition.'
complete -c yabai -l uninstall-sa -d 'Uninstall the scripting-addition.'
complete -c yabai -l install-service -d 'Write launchd service file to disk.'
complete -c yabai -l uninstall-service -d 'Remove launchd service file from disk.'
complete -c yabai -l start-service -d 'Enable, load, and start the launchd service.'
complete -c yabai -l restart-service -d 'Attempts to restart the service instance.'
complete -c yabai -l stop-service -d 'Stops a running instance of the service.'
complete -c yabai -s m -l message -d '<msg>    Send message to a running instance of yabai.'
complete -c yabai -s c -l config -d '<config>  Use the specified configuration file.'
complete -c yabai -s V -l verbose -d 'Output debug information to stdout.'
complete -c yabai -n __fish_no_arguments -s v -l version -d 'Print version to stdout and exit.'
complete -c yabai -s h -l help -d 'Print options to stdout and exit.'
