complete -c zed -l configdir -d 'configuration and credentials directory (default "/home/x/.zed")'
complete -c zed -l cpuprofile -d 'write cpu profile to given file name'
complete -c zed -s h -d 'display help (default "false")'
complete -c zed -l help -d 'display help (default "false")'
complete -c zed -l hidden -d 'show hidden options (default "false")'
complete -c zed -l lake -d 'lake location (env ZED_LAKE) (default /home/x/drive/zlake)'
complete -c zed -l memprofile -d 'write memory profile to given file name'
complete -c zed -s q -d 'quiet mode (default "false")'
complete -c zed -n __fish_no_arguments -l version -d 'print version and exit (default "false")'
complete -c zed -n '__fish_seen_subcommand_from auth' -l configdir -d 'configuration and credentials directory (default "/home/x/.zed")'
complete -c zed -n '__fish_seen_subcommand_from auth' -l cpuprofile -d 'write cpu profile to given file name'
complete -c zed -n '__fish_seen_subcommand_from auth' -s h -d 'display help (default "false")'
complete -c zed -n '__fish_seen_subcommand_from auth' -l help -d 'display help (default "false")'
complete -c zed -n '__fish_seen_subcommand_from auth' -l hidden -d 'show hidden options (default "false")'
complete -c zed -n '__fish_seen_subcommand_from auth' -l lake -d 'lake location (env ZED_LAKE) (default /home/x/drive/zlake)'
complete -c zed -n '__fish_seen_subcommand_from auth' -l memprofile -d 'write memory profile to given file name'
complete -c zed -n '__fish_seen_subcommand_from auth' -s q -d 'quiet mode (default "false")'
complete -c zed -n __fish_no_arguments -l version -d 'print version and exit (default "false")'
complete -c zed -n '__fish_seen_subcommand_from branch' -l configdir -d 'configuration and credentials directory (default "/home/x/.zed")'
complete -c zed -n '__fish_seen_subcommand_from branch' -l cpuprofile -d 'write cpu profile to given file name'
complete -c zed -n '__fish_seen_subcommand_from branch' -s h -d 'display help (default "false")'
complete -c zed -n '__fish_seen_subcommand_from branch' -l help -d 'display help (default "false")'
complete -c zed -n '__fish_seen_subcommand_from branch' -l hidden -d 'show hidden options (default "false")'
complete -c zed -n '__fish_seen_subcommand_from branch' -l lake -d 'lake location (env ZED_LAKE) (default /home/x/drive/zlake)'
complete -c zed -n '__fish_seen_subcommand_from branch' -l memprofile -d 'write memory profile to given file name'
complete -c zed -n '__fish_seen_subcommand_from branch' -s q -d 'quiet mode (default "false")'
complete -c zed -n __fish_no_arguments -l version -d 'print version and exit (default "false")'
complete -c zed -n '__fish_seen_subcommand_from compact' -l configdir -d 'configuration and credentials directory (default "/home/x/.zed")'
complete -c zed -n '__fish_seen_subcommand_from compact' -l cpuprofile -d 'write cpu profile to given file name'
complete -c zed -n '__fish_seen_subcommand_from compact' -s h -d 'display help (default "false")'
complete -c zed -n '__fish_seen_subcommand_from compact' -l help -d 'display help (default "false")'
complete -c zed -n '__fish_seen_subcommand_from compact' -l hidden -d 'show hidden options (default "false")'
complete -c zed -n '__fish_seen_subcommand_from compact' -l lake -d 'lake location (env ZED_LAKE) (default /home/x/drive/zlake)'
complete -c zed -n '__fish_seen_subcommand_from compact' -l memprofile -d 'write memory profile to given file name'
complete -c zed -n '__fish_seen_subcommand_from compact' -s q -d 'quiet mode (default "false")'
complete -c zed -n __fish_no_arguments -l version -d 'print version and exit (default "false")'
complete -c zed -n '__fish_seen_subcommand_from create' -l configdir -d 'configuration and credentials directory (default "/home/x/.zed")'
complete -c zed -n '__fish_seen_subcommand_from create' -l cpuprofile -d 'write cpu profile to given file name'
complete -c zed -n '__fish_seen_subcommand_from create' -s h -d 'display help (default "false")'
complete -c zed -n '__fish_seen_subcommand_from create' -l help -d 'display help (default "false")'
complete -c zed -n '__fish_seen_subcommand_from create' -l hidden -d 'show hidden options (default "false")'
complete -c zed -n '__fish_seen_subcommand_from create' -l lake -d 'lake location (env ZED_LAKE) (default /home/x/drive/zlake)'
complete -c zed -n '__fish_seen_subcommand_from create' -l memprofile -d 'write memory profile to given file name'
complete -c zed -n '__fish_seen_subcommand_from create' -s q -d 'quiet mode (default "false")'
complete -c zed -n __fish_no_arguments -l version -d 'print version and exit (default "false")'
complete -c zed -n '__fish_seen_subcommand_from delete' -l configdir -d 'configuration and credentials directory (default "/home/x/.zed")'
complete -c zed -n '__fish_seen_subcommand_from delete' -l cpuprofile -d 'write cpu profile to given file name'
complete -c zed -n '__fish_seen_subcommand_from delete' -s h -d 'display help (default "false")'
complete -c zed -n '__fish_seen_subcommand_from delete' -l help -d 'display help (default "false")'
complete -c zed -n '__fish_seen_subcommand_from delete' -l hidden -d 'show hidden options (default "false")'
complete -c zed -n '__fish_seen_subcommand_from delete' -l lake -d 'lake location (env ZED_LAKE) (default /home/x/drive/zlake)'
complete -c zed -n '__fish_seen_subcommand_from delete' -l memprofile -d 'write memory profile to given file name'
complete -c zed -n '__fish_seen_subcommand_from delete' -s q -d 'quiet mode (default "false")'
complete -c zed -n __fish_no_arguments -l version -d 'print version and exit (default "false")'
complete -c zed -n '__fish_seen_subcommand_from drop' -l configdir -d 'configuration and credentials directory (default "/home/x/.zed")'
complete -c zed -n '__fish_seen_subcommand_from drop' -l cpuprofile -d 'write cpu profile to given file name'
complete -c zed -n '__fish_seen_subcommand_from drop' -s h -d 'display help (default "false")'
complete -c zed -n '__fish_seen_subcommand_from drop' -l help -d 'display help (default "false")'
complete -c zed -n '__fish_seen_subcommand_from drop' -l hidden -d 'show hidden options (default "false")'
complete -c zed -n '__fish_seen_subcommand_from drop' -l lake -d 'lake location (env ZED_LAKE) (default /home/x/drive/zlake)'
complete -c zed -n '__fish_seen_subcommand_from drop' -l memprofile -d 'write memory profile to given file name'
complete -c zed -n '__fish_seen_subcommand_from drop' -s q -d 'quiet mode (default "false")'
complete -c zed -n __fish_no_arguments -l version -d 'print version and exit (default "false")'
complete -c zed -n '__fish_seen_subcommand_from init' -l configdir -d 'configuration and credentials directory (default "/home/x/.zed")'
complete -c zed -n '__fish_seen_subcommand_from init' -l cpuprofile -d 'write cpu profile to given file name'
complete -c zed -n '__fish_seen_subcommand_from init' -s h -d 'display help (default "false")'
complete -c zed -n '__fish_seen_subcommand_from init' -l help -d 'display help (default "false")'
complete -c zed -n '__fish_seen_subcommand_from init' -l hidden -d 'show hidden options (default "false")'
complete -c zed -n '__fish_seen_subcommand_from init' -l lake -d 'lake location (env ZED_LAKE) (default /home/x/drive/zlake)'
complete -c zed -n '__fish_seen_subcommand_from init' -l memprofile -d 'write memory profile to given file name'
complete -c zed -n '__fish_seen_subcommand_from init' -s q -d 'quiet mode (default "false")'
complete -c zed -n __fish_no_arguments -l version -d 'print version and exit (default "false")'
complete -c zed -n '__fish_seen_subcommand_from load' -l configdir -d 'configuration and credentials directory (default "/home/x/.zed")'
complete -c zed -n '__fish_seen_subcommand_from load' -l cpuprofile -d 'write cpu profile to given file name'
complete -c zed -n '__fish_seen_subcommand_from load' -s h -d 'display help (default "false")'
complete -c zed -n '__fish_seen_subcommand_from load' -l help -d 'display help (default "false")'
complete -c zed -n '__fish_seen_subcommand_from load' -l hidden -d 'show hidden options (default "false")'
complete -c zed -n '__fish_seen_subcommand_from load' -l lake -d 'lake location (env ZED_LAKE) (default /home/x/drive/zlake)'
complete -c zed -n '__fish_seen_subcommand_from load' -l memprofile -d 'write memory profile to given file name'
complete -c zed -n '__fish_seen_subcommand_from load' -s q -d 'quiet mode (default "false")'
complete -c zed -n __fish_no_arguments -l version -d 'print version and exit (default "false")'
complete -c zed -n '__fish_seen_subcommand_from log' -l configdir -d 'configuration and credentials directory (default "/home/x/.zed")'
complete -c zed -n '__fish_seen_subcommand_from log' -l cpuprofile -d 'write cpu profile to given file name'
complete -c zed -n '__fish_seen_subcommand_from log' -s h -d 'display help (default "false")'
complete -c zed -n '__fish_seen_subcommand_from log' -l help -d 'display help (default "false")'
complete -c zed -n '__fish_seen_subcommand_from log' -l hidden -d 'show hidden options (default "false")'
complete -c zed -n '__fish_seen_subcommand_from log' -l lake -d 'lake location (env ZED_LAKE) (default /home/x/drive/zlake)'
complete -c zed -n '__fish_seen_subcommand_from log' -l memprofile -d 'write memory profile to given file name'
complete -c zed -n '__fish_seen_subcommand_from log' -s q -d 'quiet mode (default "false")'
complete -c zed -n __fish_no_arguments -l version -d 'print version and exit (default "false")'
complete -c zed -n '__fish_seen_subcommand_from ls' -l configdir -d 'configuration and credentials directory (default "/home/x/.zed")'
complete -c zed -n '__fish_seen_subcommand_from ls' -l cpuprofile -d 'write cpu profile to given file name'
complete -c zed -n '__fish_seen_subcommand_from ls' -s h -d 'display help (default "false")'
complete -c zed -n '__fish_seen_subcommand_from ls' -l help -d 'display help (default "false")'
complete -c zed -n '__fish_seen_subcommand_from ls' -l hidden -d 'show hidden options (default "false")'
complete -c zed -n '__fish_seen_subcommand_from ls' -l lake -d 'lake location (env ZED_LAKE) (default /home/x/drive/zlake)'
complete -c zed -n '__fish_seen_subcommand_from ls' -l memprofile -d 'write memory profile to given file name'
complete -c zed -n '__fish_seen_subcommand_from ls' -s q -d 'quiet mode (default "false")'
complete -c zed -n __fish_no_arguments -l version -d 'print version and exit (default "false")'
complete -c zed -n '__fish_seen_subcommand_from manage' -l configdir -d 'configuration and credentials directory (default "/home/x/.zed")'
complete -c zed -n '__fish_seen_subcommand_from manage' -l cpuprofile -d 'write cpu profile to given file name'
complete -c zed -n '__fish_seen_subcommand_from manage' -s h -d 'display help (default "false")'
complete -c zed -n '__fish_seen_subcommand_from manage' -l help -d 'display help (default "false")'
complete -c zed -n '__fish_seen_subcommand_from manage' -l hidden -d 'show hidden options (default "false")'
complete -c zed -n '__fish_seen_subcommand_from manage' -l lake -d 'lake location (env ZED_LAKE) (default /home/x/drive/zlake)'
complete -c zed -n '__fish_seen_subcommand_from manage' -l memprofile -d 'write memory profile to given file name'
complete -c zed -n '__fish_seen_subcommand_from manage' -s q -d 'quiet mode (default "false")'
complete -c zed -n __fish_no_arguments -l version -d 'print version and exit (default "false")'
complete -c zed -n '__fish_seen_subcommand_from merge' -l configdir -d 'configuration and credentials directory (default "/home/x/.zed")'
complete -c zed -n '__fish_seen_subcommand_from merge' -l cpuprofile -d 'write cpu profile to given file name'
complete -c zed -n '__fish_seen_subcommand_from merge' -s h -d 'display help (default "false")'
complete -c zed -n '__fish_seen_subcommand_from merge' -l help -d 'display help (default "false")'
complete -c zed -n '__fish_seen_subcommand_from merge' -l hidden -d 'show hidden options (default "false")'
complete -c zed -n '__fish_seen_subcommand_from merge' -l lake -d 'lake location (env ZED_LAKE) (default /home/x/drive/zlake)'
complete -c zed -n '__fish_seen_subcommand_from merge' -l memprofile -d 'write memory profile to given file name'
complete -c zed -n '__fish_seen_subcommand_from merge' -s q -d 'quiet mode (default "false")'
complete -c zed -n __fish_no_arguments -l version -d 'print version and exit (default "false")'
complete -c zed -n '__fish_seen_subcommand_from query' -l configdir -d 'configuration and credentials directory (default "/home/x/.zed")'
complete -c zed -n '__fish_seen_subcommand_from query' -l cpuprofile -d 'write cpu profile to given file name'
complete -c zed -n '__fish_seen_subcommand_from query' -s h -d 'display help (default "false")'
complete -c zed -n '__fish_seen_subcommand_from query' -l help -d 'display help (default "false")'
complete -c zed -n '__fish_seen_subcommand_from query' -l hidden -d 'show hidden options (default "false")'
complete -c zed -n '__fish_seen_subcommand_from query' -l lake -d 'lake location (env ZED_LAKE) (default /home/x/drive/zlake)'
complete -c zed -n '__fish_seen_subcommand_from query' -l memprofile -d 'write memory profile to given file name'
complete -c zed -n '__fish_seen_subcommand_from query' -s q -d 'quiet mode (default "false")'
complete -c zed -n __fish_no_arguments -l version -d 'print version and exit (default "false")'
complete -c zed -n '__fish_seen_subcommand_from rename' -l configdir -d 'configuration and credentials directory (default "/home/x/.zed")'
complete -c zed -n '__fish_seen_subcommand_from rename' -l cpuprofile -d 'write cpu profile to given file name'
complete -c zed -n '__fish_seen_subcommand_from rename' -s h -d 'display help (default "false")'
complete -c zed -n '__fish_seen_subcommand_from rename' -l help -d 'display help (default "false")'
complete -c zed -n '__fish_seen_subcommand_from rename' -l hidden -d 'show hidden options (default "false")'
complete -c zed -n '__fish_seen_subcommand_from rename' -l lake -d 'lake location (env ZED_LAKE) (default /home/x/drive/zlake)'
complete -c zed -n '__fish_seen_subcommand_from rename' -l memprofile -d 'write memory profile to given file name'
complete -c zed -n '__fish_seen_subcommand_from rename' -s q -d 'quiet mode (default "false")'
complete -c zed -n __fish_no_arguments -l version -d 'print version and exit (default "false")'
complete -c zed -n '__fish_seen_subcommand_from revert' -l configdir -d 'configuration and credentials directory (default "/home/x/.zed")'
complete -c zed -n '__fish_seen_subcommand_from revert' -l cpuprofile -d 'write cpu profile to given file name'
complete -c zed -n '__fish_seen_subcommand_from revert' -s h -d 'display help (default "false")'
complete -c zed -n '__fish_seen_subcommand_from revert' -l help -d 'display help (default "false")'
complete -c zed -n '__fish_seen_subcommand_from revert' -l hidden -d 'show hidden options (default "false")'
complete -c zed -n '__fish_seen_subcommand_from revert' -l lake -d 'lake location (env ZED_LAKE) (default /home/x/drive/zlake)'
complete -c zed -n '__fish_seen_subcommand_from revert' -l memprofile -d 'write memory profile to given file name'
complete -c zed -n '__fish_seen_subcommand_from revert' -s q -d 'quiet mode (default "false")'
complete -c zed -n __fish_no_arguments -l version -d 'print version and exit (default "false")'
complete -c zed -n '__fish_seen_subcommand_from serve' -l configdir -d 'configuration and credentials directory (default "/home/x/.zed")'
complete -c zed -n '__fish_seen_subcommand_from serve' -l cpuprofile -d 'write cpu profile to given file name'
complete -c zed -n '__fish_seen_subcommand_from serve' -s h -d 'display help (default "false")'
complete -c zed -n '__fish_seen_subcommand_from serve' -l help -d 'display help (default "false")'
complete -c zed -n '__fish_seen_subcommand_from serve' -l hidden -d 'show hidden options (default "false")'
complete -c zed -n '__fish_seen_subcommand_from serve' -l lake -d 'lake location (env ZED_LAKE) (default /home/x/drive/zlake)'
complete -c zed -n '__fish_seen_subcommand_from serve' -l memprofile -d 'write memory profile to given file name'
complete -c zed -n '__fish_seen_subcommand_from serve' -s q -d 'quiet mode (default "false")'
complete -c zed -n __fish_no_arguments -l version -d 'print version and exit (default "false")'
complete -c zed -n '__fish_seen_subcommand_from use' -l configdir -d 'configuration and credentials directory (default "/home/x/.zed")'
complete -c zed -n '__fish_seen_subcommand_from use' -l cpuprofile -d 'write cpu profile to given file name'
complete -c zed -n '__fish_seen_subcommand_from use' -s h -d 'display help (default "false")'
complete -c zed -n '__fish_seen_subcommand_from use' -l help -d 'display help (default "false")'
complete -c zed -n '__fish_seen_subcommand_from use' -l hidden -d 'show hidden options (default "false")'
complete -c zed -n '__fish_seen_subcommand_from use' -l lake -d 'lake location (env ZED_LAKE) (default /home/x/drive/zlake)'
complete -c zed -n '__fish_seen_subcommand_from use' -l memprofile -d 'write memory profile to given file name'
complete -c zed -n '__fish_seen_subcommand_from use' -s q -d 'quiet mode (default "false")'
complete -c zed -n __fish_no_arguments -l version -d 'print version and exit (default "false")'
complete -c zed -n '__fish_seen_subcommand_from vacate' -l configdir -d 'configuration and credentials directory (default "/home/x/.zed")'
complete -c zed -n '__fish_seen_subcommand_from vacate' -l cpuprofile -d 'write cpu profile to given file name'
complete -c zed -n '__fish_seen_subcommand_from vacate' -s h -d 'display help (default "false")'
complete -c zed -n '__fish_seen_subcommand_from vacate' -l help -d 'display help (default "false")'
complete -c zed -n '__fish_seen_subcommand_from vacate' -l hidden -d 'show hidden options (default "false")'
complete -c zed -n '__fish_seen_subcommand_from vacate' -l lake -d 'lake location (env ZED_LAKE) (default /home/x/drive/zlake)'
complete -c zed -n '__fish_seen_subcommand_from vacate' -l memprofile -d 'write memory profile to given file name'
complete -c zed -n '__fish_seen_subcommand_from vacate' -s q -d 'quiet mode (default "false")'
complete -c zed -n __fish_no_arguments -l version -d 'print version and exit (default "false")'
complete -c zed -n '__fish_seen_subcommand_from vacuum' -l configdir -d 'configuration and credentials directory (default "/home/x/.zed")'
complete -c zed -n '__fish_seen_subcommand_from vacuum' -l cpuprofile -d 'write cpu profile to given file name'
complete -c zed -n '__fish_seen_subcommand_from vacuum' -s h -d 'display help (default "false")'
complete -c zed -n '__fish_seen_subcommand_from vacuum' -l help -d 'display help (default "false")'
complete -c zed -n '__fish_seen_subcommand_from vacuum' -l hidden -d 'show hidden options (default "false")'
complete -c zed -n '__fish_seen_subcommand_from vacuum' -l lake -d 'lake location (env ZED_LAKE) (default /home/x/drive/zlake)'
complete -c zed -n '__fish_seen_subcommand_from vacuum' -l memprofile -d 'write memory profile to given file name'
complete -c zed -n '__fish_seen_subcommand_from vacuum' -s q -d 'quiet mode (default "false")'
complete -c zed -n __fish_no_arguments -l version -d 'print version and exit (default "false")'
complete -c zed -n '__fish_seen_subcommand_from vector' -l configdir -d 'configuration and credentials directory (default "/home/x/.zed")'
complete -c zed -n '__fish_seen_subcommand_from vector' -l cpuprofile -d 'write cpu profile to given file name'
complete -c zed -n '__fish_seen_subcommand_from vector' -s h -d 'display help (default "false")'
complete -c zed -n '__fish_seen_subcommand_from vector' -l help -d 'display help (default "false")'
complete -c zed -n '__fish_seen_subcommand_from vector' -l hidden -d 'show hidden options (default "false")'
complete -c zed -n '__fish_seen_subcommand_from vector' -l lake -d 'lake location (env ZED_LAKE) (default /home/x/drive/zlake)'
complete -c zed -n '__fish_seen_subcommand_from vector' -l memprofile -d 'write memory profile to given file name'
complete -c zed -n '__fish_seen_subcommand_from vector' -s q -d 'quiet mode (default "false")'
complete -c zed -n __fish_no_arguments -l version -d 'print version and exit (default "false")'
complete -c zed -n '__fish_seen_subcommand_from dev' -l configdir -d 'configuration and credentials directory (default "/home/x/.zed")'
complete -c zed -n '__fish_seen_subcommand_from dev' -l cpuprofile -d 'write cpu profile to given file name'
complete -c zed -n '__fish_seen_subcommand_from dev' -s h -d 'display help (default "false")'
complete -c zed -n '__fish_seen_subcommand_from dev' -l help -d 'display help (default "false")'
complete -c zed -n '__fish_seen_subcommand_from dev' -l hidden -d 'show hidden options (default "false")'
complete -c zed -n '__fish_seen_subcommand_from dev' -l lake -d 'lake location (env ZED_LAKE) (default /home/x/drive/zlake)'
complete -c zed -n '__fish_seen_subcommand_from dev' -l memprofile -d 'write memory profile to given file name'
complete -c zed -n '__fish_seen_subcommand_from dev' -s q -d 'quiet mode (default "false")'
complete -c zed -n __fish_no_arguments -l version -d 'print version and exit (default "false")'
