complete -c zq -l aggmem -d 'maximum memory used per aggregate function value in MiB, MB, etc (default "auto(1GiB)")'
complete -c zq -s B -d 'allow binary zng be sent to a terminal output (default "false")'
complete -c zq -s C -d 'display AST in Zed canonical format (default "false")'
complete -c zq -l color -d 'enable/disable color formatting for -Z and lake text output (default "true")'
complete -c zq -l csv.delim -d 'CSV field delimiter (default ",")'
complete -c zq -s e -d 'stop upon input errors (default "true")'
complete -c zq -s f -d 'format for output data (default "zng")' -x -a "arrows csv json lake parquet table text tsv vng zeek zjson zng zson"
complete -c zq -l fusemem -d 'maximum memory used by fuse in MiB, MB, etc (default "auto(1GiB)")'
complete -c zq -s h -d 'display help (default "false")'
complete -c zq -l help -d 'display help (default "false")'
complete -c zq -l hidden -d 'show hidden options (default "false")'
complete -c zq -s i -d 'format of input data (default "auto")' -x -a "auto arrows csv json line parquet tsv vng zeek zjson zng zson"
complete -c zq -s I -d 'source file containing Zed query text (may be used multiple times)'
complete -c zq -s J -d 'use formatted JSON output independent of -f option (default "false")'
complete -c zq -s j -d 'use line-oriented JSON output independent of -f option (default "false")'
complete -c zq -s o -d 'write data to output file'
complete -c zq -l persist -d 'regular expression to persist type definitions across the stream'
complete -c zq -l pretty -d 'tab size to pretty print JSON/ZSON output (0 for newline-delimited JSON/ZSON (default "4")'
complete -c zq -s q -d don\'t\ display\ warnings\ \(default\ \"false\"\)
complete -c zq -s s -d 'display search stats on stderr (default "false")'
complete -c zq -l sortmem -d 'maximum memory used by sort in MiB, MB, etc (default "auto(1GiB)")'
complete -c zq -l split -d 'split output into one file per data type in this directory (but see -splitsize)'
complete -c zq -l splitsize -d 'if >0 and -split is set, split into files at least this big rather than by data type (default "0B")'
complete -c zq -l unbuffered -d 'disable output buffering (default "false")'
complete -c zq -n __fish_no_arguments -l version -d 'print version and exit (default "false")'
complete -c zq -s Z -d 'use formatted ZSON output independent of -f option (default "false")'
complete -c zq -s z -d 'use line-oriented ZSON output independent of -f option (default "false")'
complete -c zq -l zng.compress -d 'compress ZNG frames (default "true")'
complete -c zq -l zng.framethresh -d 'minimum ZNG frame size in uncompressed bytes (default "524288")'
complete -c zq -l zng.readmax -d 'maximum ZNG read buffer size in MiB, MB, etc. (default "auto(1GiB)")'
complete -c zq -l zng.readsize -d 'target ZNG read buffer size in MiB, MB, etc. (default "auto(512KiB)")'
complete -c zq -l zng.threads -d 'number of ZNG read threads (0=GOMAXPROCS) (default "0")'
complete -c zq -l zng.validate -d 'validate format when reading ZNG (default "false")'
